/-
  Knots.ConwayPD — The Conway knot (11n34) and the Kinoshita-Terasaka knot (11n42)
  ===============================================================================

  The two concrete PD codes: the Conway knot 11n34 (discovered by Conway via his
  knot notation, 11 crossings, trivial Alexander polynomial) and the
  Kinoshita-Terasaka knot 11n42 — the mutant pair sharing a trivial Alexander
  polynomial (section 4 of `Knots.Conway` for the proof).

  Extracted from `Knots.Conway` (split #18397 tranche 2; tranche 1 = `Knots.Slice`
  in #18528). Epic #2874.
-/

/-
  English mirror of `ConwayPD.lean` (FR canonical, header mono-lingual EN).
  Convention EPIC #4980 : distinct FR + EN sibling files; body signatures,
  proofs, sorry markers, and tactics remain byte-identical between the two
  files (anti-§D byte-identity invariant).
-/

import Knots.Basic_en

namespace Knots_en

/-! ## 2. The Conway knot (11n34)

11 crossings in the Rolfsen table. Discovered by Conway (1970).
Trivial Alexander polynomial. Topologically slice (Freedman).
Not smoothly slice (Piccirillo 2018).

PD-code from the KnotInfo census (generated by spherogram 2.4.1),
**corrected**: the code committed by #12892 was not connected — its
crossing 11 `⟨21, 22, 22, 21⟩` used only edges {21, 22}, a component
isolated from the rest of the diagram, and edge 19 appeared twice within
its own crossing `⟨19, 14, 20, 19⟩`. The `wf` control (labels in [1, 22],
each exactly twice) does not see connectivity: the defect passed.
Measured consequence: the crossing-11 row was entirely zero in the
designated minor → determinant 0, and the original
`conway_trivial_alexander` statement (`= 1`) was false under the designated
normalization. The tuples below are the (t₁, t₂, t₃, t₀) rotation of the
census tuples, so that the over-strand sits at positions (e2, e4) of this
file's convention. Verified designated target (Python probe faithful to the
construction, validated on 3₁/4₁/5₁): minor = −t⁶, a unit — Δ = 1
classically.
-/

def conwayKnotDiagram : KnotDiagram where
  crossings := [
    ⟨1, 4, 22, 3⟩,
    ⟨7, 2, 6, 1⟩,
    ⟨3, 8, 2, 7⟩,
    ⟨4, 12, 5, 11⟩,
    ⟨12, 6, 13, 5⟩,
    ⟨16, 9, 15, 8⟩,
    ⟨9, 21, 10, 20⟩,
    ⟨17, 11, 18, 10⟩,
    ⟨13, 19, 14, 18⟩,
    ⟨19, 15, 20, 14⟩,
    ⟨22, 17, 21, 16⟩
  ]
  numEdges := 22

/-- Control: the corrected code is well-formed in the `wf` sense (each label
of [1, 22] exactly twice). The previous disconnected code also passed this
control — the arc control is what distinguishes. -/
theorem conway_wf : conwayKnotDiagram.wf = true := by
  decide

/-- Control: the arc partition of the corrected code — stated in §4
(`conway_arcPartition`), after `arcPartition` is defined. -/

def conwayKnot : Knot where
  diagram := conwayKnotDiagram

/-! ## 3. The Kinoshita-Terasaka knot (11n42)

Also 11 crossings. Shares the trivial Alexander polynomial with 11n34.
IS smoothly slice (bounds a disk in B⁴).
Mutant of the Conway knot.

Census PD-code corrected as in §2 (the previous code was connected but
carried intra-crossing repeated edges at crossings 10 and 11 —
`⟨19, 14, 20, 19⟩` and `⟨21, 12, 22, 21⟩` — yielding a non-unit designated
minor of degree 7, false for Δ = 1). Same (t₁, t₂, t₃, t₀) rotation.
Verified designated target: minor = t⁵, a unit.
-/

def kinoshitaTerasakaDiagram : KnotDiagram where
  crossings := [
    ⟨1, 4, 22, 3⟩,
    ⟨7, 2, 6, 1⟩,
    ⟨3, 8, 2, 7⟩,
    ⟨4, 12, 5, 11⟩,
    ⟨12, 6, 13, 5⟩,
    ⟨17, 9, 18, 8⟩,
    ⟨9, 15, 10, 14⟩,
    ⟨20, 11, 19, 10⟩,
    ⟨14, 19, 13, 18⟩,
    ⟨15, 21, 16, 20⟩,
    ⟨21, 17, 22, 16⟩
  ]
  numEdges := 22

/-- `wf` control of the corrected KT code (cf. `conway_wf`). -/
theorem kinoshitaTerasaka_wf : kinoshitaTerasakaDiagram.wf = true := by
  decide

/-- Control: arc partition of the corrected KT code — stated in §4
(`kinoshitaTerasaka_arcPartition`). -/

def kinoshitaTerasakaKnot : Knot where
  diagram := kinoshitaTerasakaDiagram


end Knots_en
