# Cloud-VolTargeting - Volatility Targeting Strategy
# Educational notebook Cloud-06: Three variants of volatility targeting

from AlgorithmImports import *

class VolTargetingAlgorithm(QCAlgorithm):
    """
    Volatility Targeting Strategy with three variants:
    - v1: Single asset (SPY) with vol targeting
    - v2: Multi-asset equal risk contribution
    - v3: Multi-asset with momentum filter
    """

    def initialize(self):
        self.set_cash(100000)
        self.set_brokerage_model(BrokerageName.INTERACTIVE_BROKERS_BROKERAGE, AccountType.MARGIN)
        # Aligned baseline period 2018-2025 (#1630). Original start was 2014;
        # standardized to 2018-01-01 for cross-strategy comparison.
        # `start` / `end` parameters override it (experiment #18921 runs 2007-2026).
        start = datetime.strptime(self.get_parameter("start", "2018-01-01"), "%Y-%m-%d")
        end = datetime.strptime(self.get_parameter("end", "2025-01-01"), "%Y-%m-%d")
        self.set_start_date(start.year, start.month, start.day)
        self.set_end_date(end.year, end.month, end.day)

        self.version = self.get_parameter("version", "1")

        # Experiment #18921 (pre-registered in the issue, comment 5964767205):
        # vol_model = rv21 (default, the code below unchanged) | har | tsfm |
        # placebo_<seed>. Forecasts come from vol_forecasts.py, generated by
        # ML-Training-Pipeline/scripts/voltarget_forecasts.py (v2 only).
        self.vol_model = self.get_parameter("vol_model", "rv21")
        self.fee_bps = self.get_parameter("fee_bps", "")
        self.forecasts = None
        if self.vol_model != "rv21":
            from vol_forecasts import DATES, FORECASTS
            if self.vol_model not in FORECASTS:
                raise ValueError(f"unknown vol_model {self.vol_model}")
            self.forecasts = FORECASTS
            self.forecast_index = {d[:7]: i for i, d in enumerate(DATES)}
            self.forecast_dates = DATES
        self.rv21_qc = {}        # last rv21 computed by QC, per ticker
        self.sessions = 0
        self.bars_seen = 0       # daily SPY bars, for the daily equity record

        self.target_vol = 0.12 if self.version == "1" else 0.10
        self.lookback = 21
        self.min_allocation = 0.30 if self.version == "1" else 0.0
        self.max_allocation = 1.50 if self.version == "1" else 0.50

        if self.version == "1":
            self.tickers = ["SPY"]
        else:
            self.tickers = ["SPY", "QQQ", "IEF", "GLD"]

        for ticker in self.tickers:
            security = self.add_equity(ticker, Resolution.DAILY)
            if self.fee_bps:
                security.set_fee_model(NotionalFeeModel(float(self.fee_bps)))

        self.schedule.on(
            self.date_rules.month_start(),
            self.time_rules.after_market_open("SPY", 30),
            self.rebalance
        )

    def rebalance(self):
        if self.version == "1":
            self.rebalance_v1()
        elif self.version == "2":
            self.rebalance_v2()
        elif self.version == "3":
            self.rebalance_v3()

    def _get_closes(self, symbol, period):
        """Get close prices as numpy array from QC history API."""
        hist = self.history(symbol, period, Resolution.DAILY)
        if hist.empty or len(hist) < period:
            return None
        return hist['close'].values

    def rebalance_v1(self):
        spy = self.symbol("SPY")
        closes = self._get_closes(spy, self.lookback)
        if closes is None:
            self.debug("Not enough history for vol calculation")
            return

        realized_vol = self.calculate_realized_vol(closes)

        if realized_vol == 0:
            allocation = self.min_allocation
        else:
            allocation = self.target_vol / realized_vol
            allocation = max(self.min_allocation, min(allocation, self.max_allocation))

        self.debug(f"v1 - Realized vol: {realized_vol:.4f}, Target allocation: {allocation:.2f}")
        self.set_holdings(spy, allocation)

    def rebalance_v2(self):
        target_vol_per_asset = self.target_vol / len(self.tickers)
        portfolio_targets = {}

        for ticker in self.tickers:
            symbol = self.symbol(ticker)
            closes = self._get_closes(symbol, self.lookback)
            if closes is None:
                self.debug(f"Not enough history for {ticker}")
                continue

            realized_vol = self.calculate_realized_vol(closes)
            self.rv21_qc[ticker] = realized_vol
            if self.forecasts is not None:
                realized_vol = self._forecast_vol(ticker)
            if realized_vol == 0:
                self.debug(f"Realized vol is zero for {ticker}")
                continue

            allocation = target_vol_per_asset / realized_vol
            allocation = max(0.0, min(allocation, self.max_allocation))
            portfolio_targets[symbol] = allocation
            self.debug(f"v2 - {ticker}: vol={realized_vol:.4f}, alloc={allocation:.2f}")

        if portfolio_targets:
            total_alloc = sum(portfolio_targets.values())
            if total_alloc > 1.0:
                scale_factor = 1.0 / total_alloc
                portfolio_targets = {k: v * scale_factor for k, v in portfolio_targets.items()}
            for symbol, weight in portfolio_targets.items():
                self.set_holdings(symbol, weight)

    def rebalance_v3(self):
        target_vol_per_asset = self.target_vol / len(self.tickers)
        momentum_period = 126
        portfolio_targets = {}

        for ticker in self.tickers:
            symbol = self.symbol(ticker)
            period = max(self.lookback, momentum_period)
            closes = self._get_closes(symbol, period)
            if closes is None or len(closes) < momentum_period:
                self.debug(f"Not enough history for {ticker}")
                continue

            momentum = (closes[-1] - closes[-momentum_period]) / closes[-momentum_period]
            if momentum <= 0:
                self.debug(f"v3 - {ticker}: momentum={momentum:.4f} (negative, skipped)")
                continue

            vol_closes = closes[-self.lookback:]
            realized_vol = self.calculate_realized_vol(vol_closes)
            if realized_vol == 0:
                self.debug(f"Realized vol is zero for {ticker}")
                continue

            allocation = target_vol_per_asset / realized_vol
            allocation = max(0.0, min(allocation, self.max_allocation))
            portfolio_targets[symbol] = allocation
            self.debug(f"v3 - {ticker}: momentum={momentum:.4f}, vol={realized_vol:.4f}, alloc={allocation:.2f}")

        if not portfolio_targets:
            self.debug("v3 - No asset with positive momentum, going 100% IEF")
            ief_symbol = self.symbol("IEF")
            self.set_holdings(ief_symbol, 1.0)
            return

        total_alloc = sum(portfolio_targets.values())
        if total_alloc > 1.0:
            scale_factor = 1.0 / total_alloc
            portfolio_targets = {k: v * scale_factor for k, v in portfolio_targets.items()}
        for symbol, weight in portfolio_targets.items():
            self.set_holdings(symbol, weight)

    def calculate_realized_vol(self, closes):
        if len(closes) < 2:
            return 0.0
        log_returns = np.log(closes[1:] / closes[:-1])
        if len(log_returns) < 2:
            return 0.0
        realized_vol = np.std(log_returns) * np.sqrt(252)
        return realized_vol

    # --- Experiment #18921: forecast lookup and rv21 record -----------------

    def on_data(self, data):
        # QC's own rv21 (pre-reg section 2), read back through /backtests/chart/read.
        # Plotted as a step every 5 sessions, so that a month without a rebalance
        # shows up as a flat step (month_start() without a symbol skips the months
        # whose 1st is not a trading day: 85 of 236 over 2007-2026, measured).
        self.sessions += 1
        if self.sessions % 5 == 0:
            for ticker, vol in self.rv21_qc.items():
                self.plot("coursia-18921-rv21", ticker, vol)
        # Daily net equity at each close (pre-reg section 4). "Strategy Equity" is
        # stored on a uniform grid of about 1.3 days over 20 years, not per session;
        # five interleaved series, one point every 5 sessions each, keep their dates.
        if data.bars.contains_key("SPY"):
            self.plot("coursia-18921-equity", f"e{self.bars_seen % 5}",
                      self.portfolio.total_portfolio_value)
            self.bars_seen += 1

    def _forecast_vol(self, ticker):
        """Vol forecast for this month's rebalance; fails loudly if missing."""
        key = self.time.strftime("%Y-%m")
        if key not in self.forecast_index:
            raise ValueError(f"no {self.vol_model} forecast for {key}")
        return self.forecasts[self.vol_model][ticker][self.forecast_index[key]]


class NotionalFeeModel(FeeModel):
    """Flat fee in basis points of the traded notional (experiment #18921: 5 bps)."""

    def __init__(self, bps):
        super().__init__()
        self.rate = bps / 10000.0

    def get_order_fee(self, parameters):
        order = parameters.order
        notional = abs(order.get_value(parameters.security))
        return OrderFee(CashAmount(notional * self.rate, "USD"))
