"""Lean diagnostic-class error marker, pinned against REAL Lean output (#8694).

Why this file exists
--------------------
``LeanVerifier._extract_errors`` (``agent_tests/lean_server.py``) and
``prover.tools._parse_lean_errors`` are two parsers of the same lake output.
Their docstrings claim to "mirror" each other, but nothing enforced it: the
agreement was prose. Both anchored on the literal ``error:``, and current
Lean 4 tags many diagnostics with a class between the keyword and the colon
(``error(lean.unknownIdentifier):``). Measured on the real build output below,
the pair reported **1 of the 3** errors actually emitted -- the #6790
false-negative signature (``level_1_build == False AND errors == []``) coming
back through a new spelling, five years of regression tests notwithstanding.

The tests that were supposed to catch this could not: every fixture in
``test_prover_guards.py::test_parse_lean_errors_*`` is a hand-written string in
a format someone remembered, so code and tests encoded the same partial
knowledge of Lean and confirmed each other. A green suite measured its own
internal coherence, never contact with the tool.

Hence the rule this file applies: **if the test can pass while Lean has changed
its format, it is not testing Lean.** ``REAL_BROKEN_BUILD`` below is pasted
from a real run, not regenerated by hand.

Provenance of ``REAL_BROKEN_BUILD``
-----------------------------------
Captured 2026-07-28 against ``knot_lean`` (Lean 4 / Mathlib, fresh build)::

    $ cat > /tmp/broken.lean <<'EOF'
    import Knots.Basic
    theorem bad_type : (1 : Nat) = "x" := rfl
    def bad_id : Nat := undefinedThing
    #print axioms Knots.nonexistent_decl
    example : True := by exact sorry
    EOF
    $ lake env lean /tmp/broken.lean   # returncode 1

Verbatim, with ONE documented normalization: the absolute Windows temp
directory of the capturing machine was replaced by ``/tmp`` so the fixture is
machine-neutral. Nothing else was touched -- the diagnostics, their spellings,
the multi-line continuation and the trailing warning are exactly as Lean
emitted them.

Run from ``agent_tests/``::

    python -m pytest tests/test_error_marker_contract.py -q
"""

from __future__ import annotations

import sys
from pathlib import Path

# Make the package importable regardless of how pytest is invoked.
HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(ROOT))

from lean_server import LeanVerifier  # noqa: E402
from prover.tools import _parse_lean_errors  # noqa: E402


REAL_BROKEN_BUILD = (
    "warning: mathlib: repository '/tmp/knot_lean/.lake/packages/mathlib' has local changes\n"
    "/tmp/broken.lean:2:31: error: Type mismatch\n"
    '  "x"\n'
    "has type\n"
    "  String\n"
    "but is expected to have type\n"
    "  ℕ\n"
    "/tmp/broken.lean:3:20: error(lean.unknownIdentifier): Unknown identifier `undefinedThing`\n"
    "/tmp/broken.lean:4:14: error(lean.unknownIdentifier): Unknown constant `Knots.nonexistent_decl`\n"
    "/tmp/broken.lean:5:0: warning: declaration uses `sorry`\n"
)

# The three diagnostics Lean actually reported, by source line. One bare
# ``error:`` and two ``error(<class>):`` -- the mix is the point: a parser that
# handles only the spelling it was written against looks like it works.
EXPECTED_ERROR_LINES = [2, 3, 4]


def test_extract_errors_sees_every_real_error():
    """The authority must not miss a diagnostic because of its class tag."""
    found = LeanVerifier._extract_errors(REAL_BROKEN_BUILD)
    assert len(found) == 3, (
        "expected the 3 errors Lean emitted, got "
        f"{len(found)}: {found}. A class-tagged diagnostic "
        "(error(lean.unknownIdentifier):) carries neither ': error:' nor a "
        "leading 'error:', so literal gates silently drop it."
    )
    assert any("error(lean.unknownIdentifier)" in e for e in found)


def test_parse_lean_errors_sees_every_real_error():
    """The inline parser must agree with the authority, on real output."""
    found = _parse_lean_errors(REAL_BROKEN_BUILD)
    assert [e["line"] for e in found] == EXPECTED_ERROR_LINES
    assert found[1]["message"] == "Unknown identifier `undefinedThing`"
    assert found[2]["message"] == "Unknown constant `Knots.nonexistent_decl`"


def test_the_two_parsers_agree_on_real_output():
    """Pin the contract the two docstrings *claim* but nothing enforced.

    The parsers live in modules that cannot share an import (``lean_server.py``
    sits one directory up and is spec-loaded by ``prover/verifier.py``), so
    their marker is duplicated. Duplication maintained by prose is what let
    them drift; this test is the machine check that replaces the prose.
    """
    authority = LeanVerifier._extract_errors(REAL_BROKEN_BUILD)
    inline = _parse_lean_errors(REAL_BROKEN_BUILD)
    assert len(authority) == len(inline), (
        f"authority saw {len(authority)} errors, inline parser saw "
        f"{len(inline)} -- this disagreement IS the #6790 false negative"
    )


def test_warnings_are_not_errors():
    """``declaration uses `sorry``` is a warning; counting it as an error would
    make every sorry-bearing build look broken."""
    for entry in LeanVerifier._extract_errors(REAL_BROKEN_BUILD):
        assert "warning:" not in entry
    assert all(e["line"] != 5 for e in _parse_lean_errors(REAL_BROKEN_BUILD))


def test_no_false_positive_on_the_word_error():
    """Prose containing the word must not be mistaken for a diagnostic."""
    benign = "  Unknown identifier 'error'\ninfo: rebuilding\n"
    assert LeanVerifier._extract_errors(benign) == []
    assert _parse_lean_errors(benign) == []


# --- non-regression: the formats #6790 / grain a-2 were written against ------
# The fix is purely additive. These are the historical spellings pinned by
# test_prover_guards.py; they must keep parsing identically.


def test_legacy_positional_still_parsed():
    line = "Foo.lean:12:3: error: type mismatch"
    assert LeanVerifier._extract_errors(line) == [line]
    assert _parse_lean_errors(line) == [{"line": 12, "message": "type mismatch"}]


def test_legacy_lake_prefix_still_parsed():
    line = "error: Conway/Life/HashlifeCorrectness.lean:2940:79: unexpected token"
    assert LeanVerifier._extract_errors(line) == [line]
    assert _parse_lean_errors(line) == [{"line": 2940, "message": "unexpected token"}]


def test_legacy_module_level_still_parsed():
    line = "MyMod.lean: error: cannot synthesize type"
    assert LeanVerifier._extract_errors(line) == [line]
    assert _parse_lean_errors(line) == [
        {"line": None, "message": "cannot synthesize type"}
    ]
