"""measure_voicedesign_narrator.py -- tranche 2 #15002 motion/motifs3 measurement.

Reproduces the live WAV generated by Qwen3-TTS VoiceDesign (gateway :8196) on
the Boule de Suif narrator opening (c.293, 68 syllables), then runs the
two prosody_lab instruments on it:

  - syllable_pitch.py  -> motion (st/syll), flat_pct (% flat transitions), span
  - measure_melody.py  -> effective_notes (Shannon exp), top3_pct, motif_pct

Acceptance #15002 criterion #2 demands:
  - motion >= 2.0 st/syll
  - motif_pct <= 40% (motifs3 in the body wording)

A "DRONE" baseline (FishAudio S2-Pro v4_narrator_male_neutral) was measured
on 2026-08-18 in #1028 (comments) and re-measured in #11624 (6.0 effective
notes, 72.8% top-3, 82.2% motifs). The VoiceDesign path is the remediation
introduced by PR #15016 (c.293). This script provides the post-remediation
verdict.

Run::

    python measure_voicedesign_narrator.py [--out-json results.json]

Verdicts:
  - PASS   motion >= 2.0 AND motif_pct <= 40%
  - PARTIAL motion >= 1.6 OR flat_pct <= 55%
  - FAIL   otherwise

Side effects:
  - WAV/MP3 saved under prosody_lab/_tranche2_15002/ (gitignored)
  - SHA256 logged for reproducibility
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

# Local imports
HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

try:
    from syllable_pitch import analyze_syllables
    from measure_melody import measure_clip
except ImportError:
    from syllable_pitch import analyze_syllables  # type: ignore
    from measure_melody import measure_clip  # type: ignore


# Boule de Suif, narrator opening -- same 68-syllable extract used in c.293
# (no stage directions in brackets -- _strip_brackets_for_qwen already applied
# upstream in p5_tts.py; this is the clean narrator prose).
TEXT = (
    "Pendant plusieurs jours, les voyageurs restèrent enfermés dans le "
    "bateau, sans pouvoir sortir, à cause du gros temps qui les empêchait "
    "de toucher terre. Ils finirent par s'ennuyer beaucoup."
)

INSTRUCTIONS = (
    "Voix masculine fran\\u00e7aise, timbre litt\\u00e9raire neutre, "
    "rythme narratif pos\\u00e9, prosodie expressive avec variation de "
    "hauteur et d'intensit\\u00e9, pas monotone, style lecture audiobook."
)

GATEWAY_URL = "http://localhost:8196"


def _sha256(b: bytes) -> str:
    return hashlib.sha256(b).hexdigest()


def _wav_to_mp3(wav_path: Path, mp3_path: Path, bitrate: str = "192k") -> None:
    """Convert WAV -> MP3 via ffmpeg (pydub fallback)."""
    try:
        from pydub import AudioSegment
        a = AudioSegment.from_wav(wav_path)
        a.export(mp3_path, format="mp3", bitrate=bitrate)
        return
    except Exception:
        pass
    subprocess.run(
        ["ffmpeg", "-y", "-i", str(wav_path), "-b:a", bitrate, str(mp3_path)],
        check=True, capture_output=True,
    )


def synth_voicedesign(text: str, instructions: str, per_chunk_timeout: int = 290) -> bytes:
    """Synthesize via the gateway :8196 -- qwen_tts_voicedesign_chunked.

    Note (c.295): the post-#15016 signature evolved -- ``qwen_tts_voicedesign_chunked``
    accepts ``per_chunk_timeout`` (not ``timeout``); ``max_chars=160`` and
    ``gap_ms=120`` are internal defaults and not exposed.
    """
    from qwen_tts_client import qwen_tts_voicedesign_chunked
    return qwen_tts_voicedesign_chunked(
        text=text,
        instructions=instructions,
        language="French",
        per_chunk_timeout=per_chunk_timeout,
    )


def synth_fishaudio_baseline(text: str) -> bytes:
    """Synthesize via the legacy FishAudio S2-Pro path (v4_narrator_male_neutral).

    Returns the WAV bytes produced by p5_tts._synthesize_fishaudio_path with
    the same text. Imported lazily to avoid pulling in torch/grpc deps when
    only VoiceDesign is exercised.
    """
    from v4.fishaudio_client import fishaudio_tts
    return fishaudio_tts(
        text=text,
        reference_id="v4_narrator_male_neutral",
        seed=42,
    )


def verdict_motion(motion: float | None) -> str:
    if motion is None:
        return "INSUFFICIENT"
    if motion >= 2.0:
        return "EXPRESSIVE"
    if motion >= 1.6:
        return "MODERATE"
    if motion >= 1.0:
        return "FLAT"
    return "DRONE"


def verdict_flat(pct: float | None) -> str:
    if pct is None:
        return "INSUFFICIENT"
    if pct <= 40.0:
        return "EXPRESSIVE"
    if pct <= 55.0:
        return "MODERATE"
    if pct <= 70.0:
        return "FLAT"
    return "DRONE"


def verdict_motif(pct: float | None) -> str:
    if pct is None:
        return "INSUFFICIENT"
    if pct <= 40.0:
        return "EXPRESSIVE"
    if pct <= 55.0:
        return "MODERATE"
    if pct <= 70.0:
        return "FLAT"
    return "DRONE"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out-json", default=None, help="Write results JSON here")
    parser.add_argument("--skip-baseline", action="store_true",
                        help="Skip FishAudio baseline (saves time)")
    args = parser.parse_args()

    out_dir = HERE / "_tranche2_15002"
    out_dir.mkdir(exist_ok=True)

    results: dict = {
        "text_sha256": _sha256(TEXT.encode("utf-8")),
        "text_len_chars": len(TEXT),
        "instr_sha256": _sha256(INSTRUCTIONS.encode("utf-8")),
    }

    # --- VoiceDesign --------------------------------------------------
    print("== VoiceDesign ==", flush=True)
    wav_vd = synth_voicedesign(TEXT, INSTRUCTIONS)
    vd_path = out_dir / "voicedesign.wav"
    vd_path.write_bytes(wav_vd)
    results["voicedesign"] = {
        "wav_sha256": _sha256(wav_vd),
        "wav_bytes": len(wav_vd),
        "wav_path": str(vd_path),
    }

    # Convert to MP3 (consistent with p5 pipeline)
    mp3_vd = out_dir / "voicedesign.mp3"
    _wav_to_mp3(vd_path, mp3_vd)
    results["voicedesign"]["mp3_sha256"] = _sha256(mp3_path.read_bytes() if False else mp3_vd.read_bytes())
    results["voicedesign"]["mp3_bytes"] = mp3_vd.stat().st_size

    # Motion + flat via syllable_pitch
    a = analyze_syllables(str(mp3_vd))
    motion = a.get("mean_abs_interval_st")  # st/syll (post-rename in c.295)
    flat_pct = a.get("pct_flat_transitions")  # % flat transitions (post-rename)
    n_syll = a.get("n_syllables", 0)
    results["voicedesign"]["syllable_pitch"] = {
        "n_syllables": n_syll,
        "motion_st_per_syll": motion,
        "flat_pct": flat_pct,
        "span_st": a.get("melodic_span_st"),
        "span_p5p95_st": a.get("melodic_span_p5p95_st"),
        "verdict": a.get("verdict"),
        "local_verdict": a.get("local_verdict"),
        "structure_assessed": a.get("structure_assessed"),
        "drone_reasons": a.get("drone_reasons"),
        "verdict_motion": verdict_motion(motion),
        "verdict_flat": verdict_flat(flat_pct),
    }

    # Melody metrics via measure_melody
    m = measure_clip(str(mp3_vd))
    motif_pct = m.get("motif_pct")
    top3_pct = m.get("top3_pct")
    eff_notes = m.get("effective_notes")
    results["voicedesign"]["measure_melody"] = {
        "effective_notes": eff_notes,
        "top3_pct": top3_pct,
        "motif_pct": motif_pct,
        "verdict_motif": verdict_motif(motif_pct),
        "n_distinct_notes": m.get("n_distinct_notes"),
    }

    # --- FishAudio baseline (optional) --------------------------------
    if not args.skip_baseline:
        print("== FishAudio baseline ==", flush=True)
        try:
            wav_fa = synth_fishaudio_baseline(TEXT)
            fa_path = out_dir / "fishaudio.wav"
            fa_path.write_bytes(wav_fa)
            mp3_fa = out_dir / "fishaudio.mp3"
            _wav_to_mp3(fa_path, mp3_fa)
            a_fa = analyze_syllables(str(mp3_fa))
            m_fa = measure_clip(str(mp3_fa))
            results["fishaudio"] = {
                "wav_sha256": _sha256(wav_fa),
                "wav_bytes": len(wav_fa),
                "syllable_pitch": {
                    "n_syllables": a_fa.get("n_syllables"),
                    "motion_st_per_syll": a_fa.get("motion"),
                    "flat_pct": a_fa.get("flat_pct"),
                    "verdict_motion": verdict_motion(a_fa.get("motion")),
                },
                "measure_melody": {
                    "effective_notes": m_fa.get("effective_notes"),
                    "top3_pct": m_fa.get("top3_pct"),
                    "motif_pct": m_fa.get("motif_pct"),
                    "verdict_motif": verdict_motif(m_fa.get("motif_pct")),
                },
            }
        except Exception as e:
            print(f"BASELINE_FAILED: {e}", flush=True)
            results["fishaudio"] = {"error": str(e)}

    # --- Acceptance verdict -------------------------------------------
    motion = results["voicedesign"]["syllable_pitch"]["motion_st_per_syll"]
    motif_pct = results["voicedesign"]["measure_melody"]["motif_pct"]
    motion_ok = motion is not None and motion >= 2.0
    motif_ok = motif_pct is not None and motif_pct <= 40.0
    if motion_ok and motif_ok:
        results["acceptance_criterion_2"] = "PASS"
    elif (motion is not None and motion >= 1.6) or (motif_pct is not None and motif_pct <= 55.0):
        results["acceptance_criterion_2"] = "PARTIAL"
    else:
        results["acceptance_criterion_2"] = "FAIL"

    # --- Output -------------------------------------------------------
    if args.out_json:
        Path(args.out_json).write_text(json.dumps(results, indent=2, ensure_ascii=False))
        print(f"Written: {args.out_json}", flush=True)
    else:
        print(json.dumps(results, indent=2, ensure_ascii=False))

    return 0 if results["acceptance_criterion_2"] in ("PASS", "PARTIAL") else 1


if __name__ == "__main__":
    sys.exit(main())
