/-
# Grothendieck tribute — Part 20: Sheaf cohomology (Ext-based)

Alexandre Grothendieck (1928-2014).

Phase 5 extension (#2159, Epic #1646).

Parts 1-19 established the fundamentals: categories, sieves, topologies,
lattice operations, pullback identities, sheaf basics, covering closure,
calibration, subcanonicity, dense topologies, coverage generation, conservative
coherence, site points, schemes, Zariski schemes, constant sheaves, left exactness,
Cech cohomology, Mayer-Vietoris squares, internal hom of sheaves.

This module introduces **sheaf cohomology** for abelian sheaves on a site
(C, J), following Mathlib's Ext-based definition (SGA 4 II, Grothendieck 1957).
The cohomology H^n(F) is defined as the Ext-group from the constant sheaf with
values ULift Z to F, following Joel Riou's definition (2024) which realizes
the classical sheaf cohomology of SGA 4 II in Mathlib.

Key constructions bridged from Mathlib (`CategoryTheory.Sites.SheafCohomology.Basic`):

  - `Sheaf.H F n` : the nth cohomology group of an abelian sheaf F
  - `Sheaf.cohomologyPresheaf F n` : the presheaf U ↦ Ext^n(free(yoneda U), F)
  - `Sheaf.H' F n X` : degree-n cohomology at an object X
  - `Sheaf.H.equiv₀` : H^0(F) ≃+ F(T) when T is terminal (global sections)
  - `Sheaf.H.map` : the induced map on cohomology by a sheaf morphism
  - `Sheaf.functorH J n` : the cohomology functor Sheaf J AddCommGrp ⥤ AddCommGrp
  - Functoriality lemmas: map_id, map_comp, map_add
  - Vanishing: injective sheaf -> Subsingleton H^{n+1}, zero sheaf -> Subsingleton

This is the foundation of the cohomological machinery of Grothendieck toposes:
derived functors, spectral sequences, and their applications (Hodge theory,
number theory, algebraic geometry).

Epic #1646, Phase 5 (#2159), See #2159. All `sorry`s eliminated at creation.

### Accessibility note (Epics #1452/#1453)

This module exposes **2 noncomputable def + 3 theorem** on sheaf cohomology
(H^0 = global sections, functoriality, vanishing), progressive accessibility
by 8 thematic sections: (1) cohomology groups, (2) cohomology presheaf,
(3) degree-n cohomology at an object, (4) degree-zero cohomology and global
sections, (5) induced map on cohomology, (6) cohomology functor,
(7) vanishing results, (8) bridge theorems.

### i18n convention (EPIC #4980 ratified by user 2026-07-04)

This substantial module is paired with its English twin in the sibling file
`Basic_en.lean` (sibling pair model, see PR #6154 for the pilot on
`Utility.lean` and #6275/#6277/#6280/#6284/#6291 for the rollout continuity
Phase 2+). Namespace suffix `_en` applied to the EN file (anti-collision,
per code-style.md #4980). For the canonical French version, see `Basic.lean`.
-/

import Mathlib.CategoryTheory.Sites.SheafCohomology.Basic

universe w' w v u

namespace Grothendieck.SheafCohomology_en

open CategoryTheory Category Opposite Limits

variable {C : Type u} [Category.{v} C] {J : GrothendieckTopology C}

/-!
## 1. Sheaf cohomology groups

The cohomology group `Sheaf.H F n` of an abelian sheaf F in degree n is
defined as the Ext-group from the constant sheaf with values ULift Z to F:

  H^n(F) = Ext^n(constantSheaf J AddCommGrp (ULift Z), F)

This follows Mathlib's definition (Joel Riou, 2024) and corresponds to the
classical sheaf cohomology in SGA 4 II.

Requires `HasSheafify J AddCommGrp` and `HasExt (Sheaf J AddCommGrp)`.
-/

-- The nth cohomology group of an abelian sheaf F (Ext-based).
#check @CategoryTheory.Sheaf.H

/-!
## 2. The cohomology presheaf

Given an abelian sheaf F, `cohomologyPresheaf F n` is the presheaf
which sends U : C^op to the Ext-group from the free abelian sheaf
generated by yoneda.obj U to F. This is a presheaf of abelian groups.

When evaluated at a terminal object T, this recovers H^n(F) (up to
the equivalence `H.equiv_0`).
-/

-- The cohomology presheaf functor (bifunctor variant).
#check @CategoryTheory.Sheaf.cohomologyPresheafFunctor

-- The cohomology presheaf: U ↦ Ext^n(free(yoneda U), F).
#check @CategoryTheory.Sheaf.cohomologyPresheaf

/-!
## 3. Degree-n cohomology at an object

`Sheaf.H' F n X` is the degree-n sheaf cohomology of X with values in F,
defined as `(F.cohomologyPresheaf n).obj (op X)`.

This is the "local" version of cohomology -- it varies functorially in X.
-/

-- Degree-n cohomology of X with values in F.
#check @CategoryTheory.Sheaf.H'

/-!
## 4. Degree-zero cohomology and global sections

When C has a terminal object T, the degree-zero cohomology H^0(F) is
additively equivalent to the group of global sections F(T):

  H^0(F) =+ F(T)

via `H.equiv_0`. This is the sheaf-theoretic version of the familiar
identification H^0(X, F) = Gamma(X, F) in classical sheaf cohomology.

The equivalence is natural: a morphism f : F --> G induces a commutative
square relating H.map f 0 and f.app (op T).
-/

-- The additive equivalence H^0(F) =+ F(T) for terminal T.
#check @CategoryTheory.Sheaf.H.equiv₀

-- H.equiv_0 is natural in the sheaf argument.
#check @CategoryTheory.Sheaf.H.equiv₀_naturality

-- The symmetry of naturality for equiv_0.
#check @CategoryTheory.Sheaf.H.equiv₀_symm_naturality

/-!
## 5. The induced map on cohomology

Given a morphism f : F --> G of abelian sheaves, `H.map f n` is the
induced additive map H^n(F) ->+ H^n(G). This makes H^n a functor
from Sheaf J AddCommGrp to AddCommGrp.

Key properties:
  - H.map (1 F) n = id  (functoriality: identity)
  - H.map (f >> g) n = H.map g n . H.map f n  (functoriality: composition)
  - H.map (f + g) n x = H.map f n x + H.map g n x  (additivity)
-/

-- The induced map on cohomology by a sheaf morphism.
#check @CategoryTheory.Sheaf.H.map

-- Functoriality: H.map (1 F) n x = x.
#check @CategoryTheory.Sheaf.H.map_id_apply

-- Functoriality: H.map (f >> g) n x = H.map g n (H.map f n x).
#check @CategoryTheory.Sheaf.H.map_comp_apply

-- Additivity: H.map (f + g) n x = H.map f n x + H.map g n x.
#check @CategoryTheory.Sheaf.H.map_add_apply

-- Explicit unfolding: H.map f n x = x.comp (Ext.mk_0 f) (add_zero n).
#check @CategoryTheory.Sheaf.H.map_apply

/-!
## 6. The cohomology functor

`functorH J n` packages the cohomology groups into a functor:

  functorH J n : Sheaf J AddCommGrp ⥤ AddCommGrp

It sends F to H^n(F) and f to H.map f n. This functor is additive
(instance `(functorH J n).Additive`).
-/

-- The cohomology functor Sheaf J AddCommGrp >> AddCommGrp.
#check @CategoryTheory.Sheaf.functorH

-- Simps lemma: (functorH J n).map f = ofHom (H.map f n).
#check @CategoryTheory.Sheaf.functorH_map

/-!
## 7. Vanishing results

Two key vanishing results:

1. **Injective sheaf**: if F is injective, then H^{n+1}(F) is a subsingleton
   (at most one element) for all n. This reflects the classical fact that
   injective objects have no higher cohomology.
   (Instance in Mathlib: anonymous `instance [Injective F] : Subsingleton (H F (n + 1))`)

2. **Zero sheaf**: if F is the zero object, then H^n(F) is a subsingleton
   for all n. The cohomology of the zero sheaf vanishes in all degrees.
-/

-- Zero sheaf -> Subsingleton H^n(F).
#check @CategoryTheory.Sheaf.subsingleton_H_of_isZero

/-!
## 8. Bridge theorems

Bridge theorems connecting Mathlib's Ext-based cohomology to concrete verification.
-/

/-- Bridge theorem: degree-zero cohomology H^0(F) is additively equivalent
    to the global sections F(T) when T is terminal. This is the fundamental
    identification H^0 = Gamma in sheaf cohomology. -/

noncomputable def H0_equiv_global_sections
    (F : Sheaf J AddCommGrpCat.{w}) {T : C} (hT : IsTerminal T)
    [HasSheafify J AddCommGrpCat.{w}] [HasExt.{w'} (Sheaf J AddCommGrpCat.{w})] :
    CategoryTheory.Sheaf.H F 0 ≃+ F.obj.obj (op T) :=
  CategoryTheory.Sheaf.H.equiv₀ F hT

/-- Bridge theorem: the cohomology functor is additive. For any f : F --> G
    and g : F --> G, the induced map on cohomology satisfies
    H.map (f + g) n x = H.map f n x + H.map g n x. -/

theorem H_map_add {F G : Sheaf J AddCommGrpCat.{w}} (f g : F ⟶ G)
    [HasSheafify J AddCommGrpCat.{w}] [HasExt.{w'} (Sheaf J AddCommGrpCat.{w})]
    {n : ℕ} (x : CategoryTheory.Sheaf.H F n) :
    CategoryTheory.Sheaf.H.map (f + g) n x =
      CategoryTheory.Sheaf.H.map f n x + CategoryTheory.Sheaf.H.map g n x :=
  CategoryTheory.Sheaf.H.map_add_apply f g x

/-- Bridge theorem: the cohomology functor respects composition.
    H.map (f >> g) n = H.map g n . H.map f n. -/

theorem H_map_comp {F G G' : Sheaf J AddCommGrpCat.{w}} (f : F ⟶ G) (g : G ⟶ G')
    [HasSheafify J AddCommGrpCat.{w}] [HasExt.{w'} (Sheaf J AddCommGrpCat.{w})]
    {n : ℕ} (x : CategoryTheory.Sheaf.H F n) :
    CategoryTheory.Sheaf.H.map (f ≫ g) n x =
      CategoryTheory.Sheaf.H.map g n (CategoryTheory.Sheaf.H.map f n x) :=
  CategoryTheory.Sheaf.H.map_comp_apply f g x

/-- Bridge theorem: the cohomology functor respects identities.
    H.map (1 F) n x = x. -/

theorem H_map_id (F : Sheaf J AddCommGrpCat.{w})
    [HasSheafify J AddCommGrpCat.{w}] [HasExt.{w'} (Sheaf J AddCommGrpCat.{w})]
    {n : ℕ} (x : CategoryTheory.Sheaf.H F n) :
    CategoryTheory.Sheaf.H.map (𝟙 F) n x = x :=
  CategoryTheory.Sheaf.H.map_id_apply x

/-- Bridge construction: the cohomology presheaf at an object X.
    This is `(F.cohomologyPresheaf n).obj (op X)`, the degree-n
    cohomology of X with values in F. -/

noncomputable def cohomologyAt
    (F : Sheaf J AddCommGrpCat.{v}) (n : ℕ) (X : C)
    [HasSheafify J AddCommGrpCat.{v}] [HasExt.{w'} (Sheaf J AddCommGrpCat.{v})] :
    AddCommGrpCat.{w'} :=
  CategoryTheory.Sheaf.H' F n X

end Grothendieck.SheafCohomology_en
