"""Generate research.ipynb for Gaussian-Direction-Classifier project.

Walk-forward 5-fold x 4 seeds validation of GaussianNB direction prediction.
Reference: Hands-On AI Trading, Example 15 (Gaussian Naive Bayes).
"""
import json
import uuid

def md(lines):
    return {"cell_type": "markdown", "id": uuid.uuid4().hex[:8], "metadata": {}, "source": lines}

def code(lines):
    return {
        "cell_type": "code",
        "execution_count": None,
        "id": uuid.uuid4().hex[:8],
        "metadata": {},
        "outputs": [],
        "source": lines,
    }

cells = [
    md([
        "# GaussianNB Direction Classifier - Recherche Multi-Seed\n",
        "\n",
        "Validation walk-forward 5-fold x 4 seeds du classifieur Naive Bayes Gaussien\n",
        "pour la prediction de direction (hausse/baisse) sur actions US.\n",
        "\n",
        "**Reference** : *Hands-On AI Trading*, Example 15 (Jared Broad)\n",
        "\n",
        "**Approche** :\n",
        "- Features : rendements 2j, 5j, 10j, 21j par action\n",
        "- Cible : direction du rendement suivant (hausse=1, baisse=0)\n",
        "- Modele : GaussianNB (sklearn)\n",
        "- Validation : Walk-forward 5-fold x 4 seeds (0, 7, 42, 99)\n",
        "- Couts de transaction : 10bps par changement de position\n",
        "- Benchmark : Buy-and-Hold equity-weighted\n",
        "\n",
        "**Verdict honnete** : BEATS / NO BEATS / INCONCLUSIVE (edge >= 2sigma cross-seed)",
    ]),

    code([
        "import numpy as np\n",
        "import pandas as pd\n",
        "import matplotlib.pyplot as plt\n",
        "from sklearn.naive_bayes import GaussianNB\n",
        "from sklearn.preprocessing import StandardScaler\n",
        "from sklearn.metrics import accuracy_score\n",
        "import yfinance as yf\n",
        "import warnings\n",
        "warnings.filterwarnings('ignore')\n",
        "\n",
        "SEEDS = [0, 7, 42, 99]\n",
        "N_FOLDS = 5\n",
        "TCOST_BPS = 10\n",
        "FEATURE_WINDOWS = [2, 5, 10, 21]\n",
        "TICKERS = ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'NVDA', 'META', 'TSLA', 'NFLX']\n",
        "np.random.seed(42)\n",
        "print('Configuration OK')\n",
        "print(f'Tickers: {TICKERS}')\n",
        "print(f'Seeds: {SEEDS}, Folds: {N_FOLDS}, TCOST: {TCOST_BPS}bps')",
    ]),

    md([
        "## 1. Telechargement des Donnees\n",
        "\n",
        "Donnees quotidiennes pour 8 actions tech/growth US (2015-2025).",
    ]),

    code([
        "# Telecharger les donnees\n",
        "print('Telechargement des donnees...')\n",
        "raw = yf.download(TICKERS, start='2014-01-01', end='2025-01-01', auto_adjust=True)\n",
        "\n",
        "# Extraire les prix de cloture\n",
        "if isinstance(raw.columns, pd.MultiIndex):\n",
        "    prices = raw['Close'].copy()\n",
        "else:\n",
        "    prices = raw[['Close']].copy() if 'Close' in raw.columns else raw.copy()\n",
        "\n",
        "# Nettoyer\n",
        "prices = prices.dropna(axis=1, thresh=len(prices) * 0.9)\n",
        "prices = prices.dropna()\n",
        "\n",
        "print(f'Periode: {prices.index[0].date()} a {prices.index[-1].date()}')\n",
        "print(f'Actions: {list(prices.columns)}')\n",
        "print(f'Jours: {len(prices)}')\n",
        "print(f'\\nPrix les plus recents:')\n",
        "for t in prices.columns:\n",
        "    print(f'  {t}: ${float(prices[t].iloc[-1]):,.2f}')",
    ]),

    md([
        "## 2. Feature Engineering\n",
        "\n",
        "4 features par action : rendements 2j, 5j, 10j, 21j.\n",
        "Cible : direction du rendement du jour suivant.",
    ]),

    code([
        "# Calculer les features et cibles\n",
        "all_features = []\n",
        "all_targets = []\n",
        "all_dates = []\n",
        "all_tickers_list = []\n",
        "\n",
        "for ticker in prices.columns:\n",
        "    close = prices[ticker].values\n",
        "    n = len(close)\n",
        "    \n",
        "    # Features: rendements sur differentes fenetres\n",
        "    feats = np.full((n, len(FEATURE_WINDOWS)), np.nan)\n",
        "    for j, w in enumerate(FEATURE_WINDOWS):\n",
        "        feats[w:, j] = close[w:] / close[:-w] - 1\n",
        "    \n",
        "    # Cible: direction du rendement suivant\n",
        "    target = np.full(n, np.nan)\n",
        "    target[:-1] = (close[1:] > close[:-1]).astype(int)\n",
        "    \n",
        "    # Masque valide (apres warmup 21j)\n",
        "    valid = ~np.any(np.isnan(feats), axis=1) & ~np.isnan(target)\n",
        "    \n",
        "    all_features.append(feats[valid])\n",
        "    all_targets.append(target[valid])\n",
        "    all_dates.extend(prices.index[valid])\n",
        "    all_tickers_list.extend([ticker] * valid.sum())\n",
        "\n",
        "X_all = np.vstack(all_features)\n",
        "y_all = np.concatenate(all_targets)\n",
        "dates_all = pd.DatetimeIndex(all_dates)\n",
        "tickers_all = np.array(all_tickers_list)\n",
        "\n",
        "print(f'Features: {X_all.shape}')\n",
        "print(f'Cible: {y_all.mean():.3f} (taux de hausse)')\n",
        "print(f'Echantillons: {len(X_all)}')\n",
        "print(f'NaN residuels: {np.isnan(X_all).sum()}')",
    ]),

    md([
        "## 3. Walk-Forward Validation Multi-Seed\n",
        "\n",
        "Walk-forward 5-fold avec fenetre expansive.\n",
        "Strategie : chaque jour, predire direction de chaque action,\n",
        "investir dans les 3 actions avec la plus forte probabilite de hausse.\n",
        "Couts de transaction : 10bps par changement de position.",
    ]),

    code([
        "def simulate_portfolio(pred_probs_all, returns_all, tickers_arr, dates_arr,\n",
        "                      n_top=3, tcost_bps=10):\n",
        "    \"\"\"Simule un portefeuille long-only avec selection par probabilite.\"\"\"\n",
        "    tcost = tcost_bps / 10000\n",
        "    df = pd.DataFrame({\n",
        "        'prob': pred_probs_all,\n",
        "        'ret': returns_all,\n",
        "        'ticker': tickers_arr,\n",
        "        'date': dates_arr\n",
        "    })\n",
        "    \n",
        "    unique_dates = sorted(df['date'].unique())\n",
        "    position = set()\n",
        "    daily_returns = []\n",
        "    \n",
        "    for d in unique_dates:\n",
        "        day_data = df[df['date'] == d]\n",
        "        top_n = day_data.nlargest(n_top, 'prob')['ticker'].tolist()\n",
        "        new_pos = set(top_n)\n",
        "        \n",
        "        # Couts de transaction sur les changements\n",
        "        n_changes = len(position.symmetric_difference(new_pos))\n",
        "        cost = n_changes * tcost / 2\n",
        "        \n",
        "        # Rendement egal-pondere du portefeuille\n",
        "        day_rets = day_data[day_data['ticker'].isin(top_n)]['ret'].values\n",
        "        port_ret = np.mean(day_rets) - cost if len(day_rets) > 0 else 0\n",
        "        \n",
        "        daily_returns.append(port_ret)\n",
        "        position = new_pos\n",
        "    \n",
        "    daily_returns = np.array(daily_returns)\n",
        "    sharpe = np.mean(daily_returns) / (np.std(daily_returns) + 1e-10) * np.sqrt(252)\n",
        "    cum_ret = np.sum(daily_returns)\n",
        "    \n",
        "    return {\n",
        "        'cum_return': cum_ret,\n",
        "        'sharpe': sharpe,\n",
        "        'daily_returns': daily_returns,\n",
        "        'n_days': len(daily_returns)\n",
        "    }",
    ]),

    code([
        "# Walk-Forward Validation Multi-Seed\n",
        "print('='*60)\n",
        "print('WALK-FORWARD VALIDATION - GaussianNB Direction Classifier')\n",
        "print('='*60)\n",
        "\n",
        "# Rendements quotidiens par action\n",
        "returns_dict = {}\n",
        "for ticker in prices.columns:\n",
        "    close = prices[ticker].values\n",
        "    returns_dict[ticker] = np.diff(close) / close[:-1]\n",
        "returns_dates = prices.index[1:]\n",
        "returns_series = {t: pd.Series(returns_dict[t], index=returns_dates) for t in returns_dict}\n",
        "\n",
        "results_all = []\n",
        "n_total = len(X_all)\n",
        "fold_size = n_total // (N_FOLDS + 1)\n",
        "\n",
        "for SEED in SEEDS:\n",
        "    np.random.seed(SEED)\n",
        "    \n",
        "    for fold in range(N_FOLDS):\n",
        "        train_end = fold_size * (fold + 1)\n",
        "        test_start = train_end\n",
        "        test_end = min(train_end + fold_size, n_total)\n",
        "        \n",
        "        if test_end <= test_start:\n",
        "            continue\n",
        "        \n",
        "        X_train, X_test = X_all[:train_end], X_all[test_start:test_end]\n",
        "        y_train, y_test = y_all[:train_end], y_all[test_start:test_end]\n",
        "        \n",
        "        scaler = StandardScaler()\n",
        "        X_train_s = scaler.fit_transform(X_train)\n",
        "        X_test_s = scaler.transform(X_test)\n",
        "        \n",
        "        model = GaussianNB()\n",
        "        model.fit(X_train_s, y_train)\n",
        "        \n",
        "        prob_up = model.predict_proba(X_test_s)[:, 1]\n",
        "        pred_binary = (prob_up > 0.5).astype(int)\n",
        "        accuracy = accuracy_score(y_test, pred_binary)\n",
        "        \n",
        "        # Rendements pour la simulation\n",
        "        test_dates = dates_all[test_start:test_end]\n",
        "        test_tickers = tickers_all[test_start:test_end]\n",
        "        test_returns = np.array([\n",
        "            returns_series[t].get(d, 0.0) if t in returns_series else 0.0\n",
        "            for t, d in zip(test_tickers, test_dates)\n",
        "        ])\n",
        "        \n",
        "        trade_result = simulate_portfolio(\n",
        "            prob_up, test_returns, test_tickers, test_dates,\n",
        "            n_top=3, tcost_bps=TCOST_BPS)\n",
        "        \n",
        "        results_all.append({\n",
        "            'seed': SEED, 'fold': fold, 'model': 'GaussianNB',\n",
        "            'accuracy': accuracy,\n",
        "            'sharpe': trade_result['sharpe'],\n",
        "            'cum_return': trade_result['cum_return'],\n",
        "            'n_days': trade_result['n_days']\n",
        "        })\n",
        "        \n",
        "        print(f'Seed={SEED}, Fold={fold}: Acc={accuracy:.3f}, '\n",
        "              f'Sharpe={trade_result[\"sharpe\"]:.2f}, '\n",
        "              f'CumRet={trade_result[\"cum_return\"]:.4f}')\n",
        "\n",
        "print(f'\\nTotal configurations: {len(results_all)}')",
    ]),

    md([
        "## 4. Resultats et Verdict Multi-Seed\n",
        "\n",
        "Agreger les resultats walk-forward et calculer le verdict honnete.\n",
        "\n",
        "- Edge = Sharpe modele - Sharpe benchmark\n",
        "- z-score = edge / std(edge) cross-seed\n",
        "- Verdict : BEATS si z > 2, NO BEATS si z < -2, INCONCLUSIVE sinon",
    ]),

    code([
        "# Agreger les resultats\n",
        "df_results = pd.DataFrame(results_all)\n",
        "\n",
        "print('='*60)\n",
        "print('RESULTATS MULTI-SEED - GaussianNB Direction Classifier')\n",
        "print('='*60)\n",
        "\n",
        "seed_stats = df_results.groupby('seed').agg({\n",
        "    'accuracy': 'mean',\n",
        "    'sharpe': 'mean',\n",
        "    'cum_return': 'mean'\n",
        "}).round(4)\n",
        "\n",
        "print('\\nStats par seed (moyenne 5 folds):')\n",
        "print(seed_stats.to_string())\n",
        "\n",
        "# Benchmark: Buy-and-Hold equity-weighted\n",
        "bh_rets = np.mean([returns_dict[t] for t in prices.columns if t in returns_dict], axis=0)\n",
        "bh_sharpe = np.mean(bh_rets) / (np.std(bh_rets) + 1e-10) * np.sqrt(252)\n",
        "print(f'\\nBenchmark Buy-and-Hold Sharpe: {bh_sharpe:.2f}')\n",
        "\n",
        "seed_sharpes = seed_stats['sharpe'].values\n",
        "edges = seed_sharpes - bh_sharpe\n",
        "mean_edge = np.mean(edges)\n",
        "std_edge = np.std(edges, ddof=1) if len(edges) > 1 else 1.0\n",
        "z_score = mean_edge / std_edge if std_edge > 1e-10 else 0\n",
        "\n",
        "print(f'\\nEdge moyen vs BH: {mean_edge:.3f} (std: {std_edge:.3f})')\n",
        "print(f'z-score: {z_score:.2f}')\n",
        "\n",
        "if z_score > 2:\n",
        "    verdict = 'BEATS'\n",
        "elif z_score < -2:\n",
        "    verdict = 'NO BEATS'\n",
        "elif std_edge < 1e-6 and mean_edge < -0.1:\n",
        "    verdict = 'NO BEATS (deterministic)'\n",
        "elif std_edge < 1e-6 and mean_edge > 0.1:\n",
        "    verdict = 'INCONCLUSIVE (deterministic, edge>0 but untested)'\n",
        "else:\n",
        "    verdict = 'INCONCLUSIVE'\n",
        "\n",
        "print(f'\\nVERDICT: {verdict}')\n",
        "print(f'  Accuracy moyenne: {seed_stats[\"accuracy\"].mean():.3f}')\n",
        "print(f'  Sharpe moyen: {seed_stats[\"sharpe\"].mean():.2f}')\n",
        "print(f'  Sharpe range: [{seed_stats[\"sharpe\"].min():.2f}, {seed_stats[\"sharpe\"].max():.2f}]')\n",
        "print(f'  Benchmark BH Sharpe: {bh_sharpe:.2f}')\n",
        "print(f'  z-score edge: {z_score:.2f}')",
    ]),

    md([
        "## 5. Visualisation",
    ]),

    code([
        "# Visualisation\n",
        "fig, axes = plt.subplots(1, 3, figsize=(18, 5))\n",
        "\n",
        "# 1. Sharpe par seed\n",
        "colors = ['#2ecc71' if s > bh_sharpe else '#e74c3c' for s in seed_stats['sharpe']]\n",
        "axes[0].bar([f'Seed {s}' for s in seed_stats.index], seed_stats['sharpe'], color=colors, alpha=0.8)\n",
        "axes[0].axhline(y=bh_sharpe, color='navy', linestyle='--', label=f'BH Sharpe={bh_sharpe:.2f}')\n",
        "axes[0].set_title('Sharpe Ratio par Seed')\n",
        "axes[0].set_ylabel('Sharpe')\n",
        "axes[0].legend()\n",
        "axes[0].grid(True, alpha=0.3)\n",
        "\n",
        "# 2. Accuracy par fold/seed\n",
        "for seed in SEEDS:\n",
        "    seed_data = df_results[df_results['seed'] == seed]\n",
        "    axes[1].plot(seed_data['fold'], seed_data['accuracy'], 'o-', label=f'Seed {seed}')\n",
        "axes[1].axhline(y=0.5, color='gray', linestyle='--', label='Random (50%)')\n",
        "axes[1].set_title('Accuracy par Fold')\n",
        "axes[1].set_xlabel('Fold')\n",
        "axes[1].set_ylabel('Accuracy')\n",
        "axes[1].legend(fontsize=8)\n",
        "axes[1].grid(True, alpha=0.3)\n",
        "\n",
        "# 3. Distribution des cum_returns\n",
        "for seed in SEEDS:\n",
        "    seed_data = df_results[df_results['seed'] == seed]\n",
        "    axes[2].hist(seed_data['cum_return'], bins=5, alpha=0.5, label=f'Seed {seed}')\n",
        "axes[2].set_title('Distribution Rendements Cumules')\n",
        "axes[2].set_xlabel('Rendement Cumule')\n",
        "axes[2].legend(fontsize=8)\n",
        "axes[2].grid(True, alpha=0.3)\n",
        "\n",
        "plt.suptitle(f'GaussianNB Direction Classifier - Verdict: {verdict}', fontsize=14, fontweight='bold')\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print(f'\\nResume final:')\n",
        "print(f'  Modele: GaussianNB (sklearn)')\n",
        "print(f'  Features: rendements {FEATURE_WINDOWS}j par action')\n",
        "print(f'  Actions: {len(prices.columns)} tickers')\n",
        "print(f'  Validation: {N_FOLDS}-fold walk-forward x {len(SEEDS)} seeds')\n",
        "print(f'  Transaction costs: {TCOST_BPS}bps')\n",
        "print(f'  VERDICT: {verdict} (z={z_score:.2f})')",
    ]),
]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.10.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

output_path = "research.ipynb"
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f"Notebook generated: {output_path}")
print(f"Cells: {len(cells)} ({sum(1 for c in cells if c['cell_type']=='code')} code, {sum(1 for c in cells if c['cell_type']=='markdown')} markdown)")
