"""Generate research.ipynb for Mamba-Crypto-Ranking project.

Pure-PyTorch Selective State-Space Model (Mamba) for crypto direction prediction.
Reference: Gu & Dao 2023, "Mamba: Linear-Time Sequence Modeling with Selective State Spaces"
Comparison baselines: DLinear, TFT (from #944 results).
Walk-forward 5-fold x 4 seeds validation. CPU-only (po-2025 thermal constraint).
"""
import json
import uuid


def md(lines):
    return {"cell_type": "markdown", "id": uuid.uuid4().hex[:8], "metadata": {}, "source": lines}


def code(lines):
    return {
        "cell_type": "code",
        "execution_count": None,
        "id": uuid.uuid4().hex[:8],
        "metadata": {},
        "outputs": [],
        "source": lines,
    }


cells = [
    md([
        "# Mamba State-Space Crypto Direction Prediction\n",
        "\n",
        "Pure-PyTorch Selective SSM (Mamba, Gu & Dao 2023) pour la prediction de direction\n",
        "crypto (BTC-USD, ETH-USD). Comparaison a DLinear et TFT (resultats #944).\n",
        "\n",
        "**Architecture Mamba** : selective scan avec input-dependent discretization,\n",
        "sans custom CUDA kernels (pure PyTorch, CPU-compatible).\n",
        "\n",
        "**Approche** :\n",
        "- Donnees : BTC-USD + ETH-USD (yfinance, 2018-2024)\n",
        "- Features : log-returns, RSI(14), MACD signal, Bollinger position, lagged 1-5\n",
        "- Modeles : Mamba (selective SSM), DLinear, TFT (lite)\n",
        "- Validation : Walk-forward 5-fold x 4 seeds (0, 7, 42, 99)\n",
        "- Couts : 10bps par changement de position\n",
        "- CPU-only (po-2025 contrainte thermique)\n",
        "\n",
        "**Verdict honnete** : BEATS / NO BEATS / INCONCLUSIVE (edge >= 2sigma cross-seed)",
    ]),

    code([
        "import numpy as np\n",
        "import pandas as pd\n",
        "import torch\n",
        "import torch.nn as nn\n",
        "import torch.nn.functional as F\n",
        "import matplotlib.pyplot as plt\n",
        "import yfinance as yf\n",
        "from sklearn.preprocessing import StandardScaler\n",
        "import warnings\n",
        "warnings.filterwarnings('ignore')\n",
        "\n",
        "SEEDS = [0, 7, 42, 99]\n",
        "N_FOLDS = 5\n",
        "TCOST_BPS = 10\n",
        "SEQUENCE_LENGTH = 21\n",
        "TICKERS = ['BTC-USD', 'ETH-USD']\n",
        "DEVICE = torch.device('cpu')\n",
        "\n",
        "np.random.seed(42)\n",
        "torch.manual_seed(42)\n",
        "print(f'PyTorch {torch.__version__}')\n",
        "print(f'Device: {DEVICE}')\n",
        "print(f'Tickers: {TICKERS}')\n",
        "print(f'Seeds: {SEEDS}, Folds: {N_FOLDS}, SeqLen: {SEQUENCE_LENGTH}')",
    ]),

    md([
        "## 1. Telechargement et Feature Engineering\n",
        "\n",
        "Donnees quotidiennes BTC-USD + ETH-USD (2018-2024).\n",
        "Features : log-returns, RSI(14), MACD signal, Bollinger position, lagged returns 1-5.",
    ]),

    code([
        "# Telechargement\n",
        "print('Telechargement des donnees...')\n",
        "raw = yf.download(TICKERS, start='2017-01-01', end='2025-01-01', auto_adjust=True)\n",
        "\n",
        "if isinstance(raw.columns, pd.MultiIndex):\n",
        "    prices = raw['Close'].copy()\n",
        "else:\n",
        "    prices = raw[['Close']].copy()\n",
        "\n",
        "prices = prices.dropna()\n",
        "print(f'Periode: {prices.index[0].date()} a {prices.index[-1].date()}')\n",
        "print(f'Jours: {len(prices)}')\n",
        "print(f'Prix recents:')\n",
        "for t in prices.columns:\n",
        "    print(f'  {t}: ${float(prices[t].iloc[-1]):,.2f}')",
    ]),

    code([
        "def compute_features(close_prices):\n",
        "    \"\"\"Compute features from close prices.\"\"\"\n",
        "    c = close_prices.values.ravel()\n",
        "\n",
        "    # Log returns (index shifted by 1 for diff)\n",
        "    log_ret = np.log(c[1:] / c[:-1])\n",
        "    df = pd.DataFrame({'log_ret': log_ret}, index=close_prices.index[1:])\n",
        "\n",
        "    # RSI(14)\n",
        "    delta = df['log_ret'].diff()\n",
        "    gain = delta.where(delta > 0, 0).rolling(14).mean()\n",
        "    loss = (-delta.where(delta < 0, 0)).rolling(14).mean()\n",
        "    rs = gain / (loss + 1e-10)\n",
        "    df['rsi14'] = 100 - (100 / (1 + rs))\n",
        "\n",
        "    # MACD signal\n",
        "    ema12 = df['log_ret'].ewm(span=12).mean()\n",
        "    ema26 = df['log_ret'].ewm(span=26).mean()\n",
        "    df['macd_signal'] = (ema12 - ema26).ewm(span=9).mean()\n",
        "\n",
        "    # Bollinger position\n",
        "    sma20 = df['log_ret'].rolling(20).mean()\n",
        "    std20 = df['log_ret'].rolling(20).std()\n",
        "    df['boll_pos'] = (df['log_ret'] - sma20) / (std20 + 1e-10)\n",
        "\n",
        "    # Lagged returns\n",
        "    for lag in range(1, 6):\n",
        "        df[f'lag_{lag}'] = df['log_ret'].shift(lag)\n",
        "\n",
        "    # Target: direction of next day\n",
        "    df['target'] = (df['log_ret'].shift(-1) > 0).astype(int)\n",
        "\n",
        "    df = df.dropna()\n",
        "    return df\n",
        "\n",
        "\n",
        "# Build features per ticker then combine\n",
        "all_dfs = []\n",
        "for ticker in prices.columns:\n",
        "    feat_df = compute_features(prices[[ticker]])\n",
        "    feat_df['ticker'] = ticker\n",
        "    all_dfs.append(feat_df)\n",
        "\n",
        "data = pd.concat(all_dfs, axis=0).sort_index()\n",
        "feature_cols = ['log_ret', 'rsi14', 'macd_signal', 'boll_pos',\n",
        "                'lag_1', 'lag_2', 'lag_3', 'lag_4', 'lag_5']\n",
        "\n",
        "X_all = data[feature_cols].values.astype(np.float32)\n",
        "y_all = data['target'].values.astype(np.int64)\n",
        "dates_all = data.index\n",
        "tickers_all = data['ticker'].values\n",
        "\n",
        "print(f'Features: {X_all.shape}')\n",
        "print(f'Feature cols: {feature_cols}')\n",
        "print(f'Target balance: {y_all.mean():.3f} (hausse)')\n",
        "print(f'Samples: {len(X_all)}')",
    ]),

    md([
        "## 2. Modeles\n",
        "\n",
        "### 2a. Selective SSM (Mamba) — Pure PyTorch\n",
        "\n",
        "Implementation sans custom CUDA kernels :\n",
        "- Discretisation input-dependente (A, B, C, Delta sont fonctions de x)\n",
        "- Selective scan en Python pur (pas de parallelisme CUDA mais correct)\n",
        "- Architecture : input -> 2 layers Mamba -> linear head",
    ]),

    code([
        "class SelectiveSSMBlock(nn.Module):\n",
        "    \"\"\"Single selective state-space model block (Mamba-style, pure PyTorch).\"\"\"\n",
        "\n",
        "    def __init__(self, d_model, d_state=16, d_conv=4, expand=2):\n",
        "        super().__init__()\n",
        "        self.d_model = d_model\n",
        "        self.d_state = d_state\n",
        "        self.d_inner = int(expand * d_model)\n",
        "\n",
        "        # Input projection\n",
        "        self.in_proj = nn.Linear(d_model, self.d_inner * 2, bias=False)\n",
        "\n",
        "        # Conv for local context\n",
        "        self.conv1d = nn.Conv1d(\n",
        "            self.d_inner, self.d_inner,\n",
        "            kernel_size=d_conv, padding=d_conv - 1,\n",
        "            groups=self.d_inner\n",
        "        )\n",
        "\n",
        "        # SSM parameters (input-dependent)\n",
        "        self.x_proj = nn.Linear(self.d_inner, d_state * 2 + 1, bias=False)\n",
        "        self.dt_proj = nn.Linear(1, self.d_inner, bias=True)\n",
        "\n",
        "        # A parameter (diagonal, log space for stability)\n",
        "        A = torch.arange(1, d_state + 1, dtype=torch.float32).unsqueeze(0).expand(self.d_inner, -1)\n",
        "        self.A_log = nn.Parameter(torch.log(A))\n",
        "        self.D = nn.Parameter(torch.ones(self.d_inner))\n",
        "\n",
        "        # Output projection\n",
        "        self.out_proj = nn.Linear(self.d_inner, d_model, bias=False)\n",
        "        self.norm = nn.LayerNorm(d_model)\n",
        "\n",
        "    def forward(self, x):\n",
        "        \"\"\"\n",
        "        x: (batch, seq_len, d_model)\n",
        "        Returns: (batch, seq_len, d_model)\n",
        "        \"\"\"\n",
        "        B_sz, L, _ = x.shape\n",
        "        residual = x\n",
        "        x = self.norm(x)\n",
        "\n",
        "        xz = self.in_proj(x)  # (B, L, 2*d_inner)\n",
        "        x_proj, z = xz.chunk(2, dim=-1)  # each (B, L, d_inner)\n",
        "\n",
        "        # Conv for local context\n",
        "        x_conv = x_proj.transpose(1, 2)  # (B, d_inner, L)\n",
        "        x_conv = self.conv1d(x_conv)[:, :, :L].transpose(1, 2)  # (B, L, d_inner)\n",
        "        x_conv = F.silu(x_conv)\n",
        "\n",
        "        # SSM parameters from input\n",
        "        ssm_params = self.x_proj(x_conv)  # (B, L, d_state*2+1)\n",
        "        B_ssm = ssm_params[:, :, :self.d_state]  # (B, L, d_state)\n",
        "        C_ssm = ssm_params[:, :, self.d_state:self.d_state*2]  # (B, L, d_state)\n",
        "        dt = F.softplus(ssm_params[:, :, -1:])  # (B, L, 1)\n",
        "        dt = self.dt_proj(dt)  # (B, L, d_inner)\n",
        "\n",
        "        A = -torch.exp(self.A_log)  # (d_inner, d_state)\n",
        "\n",
        "        # Selective scan (sequential, CPU-safe)\n",
        "        y = self._selective_scan(x_conv, dt, A, B_ssm, C_ssm)\n",
        "        y = y + x_conv * self.D  # skip connection with D\n",
        "\n",
        "        # Gate\n",
        "        y = y * F.silu(z)\n",
        "        output = self.out_proj(y)\n",
        "        return output + residual\n",
        "\n",
        "    def _selective_scan(self, x, dt, A, B, C):\n",
        "        \"\"\"Selective scan: sequential state update (pure PyTorch).\"\"\"\n",
        "        B_sz, L, D = x.shape\n",
        "        N = self.d_state\n",
        "\n",
        "        # Discretize A and B\n",
        "        dA = torch.exp(dt.unsqueeze(-1) * A.unsqueeze(0).unsqueeze(0))  # (B, L, D, N)\n",
        "        dB = dt.unsqueeze(-1) * B.unsqueeze(2)  # (B, L, D, N)\n",
        "\n",
        "        # Sequential scan\n",
        "        h = torch.zeros(B_sz, D, N, device=x.device, dtype=x.dtype)\n",
        "        ys = []\n",
        "        for t in range(L):\n",
        "            h = h * dA[:, t] + x[:, t].unsqueeze(-1) * dB[:, t]\n",
        "            y_t = (h * C[:, t].unsqueeze(1)).sum(-1)  # (B, D)\n",
        "            ys.append(y_t)\n",
        "        return torch.stack(ys, dim=1)  # (B, L, D)\n",
        "\n",
        "\n",
        "class MambaModel(nn.Module):\n",
        "    \"\"\"Mamba-based classifier for direction prediction.\"\"\"\n",
        "\n",
        "    def __init__(self, input_dim, d_model=64, d_state=16, n_layers=2, n_classes=2):\n",
        "        super().__init__()\n",
        "        self.input_proj = nn.Linear(input_dim, d_model)\n",
        "        self.layers = nn.ModuleList([\n",
        "            SelectiveSSMBlock(d_model, d_state=d_state)\n",
        "            for _ in range(n_layers)\n",
        "        ])\n",
        "        self.head = nn.Sequential(\n",
        "            nn.LayerNorm(d_model),\n",
        "            nn.Linear(d_model, n_classes)\n",
        "        )\n",
        "\n",
        "    def forward(self, x):\n",
        "        \"\"\"x: (batch, seq_len, input_dim) -> (batch, seq_len, n_classes)\"\"\"\n",
        "        h = self.input_proj(x)\n",
        "        for layer in self.layers:\n",
        "            h = layer(h)\n",
        "        return self.head(h)\n",
        "\n",
        "print('Mamba model (pure PyTorch) defined')\n",
        "print(f'  d_model=64, d_state=16, n_layers=2')",
    ]),

    md([
        "### 2b. DLinear et TFT Lite\n",
        "\n",
        "Modeles de comparaison : DLinear (channel-independent linear) et TFT simplifie.",
    ]),

    code([
        "class DLinearModel(nn.Module):\n",
        "    \"\"\"DLinear: moving average + linear residual.\"\"\"\n",
        "\n",
        "    def __init__(self, seq_len, input_dim, n_classes=2):\n",
        "        super().__init__()\n",
        "        self.seq_len = seq_len\n",
        "        self.linear = nn.Linear(seq_len * input_dim, n_classes)\n",
        "\n",
        "    def forward(self, x):\n",
        "        B, L, D = x.shape\n",
        "        return self.linear(x.reshape(B, -1))\n",
        "\n",
        "\n",
        "class TFTLiteModel(nn.Module):\n",
        "    \"\"\"Simplified TFT: LSTM encoder + attention.\"\"\"\n",
        "\n",
        "    def __init__(self, input_dim, d_model=32, n_heads=2, n_classes=2):\n",
        "        super().__init__()\n",
        "        self.input_proj = nn.Linear(input_dim, d_model)\n",
        "        self.lstm = nn.LSTM(d_model, d_model, num_layers=1, batch_first=True)\n",
        "        self.attn = nn.MultiheadAttention(d_model, n_heads, batch_first=True)\n",
        "        self.head = nn.Sequential(\n",
        "            nn.Linear(d_model, d_model // 2),\n",
        "            nn.ReLU(),\n",
        "            nn.Linear(d_model // 2, n_classes)\n",
        "        )\n",
        "\n",
        "    def forward(self, x):\n",
        "        h = self.input_proj(x)\n",
        "        h, _ = self.lstm(h)\n",
        "        h2, _ = self.attn(h, h, h)\n",
        "        h = h + h2\n",
        "        return self.head(h[:, -1, :])  # last timestep\n",
        "\n",
        "print('DLinear + TFT Lite models defined')",
    ]),

    md([
        "## 3. Entrainement et Walk-Forward Validation\n",
        "\n",
        "Walk-forward 5-fold avec fenetre expansive.\n",
        "Sequence length = 21 jours, prediction au dernier timestep.\n",
        "Strategie : predire direction, investir si prob(hausse) > 0.5,\n",
        "couts de transaction 10bps par changement de position.",
    ]),

    code([
        "def create_sequences(X, y, seq_len):\n",
        "    \"\"\"Create overlapping sequences.\"\"\"\n",
        "    Xs, ys = [], []\n",
        "    for i in range(seq_len, len(X)):\n",
        "        Xs.append(X[i-seq_len:i])\n",
        "        ys.append(y[i])\n",
        "    return np.array(Xs), np.array(ys)\n",
        "\n",
        "\n",
        "def train_model(model, X_train, y_train, epochs, batch_size, device, lr=1e-3):\n",
        "    \"\"\"Train a model with early stopping.\"\"\"\n",
        "    model = model.to(device)\n",
        "    optimizer = torch.optim.Adam(model.parameters(), lr=lr)\n",
        "    criterion = nn.CrossEntropyLoss()\n",
        "\n",
        "    X_t = torch.FloatTensor(X_train).to(device)\n",
        "    y_t = torch.LongTensor(y_train).to(device)\n",
        "\n",
        "    best_loss = float('inf')\n",
        "    patience = 5\n",
        "    wait = 0\n",
        "\n",
        "    for epoch in range(epochs):\n",
        "        model.train()\n",
        "        indices = torch.randperm(len(X_t))\n",
        "        total_loss = 0\n",
        "        n_batches = 0\n",
        "\n",
        "        for i in range(0, len(X_t), batch_size):\n",
        "            batch_idx = indices[i:i+batch_size]\n",
        "            batch_X = X_t[batch_idx]\n",
        "            batch_y = y_t[batch_idx]\n",
        "\n",
        "            if hasattr(model, 'forward') and 'DLinear' in model.__class__.__name__:\n",
        "                logits = model(batch_X)  # DLinear uses all timesteps\n",
        "            elif 'TFTLite' in model.__class__.__name__:\n",
        "                logits = model(batch_X)  # TFT uses last timestep\n",
        "            else:\n",
        "                logits = model(batch_X)[:, -1, :]  # Mamba: last timestep\n",
        "\n",
        "            loss = criterion(logits, batch_y)\n",
        "            optimizer.zero_grad()\n",
        "            loss.backward()\n",
        "            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)\n",
        "            optimizer.step()\n",
        "\n",
        "            total_loss += loss.item()\n",
        "            n_batches += 1\n",
        "\n",
        "        avg_loss = total_loss / max(n_batches, 1)\n",
        "        if avg_loss < best_loss - 1e-4:\n",
        "            best_loss = avg_loss\n",
        "            wait = 0\n",
        "        else:\n",
        "            wait += 1\n",
        "            if wait >= patience:\n",
        "                break\n",
        "\n",
        "    return model\n",
        "\n",
        "\n",
        "def predict_direction(model, X_test, device):\n",
        "    \"\"\"Get probability of upward direction.\"\"\"\n",
        "    model.eval()\n",
        "    with torch.no_grad():\n",
        "        X_t = torch.FloatTensor(X_test).to(device)\n",
        "        if 'DLinear' in model.__class__.__name__:\n",
        "            logits = model(X_t)\n",
        "        elif 'TFTLite' in model.__class__.__name__:\n",
        "            logits = model(X_t)\n",
        "        else:\n",
        "            logits = model(X_t)[:, -1, :]\n",
        "        probs = F.softmax(logits, dim=-1)[:, 1].cpu().numpy()\n",
        "    return probs\n",
        "\n",
        "\n",
        "def simulate_strategy(pred_probs, actual_returns, tcost_bps=10):\n",
        "    \"\"\"Simulate long/flat strategy with transaction costs.\"\"\"\n",
        "    tcost = tcost_bps / 10000\n",
        "    position = 0\n",
        "    daily_rets = []\n",
        "\n",
        "    for i in range(len(pred_probs)):\n",
        "        new_pos = 1 if pred_probs[i] > 0.5 else 0\n",
        "        cost = abs(new_pos - position) * tcost\n",
        "        ret = new_pos * actual_returns[i] - cost\n",
        "        daily_rets.append(ret)\n",
        "        position = new_pos\n",
        "\n",
        "    daily_rets = np.array(daily_rets)\n",
        "    sharpe = np.mean(daily_rets) / (np.std(daily_rets) + 1e-10) * np.sqrt(252)\n",
        "    cum_ret = np.prod(1 + daily_rets) - 1\n",
        "    return {'sharpe': sharpe, 'cum_return': cum_ret, 'daily_returns': daily_rets}\n",
        "\n",
        "print('Training utilities defined')",
    ]),

    code([
        "# Build sequences\n",
        "X_seq, y_seq = create_sequences(X_all, y_all, SEQUENCE_LENGTH)\n",
        "# Align dates/tickers for the sequences\n",
        "seq_offset = SEQUENCE_LENGTH\n",
        "dates_seq = dates_all[seq_offset:]\n",
        "tickers_seq = tickers_all[seq_offset:]\n",
        "\n",
        "# Also need raw returns for simulation\n",
        "raw_returns = {}\n",
        "for t in prices.columns:\n",
        "    c = prices[t].values\n",
        "    raw_returns[t] = np.diff(c) / c[:-1]\n",
        "returns_dates = prices.index[1:]\n",
        "returns_series = {t: pd.Series(raw_returns[t], index=returns_dates) for t in raw_returns}\n",
        "\n",
        "print(f'Sequences: {X_seq.shape}')\n",
        "print(f'Target: {y_seq.shape}')\n",
        "print(f'Sequence length: {SEQUENCE_LENGTH}')",
    ]),

    md([
        "## 4. Walk-Forward Multi-Seed Validation",
    ]),

    code([
        "EPOCHS = 20\n",
        "BATCH_SIZE = 64\n",
        "INPUT_DIM = len(feature_cols)\n",
        "\n",
        "results_all = []\n",
        "n_total = len(X_seq)\n",
        "fold_size = n_total // (N_FOLDS + 1)\n",
        "\n",
        "print('='*60)\n",
        "print('WALK-FORWARD VALIDATION — Mamba vs DLinear vs TFT Lite')\n",
        "print('='*60)\n",
        "\n",
        "for SEED in SEEDS:\n",
        "    np.random.seed(SEED)\n",
        "    torch.manual_seed(SEED)\n",
        "\n",
        "    for fold in range(N_FOLDS):\n",
        "        train_end = fold_size * (fold + 1)\n",
        "        test_start = train_end\n",
        "        test_end = min(train_end + fold_size, n_total)\n",
        "\n",
        "        if test_end <= test_start:\n",
        "            continue\n",
        "\n",
        "        X_train, X_test = X_seq[:train_end], X_seq[test_start:test_end]\n",
        "        y_train, y_test = y_seq[:train_end], y_seq[test_start:test_end]\n",
        "\n",
        "        # Scale features\n",
        "        scaler = StandardScaler()\n",
        "        X_train_s = scaler.fit_transform(\n",
        "            X_train.reshape(-1, INPUT_DIM)).reshape(X_train.shape)\n",
        "        X_test_s = scaler.transform(\n",
        "            X_test.reshape(-1, INPUT_DIM)).reshape(X_test.shape)\n",
        "\n",
        "        fold_results = {'seed': SEED, 'fold': fold}\n",
        "\n",
        "        for model_name, model_cls, kwargs in [\n",
        "            ('Mamba', MambaModel,\n",
        "             {'input_dim': INPUT_DIM, 'd_model': 64, 'd_state': 16, 'n_layers': 2}),\n",
        "            ('DLinear', DLinearModel,\n",
        "             {'seq_len': SEQUENCE_LENGTH, 'input_dim': INPUT_DIM}),\n",
        "            ('TFT-Lite', TFTLiteModel,\n",
        "             {'input_dim': INPUT_DIM, 'd_model': 32, 'n_heads': 2}),\n",
        "        ]:\n",
        "            np.random.seed(SEED)\n",
        "            torch.manual_seed(SEED)\n",
        "            model = model_cls(**kwargs)\n",
        "            model = train_model(model, X_train_s, y_train, EPOCHS, BATCH_SIZE, DEVICE)\n",
        "\n",
        "            probs = predict_direction(model, X_test_s, DEVICE)\n",
        "\n",
        "            # Get actual returns for simulation\n",
        "            test_dates = dates_seq[test_start:test_end]\n",
        "            test_tickers = tickers_seq[test_start:test_end]\n",
        "            actual_rets = np.array([\n",
        "                returns_series[t].get(d, 0.0) if t in returns_series else 0.0\n",
        "                for t, d in zip(test_tickers, test_dates)\n",
        "            ])\n",
        "\n",
        "            trade_result = simulate_strategy(probs, actual_rets, TCOST_BPS)\n",
        "\n",
        "            results_all.append({\n",
        "                'seed': SEED, 'fold': fold, 'model': model_name,\n",
        "                'sharpe': trade_result['sharpe'],\n",
        "                'cum_return': trade_result['cum_return'],\n",
        "            })\n",
        "\n",
        "        # Progress print (last model in loop)\n",
        "        last = results_all[-1]\n",
        "        print(f'Seed={SEED} Fold={fold}: ' +\n",
        "              ', '.join(\n",
        "                  f\"{r['model']} S={r['sharpe']:.2f}\"\n",
        "                  for r in results_all[-3:]\n",
        "              ))\n",
        "\n",
        "print(f'\\nTotal configs: {len(results_all)}')",
    ]),

    md([
        "## 5. Resultats et Verdict Multi-Seed\n",
        "\n",
        "Agreger walk-forward par seed, comparer 3 baselines.\n",
        "Verdict : BEATS si edge >= 2sigma cross-seed.",
    ]),

    code([
        "df_results = pd.DataFrame(results_all)\n",
        "\n",
        "print('='*60)\n",
        "print('RESULTATS MULTI-SEED — Mamba vs DLinear vs TFT-Lite')\n",
        "print('='*60)\n",
        "\n",
        "seed_stats = df_results.groupby(['seed', 'model']).agg({\n",
        "    'sharpe': 'mean',\n",
        "    'cum_return': 'mean'\n",
        "}).round(4)\n",
        "\n",
        "print('\\nSharpe par seed et modele:')\n",
        "print(seed_stats['sharpe'].unstack().to_string())\n",
        "\n",
        "# Benchmark: Buy-and-Hold equal-weighted\n",
        "bh_daily = []\n",
        "for t in prices.columns:\n",
        "    bh_daily.append(raw_returns[t])\n",
        "bh_rets = np.mean(bh_daily, axis=0)\n",
        "bh_sharpe = np.mean(bh_rets) / (np.std(bh_rets) + 1e-10) * np.sqrt(252)\n",
        "print(f'\\nBenchmark BH Sharpe: {bh_sharpe:.2f}')\n",
        "\n",
        "# Per-model verdict\n",
        "model_sharpes = {}\n",
        "for model_name in df_results['model'].unique():\n",
        "    model_data = df_results[df_results['model'] == model_name]\n",
        "    seed_means = model_data.groupby('seed')['sharpe'].mean().values\n",
        "    model_sharpes[model_name] = seed_means\n",
        "\n",
        "print('\\n--- Verdicts par modele ---')\n",
        "for model_name, sharpes in model_sharpes.items():\n",
        "    edges = sharpes - bh_sharpe\n",
        "    mean_edge = np.mean(edges)\n",
        "    std_edge = np.std(edges, ddof=1) if len(edges) > 1 else 1.0\n",
        "    z = mean_edge / std_edge if std_edge > 1e-10 else 0\n",
        "\n",
        "    if z > 2:\n",
        "        verdict = 'BEATS'\n",
        "    elif z < -2:\n",
        "        verdict = 'NO BEATS'\n",
        "    else:\n",
        "        verdict = 'INCONCLUSIVE'\n",
        "\n",
        "    print(f'{model_name}: Sharpe={np.mean(sharpes):.3f}, '\n",
        "          f'Edge={mean_edge:.3f} (std={std_edge:.3f}), '\n",
        "          f'z={z:.2f} -> {verdict}')\n",
        "\n",
        "# Best model comparison\n",
        "best_model = max(model_sharpes.keys(), key=lambda m: np.mean(model_sharpes[m]))\n",
        "print(f'\\nBest model: {best_model} (Sharpe {np.mean(model_sharpes[best_model]):.3f})')\n",
        "print(f'BH baseline: {bh_sharpe:.3f}')",
    ]),

    md([
        "## 6. Visualisation",
    ]),

    code([
        "fig, axes = plt.subplots(1, 3, figsize=(18, 5))\n",
        "\n",
        "colors_map = {'Mamba': '#2196F3', 'DLinear': '#4CAF50', 'TFT-Lite': '#FF9800'}\n",
        "\n",
        "# 1. Sharpe par seed et modele\n",
        "for model_name in df_results['model'].unique():\n",
        "    model_data = df_results[df_results['model'] == model_name]\n",
        "    seed_means = model_data.groupby('seed')['sharpe'].mean()\n",
        "    axes[0].plot(seed_means.index, seed_means.values, 'o-',\n",
        "                 label=model_name, color=colors_map.get(model_name, 'gray'))\n",
        "axes[0].axhline(y=bh_sharpe, color='navy', linestyle='--',\n",
        "                label=f'BH Sharpe={bh_sharpe:.2f}')\n",
        "axes[0].set_title('Sharpe Ratio par Seed')\n",
        "axes[0].set_ylabel('Sharpe')\n",
        "axes[0].set_xlabel('Seed')\n",
        "axes[0].legend()\n",
        "axes[0].grid(True, alpha=0.3)\n",
        "\n",
        "# 2. Distribution des Sharpes (violin-style)\n",
        "model_names = list(df_results['model'].unique())\n",
        "sharpes_by_model = [df_results[df_results['model'] == m]['sharpe'].values\n",
        "                    for m in model_names]\n",
        "bp = axes[1].boxplot(sharpes_by_model, labels=model_names, patch_artist=True)\n",
        "for patch, name in zip(bp['boxes'], model_names):\n",
        "    patch.set_facecolor(colors_map.get(name, 'lightgray'))\n",
        "axes[1].axhline(y=bh_sharpe, color='navy', linestyle='--', label=f'BH={bh_sharpe:.2f}')\n",
        "axes[1].set_title('Distribution Sharpe (folds x seeds)')\n",
        "axes[1].set_ylabel('Sharpe')\n",
        "axes[1].legend()\n",
        "axes[1].grid(True, alpha=0.3)\n",
        "\n",
        "# 3. Cumulative returns par seed\n",
        "for model_name in df_results['model'].unique():\n",
        "    model_data = df_results[df_results['model'] == model_name]\n",
        "    seed_cumrets = model_data.groupby('seed')['cum_return'].mean()\n",
        "    axes[2].bar([f'{model_name}\\nS{s}' for s in seed_cumrets.index],\n",
        "                seed_cumrets.values, alpha=0.7,\n",
        "                color=colors_map.get(model_name, 'gray'))\n",
        "axes[2].set_title('Rendement Cumule Moyen par Seed')\n",
        "axes[2].set_ylabel('Cum Return')\n",
        "axes[2].grid(True, alpha=0.3)\n",
        "\n",
        "# Determine global verdict\n",
        "all_z = []\n",
        "for model_name, sharpes in model_sharpes.items():\n",
        "    edges = sharpes - bh_sharpe\n",
        "    mean_e = np.mean(edges)\n",
        "    std_e = np.std(edges, ddof=1) if len(edges) > 1 else 1.0\n",
        "    z = mean_e / std_e if std_e > 1e-10 else 0\n",
        "    all_z.append((model_name, z))\n",
        "\n",
        "best_z = max(all_z, key=lambda x: x[1])\n",
        "global_verdict = 'BEATS' if best_z[1] > 2 else ('NO BEATS' if best_z[1] < -2 else 'INCONCLUSIVE')\n",
        "\n",
        "plt.suptitle(f'Mamba Crypto Direction — Verdict: {global_verdict} (best z={best_z[1]:.2f}, {best_z[0]})',\n",
        "             fontsize=14, fontweight='bold')\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print(f'\\nResume final:')\n",
        "print(f'  Mamba: selective SSM (pure PyTorch, d_model=64, d_state=16, 2 layers)')\n",
        "print(f'  Baselines: DLinear, TFT-Lite, Buy-and-Hold')\n",
        "print(f'  Donnees: {TICKERS} (2018-2024)')\n",
        "print(f'  Features: {len(feature_cols)} ({INPUT_DIM} dim)')\n",
        "print(f'  Validation: {N_FOLDS}-fold WF x {len(SEEDS)} seeds')\n",
        "print(f'  Transaction costs: {TCOST_BPS}bps')\n",
        "print(f'  Device: {DEVICE} (CPU-only)')\n",
        "print(f'  VERDICT: {global_verdict}')",
    ]),
]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.10.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

output_path = "research.ipynb"
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f"Notebook generated: {output_path}")
print(f"Cells: {len(cells)} ({sum(1 for c in cells if c['cell_type']=='code')} code, {sum(1 for c in cells if c['cell_type']=='markdown')} markdown)")
