/-
Copyright (c) 2026 CoursIA. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Hommage Grothendieck — Part 48 : arrow forms of the topology generated by a pretopology

Alexandre Grothendieck (1928-2014).

Extension Phase 5 (#2159, EPIC #1646).

Parts 1-47 established the foundations: categories, sieves, topologies,
lattice laws, pullback identities, sheaf bases, covering closure,
calibration, subcanonicity, dense topologies, sheaves, internal hom,
Čech cohomology, Mayer-Vietoris limit, Kan extensions, adjunctions, monads,
equivalences, monoidal categories, the Grothendieck construction, the
direct/exceptional image, the arrow form of the covering, the coherence
laws of the pullback pseudo-functor, the indexed lattice laws, the arrow
form of the dense topologies, the arrow form of the pushforward-pullback
adjunction, of the bind and of the extremal topologies.

This part applies the guiding thread "arrow form" to the topology generated
by a pretopology. Mathlib defines the completion
`Pretopology.toGrothendieck` (a sieve is covering if it contains a family of
the pretopology) and the Galois adjunction `Pretopology.gi`, but no law gives
its arrow form: the relation `(K.toGrothendieck).Covers S f` is never
connected to the pretopology `K`. We fill the gap with the characteristic
arrow form (`covers_iff_of_pretopology`), its fallbacks on the identity and
the maximal sieve, the presentation by `Sieve.generate`, the monotonicity of
the generated topology and the laws of the Galois adjunction.
-/

import Mathlib.CategoryTheory.Sites.Pretopology

namespace Grothendieck.CoversOfPretopology_en

open CategoryTheory

/-!
## Section 1 : the arrow form of the generated topology

The completion `Pretopology.toGrothendieck` declares a sieve `S` covering on
`X` as soon as it contains a family `R` of the pretopology
(`Pretopology.mem_toGrothendieck`). In arrow form, this becomes:
`K.toGrothendieck` covers `f : Y ⟶ X` by `S` if and only if the pullback
`S.pullback f` contains a family `R ∈ K Y`. This law, absent from Mathlib, is
the heart of the bridge between a pretopology and the topology it generates.
-/

/-- The arrow form of the topology generated by a pretopology:
    `K.toGrothendieck` covers `f : Y ⟶ X` by `S` if and only if the pullback
    `S.pullback f` contains a family `R` of the pretopology at `Y`:
    `∃ R ∈ K Y, R ≤ (S.pullback f : Presieve Y)`.
    Proof: `covers_iff` reduces the cover to the membership of the pullback,
    which is exactly the definition of `toGrothendieck`
    (`Pretopology.mem_toGrothendieck`). -/
theorem covers_iff_of_pretopology {C : Type*} [Category C] [Limits.HasPullbacks C] {X Y : C} (K : Pretopology C)
    (S : Sieve X) (f : Y ⟶ X) :
    (K.toGrothendieck).Covers S f ↔ ∃ R ∈ K Y, R ≤ (S.pullback f : Presieve Y) := by
  rw [GrothendieckTopology.covers_iff]
  exact Pretopology.mem_toGrothendieck K Y (S.pullback f)

/-- The direct arrow form: a family `R ∈ K Y` contained in `S.pullback f`
    makes `K.toGrothendieck` covering.
    Proof: the direct implication of `covers_iff_of_pretopology`. -/
theorem covers_of_mem_pretopology {C : Type*} [Category C] [Limits.HasPullbacks C] {X Y : C} (K : Pretopology C)
    (S : Sieve X) (f : Y ⟶ X) {R : Presieve Y} (hR : R ∈ K Y)
    (hRS : R ≤ (S.pullback f : Presieve Y)) : (K.toGrothendieck).Covers S f := by
  exact (covers_iff_of_pretopology K S f).mpr ⟨R, hR, hRS⟩

/-- The special case where the witness family is the pullback itself: if
    `S.pullback f` is a family of `K` at `Y`, then `K.toGrothendieck` covers.
    Proof: `covers_of_mem_pretopology` with the witness `S.pullback f` and
    the reflexivity of the order. -/
theorem covers_self_of_mem_pretopology {C : Type*} [Category C] [Limits.HasPullbacks C] {X Y : C} (K : Pretopology C)
    (S : Sieve X) (f : Y ⟶ X) (h : (S.pullback f : Presieve Y) ∈ K Y) :
    (K.toGrothendieck).Covers S f := by
  exact
    covers_of_mem_pretopology K S f h
      (le_rfl : (S.pullback f : Presieve Y) ≤ (S.pullback f : Presieve Y))

/-!
## Section 2 : fallbacks on the identity and the maximal sieve

Two immediate fallbacks of the arrow form. On the identity, the pullback is
the sieve itself (`Sieve.pullback_id`): a sieve of the pretopology therefore
covers the identity. The maximal sieve `⊤` is always covering along any
arrow, because the pretopology always contains a witness — the singleton of
the identity, by `Pretopology.has_isos` — and `⊤` is the total family.
-/

/-- A sieve of the pretopology covers the identity: `(S : Presieve X) ∈ K X`
    implies that `K.toGrothendieck` covers `S (𝟙 X)`.
    Proof: `covers_iff_of_pretopology`, then the pullback along the identity
    is the sieve itself (`Sieve.pullback_id`); the witness is `S` and the
    order is reflexive. -/
theorem covers_id_of_mem_pretopology {C : Type*} [Category C] [Limits.HasPullbacks C] {X : C} (K : Pretopology C)
    (S : Sieve X) (h : (S : Presieve X) ∈ K X) : (K.toGrothendieck).Covers S (𝟙 X) := by
  rw [covers_iff_of_pretopology, Sieve.pullback_id]
  exact ⟨(S : Presieve X), h, (le_rfl : (S : Presieve X) ≤ (S : Presieve X))⟩

/-- The generated topology covers the maximal sieve on the identity:
    `(K.toGrothendieck).Covers ⊤ (𝟙 X)`.
    Proof: `covers_iff` then the maximal sieve belongs to every topology
    (`GrothendieckTopology.top_mem`), with `Sieve.pullback_top`. -/
theorem covers_top_id {C : Type*} [Category C] [Limits.HasPullbacks C] {X : C} (K : Pretopology C) :
    (K.toGrothendieck).Covers (⊤ : Sieve X) (𝟙 X) := by
  rw [GrothendieckTopology.covers_iff, Sieve.pullback_top]
  exact K.toGrothendieck.top_mem X

/-- The generated topology covers the maximal sieve along any arrow:
    `(K.toGrothendieck).Covers ⊤ f`.
    Proof: the arrow form reduces to a witness family; the pretopology always
    contains the singleton of the identity (`Pretopology.has_isos`), and the
    singleton is contained in `⊤`, the total family. -/
theorem covers_top_of_pretopology {C : Type*} [Category C] [Limits.HasPullbacks C] {X Y : C} (K : Pretopology C)
    (f : Y ⟶ X) : (K.toGrothendieck).Covers (⊤ : Sieve X) f := by
  rw [covers_iff_of_pretopology, Sieve.pullback_top]
  refine ⟨Presieve.singleton (𝟙 Y), K.has_isos (𝟙 Y), ?_⟩
  intro Z g hg
  trivial

/-!
## Section 3 : the presentation by `Sieve.generate`

A sieve is a family of arrows closed under precomposition; a pretopology is
naturally expressed on families (`Presieve`). The generator `Sieve.generate`
relates the two through the adjunction `Sieve.generate ⊣ Presieve.arrows`
(`Sieve.generate_le_iff`, `Sieve.le_generate`). The arrow form therefore also
rewrites as: `K.toGrothendieck` covers if and only if the pullback contains
the generator of a family of the pretopology.
-/

/-- The `generate` presentation of the arrow form: `K.toGrothendieck` covers
    `S f` if and only if there exists `R ∈ K Y` whose generator is contained
    in `S.pullback f`: `Sieve.generate R ≤ S.pullback f`.
    Proof: `covers_iff_of_pretopology` then the adjunction
    `Sieve.generate ⊣ Presieve.arrows` (`Sieve.generate_le_iff`). -/
theorem covers_iff_generate_of_pretopology {C : Type*} [Category C] [Limits.HasPullbacks C] {X Y : C}
    (K : Pretopology C) (S : Sieve X) (f : Y ⟶ X) :
    (K.toGrothendieck).Covers S f ↔ ∃ R ∈ K Y, Sieve.generate R ≤ S.pullback f := by
  rw [covers_iff_of_pretopology]
  constructor
  · rintro ⟨R, hR, hRS⟩
    exact ⟨R, hR, (Sieve.generate_le_iff R (S.pullback f)).mpr hRS⟩
  · rintro ⟨R, hR, hgen⟩
    exact ⟨R, hR, (Sieve.generate_le_iff R (S.pullback f)).mp hgen⟩

/-- A family of the pretopology covers the generator of its sieve:
    `R ∈ K X` implies that `K.toGrothendieck` covers `Sieve.generate R`
    along the identity.
    Proof: `covers_iff_of_pretopology`, the pullback along the identity is
    the sieve itself, and the witness `R` is contained in its generator
    (`Sieve.le_generate`). -/
theorem covers_generate_id_of_mem_pretopology {C : Type*} [Category C] [Limits.HasPullbacks C] {X : C}
    (K : Pretopology C) {R : Presieve X} (hR : R ∈ K X) :
    (K.toGrothendieck).Covers (Sieve.generate R) (𝟙 X) := by
  rw [covers_iff_of_pretopology, Sieve.pullback_id]
  exact ⟨R, hR, Sieve.le_generate R⟩

/-!
## Section 4 : monotonicity and Galois adjunction

The completion `toGrothendieck` is monotone in the pretopology, hence so is
the arrow form (`monotone_covers_of_le_pretopology`). The Galois adjunction
`Pretopology.gi` makes these laws structural: the generated topology is
smaller than a topology `J` if and only if the pretopology is contained in
the canonical pretopology of `J` (`toGrothendieck_le_iff`), and every
pretopology is contained in the pretopology generated by its completion
(`le_toGrothendieck_toPretopology`), of which we give the pointwise version
(`mem_toPretopology_of_mem`).
-/

/-- The arrow form is monotone in the pretopology: if `K₁ ≤ K₂` and
    `K₁.toGrothendieck` covers `S f`, then `K₂.toGrothendieck` covers it too.
    Proof: both arrow forms reduce to the existence of a witness family;
    `Pretopology.le_def` propagates the membership from `K₁` to `K₂`. -/
theorem monotone_covers_of_le_pretopology {C : Type*} [Category C] [Limits.HasPullbacks C] {X Y : C}
    {K₁ K₂ : Pretopology C} (h : K₁ ≤ K₂) (S : Sieve X) (f : Y ⟶ X)
    (hC : (K₁.toGrothendieck).Covers S f) : (K₂.toGrothendieck).Covers S f := by
  rw [covers_iff_of_pretopology] at hC ⊢
  rcases hC with ⟨R, hR, hRS⟩
  exact ⟨R, (Pretopology.le_def.mp h) Y hR, hRS⟩

/-- The universal character of the completion: `K.toGrothendieck ≤ J` if and
    only if `K ≤ J.toPretopology` — the canonical pretopology of `J`.
    Proof: the Galois connection of `Pretopology.gi`. -/
theorem toGrothendieck_le_iff {C : Type*} [Category C] [Limits.HasPullbacks C] (K : Pretopology C)
    (J : GrothendieckTopology C) : K.toGrothendieck ≤ J ↔ K ≤ J.toPretopology := by
  exact (Pretopology.gi C).gc K J

/-- Every pretopology is contained in the pretopology generated by its
    completion: `K ≤ K.toGrothendieck.toPretopology`.
    Proof: the Galois connection of `Pretopology.gi` applied to `le_rfl` —
    `K.toGrothendieck ≤ K.toGrothendieck` is equivalent, by the universal
    character, to `K ≤ K.toGrothendieck.toPretopology`. -/
theorem le_toGrothendieck_toPretopology {C : Type*} [Category C] [Limits.HasPullbacks C] (K : Pretopology C) :
    K ≤ K.toGrothendieck.toPretopology := by
  exact ((Pretopology.gi C).gc K (K.toGrothendieck)).mp le_rfl

/-- The pointwise version of the unit: a family `R ∈ K X` generates a sieve
    covering for the generated topology: `Sieve.generate R ∈ K.toGrothendieck X`.
    Proof: `Pretopology.mem_toGrothendieck` reduces the membership to the
    existence of a witness of the pretopology in the generator; the witness
    is `R` itself, contained in its generator (`Sieve.le_generate`). -/
theorem mem_toPretopology_of_mem {C : Type*} [Category C] [Limits.HasPullbacks C] {X : C} (K : Pretopology C)
    {R : Presieve X} (hR : R ∈ K X) : Sieve.generate R ∈ K.toGrothendieck X := by
  rw [Pretopology.mem_toGrothendieck]
  exact ⟨R, hR, Sieve.le_generate R⟩

end Grothendieck.CoversOfPretopology_en
