/-
Copyright (c) 2026 CoursIA. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# A tribute to Grothendieck — Part 69: arrow form of the étale topology

Alexander Grothendieck (1928-2014).

Extension Phase 5 (#2159, EPIC #1646).

Parts 1-68 established the fundamentals: categories, sieves, topologies,
lattice laws, pullback identities, bases of sheaves, covering closure,
calibration, subcanonicity, dense topologies, sheaves, internal hom,
Cech cohomology, Mayer-Vietoris limits, Kan extensions, adjunctions,
monads, equivalences, monoidal categories, the Grothendieck construction,
the direct/exceptional image, the arrow form of covering, coherence laws
of the pullback pseudofunctor, indexed lattice laws, the arrow form of the
dense and extremal topologies, of the pushforward-pullback adjunction, of
bind, of the topology generated by a pretopology, of the topology induced
along a functor, of functors preserving covers, of the composition laws of
these functors, of the topology generated by a coverage, of the topology
generated by a precoverage, of the Zariski topology on schemes, of the
atomic topology, of the subobject classifier, of the Lawvere–Tierney
topology and its dictionary, of continuous functors and the comparison
lemma, of the Plus construction, of the product-equalizer sheaf condition
and its characterizations, of the topology spectrum of a presheaf, of the
local surjectivity spectrum, and of the topology of a topological space.

This part applies the "arrow form" guiding thread to the **étale topology**
`Scheme.etaleTopology` — the topology of étale sites, the heart of the étale
cohomology of SGA 4-½ and of the Weil program Grothendieck architected.
Mathlib defines `etaleTopology := grothendieckTopology @Etale` (the topology
generated by jointly surjective families of étale maps), provides the
pointwise bridge `mem_grothendieckTopology_iff` (membership = existence of
an étale cover refining the sieve) and the comparison
`zariskiTopology_le_etaleTopology`, but **no law connects the étale
topology to the arrow form `J.Covers`**. We fill the gap with eight
theorems:

  - `etale_topology_eq_pretopology`: definitional bridge, `etaleTopology =
    etalePretopology.toGrothendieck` (exact mirror of `zariskiTopology_eq`);
  - `covers_iff_etale` (central, P54/P56 mold instantiated): for schemes
    `X Y`, an arrow `f : Y ⟶ X` and a sieve `S` on `X`,
    `etaleTopology.Covers S f ↔ ∃ 𝒰 : Scheme.Cover.{u}
    Scheme.etalePrecoverage Y, Presieve.ofArrows 𝒰.X 𝒰.f ≤ S.pullback f`
    — arrow covering is tested on `Y` by the existence of an étale
    covering family refining the pullback;
  - `covers_etale_of_cover`: the constructive direction of the central one;
  - `zariski_covers_etale`: every Zariski cover is an étale cover (arrow
    corollary of `zariskiTopology_le_etaleTopology` — open immersions are
    étale);
  - `covers_etale_of_mem`: any arrow of `S` covers any arrow;
  - `covers_etale_precomp`: stability under precomposition;
  - `covers_etale_id`: pointwise fallout at the identity;
  - `covers_etale_top`: the maximal sieve covers any arrow.

The guiding thread: every pointwise statement `S ∈ J X` has an arrow-form
twin `J.Covers S f` (by `covers_iff`, `S.pullback f ∈ J Y`). After the
dense topology (P44), the coherent, regular and extensive topologies
(P55a-c), the Zariski topology (P56) and the atomic topology (P57), the
étale topology carries on the series of named topologies — and it is the
one that carries Grothendieck's name in the history of mathematics.

i18n convention (EPIC #4980 ratified 2026-07-04): this module is paired
with its French twin in the sibling file `CoversEtaleArrow.lean` (sibling
pair pattern, see PR #6154 for the pilot on `Utility.lean`). The `_en`
suffix is applied to the namespace of this file (anti-collision, per
code-style.md #4980). Theorem statements, lemma names, Lean tactics and
Mathlib references remain in English; only the docstrings `/-- ... -/`
and the comments `-- ...` differ between the two files (byte-identity
preserved).
-/

import Mathlib.AlgebraicGeometry.Sites.Etale

namespace Grothendieck.CoversEtaleArrow_en

open CategoryTheory AlgebraicGeometry

universe u

/-!
## Section 1: the definitional bridge and the central arrow form

Mathlib's étale topology is an `abbrev` over `(precoverage @Etale).toGrothendieck`.
We first establish the bridge to the pretopology (mirror of `zariskiTopology_eq`),
then the central arrow form: `S` covers `f` for `etaleTopology` if and only
if the pullback `S.pullback f` contains a jointly surjective family of
étale maps (a `Scheme.Cover.{u} Scheme.etalePrecoverage Y`).
-/

/-- Definitional bridge: the étale topology is the topology generated by
    the étale pretopology — the exact mirror of `zariskiTopology_eq`.
    Proof: `Precoverage.toGrothendieck_toPretopology_eq_toGrothendieck`
    relates the two generation paths. -/
theorem etale_topology_eq_pretopology :
    Scheme.etaleTopology.{u} = Scheme.etalePretopology.toGrothendieck :=
  Precoverage.toGrothendieck_toPretopology_eq_toGrothendieck.symm

/-- Arrow form of the étale topology: `etaleTopology.Covers S f` if and
    only if there exists an étale cover `𝒰` of `Y` whose family of arrows
    refines the pullback `S.pullback f`.
    Proof: `covers_iff` reduces the left-hand side to `S.pullback f ∈
    etaleTopology Y`, then `mem_grothendieckTopology_iff` (membership in
    the topology generated by `@Etale` is the existence of a refining
    cover) concludes. -/
theorem covers_iff_etale {X Y : Scheme.{u}} (S : Sieve X) (f : Y ⟶ X) :
    Scheme.etaleTopology.Covers S f ↔
      ∃ 𝒰 : Scheme.Cover.{u} Scheme.etalePrecoverage Y,
        Presieve.ofArrows 𝒰.X 𝒰.f ≤ S.pullback f := by
  rw [GrothendieckTopology.covers_iff]
  exact Scheme.mem_grothendieckTopology_iff (P := @Etale)

/-- Constructive direction of the central theorem: an explicit étale cover
    of `Y` refining `S.pullback f` witnesses the arrow cover. -/
theorem covers_etale_of_cover {X Y : Scheme.{u}} (S : Sieve X) (f : Y ⟶ X)
    (𝒰 : Scheme.Cover.{u} Scheme.etalePrecoverage Y)
    (h : Presieve.ofArrows 𝒰.X 𝒰.f ≤ S.pullback f) :
    Scheme.etaleTopology.Covers S f :=
  (covers_iff_etale S f).2 ⟨𝒰, h⟩

/-!
## Section 2: monotonicity Zariski → étale

`zariskiTopology_le_etaleTopology` says the Zariski topology is coarser:
every open immersion is étale (`IsOpenImmersion → Etale`), hence every
Zariski cover is an étale cover. The arrow form of this comparison is an
immediate transport by `covers_iff`.
-/

/-- Every Zariski arrow cover is an étale arrow cover:
    `zariskiTopology.Covers S f → etaleTopology.Covers S f`.
    Proof: `covers_iff` on both sides, then `zariskiTopology_le_etaleTopology`
    transports the membership of the pullback. -/
theorem zariski_covers_etale {X Y : Scheme.{u}} (S : Sieve X) (f : Y ⟶ X)
    (h : Scheme.zariskiTopology.Covers S f) :
    Scheme.etaleTopology.Covers S f := by
  rw [GrothendieckTopology.covers_iff] at h ⊢
  exact Scheme.zariskiTopology_le_etaleTopology Y h

/-!
## Section 3: witness arrows, stability, identity

Three consequences of sieve calculus, independent of the étale specifics
(they hold for any topology, but are stated here for `etaleTopology` as
laws of the étale arrow form): one *witness* arrow belonging to `S`
suffices, the arrow cover is stable under precomposition, and the form
above the identity falls back to pointwise membership.
-/

/-- Any arrow of `S` covers any arrow towards `X` for the étale topology:
    `S f → etaleTopology.Covers S f`.
    Proof: `S f` forces `S.pullback f = ⊤` (`Sieve.pullback_eq_top_of_mem`),
    and the maximal sieve belongs to any topology (`top_mem`). -/
theorem covers_etale_of_mem {X Y : Scheme.{u}} (S : Sieve X) {f : Y ⟶ X}
    (h : S f) :
    Scheme.etaleTopology.Covers S f := by
  rw [GrothendieckTopology.covers_iff, Sieve.pullback_eq_top_of_mem S h]
  exact GrothendieckTopology.top_mem Scheme.etaleTopology Y

/-- The étale arrow form is stable under precomposition: if `S` covers
    `f : Y ⟶ X`, then `S` also covers `g ≫ f` for any `g : Z ⟶ Y`.
    Proof: `covers_iff` on both sides, then `Sieve.pullback_comp`
    identifies `S.pullback (g ≫ f)` with `(S.pullback f).pullback g`, and
    `pullback_stable` of the topology concludes. -/
theorem covers_etale_precomp {X Y Z : Scheme.{u}} (S : Sieve X)
    (f : Y ⟶ X) (g : Z ⟶ Y) :
    Scheme.etaleTopology.Covers S f →
      Scheme.etaleTopology.Covers S (g ≫ f) := by
  intro h
  rw [GrothendieckTopology.covers_iff] at h ⊢
  rw [Sieve.pullback_comp]
  exact Scheme.etaleTopology.pullback_stable g h

/-- The étale arrow form above the identity coincides with pointwise
    membership: `etaleTopology.Covers S (𝟙 X) ↔ S ∈ etaleTopology X`.
    Proof: `covers_iff` then `Sieve.pullback_id`. -/
theorem covers_etale_id {X : Scheme.{u}} (S : Sieve X) :
    Scheme.etaleTopology.Covers S (𝟙 X) ↔
      S ∈ Scheme.etaleTopology X := by
  rw [GrothendieckTopology.covers_iff, Sieve.pullback_id]

/-- The maximal sieve covers any arrow for the étale topology:
    `etaleTopology.Covers ⊤ f`.
    Proof: `covers_iff` then `Sieve.pullback_top`, and `top_mem` concludes. -/
theorem covers_etale_top {X Y : Scheme.{u}} (f : Y ⟶ X) :
    Scheme.etaleTopology.Covers ⊤ f := by
  rw [GrothendieckTopology.covers_iff, Sieve.pullback_top]
  exact GrothendieckTopology.top_mem Scheme.etaleTopology Y

end Grothendieck.CoversEtaleArrow_en
