/-
Copyright (c) 2026 CoursIA. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Grothendieck tribute — Part 56: arrow form of the Zariski topology

Alexandre Grothendieck (1928-2014).

Extension Phase 5 (#2159, EPIC #1646).

Parts 1-55 established the fundamentals: categories, sieves, topologies,
lattice laws, pullback identities, bases of sheaves, covering closure,
calibration, subcanonicity, dense topologies, sheaves, internal hom,
Cech cohomology, Mayer-Vietoris limits, Kan extensions, adjunctions,
monads, equivalences, monoidal categories, the Grothendieck construction,
the direct/exceptional image, the arrow form of coverage, the coherence
laws of the pullback pseudofunctor, the indexed lattice laws, the arrow
form of the dense, extreme topologies, of the pushforward-pullback
adjunction, of the bind, of the topology generated by a pretopology,
of the topology induced along a functor, of cover-preserving functors,
of the composition laws of these functors, of the topology generated
by a `Coverage`-style coverage, and of the topology generated by a
precoverage.

This part applies the "arrow form" thread to the **Zariski topology on
the category of schemes** — the first *named* concrete topology of the
series (after the dense topology of Part 44, defined on an abstract
category). Mathlib provides `Scheme.zariskiPretopology :=
pretopology @IsOpenImmersion`, the bridge `Scheme.zariskiTopology_eq`
(`zariskiTopology = zariskiPretopology.toGrothendieck`) and the
pointwise characterization `Pretopology.mem_toGrothendieck`, but **no
law connects the Zariski topology to the arrow form** `J.Covers`. We
fill the gap with six original theorems:

  - `covers_iff_zariski` (central, P54 template instantiated): for
    schemes `X Y`, an arrow `f : Y ⟶ X` and a sieve `S` on `X`,
    `Scheme.zariskiTopology.Covers S f ↔ ∃ R ∈ Scheme.zariskiPretopology Y,
    R ≤ (S.pullback f).arrows` — arrow coverage is tested on `Y` by the
    existence of a covering family of open immersions refining the
    pullback.
  - `covers_iff_exists_cover` (Zariski-specific, signature theorem):
    `Scheme.zariskiTopology.Covers S f ↔ ∃ 𝒰 : Y.Cover (precoverage
    IsOpenImmersion), Presieve.ofArrows 𝒰.X 𝒰.f ≤ S.pullback f` — in
    the world of schemes, covering means **being refined by a concrete
    open cover** (`Scheme.Cover`). This is the geometric
    characterization of the arrow form, absent from the generic level
    of Parts 52-54 (which operate on an abstract pretopology, with no
    concrete "cover" object).
  - `covers_zariski_of_mem` (base case): if `R` is a covering family
    for the Zariski pretopology, the sieve it generates covers the
    identity.
  - `covers_zariski_of_mem_arrow` (generalized case): the coverage
    generated by `R ∈ zariskiPretopology X` covers any arrow
    `f : Y ⟶ X` — the refinement descends to `Y` via `pullbackArrows`,
    the base-change stability of the pretopology.
  - `covers_zariski_top`: the trivial coverage `⊤` covers any arrow —
    the witness is `Presieve.singleton (𝟙 Y)`, admitted by the
    `has_isos` axiom of pretopologies (the identity is an open
    immersion).
  - `covers_iff_pullback_zariski` (pointwise fallout): covering along
    the identity is equivalent to belonging to the topology.

Each proof is a **real tactic proof** (MED vein): Mathlib axioms
(`GrothendieckTopology.covers_iff`, `Scheme.zariskiTopology_eq`,
`Pretopology.mem_toGrothendieck`, `Scheme.mem_grothendieckTopology_iff`,
`Sieve.pullback_id`, `Sieve.le_generate`, `Sieve.generate_le_iff`,
`Sieve.pullbackArrows_comm`, `Pretopology.pullbacks`, `Pretopology.has_isos`,
`GrothendieckTopology.covering_iff_covers_id`) composed into a concrete
instantiation. No proof is a re-export or an unfold.

### Autonomy with respect to Part 54

Part 54 (`CoversPretopologyArrow`, generic arrow form for
`Pretopology.toGrothendieck`) is not merged at the time of writing:
this module is **autonomous on `main`** — it imports no feature branch
and reinstalls locally the three tactics of the template, instantiated
at `K := Scheme.zariskiPretopology`. When Part 54 merges, theorems 1
and 3-6 will follow from it by rewriting; theorem 2
(`covers_iff_exists_cover`) will remain specific, since `Scheme.Cover`
has no analogue at the generic level.

EPIC #1646, Phase 5 (#2159). All `sorry`s eliminated at creation.

### i18n convention (EPIC #4980 ratified by user 2026-07-04)

This module is paired with its French twin in the sibling file
`CoversZariskiArrow.lean` (sibling pair model, see PR #6154 for the
pilot on `Utility.lean`). The `_en` namespace suffix is applied to this
EN file (anti-collision, per code-style.md #4980). Theorem statements,
lemma names, Lean tactics and Mathlib references remain in English;
only the `/-- ... -/` docstrings and `-- ...` comments differ between
the two files (byte-identity preservation).
-/

import Mathlib.AlgebraicGeometry.Sites.BigZariski

namespace Grothendieck.CoversZariskiArrow_en

open CategoryTheory Limits AlgebraicGeometry

universe u

/-!
## Section 1: the central bridge — arrow form ↔ test on the pullback target

The Zariski topology is the fundamental example of a Grothendieck
topology arising from a pretopology: `Scheme.zariskiPretopology :=
pretopology @IsOpenImmersion` (covering families are jointly
surjective families of open immersions), and `Scheme.zariskiTopology_eq`
identifies the generated topology. The arrow form
`J.Covers S f ↔ S.pullback f ∈ J Y` (Mathlib `covers_iff`) combines
with `Pretopology.mem_toGrothendieck` (membership in the generated
topology means containing a covering family) to give the concrete test:
`Covers S f` iff there exists a covering family of open immersions on
`Y` refining the pullback of `S` along `f`.
-/

/-- Central bridge: the arrow form for the Zariski topology is
    equivalent to the existential test on the pretopology of the target:
    `Scheme.zariskiTopology.Covers S f ↔ ∃ R ∈ Scheme.zariskiPretopology Y,
    R ≤ (S.pullback f).arrows`.
    Proof: `covers_iff` reduces to `S.pullback f ∈ zariskiTopology Y`,
    `zariskiTopology_eq` moves to `zariskiPretopology.toGrothendieck`,
    then `Pretopology.mem_toGrothendieck` identifies with the existence
    of a covering family `R` above the pullback. -/
theorem covers_iff_zariski {X Y : Scheme.{u}} (S : Sieve X) (f : Y ⟶ X) :
    Scheme.zariskiTopology.Covers S f ↔
      ∃ R ∈ Scheme.zariskiPretopology Y, R ≤ (S.pullback f).arrows := by
  rw [GrothendieckTopology.covers_iff, Scheme.zariskiTopology_eq]
  exact Pretopology.mem_toGrothendieck _ _ _

/-!
## Section 2: Zariski specificity — the open-cover characterization

This is the contribution absent from the generic level of Parts 52-54:
in the category of schemes, the Zariski pretopology comes from a
morphism property (`IsOpenImmersion`), and Mathlib characterizes
membership in the generated topology by the existence of a **concrete
cover** (`Scheme.Cover`, an indexed family of jointly surjective open
immersions) whose generated sieve refines `S`. In arrow form:
`Covers S f` iff an open cover of `Y` refines the pullback. This is
the formulation a geometer uses: covering a scheme means exhibiting an
open cover.
-/

/-- Zariski specificity (signature theorem): the arrow form for the
    Zariski topology is equivalent to the existence of a concrete open
    cover of the target:
    `Scheme.zariskiTopology.Covers S f ↔ ∃ 𝒰 : Y.Cover (precoverage
    IsOpenImmersion), Presieve.ofArrows 𝒰.X 𝒰.f ≤ S.pullback f`.
    Proof: `covers_iff` reduces to the pointwise level on `Y`, then
    `Scheme.mem_grothendieckTopology_iff` (Mathlib,
    `AlgebraicGeometry.Sites.Pretopology`) identifies membership with
    the existence of a `Scheme.Cover` by open immersions refining the
    sieve. -/
theorem covers_iff_exists_cover {X Y : Scheme.{u}} (S : Sieve X) (f : Y ⟶ X) :
    Scheme.zariskiTopology.Covers S f ↔
      ∃ 𝒰 : Scheme.Cover.{u} (Scheme.precoverage IsOpenImmersion) Y,
        Presieve.ofArrows 𝒰.X 𝒰.f ≤ S.pullback f := by
  rw [GrothendieckTopology.covers_iff]
  exact Scheme.mem_grothendieckTopology_iff (P := IsOpenImmersion)

/-!
## Section 3: base cases — covering families and the generated sieve

When the pretopology provides a family `R` of covering open immersions
on `X`, the sieve `Sieve.generate R` it generates covers. On the
identity, the pullback is trivial (`Sieve.pullback_id`) and `R` itself
is the witness (`Sieve.le_generate`). For a general arrow, the
refinement descends to `Y` via `pullbackArrows`, admitted in the
pretopology by the base-change stability axiom
(`Pretopology.pullbacks`); the commutation
`generate ∘ pullbackArrows = pullback ∘ generate`
(`Sieve.pullbackArrows_comm`) closes the goal.
-/

/-- Base case: if `R` is a family of covering open immersions of `X`
    (for `zariskiPretopology`), then the sieve it generates covers the
    identity:
    `Scheme.zariskiTopology.Covers (Sieve.generate R) (𝟙 X)`.
    Proof: `covers_iff_zariski` reduces to the existential test on
    `X`, `Sieve.pullback_id` trivializes the pullback, and `R` is its
    own witness by `Sieve.le_generate`. -/
theorem covers_zariski_of_mem {X : Scheme.{u}} {R : Presieve X}
    (hR : R ∈ Scheme.zariskiPretopology X) :
    Scheme.zariskiTopology.Covers (Sieve.generate R) (𝟙 X) := by
  rw [covers_iff_zariski, Sieve.pullback_id]
  exact ⟨R, hR, Sieve.le_generate R⟩

/-- Generalized base case: the coverage generated by `R` covers any
    arrow `f : Y ⟶ X`. Proof: the witness on `Y` is
    `R.pullbackArrows f`, admitted in the pretopology by
    `Pretopology.pullbacks` (base-change stability — the preimage of
    an open cover along a scheme arrow is an open cover), and
    `Sieve.pullbackArrows_comm` commutes generation and pullback. -/
theorem covers_zariski_of_mem_arrow {X Y : Scheme.{u}} (f : Y ⟶ X)
    {R : Presieve X} (hR : R ∈ Scheme.zariskiPretopology X) :
    Scheme.zariskiTopology.Covers (Sieve.generate R) f := by
  rw [covers_iff_zariski]
  refine ⟨R.pullbackArrows f, Scheme.zariskiPretopology.pullbacks f R hR, ?_⟩
  rw [← Sieve.generate_le_iff, Sieve.pullbackArrows_comm]

/-- Special case on the top sieve:
    `Scheme.zariskiTopology.Covers ⊤ f` for any arrow `f : Y ⟶ X`.
    Proof: the witness is `Presieve.singleton (𝟙 Y)`, admitted by the
    `Pretopology.has_isos` axiom (the identity is an isomorphism, hence
    a trivial open immersion), which dominates `⊤`. -/
theorem covers_zariski_top {X Y : Scheme.{u}} (f : Y ⟶ X) :
    Scheme.zariskiTopology.Covers (⊤ : Sieve X) f := by
  rw [covers_iff_zariski]
  exact ⟨Presieve.singleton (𝟙 Y), Scheme.zariskiPretopology.has_isos (𝟙 Y), by simp⟩

/-!
## Section 4: pointwise fallout

Specialization to the identity: covering along the identity is
equivalent to belonging to the topology — Mathlib's
`covering_iff_covers_id`, connected to `zariskiTopology` via
`zariskiTopology_eq`.
-/

/-- Pointwise fallout: covering along the identity is equivalent to
    belonging to the Zariski topology:
    `Scheme.zariskiTopology.Covers S (𝟙 X) ↔ S ∈ Scheme.zariskiTopology X`.
    Proof: `zariskiTopology_eq` moves to the pointwise level, then it
    is exactly `GrothendieckTopology.covering_iff_covers_id`. -/
theorem covers_iff_pullback_zariski {X : Scheme.{u}} (S : Sieve X) :
    Scheme.zariskiTopology.Covers S (𝟙 X) ↔ S ∈ Scheme.zariskiTopology X := by
  rw [Scheme.zariskiTopology_eq]
  exact (GrothendieckTopology.covering_iff_covers_id
    (J := Scheme.zariskiPretopology.toGrothendieck) S).symm

end Grothendieck.CoversZariskiArrow_en
