/-

# Grothendieck tribute — Part 9: Coverage generation and sheaf characterization

Alexandre Grothendieck (1928-2014).

Phase 5 extension (#2159, Epic #1646).

Parts 1-4 established the fundamentals: categories, sieves, topologies,
lattice operations, pullback identities, sheaf basics, and covering closure.
Parts 5-8 built on that with calibration, lattice laws, sheaf properties,
and topology ordering.

This module addresses the central generation question: how does one
*construct* a Grothendieck topology from simpler data?

  - A **Coverage** is a collection of covering families stable under
    pullback (but not necessarily saturated under transitivity).
  - `Coverage.toGrothendieck` saturates a coverage into a full topology.
  - The **key theorem**: a presheaf is a sheaf for the generated topology
    iff it satisfies the sheaf condition for every covering family.
  - The sup of coverages corresponds to the intersection of sheaf categories.

These facts show that coverages (much simpler data) determine the same
sheaf theory as the full topology they generate.

Epic #1646, Phase 5 (#2159). All `sorry`s eliminated at creation.

This module is the English-language mirror of `CoverageGen.lean` (FR canonical).
Per the EPIC #4980 convention (ratified by user 2026-07-04), the FR-first file is
the canonical source; this sibling carries the same theorems, signatures, and proof
bodies, with English documentation. Anti-§D byte-identity (L298) holds: every
`theorem` signature, `abbrev`, `import`, `open`, and proof body is BYTE-IDENTICAL
to the FR canonical — only the docstrings and headers differ. The namespace suffix
is `Grothendieck.CoverageGen_en` to avoid collisions.

For the canonical French version, see `CoverageGen.lean`.
-/

import Mathlib.CategoryTheory.Sites.Coverage

namespace Grothendieck_en

open CategoryTheory
/-!
## Coverage → Grothendieck topology

A coverage K on C is a collection of covering presieves at each object,
stable under pullback. The function `Coverage.toGrothendieck` saturates
a coverage into a full Grothendieck topology by closing under:
  - the maximal sieve (identity axiom)
  - pullback stability (inherited from K)
  - transitivity (generated from K)

The result is the *smallest* Grothendieck topology containing K.
-/

/-- The Grothendieck topology generated by a coverage.
    This is `Coverage.toGrothendieck`: the smallest topology whose
    associated coverage contains K. -/

abbrev coverageToTopology {C : Type*} [Category C] (K : Coverage C) :
    GrothendieckTopology C :=
  Coverage.toGrothendieck K

/-!
## The coverage-to-topology is an infimum

The topology generated by a coverage K is the infimum of all topologies
whose associated coverage contains K. This gives an alternative
characterization via order theory.
-/

/-- The topology generated by a coverage K is the infimum of all
    topologies J such that K ≤ J.toCoverage.
    Direct restatement of `Coverage.toGrothendieck_eq_sInf`. -/

theorem coverageToTopology_eq_sInf {C : Type*} [Category C] (K : Coverage C) :
    Coverage.toGrothendieck K =
    sInf {J : GrothendieckTopology C | K ≤ J.toCoverage} :=
  Coverage.toGrothendieck_eq_sInf K

/-!
## Sup of coverages and sheaf preservation

The supremum of two coverages K ⊔ L covers each object with K's families
union L's families. The sheaf condition for the sup-coverage is equivalent
to being a sheaf for both K and L individually.
-/

/-- Covering families for the sup of two coverages.
    Direct restatement of `Coverage.sup_covering`. -/

theorem sup_coverage {C : Type*} [Category C] (K L : Coverage C) (X : C) :
    (K ⊔ L) X = K X ∪ L X :=
  Coverage.sup_covering K L X

/-- A Type-valued presheaf is a sheaf for the topology generated by a
    coverage iff it satisfies the sheaf condition for every covering
    family of the coverage. This is the **fundamental theorem** connecting
    coverages to sheaf theory: the simpler coverage data suffices.
    Uses `Presieve.isSheaf_coverage`. -/

theorem isSheaf_coverageToTopology {C : Type*} [Category C]
    (K : Coverage C) (P : Cᵒᵖ ⥤ Type*) :
    Presieve.IsSheaf (Coverage.toGrothendieck K) P ↔
    ∀ {X : C} (R : Presieve X), R ∈ K X → Presieve.IsSheafFor P R :=
  Presieve.isSheaf_coverage K P

/-- A presheaf is a sheaf for K ⊔ L's generated topology iff it is a sheaf
    for each coverage's generated topology individually.
    Uses `Presieve.isSheaf_sup`. -/

theorem isSheaf_sup_coverage {C : Type*} [Category C]
    (K L : Coverage C) (P : Cᵒᵖ ⥤ Type*) :
    Presieve.IsSheaf (K ⊔ L).toGrothendieck P ↔
    Presieve.IsSheaf K.toGrothendieck P ∧ Presieve.IsSheaf L.toGrothendieck P :=
  Presieve.isSheaf_sup K L P

/-!
## Any covering presieve that is contained in a sieve makes that sieve covering

If R ∈ K X (a covering presieve for the coverage) and R ≤ S (the presieve
is contained in the sieve S), then S is covering for the generated topology.
-/

/-- Superset preservation: if a covering presieve R is contained in a sieve S,
    then S is covering for the generated topology.
    Uses `Coverage.mem_toGrothendieck_sieves_of_superset`. -/

theorem superset_mem_coverageToTopology {C : Type*} [Category C]
    (K : Coverage C) {X : C} {S : Sieve X} {R : Presieve X}
    (hRS : R ≤ S) (hR : R ∈ K X) :
    S ∈ Coverage.toGrothendieck K X :=
  Coverage.mem_toGrothendieck_sieves_of_superset K hRS hR

/-!
## Sieve generation from covering presieves

A covering presieve R generates a covering sieve for the associated topology.
This is the most basic way a covering family produces a covering sieve.
-/

/-- A covering presieve generates a covering sieve for the associated
    Grothendieck topology. Uses `Coverage.Saturate.of`. -/

theorem generate_mem_coverageToTopology {C : Type*} [Category C]
    (K : Coverage C) {X : C} {R : Presieve X} (hR : R ∈ K X) :
    Sieve.generate R ∈ Coverage.toGrothendieck K X :=
  Coverage.Saturate.of _ _ hR

/-!
## Topology covers extend coverage covers

Every covering presieve from a coverage extends to a covering sieve
via `Sieve.generate`. This bridges the presieve/sieve gap.
-/

/-- A sieve generated from a coverage family covers in the generated
    topology. Restatement using `Sieve.generate`. -/

theorem sieve_generate_covering {C : Type*} [Category C]
    (K : Coverage C) (X : C) (R : Presieve X) (hR : R ∈ K X) :
    Sieve.generate R ∈ Coverage.toGrothendieck K X :=
  Coverage.Saturate.of _ _ hR

end Grothendieck_en
