/-
Copyright (c) 2026 CoursIA. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Hommage Grothendieck — Part 50: arrow form of cover-preserving functors

Alexandre Grothendieck (1928-2014).

Extension Phase 5 (#2159, EPIC #1646).

Parts 1-49 established the foundations: categories, sieves, topologies,
lattice laws, pullback identities, sheaf bases, covering closure,
calibration, subcanonicity, dense topologies, sheaves, internal hom, Čech
cohomology, Mayer-Vietoris limits, Kan extensions, adjunctions, monads,
equivalences, monoidal categories, the Grothendieck construction, direct and
exceptional images, the arrow form of covering, the coherence laws of the
pullback pseudofunctor, the indexed lattice laws, the arrow form of dense
and extremal topologies, of the pushforward-pullback adjunction, of bind, of
the topology generated by a pretopology and of the topology induced along a
functor.

This part applies the "arrow form" thread to **cover-preserving functors**.
Mathlib defines the `CoverPreserving J K G` structure **pointwise**: for any
covering sieve `S ∈ J U`, the image `S.functorPushforward G` is covering in
`K (G.obj U)`. This structure sits at the core of site theory (morphisms of
sites, `inducedTopology_coverPreserving`, sheaf comparison) — but **no law
connects `CoverPreserving` to the arrow form `J.Covers S f`**. We fill the
gap: the central theorem (`covers_pushforward_of_coverPreserving`,
transporting a cover along `f` through the functor), its identity
consequence, and the bridge to the induced topology
(`covers_inducedTopology`, corollary of `Functor.inducedTopology_coverPreserving`).

The pivot lemma is `Sieve.functorPushforward_pullback_le`: the image under
`G` of the pullback of `S` along `f` is contained in the pullback (along
`G.map f`) of the image of `S`. This is the pushforward/pullback
naturality square, whose pullback stability of the topology
(`J.pullback_stable`) coupled with monotonicity (`J.superset_covering`)
yields exactly the requested transport.
-/

import Mathlib.CategoryTheory.Sites.CoverPreserving
import Mathlib.CategoryTheory.Sites.DenseSubsite.InducedTopology

namespace Grothendieck.CoversCoverPreserving_en

open CategoryTheory

/-!
## Section 1: the central theorem

A cover-preserving functor transports the arrow form of covering: if `J`
covers `f` by `S`, then `K` covers `G.map f` by the image
`S.functorPushforward G`. The proof unfolds `covers_iff` on both sides,
applies `G.cover_preserve` to the covering pullback, then lifts the result
in `K` by monotonicity along the naturality square.
-/

universe u v u' v'

/-- Transport of the arrow form by a cover-preserving functor:
    `J.Covers S f → K.Covers (S.functorPushforward G) (G.map f)`.
    Proof: `covers_iff` reduces to the pointwise level, `G.cover_preserve`
    transports `S.pullback f ∈ J Y` to
    `(S.pullback f).functorPushforward G ∈ K (G.obj Y)`, then
    `K.superset_covering` with `Sieve.functorPushforward_pullback_le`
    (the pushforward/pullback square) lifts into `K`. -/
theorem covers_pushforward_of_coverPreserving {C : Type u} [Category.{v} C]
    {D : Type u'} [Category.{v'} D] {J : GrothendieckTopology C} {K : GrothendieckTopology D}
    {G : C ⥤ D} (hG : CoverPreserving J K G) {X Y : C} (f : Y ⟶ X) (S : Sieve X)
    (hS : J.Covers S f) : K.Covers (S.functorPushforward G) (G.map f) := by
  rw [GrothendieckTopology.covers_iff] at hS ⊢
  have hLe : (S.pullback f).functorPushforward G ≤ (S.functorPushforward G).pullback (G.map f) := by
    rw [Sieve.functorPushforward_le_iff_le_functorPullback]
    rw [Sieve.functorPullback_pullback]
    exact Sieve.pullback_monotone _ (Sieve.le_functorPushforward_pullback _ _)
  exact K.superset_covering hLe (hG.cover_preserve hS)

/-!
## Section 2: identity consequence

`G.map (𝟙 X) = 𝟙 (G.obj X)` reduces the transport to the pointwise form.
-/

/-- Identity consequence: the arrow form transported by `G` reduces to the
    pointwise stability `S ∈ J X → S.functorPushforward G ∈ K (G.obj X)`
    once `G.map (𝟙 X)` is simplified.
    Proof: direct application of the central theorem to `f = 𝟙 X`, then
    `Functor.map_id`. -/
theorem covers_id_of_coverPreserving {C : Type u} [Category.{v} C]
    {D : Type u'} [Category.{v'} D] {J : GrothendieckTopology C} {K : GrothendieckTopology D}
    {G : C ⥤ D} (hG : CoverPreserving J K G) {X : C} (S : Sieve X)
    (hS : J.Covers S (𝟙 X)) : K.Covers (S.functorPushforward G) (𝟙 (G.obj X)) := by
  simpa using covers_pushforward_of_coverPreserving hG (𝟙 X) S hS

/-!
## Section 3: bridge to the induced topology

`Functor.inducedTopology_coverPreserving` asserts that `G` is
cover-preserving for `G.inducedTopology K` (the topology induced along
`G`, part 49). The central theorem specialized then gives the arrow form
of the bridge: a cover of the induced topology is transported by `G` into
a cover of `K`. This is the arrow counterpart of the fact that the image
of an induced-covering sieve is covering in `K`.
-/

/-- Bridge to the induced topology: `(G.inducedTopology K).Covers S f`
    implies `K.Covers (S.functorPushforward G) (G.map f)`.
    Proof: `Functor.inducedTopology_coverPreserving` provides the
    cover-preserving functor, the central theorem concludes. -/
theorem covers_inducedTopology {C : Type u} [Category.{v} C]
    {D : Type u'} [Category.{v'} D] (G : C ⥤ D) (K : GrothendieckTopology D)
    [G.IsLocallyFull K] [G.IsLocallyFaithful K] [G.LocallyCoverDense K]
    {X Y : C} (f : Y ⟶ X) (S : Sieve X) (hS : (G.inducedTopology K).Covers S f) :
    K.Covers (S.functorPushforward G) (G.map f) :=
  covers_pushforward_of_coverPreserving
    (Functor.inducedTopology_coverPreserving (G := G) (K := K)) f S hS

end Grothendieck.CoversCoverPreserving_en
