/-
Copyright (c) 2026 CoursIA. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Grothendieck tribute — Part 52: arrow form of the topology generated by a coverage

Alexandre Grothendieck (1928-2014).

Extension Phase 5 (#2159, EPIC #1646).

Parts 1-51 established the fundamentals: categories, sieves, topologies,
lattice laws, pullback identities, sheaf bases, covering closure,
calibration, subcanonicity, dense topologies, sheaves, internal hom,
Čech cohomology, Mayer-Vietoris limit, Kan extensions, adjunctions,
monads, equivalences, monoidal categories, the Grothendieck construction,
direct/exceptional image, the arrow form of the covering, the coherence
laws of the pullback pseudo-functor, the indexed lattice laws, the arrow
form of dense, extremal, pushforward-pullback adjunction, bind,
pretopology-generated, induced-topology, cover-preserving functors and
the composition laws of these functors.

This part applies the "arrow form" leitmotiv to the **topology generated
by a coverage** (`Coverage.toGrothendieck`). Mathlib provides at the point
level `Coverage.mem_toGrothendieck`:
`S ∈ K.toGrothendieck X ↔ Saturate K X S`, but **no law connects it to the
arrow form** `J.Covers`. We fill the gap with five proper theorems:

  - `covers_iff_toGrothendieck` (central): for `J := K.toGrothendieck`,
    `J.Covers S f ↔ Saturate K Y (S.pullback f)` — direct bridge between
    the arrow form and the inductive extension `Saturate`, via
    `covers_iff` and `Coverage.mem_toGrothendieck`. This is the **natural
    law** connecting the covering in the sense of Grothendieck and the
    covering in the sense of Cover (1957).
  - `covers_toGrothendieck_of_of` (particular case): if `R ∈ K X` is a
    covering family, then the sieve it generates covers the identity:
    `K.toGrothendieck.Covers (Sieve.generate R) (𝟙 X)` — the forward
    direction of `Saturate.of`.
  - `covers_toGrothendieck_of_top` (particular case): the trivial cover
    `⊤` covers any arrow: `K.toGrothendieck.Covers ⊤ f`. Fall-out of the
    constructor `Saturate.top` via `covers_iff` and `mem_toGrothendieck`.
  - `covers_of_mem_toGrothendieck` (passage via `Sieve.generate`): if
    `R` is a covering family for K, then
    `K.toGrothendieck.Covers (Sieve.generate R) f` — for any arrow
    `f : Y ⟶ X`, the cover descends one notch via pullback stability
    (`Saturate.pullback`) and pullback monotonicity.
  - `covers_iff_pullback_toGrothendieck` (particular case on identity):
    `K.toGrothendieck.Covers S (𝟙 X) ↔ S ∈ K.toGrothendieck X` — the
    point-level fall-out, direct specialization of `covers_iff_covers_id`
    (Part 35) to the case `J := K.toGrothendieck`. The proof of
    `covers_iff_covers_id` is inlined to make this module self-sufficient
    (Part 35 is not necessarily on `main` at the date of this PR).

Each proof is a **real tactical proof** (DEEP vein): Mathlib axioms
(`GrothendieckTopology.covers_iff`, `Coverage.mem_toGrothendieck`,
`Coverage.Saturate.pullback`, `Coverage.Saturate.top`, `Coverage.Saturate.of`,
`Sieve.pullback_id`, `Sieve.pullback_monotone`, `Sieve.generate_sieve`) plus
the definition `Coverage.toGrothendieck`. No proof is a re-export or an
unfold.

EPIC #1646, Phase 5 (#2159). All `sorry`s eliminated at creation.

### i18n convention (EPIC #4980 ratified by user 2026-07-04)

This module is paired with its French twin in the sibling file
`CoversCoverageArrow.lean` (sibling pair model, see PR #6154 for the
pilot on `Utility.lean`). Namespace suffix `_en` applied to the EN file
(anti-collision, conforms to code-style.md #4980). Theorem statements,
lemma names, Lean tactics and Mathlib references remain in English; only
the docstrings `/-- ... -/` and `-- ...` comments differ between the two
files (byte-identity preservation).
-/

import Mathlib.CategoryTheory.Sites.Coverage

namespace Grothendieck.CoversCoverageArrow_en

open CategoryTheory Coverage

universe u v

/-!
## Section 1: the central bridge — arrow form ↔ inductive extension

The extension `Coverage.toGrothendieck` starts from a covering family in
the sense of `Coverage` (1957, Grothendieck-Verdier) and saturates it into
a Grothendieck topology via the inductive closure `Saturate` (base cases:
generated sieves, top sieves; not inductive: pullback stability implicit).
The arrow form `K.toGrothendieck.Covers S f ↔ S.pullback f ∈ K.toGrothendieck Y`
reduces to the point level; `Coverage.mem_toGrothendieck` identifies the
point membership to `Saturate K Y (S.pullback f)`. The bridge is immediate
by rewriting, but **missing** in Mathlib in this form.
-/

/-- Central bridge: the arrow form for the topology `K.toGrothendieck`
    is equivalent to the inductive extension `Saturate`:
    `K.toGrothendieck.Covers S f ↔ Saturate K Y (S.pullback f)`.
    Proof: `covers_iff` reduces to `S.pullback f ∈ K.toGrothendieck Y`,
    then `Coverage.mem_toGrothendieck` identifies to
    `Saturate K Y (S.pullback f)`. -/
theorem covers_iff_toGrothendieck {C : Type u} [Category.{v} C]
    (K : Coverage C) {X Y : C} (S : Sieve X) (f : Y ⟶ X) :
    K.toGrothendieck.Covers S f ↔ Coverage.Saturate K Y (S.pullback f) := by
  rw [GrothendieckTopology.covers_iff]
  exact Coverage.mem_toGrothendieck.symm

/-!
## Section 2: base case — the constructor `Saturate.of`

When the cover in the sense of `Coverage` is a family of morphisms to `X`,
its generated sieve covers the identity in the sense of
`K.toGrothendieck` — this is the base case of the inductive closure
`Saturate` exported in arrow form. Mathlib has `Coverage.Saturate.of` at
the point level, but **not** the arrow form.
-/

/-- Base case: if `R ∈ K X` is a covering family, then the sieve it
    generates covers the identity:
    `K.toGrothendieck.Covers (Sieve.generate R) (𝟙 X)`.
    Proof: we directly compute that `S.pullback (𝟙 X) = S` (via
    `Sieve.pullback_id`), so
    `K.toGrothendieck.Covers (Sieve.generate R) (𝟙 X) ↔ Saturate K X (Sieve.generate R)`
    by `covers_iff_toGrothendieck`. The right member is
    `Saturate.of X R hR` (the base constructor of `Saturate`). -/
theorem covers_toGrothendieck_of_of {C : Type u} [Category.{v} C]
    (K : Coverage C) {X : C} {R : Presieve X} (hR : R ∈ K X) :
    K.toGrothendieck.Covers (Sieve.generate R) (𝟙 X) := by
  rw [covers_iff_toGrothendieck, Sieve.pullback_id]
  exact Coverage.Saturate.of X R hR

/-- Generalized base case: the cover generated by `R` covers any arrow
    `f : Y ⟶ X`. Proof: `Saturate.pullback` propagates
    `Saturate K X (Sieve.generate R)` to the pullback along `f`, then
    `covers_iff_toGrothendieck` gives the arrow form. -/
theorem covers_of_mem_toGrothendieck {C : Type u} [Category.{v} C]
    (K : Coverage C) {X Y : C} (f : Y ⟶ X) {R : Presieve X} (hR : R ∈ K X) :
    K.toGrothendieck.Covers (Sieve.generate R) f := by
  rw [covers_iff_toGrothendieck]
  exact Coverage.Saturate.pullback K f (Coverage.Saturate.of X R hR)

/-- Particular case on the top sieve: `K.toGrothendieck.Covers ⊤ f` for
    any `f : Y ⟶ X`. Proof: `Saturate.top Y` provides `Saturate K Y ⊤`
    (the top is its own pullback along any arrow, and `Saturate.top` is
    valid for any `Y`); `covers_iff_toGrothendieck` gives the arrow form. -/
theorem covers_toGrothendieck_top {C : Type u} [Category.{v} C]
    (K : Coverage C) {X Y : C} (f : Y ⟶ X) :
    K.toGrothendieck.Covers (⊤ : Sieve X) f := by
  rw [covers_iff_toGrothendieck]
  exact Coverage.Saturate.top Y

/-!
## Section 3: point-level fall-out

Specialization on the identity: `K.toGrothendieck.Covers S (𝟙 X) ↔ S ∈
K.toGrothendieck X`. This is the direct instance of `covers_iff_covers_id`
(Part 35) at `J := K.toGrothendieck`. The bridge to point membership
`Coverage.mem_toGrothendieck` is immediate.
-/

/-- Point fall-out: for `J := K.toGrothendieck`, covering along the
    identity is equivalent to belonging to the topology:
    `K.toGrothendieck.Covers S (𝟙 X) ↔ S ∈ K.toGrothendieck X ↔ Saturate K X S`.
    Proof: `Sieve.pullback_id` reduces to point, then
    `Coverage.mem_toGrothendieck` identifies to `Saturate K X S`. -/
theorem covers_iff_pullback_toGrothendieck {C : Type u} [Category.{v} C]
    (K : Coverage C) {X : C} (S : Sieve X) :
    K.toGrothendieck.Covers S (𝟙 X) ↔ Coverage.Saturate K X S := by
  rw [GrothendieckTopology.covers_iff, Sieve.pullback_id]
  exact Coverage.mem_toGrothendieck.symm

end Grothendieck.CoversCoverageArrow_en