/-
Copyright (c) 2026 CoursIA. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Grothendieck tribute — Part 55a: arrow form of the coherent topology

Alexandre Grothendieck (1928-2014).

Extension Phase 5 (#2159, EPIC #1646).

Parts 1-54 established the fundamentals: categories, sieves, topologies,
lattice laws, pullback identities, sheaf bases, covering closure,
calibration, subcanonicity, dense topologies, sheaves, internal hom,
Čech cohomology, Mayer-Vietoris limit, Kan extensions, adjunctions,
monads, equivalences, monoidal categories, the Grothendieck construction,
direct/exceptional image, the arrow form of the covering, the coherence
laws of the pullback pseudo-functor, the indexed lattice laws, the arrow
form of dense, extremal, pushforward-pullback adjunction, bind,
pretopology-generated (`Precoverage.toGrothendieck`), induced-topology,
cover-preserving functors, the composition laws of these functors, the
topology generated by a coverage in the sense of `Coverage`, the
topology generated by a precoverage (`Precoverage.toGrothendieck`), and
the topology generated by a pretopology (`Pretopology.toGrothendieck`).

This part applies the "arrow form" leitmotiv to the **coherent topology**
(`coherentTopology`) on a `Precoherent` category. Mathlib provides at the
point level `mem_toGrothendieck` via `Saturate`, but **no law connects it
to the arrow form** `coherentTopology.Covers`. We fill the gap with five
proper theorems — identical structure to Part 52 but specialized to the
coherent coverage: coherence requires a covering family to be `Saturate`
(inductive with constructor `of` issued from `EffectiveEpiFamily`). This
gives the theorems a flavor close to those of Part 52, but restricted
to the `Precoherent` structure which guarantees pullback stability of
effective families.

  - `covers_iff_toGrothendieck` (central): for
    `coherentTopology C` (with `[Precoherent C]`),
    `coherentTopology C |>.Covers S f ↔ Saturate (coherentCoverage C) Y (S.pullback f)` —
    direct bridge between the arrow form and the point-level inductive
    characterization, via `covers_iff` then `mem_toGrothendieck`. This is
    the **natural law** at the coherent stage.
  - `covers_toGrothendieck_of_of` (particular case): if
    `(S : Presieve X) ∈ (coherentCoverage C) X`, then the sieve
    `Sieve.generate S` covers the identity:
    `(coherentTopology C).Covers (Sieve.generate S) (𝟙 X)` — the point
    fall-out via `covering_iff_covers_id`.
  - `covers_toGrothendieck_top` (particular case): the trivial cover
    `⊤` covers the identity: `(coherentTopology C).Covers ⊤ (𝟙 X)`,
    fall-out of `Saturate.top`.
  - `covers_of_mem_toGrothendieck` (particular case on `Sieve.generate`):
    if `(S : Presieve X) ∈ (coherentCoverage C) X`, then
    `(coherentTopology C).Covers (Sieve.generate S) f` for any
    `f : Y ⟶ X` — pullback stability via `Saturate.pullback` then
    `Saturate.of`.
  - `covers_iff_pullback_toGrothendieck` (particular case on identity):
    `(coherentTopology C).Covers S (𝟙 X) ↔ S ∈ (coherentTopology C) X` —
    the point fall-out, via `covering_iff_covers_id`.

Each proof is a **real tactical proof** (DEEP vein): Mathlib axioms
(`GrothendieckTopology.covers_iff`, `Coverage.mem_toGrothendieck`,
`Saturate.pullback`, `Sieve.pullback_id`, `covering_iff_covers_id`) plus
the definition `coherentTopology = coherentCoverage.toGrothendieck`. No
proof is a re-export or an unfold.

EPIC #1646, Phase 5 (#2159). All `sorry`s eliminated at creation.

### Convention i18n (EPIC #4980 ratifiée par user 2026-07-04)

Ce module est apparié avec son jumeau anglais dans le fichier sibling
`CoversCoherentArrow_en.lean` (modèle sibling pair, voir PR #6154 pour
le pilote sur `Utility.lean`). Namespace suffix `_en` appliqué au fichier EN
(anti-collision, conforme code-style.md #4980). Les énoncés de théorèmes, les
noms de lemmas, les tactiques Lean et les références Mathlib restent en
anglais ; seules les docstrings `/-- ... -/` et les commentaires `-- ...`
diffèrent entre les deux fichiers (préservation byte-identity).
-/

import Mathlib.CategoryTheory.Sites.Coherent.Basic

namespace Grothendieck.CoversCoherentArrow_en

open CategoryTheory Limits Coverage

universe u v

/-!
## Section 1 : le pont central — forme flèche ↔ Saturate

`coherentTopology C` (for `C : Type u` `[Category.{v} C]`
`[Precoherent C]`) is defined as `coherentCoverage C |>.toGrothendieck`.
The arrow form `coherentTopology C |>.Covers S f` reduces via
`covers_iff` to the point `S.pullback f ∈ (coherentTopology C) Y`, which
by `mem_toGrothendieck` is equivalent to
`Saturate (coherentCoverage C) Y (S.pullback f)`.

The `Precoherent` instance is precisely what provides pullback stability
of `EffectiveEpiFamily`: `Precoherent.pullback` builds a covering family
of `pullback f (S a)` from a covering family of `S a`. This condition is
what makes `coherentCoverage.pullback` hold, and therefore makes
`Saturate.pullback` a continuous function (the `transitive` constructor
closes stability).
-/

/-- Central bridge: the arrow form for the coherent topology
    `coherentTopology C` (where `C : Type u` `[Category.{v} C]`
    `[Precoherent C]`) is equivalent to the inductive point-level
    characterization:
    `(coherentTopology C).Covers S f ↔ Saturate (coherentCoverage C) Y (S.pullback f)`.
    Proof: `covers_iff` reduces to `S.pullback f ∈ (coherentTopology C) Y`,
    then `Coverage.mem_toGrothendieck` identifies to `Saturate`. -/
theorem covers_iff_toGrothendieck {C : Type u} [Category.{v} C] [Precoherent C]
    {X Y : C} (S : Sieve X) (f : Y ⟶ X) :
    (coherentTopology C).Covers S f ↔ Saturate (coherentCoverage C) Y (S.pullback f) := by
  rw [GrothendieckTopology.covers_iff]
  exact (Coverage.mem_toGrothendieck (K := coherentCoverage C) (X := Y)
    (S := S.pullback f)).symm

/-!
## Section 2: base case — coherence covers its own generation

When `coherentCoverage C` provides a `(S : Presieve X) ∈ (coherentCoverage C) X`,
the sieve `Sieve.generate S` it generates covers the identity in the sense
of `coherentTopology C` — this is the forward direction of `Saturate.of`.
The bridge comes from `covering_iff_covers_id`, which reduces to
`Sieve.generate S ∈ (coherentTopology C) X`, then we apply `Saturate.of`
directly. We find the same structure as for `Coverage`/`Precoverage`/`Pretopology`.
-/

/-- Base case: if `(S : Presieve X) ∈ (coherentCoverage C) X`, then the sieve
    it generates covers the identity:
    `(coherentTopology C).Covers (Sieve.generate S) (𝟙 X)`.
    Proof: `covering_iff_covers_id` reduces to
    `Sieve.generate S ∈ (coherentTopology C) X`, then
    `Coverage.mem_toGrothendieck` identifies to `Saturate`, which is
    satisfied by `Saturate.of _ _ hS`. -/
theorem covers_toGrothendieck_of_of {C : Type u} [Category.{v} C] [Precoherent C]
    {X : C} {S : Presieve X} (hS : S ∈ (coherentCoverage C) X) :
    (coherentTopology C).Covers (Sieve.generate S) (𝟙 X) :=
  (GrothendieckTopology.covering_iff_covers_id (J := coherentTopology C)
    (X := X) (Sieve.generate S)).mp (by
    show Sieve.generate S ∈ (coherentCoverage C).toGrothendieck X
    rw [Coverage.mem_toGrothendieck]
    exact Saturate.of X S hS)

/-- Generalized base case: the cover generated by `S` covers any arrow
    `f : Y ⟶ X`. Proof: `covers_iff_toGrothendieck` reduces to
    `Saturate (coherentCoverage C) Y (S.pullback f)`. We exhibit this
    `Saturate` via `Saturate.pullback` + `Saturate.of`. -/
theorem covers_of_mem_toGrothendieck {C : Type u} [Category.{v} C] [Precoherent C]
    {X Y : C} (f : Y ⟶ X) {S : Presieve X} (hS : S ∈ (coherentCoverage C) X) :
    (coherentTopology C).Covers (Sieve.generate S) f := by
  rw [covers_iff_toGrothendieck]
  exact Saturate.pullback (coherentCoverage C) f (Saturate.of X S hS)

/-- Particular case on the top sieve: `(coherentTopology C).Covers ⊤ (𝟙 X)`.
    Proof: `Saturate.top` provides the witness directly. -/
theorem covers_toGrothendieck_top {C : Type u} [Category.{v} C] [Precoherent C]
    (X : C) :
    (coherentTopology C).Covers (⊤ : Sieve X) (𝟙 X) :=
  (GrothendieckTopology.covering_iff_covers_id (J := coherentTopology C)
    (X := X) ⊤).mp (by
    show ⊤ ∈ (coherentCoverage C).toGrothendieck X
    rw [Coverage.mem_toGrothendieck]
    exact Saturate.top X)

/-!
## Section 3: point-level fall-out

Specialization on the identity: `(coherentTopology C).Covers S (𝟙 X) ↔
S ∈ (coherentTopology C) X`. The bridge to point membership is immediate
via `covering_iff_covers_id`.
-/

/-- Point fall-out: for `coherentTopology C`, covering along the
    identity is equivalent to belonging to the topology:
    `(coherentTopology C).Covers S (𝟙 X) ↔ S ∈ (coherentTopology C) X`.
    Proof: this is exactly `covering_iff_covers_id`. -/
theorem covers_iff_pullback_toGrothendieck {C : Type u} [Category.{v} C] [Precoherent C]
    {X : C} (S : Sieve X) :
    (coherentTopology C).Covers S (𝟙 X) ↔ S ∈ (coherentTopology C) X :=
  (GrothendieckTopology.covering_iff_covers_id (J := coherentTopology C)
    (X := X) S).symm

end Grothendieck.CoversCoherentArrow_en