/-
Copyright (c) 2026 CoursIA. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Hommage Grothendieck — Part 51: composition laws of cover-preserving functors

Alexandre Grothendieck (1928-2014).

Extension Phase 5 (#2159, EPIC #1646).

Parts 1-49 established the foundations: categories, sieves, topologies,
lattice laws, pullback identities, sheaf bases, covering closure,
calibration, subcanonicity, dense topologies, sheaves, internal hom, Čech
cohomology, Mayer-Vietoris limits, Kan extensions, adjunctions, monads,
equivalences, monoidal categories, the Grothendieck construction, direct and
exceptional images, the arrow form of covering, the coherence laws of the
pullback pseudofunctor, the indexed lattice laws, the arrow form of dense
and extremal topologies, of the pushforward-pullback adjunction, of bind, of
the topology generated by a pretopology and of the topology induced along a
functor.

This part applies the "arrow form" thread to the **composition laws** of
cover-preserving functors. Mathlib provides at the pointwise level the law
`CoverPreserving.comp : (CoverPreserving J K F) → (CoverPreserving K L G) →
CoverPreserving J L (F ⋙ G)`, but **no law** connects it to the **arrow
form** `J.Covers`. We fill the gap with three proper theorems:

  - `covers_pushforward_of_coverPreserving` (central, restated) — transport
    of a cover along `f` by a cover-preserving functor:
    `J.Covers S f → K.Covers (S.functorPushforward G) (G.map f)`, via
    `covers_iff` + `cover_preserve` + `K.superset_covering` along the
    diagram `Sieve.functorPushforward_pullback_le`. Restated here to make
    the module **self-contained** (Part 50 is not yet on `main` at the
    date of this PR).
  - `covers_comp_of_coverPreserving` (composition) — if `F` is J→K
    cover-preserving and `G` is K→L cover-preserving, then
    `J.Covers S f → L.Covers (S.functorPushforward (F ⋙ G)) ((F ⋙ G).map f)`.
    The proof composes the transports: `covers_iff` on both sides,
    `Sieve.functorPushforward_comp` + `Functor.comp_map` to align the two
    stages, then successive application of the central theorem to `F` then
    `G` along the iterated naturality diagram.
  - `covers_comp_id` (unit law, left/right) — composition with identity is
    trivial. `Functor.comp_id` and `Functor.id_comp` make `F ⋙ 𝟙 = F` and
    `𝟙 ⋙ G = G` definitional, so the corresponding `Covers` coincides
    exactly with that of a single functor. Formalized as type bridges (via
    `show`) to name the definitional equality.

Each proof is a **real tactical proof** (DEEP vein): Mathlib axioms
(`Sieve.functorPushforward_pullback_le`, `Sieve.functorPushforward_comp`,
`Functor.comp_map`, `GrothendieckTopology.covers_iff`,
`GrothendieckTopology.superset_covering`) plus the definition
`CoverPreserving.cover_preserve`. No proof is a re-export or a plain unfold.

EPIC #1646, Phase 5 (#2159). All `sorry`s eliminated at creation.

### i18n convention (EPIC #4980 ratified by user 2026-07-04)

This module is paired with its English twin in the sibling file
`CoversCoverPreservingLaws_en.lean` (sibling pair model, see PR #6154 for
the pilot on `Utility.lean`). Namespace suffix `_en` applied to the EN file
(anti-collision, per code-style.md #4980). Theorem statements, lemma names,
Lean tactics, and Mathlib references remain in English; only the
docstrings `/-- ... -/` and comments `-- ...` differ between the two files
(byte-identity preservation).
-/

import Mathlib.CategoryTheory.Sites.CoverPreserving

namespace Grothendieck.CoversCoverPreservingLaws_en

open CategoryTheory

/-!
## Section 1: the central theorem (restated for self-containment)

Pivot lemma: `Sieve.functorPushforward_pullback_le` — the image under `G`
of the pullback of `S` along `f` is contained in the pullback (along
`G.map f`) of the image of `S`. This is the pushforward/pullback
naturality square, whose pullback stability of the topology coupled with
monotonicity (`J.superset_covering`) yields exactly the requested
transport. Explicit universes `u v u' v'` (the `Type*` creates auto
universes that do not unify with Mathlib's `Type u₁`).
-/

universe u v u' v' u'' v''

/-- Transport of the arrow form by a cover-preserving functor:
    `J.Covers S f → K.Covers (S.functorPushforward G) (G.map f)`.
    Proof: `covers_iff` reduces to the pointwise level, `G.cover_preserve`
    transports `S.pullback f ∈ J Y` to
    `(S.pullback f).functorPushforward G ∈ K (G.obj Y)`, then
    `K.superset_covering` with `Sieve.functorPushforward_pullback_le`
    (the pushforward/pullback square) lifts into `K`. -/
theorem covers_pushforward_of_coverPreserving {C : Type u} [Category.{v} C]
    {D : Type u'} [Category.{v'} D] {J : GrothendieckTopology C} {K : GrothendieckTopology D}
    {G : C ⥤ D} (hG : CoverPreserving J K G) {X Y : C} (f : Y ⟶ X) (S : Sieve X)
    (hS : J.Covers S f) : K.Covers (S.functorPushforward G) (G.map f) := by
  rw [GrothendieckTopology.covers_iff] at hS ⊢
  have hLe : (S.pullback f).functorPushforward G ≤ (S.functorPushforward G).pullback (G.map f) := by
    rw [Sieve.functorPushforward_le_iff_le_functorPullback]
    rw [Sieve.functorPullback_pullback]
    exact Sieve.pullback_monotone _ (Sieve.le_functorPushforward_pullback _ _)
  exact K.superset_covering hLe (hG.cover_preserve hS)

/-!
## Section 2: composition of cover-preserving functors

Three categories `C`, `D`, `E` with their explicit universes. Three
topologies `J`, `K`, `L`. Two functors `F : C ⥤ D` and `G : D ⥤ E`, each
`CoverPreserving`. The composition `F ⋙ G : C ⥤ E` is then
`CoverPreserving J L` by `CoverPreserving.comp` (Mathlib). We transport
this composition to the arrow-form level.
-/

/-- Composition of cover-preserving functors at the arrow form:
    `J.Covers S f → L.Covers (S.functorPushforward (F ⋙ G)) ((F ⋙ G).map f)`,
    given `(hF : CoverPreserving J K F) (hG : CoverPreserving K L G)`.
    Proof: `covers_iff` reduces to membership of `S.pullback f` pushed by
    `F ⋙ G` in `L`. The composition `F ⋙ G` acts on sieves via
    `Sieve.functorPushforward_comp` (two stages) and on morphisms via
    `Functor.comp_map`. We combine the two successive transports
    (`hF.cover_preserve` then `hG.cover_preserve`) along the iterated
    `Sieve.functorPushforward_pullback_le` diagram
    (`Sieve.pullback_monotone` + `le_functorPushforward_pullback` at each
    stage), then conclude by `L.superset_covering`. -/
theorem covers_comp_of_coverPreserving {C : Type u} [Category.{v} C]
    {D : Type u'} [Category.{v'} D] {E : Type u''} [Category.{v''} E]
    {J : GrothendieckTopology C} {K : GrothendieckTopology D}
    {L : GrothendieckTopology E}
    (F : C ⥤ D) (G : D ⥤ E) (hF : CoverPreserving J K F) (hG : CoverPreserving K L G)
    {X Y : C} (f : Y ⟶ X) (S : Sieve X)
    (hS : J.Covers S f) :
    L.Covers (S.functorPushforward (F ⋙ G)) ((F ⋙ G).map f) := by
  -- Step 1: convert J.Covers to pointwise membership via covers_iff.
  rw [GrothendieckTopology.covers_iff] at hS
  -- Step 2: cover_preserve (J→K via F) on S.pullback f, target K (F.obj Y).
  have hK : (S.pullback f).functorPushforward F ∈ K (F.obj Y) :=
    hF.cover_preserve hS
  -- Step 3: naturality: (S.pullback f).functorPushforward F ≤
  -- (S.functorPushforward F).pullback (F.map f). Push via covers_le_iff then
  -- K.superset_covering converts hK into K.Covers (S.functorPushforward F) (F.map f).
  have hLe : (S.pullback f).functorPushforward F
            ≤ (S.functorPushforward F).pullback (F.map f) := by
    rw [Sieve.functorPushforward_le_iff_le_functorPullback]
    rw [Sieve.functorPullback_pullback]
    exact Sieve.pullback_monotone _ (Sieve.le_functorPushforward_pullback _ _)
  have hKM : (S.functorPushforward F).pullback (F.map f) ∈ K (F.obj Y) :=
    K.superset_covering hLe hK
  -- Step 4: convert K-cover (pointwise) to K.Covers via covers_iff, then
  -- apply covers_pushforward_of_coverPreserving (the central theorem for G).
  have hKL : K.Covers (S.functorPushforward F) (F.map f) := by
    rw [GrothendieckTopology.covers_iff]; exact hKM
  have hL : L.Covers ((S.functorPushforward F).functorPushforward G) (G.map (F.map f)) :=
    covers_pushforward_of_coverPreserving hG (F.map f) (S.functorPushforward F) hKL
  -- Step 5: convert the goal to hL's form (RHS of functorPushforward_comp +
  -- F.map f ≫ G.map f for comp_map).
  -- hL is L.Covers (S.functorPushforward G (S.functorPushforward F S))
  --             (G.map (F.map f)), so the goal needs to rewrite INTO that form.
  rw [Sieve.functorPushforward_comp, Functor.comp_map]
  exact hL

/-!
## Section 3: unit law — composition with identity

Composition with the identity functor `𝟙 D : D ⥤ D` is transparent at the
arrow-form level: by `Functor.comp_id`/`Functor.id_comp`, `F ⋙ 𝟙 D = F`
(and `𝟙 C ⋙ F = F`) at the level of functor equality, so the corresponding
`Covers` coincides exactly with that of a single functor. This is the
**unit law** for `CoverPreserving` composition. These two theorems are type
bridges (via `show`) to name the definitional equality and make it
manipulable.
-/

/-- Right unit law: composition with target identity. If `F` is J→K
    cover-preserving, then `K.Covers (S.functorPushforward (F ⋙ 𝟭 D))
    ((F ⋙ 𝟭 D).map f)` is exactly the transport of `hS` by `F`.
    Proof: `Functor.comp_id` reduces `(F ⋙ 𝟭 D)` to `F` definitionally; the
    `show` rewrites the goal type to expose the form with `F` alone, then
    the central theorem concludes. -/
theorem covers_comp_id_right {C : Type u} [Category.{v} C]
    {D : Type u'} [Category.{v'} D]
    {J : GrothendieckTopology C} {K : GrothendieckTopology D}
    (F : C ⥤ D) (hF : CoverPreserving J K F)
    {X Y : C} (f : Y ⟶ X) (S : Sieve X)
    (hS : J.Covers S f) :
    K.Covers (S.functorPushforward (F ⋙ 𝟭 D)) ((F ⋙ 𝟭 D).map f) :=
  show K.Covers (S.functorPushforward F) (F.map f) from
    covers_pushforward_of_coverPreserving hF f S hS

/-- Left unit law: composition with source identity. If `G` is K→L
    cover-preserving, then `L.Covers (S.functorPushforward (𝟭 C ⋙ G))
    ((𝟭 C ⋙ G).map f)` is exactly the transport of `hS` by `G`.
    Proof: `Functor.id_comp` reduces `(𝟭 C ⋙ G)` to `G`; the `show` exposes
    the form with `G` alone, and the central theorem concludes. -/
theorem covers_comp_id_left {C : Type u} [Category.{v} C]
    {D : Type u'} [Category.{v'} D]
    {J : GrothendieckTopology C} {L : GrothendieckTopology D}
    (G : C ⥤ D) (hG : CoverPreserving J L G)
    {X Y : C} (f : Y ⟶ X) (S : Sieve X)
    (hS : J.Covers S f) :
    L.Covers (S.functorPushforward (𝟭 C ⋙ G)) ((𝟭 C ⋙ G).map f) :=
  show L.Covers (S.functorPushforward G) (G.map f) from
    covers_pushforward_of_coverPreserving hG f S hS

end Grothendieck.CoversCoverPreservingLaws_en