/-
Copyright (c) 2026 CoursIA. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Grothendieck tribute — Part 54: arrow form of the topology generated by a pretopology

Alexandre Grothendieck (1928-2014).

Extension Phase 5 (#2159, EPIC #1646).

Parts 1-53 established the fundamentals: categories, sieves, topologies,
lattice laws, pullback identities, sheaf bases, covering closure,
calibration, subcanonicity, dense topologies, sheaves, internal hom,
Čech cohomology, Mayer-Vietoris limit, Kan extensions, adjunctions,
monads, equivalences, monoidal categories, the Grothendieck construction,
direct/exceptional image, the arrow form of the covering, the coherence
laws of the pullback pseudo-functor, the indexed lattice laws, the arrow
form of dense, extremal, pushforward-pullback adjunction, bind,
pretopology-generated (`Precoverage.toGrothendieck`), induced-topology,
cover-preserving functors, the composition laws of these functors, the
topology generated by a coverage in the sense of `Coverage`, and the
topology generated by a precoverage (`Precoverage.toGrothendieck`).

This part applies the "arrow form" leitmotiv to the **topology generated
by a pretopology** (`Pretopology.toGrothendieck`). Mathlib provides at the
point level `Pretopology.mem_toGrothendieck`:
`S ∈ K.toGrothendieck X ↔ ∃ R ∈ K X, R ≤ (S : Presieve X)`, but **no law
connects it to the arrow form** `K.toGrothendieck.Covers`. We fill the
gap with five proper theorems — identical structure to Part 52 and Part 53
but at a **more explicit** level: the pretopology is defined by a concrete
condition `R ≤ (S : Presieve X)` and the inductive `Saturate` of
`Coverage`/`Precoverage` becomes a simple existential quantifier. This
gives the theorems a more concrete flavor (but without constructivity on
the witness), complementary to the two inductive levels above:

  - `covers_iff_toGrothendieck` (central): for `K : Pretopology C`,
    `K.toGrothendieck.Covers S f ↔ ∃ R ∈ K Y, R ≤ (S.pullback f).arrows` —
    direct bridge between the arrow form and the point-level
    characterization `Pretopology.mem_toGrothendieck`, via `covers_iff`.
    This is the **natural law** at the pretopology stage.
  - `covers_toGrothendieck_of_of` (particular case): if `R ∈ K X` is
    a pretopology, then the sieve it generates covers the identity:
    `K.toGrothendieck.Covers (Sieve.generate R) (𝟙 X)` — the point
    fall-out, via `covering_iff_covers_id`.
  - `covers_toGrothendieck_top` (particular case): the trivial cover `⊤`
    covers the identity: `K.toGrothendieck.Covers ⊤ (𝟙 X)`, fall-out of
    `K.has_isos` via `mem_toGrothendieck`.
  - `covers_of_mem_toGrothendieck` (particular case on `Sieve.generate`):
    if `R ∈ K X`, then `K.toGrothendieck.Covers (Sieve.generate R) f`
    for any `f : Y ⟶ X` — the pullback stability, which in the
    pretopology is `K.pullbacks` (vs inductive constructor in `Precoverage`).
  - `covers_iff_pullback_toGrothendieck` (particular case on identity):
    `K.toGrothendieck.Covers S (𝟙 X) ↔ S ∈ K.toGrothendieck X` — the point
    fall-out, via `covering_iff_covers_id`.

Each proof is a **real tactical proof** (DEEP vein): Mathlib axioms
(`GrothendieckTopology.covers_iff`, `Pretopology.mem_toGrothendieck`,
`K.pullbacks`, `Sieve.pullback_id`, `covering_iff_covers_id`) plus the
definition `Pretopology.toGrothendieck`. No proof is a re-export or an
unfold.

EPIC #1646, Phase 5 (#2159). All `sorry`s eliminated at creation.

### i18n convention (EPIC #4980 ratified by user 2026-07-04)

This module is paired with its French twin in the sibling file
`CoversPretopologyArrow.lean` (sibling pair model, see PR #6154 for the
pilot on `Utility.lean`). Namespace suffix `_en` applied to the EN file
(anti-collision, conforms to code-style.md #4980). Theorem statements,
lemma names, Lean tactics and Mathlib references remain in English; only
the docstrings `/-- ... -/` and `-- ...` comments differ between the two
files (byte-identity preservation).
-/

import Mathlib.CategoryTheory.Sites.Pretopology

namespace Grothendieck.CoversPretopologyArrow_en

open CategoryTheory Limits Pretopology

universe u v

/-!
## Section 1 : le pont central — forme flèche ↔ caractérisation existentielle

`Pretopology.toGrothendieck` starts from a pretopology
(family of "covering" presieves on each object) and extends it into a
Grothendieck topology by declaring covering any sieve that contains a
covering family in the sense of the pretopology:
`sieves X := {S | ∃ R ∈ K X, R ≤ (S : Presieve X)}`. The arrow form
`K.toGrothendieck.Covers S f ↔ S.pullback f ∈ K.toGrothendieck Y` reduces
to the point level; `Pretopology.mem_toGrothendieck` identifies the
point membership to an existential quantifier on the pretopology of `Y`.

The difference with Parts 52 and 53 is that **no inductive closure**
intervenes: the pretopology is directly characterized by existence
(`∃ R ∈ K Y, R ≤ ...`), not a `Saturate`. The proof is therefore simpler:
`covers_iff` reduces to `S.pullback f ∈ K.toGrothendieck Y`, then
`Pretopology.mem_toGrothendieck` reduces to the existential test. No
need to invoke an inductive constructor — the pretopology is **stable by
hypothesis** (its axioms are `has_isos`, `pullbacks`, `transitive`, but
in the context of `toGrothendieck` only `has_isos` and the direct
implication are used).
-/

/-- Central bridge: the arrow form for the topology `K.toGrothendieck`
    (where `K : Pretopology C`) is equivalent to the point-level
    existential characterization:
    `K.toGrothendieck.Covers S f ↔ ∃ R ∈ K Y, R ≤ (S.pullback f).arrows`.
    Proof: `covers_iff` reduces to `S.pullback f ∈ K.toGrothendieck Y`,
    then `Pretopology.mem_toGrothendieck` identifies to the existence
    of an `R ∈ K Y` above `S.pullback f`. -/
theorem covers_iff_toGrothendieck {C : Type u} [Category.{v} C] [Limits.HasPullbacks C]
    (K : Pretopology C) {X Y : C} (S : Sieve X) (f : Y ⟶ X) :
    K.toGrothendieck.Covers S f ↔ ∃ R ∈ K Y, R ≤ (S.pullback f).arrows := by
  rw [GrothendieckTopology.covers_iff]
  exact Pretopology.mem_toGrothendieck K Y _

/-!
## Section 2: base case — the pretopology covers its own generation

When the pretopology provides an `R ∈ K X`, the sieve `Sieve.generate R`
it generates covers the identity in the sense of `K.toGrothendieck` —
this is the forward direction of `Pretopology.mem_toGrothendieck`
(the `R ≤ ⊤` is trivial). The bridge comes from `covering_iff_covers_id`,
which reduces to `Sieve.generate R ∈ K.toGrothendieck X`, then we apply
`mem_toGrothendieck` to the witness `R` itself. We find the same
structure as for `Coverage`/`Precoverage` but without the inductive
constructor.
-/

/-- Base case: if `R ∈ K X` is a pretopology, then the sieve it
    generates covers the identity:
    `K.toGrothendieck.Covers (Sieve.generate R) (𝟙 X)`.
    Proof: `covering_iff_covers_id` reduces to
    `Sieve.generate R ∈ K.toGrothendieck X`, then
    `Pretopology.mem_toGrothendieck` identifies to the existence of a
    witness; here `R` itself is the witness (`R ≤ (Sieve.generate R).arrows`
    by `Sieve.le_generate`, and `R ∈ K X` by hypothesis). -/
theorem covers_toGrothendieck_of_of {C : Type u} [Category.{v} C] [Limits.HasPullbacks C]
    (K : Pretopology C) {X : C} {R : Presieve X} (hR : R ∈ K X) :
    K.toGrothendieck.Covers (Sieve.generate R) (𝟙 X) :=
  (GrothendieckTopology.covering_iff_covers_id (J := K.toGrothendieck) (X := X)
    (Sieve.generate R)).mp ⟨R, hR, Sieve.le_generate R⟩

/-- Generalized base case: the cover generated by `R` covers any arrow
    `f : Y ⟶ X`. Proof: first `covers_iff_toGrothendieck` reduces to
    the existence of an `R' ∈ K Y` above `(Sieve.generate R).pullback f`.
    We exhibit `R.pullbackArrows f`: `K.pullbacks f R hR` is
    in `K Y`, and by the definition of `Sieve.pullbackArrows_comm`,
    `R.pullbackArrows f ≤ (Sieve.generate R).pullback f`. -/
theorem covers_of_mem_toGrothendieck {C : Type u} [Category.{v} C] [Limits.HasPullbacks C]
    (K : Pretopology C) {X Y : C} (f : Y ⟶ X) {R : Presieve X} (hR : R ∈ K X) :
    K.toGrothendieck.Covers (Sieve.generate R) f := by
  rw [covers_iff_toGrothendieck]
  refine ⟨R.pullbackArrows f, K.pullbacks f R hR, ?_⟩
  rw [← Sieve.generate_le_iff, Sieve.pullbackArrows_comm]

/-- Particular case on the top sieve: `K.toGrothendieck.Covers ⊤ (𝟙 X)`.
    Proof: `K.has_isos` (the isomorphisms axiom) provides the witness
    `Presieve.singleton (𝟙 X) ∈ K X`, which dominates `⊤.arrows = ⊤`. -/
theorem covers_toGrothendieck_top {C : Type u} [Category.{v} C] [Limits.HasPullbacks C]
    (K : Pretopology C) (X : C) :
    K.toGrothendieck.Covers (⊤ : Sieve X) (𝟙 X) :=
  (GrothendieckTopology.covering_iff_covers_id (J := K.toGrothendieck) (X := X) ⊤).mp
    ⟨Presieve.singleton (𝟙 X), K.has_isos (𝟙 X), by simp⟩

/-!
## Section 3: point-level fall-out

Specialization on the identity: `K.toGrothendieck.Covers S (𝟙 X) ↔ S ∈
K.toGrothendieck X`. The bridge to point membership is immediate via
`covering_iff_covers_id`.
-/

/-- Point fall-out: for `K : Pretopology C`, covering along the
    identity is equivalent to belonging to the topology:
    `K.toGrothendieck.Covers S (𝟙 X) ↔ S ∈ K.toGrothendieck X`.
    Proof: this is exactly `covering_iff_covers_id`. -/
theorem covers_iff_pullback_toGrothendieck {C : Type u} [Category.{v} C] [Limits.HasPullbacks C]
    (K : Pretopology C) {X : C} (S : Sieve X) :
    K.toGrothendieck.Covers S (𝟙 X) ↔ S ∈ K.toGrothendieck X :=
  (GrothendieckTopology.covering_iff_covers_id (J := K.toGrothendieck) (X := X) S).symm

end Grothendieck.CoversPretopologyArrow_en
