/-
Copyright (c) 2026 CoursIA. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Grothendieck tribute — Part 53: arrow form of the topology generated by a precoverage

Alexandre Grothendieck (1928-2014).

Extension Phase 5 (#2159, EPIC #1646).

Parts 1-52 established the fundamentals: categories, sieves, topologies,
lattice laws, pullback identities, sheaf bases, covering closure,
calibration, subcanonicity, dense topologies, sheaves, internal hom,
Čech cohomology, Mayer-Vietoris limit, Kan extensions, adjunctions,
monads, equivalences, monoidal categories, the Grothendieck construction,
direct/exceptional image, the arrow form of the covering, the coherence
laws of the pullback pseudo-functor, the indexed lattice laws, the arrow
form of dense, extremal, pushforward-pullback adjunction, bind,
pretopology-generated, induced-topology, cover-preserving functors, the
composition laws of these functors, and the topology generated by a
coverage in the sense of `Coverage`.

This part applies the "arrow form" leitmotiv to the **topology generated
by a precoverage** (`Precoverage.toGrothendieck`). Mathlib provides at the
point level `Precoverage.mem_toGrothendieck_iff`:
`S ∈ J.toGrothendieck X ↔ Saturate J X S`, but **no law connects it to the
arrow form** `J.Covers`. We fill the gap with five proper theorems —
identical structure to Part 52 but at a more primitive level, since
`Precoverage.Saturate` (4 constructors: `of`, `top`, `pullback`, `transitive`)
is more primitive than `Coverage.Saturate` (3 constructors: pullback
stability being integrated in the very notion of `Coverage`):

  - `covers_iff_toGrothendieck` (central): for `J : Precoverage C`,
    `J.toGrothendieck.Covers S f ↔ Saturate J Y (S.pullback f)` — direct
    bridge between the arrow form and the inductive extension `Saturate`,
    via `covers_iff` and `Precoverage.mem_toGrothendieck_iff`. This is the
    **natural law** at the precoverage stage.
  - `covers_toGrothendieck_of_of` (particular case): if `R ∈ J X` is a
    precoverage, then the sieve it generates covers the identity:
    `J.toGrothendieck.Covers (Sieve.generate R) (𝟙 X)` — the forward
    direction of `Saturate.of`.
  - `covers_toGrothendieck_top` (particular case): the trivial cover
    `⊤` covers any arrow: `J.toGrothendieck.Covers ⊤ f`. Fall-out of the
    constructor `Saturate.top` via `covers_iff` and `mem_toGrothendieck_iff`.
  - `covers_of_mem_toGrothendieck` (passage via `Sieve.generate`): if
    `R` is a precoverage, then `J.toGrothendieck.Covers (Sieve.generate R) f`
    — for any arrow `f : Y ⟶ X`, the cover descends one notch via pullback
    stability (`Saturate.pullback`) which here appears as an **inductive
    constructor** (vs. axiom in `Coverage`).
  - `covers_iff_pullback_toGrothendieck` (particular case on identity):
    `J.toGrothendieck.Covers S (𝟙 X) ↔ S ∈ J.toGrothendieck X` — the
    point-level fall-out, via `Sieve.pullback_id` + `covers_iff`.

Each proof is a **real tactical proof** (DEEP vein): Mathlib axioms
(`GrothendieckTopology.covers_iff`, `Precoverage.mem_toGrothendieck_iff`,
`Precoverage.Saturate.pullback`, `Precoverage.Saturate.top`, `Precoverage.Saturate.of`,
`Sieve.pullback_id`, `Precoverage.generate_mem_toGrothendieck`) plus the
definition `Precoverage.toGrothendieck`. No proof is a re-export or an
unfold.

EPIC #1646, Phase 5 (#2159). All `sorry`s eliminated at creation.

### i18n convention (EPIC #4980 ratified by user 2026-07-04)

This module is paired with its French twin in the sibling file
`CoversPrecoverageArrow.lean` (sibling pair model, see PR #6154 for the
pilot on `Utility.lean`). Namespace suffix `_en` applied to the EN file
(anti-collision, conforms to code-style.md #4980). Theorem statements,
lemma names, Lean tactics and Mathlib references remain in English; only
the docstrings `/-- ... -/` and `-- ...` comments differ between the two
files (byte-identity preservation).
-/

import Mathlib.CategoryTheory.Sites.PrecoverageToGrothendieck

namespace Grothendieck.CoversPrecoverageArrow_en

open CategoryTheory Precoverage

universe u v

/-!
## Section 1: the central bridge — arrow form ↔ inductive extension

The extension `Precoverage.toGrothendieck` starts from a precoverage
(family of covering presieves on each object) and saturates it into a
Grothendieck topology via the inductive closure `Saturate` with 4
constructors: `of` (base case of a precoverage), `top` (trivial case),
`pullback` (pullback stability — which is **inductive** here and not
an axiom as in `Coverage`), and `transitive` (local character). The
arrow form `J.toGrothendieck.Covers S f ↔ S.pullback f ∈ J.toGrothendieck Y`
reduces to the point level; `Precoverage.mem_toGrothendieck_iff`
identifies the point membership to `Saturate J Y (S.pullback f)`. The
bridge is immediate by rewriting, but **missing** in Mathlib in this form.

The difference with Part 52 (`Coverage` → `Grothendieck`) is that
`Precoverage.Saturate.pullback` appears as an **inductive constructor**,
so pullback stability is internal to the induction. This gives
`covers_iff_toGrothendieck` the same statement, but the underlying proof
structure is richer (the definition of `Saturate.pullback` must be
manipulated more directly).
-/

/-- Central bridge: the arrow form for the topology `J.toGrothendieck`
    (where `J : Precoverage C`) is equivalent to the inductive extension
    `Saturate`: `J.toGrothendieck.Covers S f ↔ Saturate J Y (S.pullback f)`.
    Proof: `covers_iff` reduces to `S.pullback f ∈ J.toGrothendieck Y`,
    then `Precoverage.mem_toGrothendieck_iff` identifies to
    `Saturate J Y (S.pullback f)`. -/
theorem covers_iff_toGrothendieck {C : Type u} [Category.{v} C]
    (J : Precoverage C) {X Y : C} (S : Sieve X) (f : Y ⟶ X) :
    J.toGrothendieck.Covers S f ↔ Saturate J Y (S.pullback f) := by
  rw [GrothendieckTopology.covers_iff]
  exact Precoverage.mem_toGrothendieck_iff.symm

/-!
## Section 2: base case — the constructor `Saturate.of`

When the precoverage is a family of morphisms to `X`, its generated
sieve covers the identity in the sense of `J.toGrothendieck` — this is
the base case of the inductive closure `Saturate` exported in arrow
form. Mathlib has `Precoverage.Saturate.of` at the point level, but
**not** the arrow form. `Precoverage.generate_mem_toGrothendieck` is the
point fall-out, but we export the bridge in arrow form here.
-/

/-- Base case: if `R ∈ J X` is a precoverage, then the sieve it
    generates covers the identity:
    `J.toGrothendieck.Covers (Sieve.generate R) (𝟙 X)`.
    Proof: we directly compute that `S.pullback (𝟙 X) = S` (via
    `Sieve.pullback_id`), so
    `J.toGrothendieck.Covers (Sieve.generate R) (𝟙 X) ↔ Saturate J X (Sieve.generate R)`
    by `covers_iff_toGrothendieck`. The right member is `Saturate.of X R hR`
    (the base constructor of `Saturate`). -/
theorem covers_toGrothendieck_of_of {C : Type u} [Category.{v} C]
    (J : Precoverage C) {X : C} {R : Presieve X} (hR : R ∈ J X) :
    J.toGrothendieck.Covers (Sieve.generate R) (𝟙 X) := by
  rw [covers_iff_toGrothendieck, Sieve.pullback_id]
  exact Saturate.of X R hR

/-- Generalized base case: the cover generated by `R` covers any arrow
    `f : Y ⟶ X`. Proof: `Saturate.pullback` propagates
    `Saturate J X (Sieve.generate R)` to the pullback along `f`, then
    `covers_iff_toGrothendieck` gives the arrow form. NB: in
    `Precoverage`, `Saturate.pullback` is an **inductive constructor**
    (not an axiom as in `Coverage`). -/
theorem covers_of_mem_toGrothendieck {C : Type u} [Category.{v} C]
    (J : Precoverage C) {X Y : C} (f : Y ⟶ X) {R : Presieve X} (hR : R ∈ J X) :
    J.toGrothendieck.Covers (Sieve.generate R) f := by
  rw [covers_iff_toGrothendieck]
  exact Saturate.pullback X (Sieve.generate R) (Saturate.of X R hR) Y f

/-- Particular case on the top sieve: `J.toGrothendieck.Covers ⊤ f` for
    any `f : Y ⟶ X`. Proof: `Saturate.top Y` provides `Saturate J Y ⊤`
    (the top is its own pullback along any arrow, and `Saturate.top` is
    valid for any `Y`); `covers_iff_toGrothendieck` gives the arrow form. -/
theorem covers_toGrothendieck_top {C : Type u} [Category.{v} C]
    (J : Precoverage C) {X Y : C} (f : Y ⟶ X) :
    J.toGrothendieck.Covers (⊤ : Sieve X) f := by
  rw [covers_iff_toGrothendieck]
  exact Saturate.top Y

/-!
## Section 3: point-level fall-out

Specialization on the identity: `J.toGrothendieck.Covers S (𝟙 X) ↔ S ∈
J.toGrothendieck X`. The bridge to point membership
`Precoverage.mem_toGrothendieck_iff` is immediate.
-/

/-- Point fall-out: for `J : Precoverage C`, covering along the
    identity is equivalent to belonging to the topology:
    `J.toGrothendieck.Covers S (𝟙 X) ↔ S ∈ J.toGrothendieck X ↔ Saturate J X S`.
    Proof: `Sieve.pullback_id` reduces to point, then
    `Precoverage.mem_toGrothendieck_iff` identifies to `Saturate J X S`. -/
theorem covers_iff_pullback_toGrothendieck {C : Type u} [Category.{v} C]
    (J : Precoverage C) {X : C} (S : Sieve X) :
    J.toGrothendieck.Covers S (𝟙 X) ↔ Saturate J X S := by
  rw [GrothendieckTopology.covers_iff, Sieve.pullback_id]
  exact Precoverage.mem_toGrothendieck_iff.symm

end Grothendieck.CoversPrecoverageArrow_en