/-
Copyright (c) 2026 CoursIA. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Grothendieck tribute — Part 57: arrow form of the atomic topology

Alexandre Grothendieck (1928-2014).

Extension Phase 5 (#2159, EPIC #1646).

Parts 1-56 established the fundamentals: categories, sieves, topologies,
lattice laws, pullback identities, bases of sheaves, covering closure,
calibration, subcanonicity, dense topologies, sheaves, internal hom,
Cech cohomology, Mayer-Vietoris limits, Kan extensions, adjunctions,
monads, equivalences, monoidal categories, the Grothendieck construction,
the direct/exceptional image, the arrow form of coverage, the coherence
laws of the pullback pseudofunctor, the indexed lattice laws, the arrow
form of the dense and extreme topologies, of the pushforward-pullback
adjunction, of the bind, of the topology generated by a pretopology,
of the topology induced along a functor, of cover-preserving functors,
of the composition laws of these functors, of the topology generated
by a `Coverage`-style coverage, of the topology generated by a
precoverage, and of the Zariski topology on schemes.

This part applies the "arrow form" thread to the **atomic topology** —
the second abstract *named* topology of the series after the dense
topology (Part 44). Mathlib defines
`GrothendieckTopology.atomic (hro : RightOreCondition C) : GrothendieckTopology C`
(a sieve is covering iff it is nonempty; the right Ore condition is
required for pullback stability), but provides **neither the pointwise
bridge** (the analogue of `dense_covering` for `atomic`) **nor any
arrow-form law**. We fill the gap with six original theorems:

  - `atomic_covering` (pointwise bridge, `Iff.rfl`):
    `S ∈ atomic hro X ↔ ∃ Y f, S f` — the missing analogue of
    `dense_covering`;
  - `covers_iff_atomic` (central): `(atomic hro).Covers S f ↔ ∃ Z g,
    S (g ≫ f)` — the atomic topology covers `f` by `S` if and only if
    `S` contains at least one arrow above `f`;
  - `covers_atomic_of_mem`: any arrow of `S` covers any arrow;
  - `covers_atomic_precomp`: stability under precomposition;
  - `covers_atomic_id`: pointwise collapse at the identity;
  - `covers_atomic_top`: the maximal sieve covers every arrow.

The guiding thread: every pointwise statement `S ∈ J X` has a twin in
arrow form `J.Covers S f` (via `covers_iff`, `S.pullback f ∈ J Y`).
After the dense topology (P44) and the Zariski topology (P56), the
atomic topology is the third named milestone: its arrow form says
exactly that "covering = being nonempty above the target".
-/

import Mathlib.CategoryTheory.Sites.Grothendieck

namespace Grothendieck.CoversAtomicArrow_en

open CategoryTheory

/-!
## Section 1: the pointwise bridge and the arrow form

Mathlib's atomic topology is constructed pointwise
(`sieves X := {S | ∃ (Y) (f : Y ⟶ X), S f}`), but without the membership
lemma that Mathlib provides for `dense` (`dense_covering`). We establish
it first (`Iff.rfl`: it is the very definition), then translate it to
arrow form: `S` covers `f` for `atomic` if and only if the pullback
`S.pullback f` is nonempty — that is, iff `S` contains an arrow
compositing above `f`.
-/

/-- Pointwise bridge for the atomic topology — the analogue of Mathlib's
    `dense_covering`, absent from the library: a sieve is covering for
    `atomic hro X` if and only if it contains at least one arrow.
    Proof: `Iff.rfl` — membership is *defined* by this predicate in the
    construction of the topology. -/
theorem atomic_covering {C : Type*} [Category C] (hro : GrothendieckTopology.RightOreCondition C)
    {X : C} (S : Sieve X) :
    S ∈ GrothendieckTopology.atomic hro X ↔ ∃ (Y : C) (f : Y ⟶ X), S f :=
  Iff.rfl

/-- Arrow form of the atomic topology: `(atomic hro).Covers S f` if and
    only if `S` contains an arrow above `f` — nonemptiness of the sieve
    is tested after pullback along `f`.
    Proof: `covers_iff` reduces the left-hand side to `S.pullback f ∈
    atomic hro Y`, `atomic_covering` unfolds membership into "the
    pullback is nonempty", and the definition of the pullback of a sieve
    (`S.pullback f g = S (g ≫ f)`, plus associativity) makes both sides
    coincide. -/
theorem covers_iff_atomic {C : Type*} [Category C]
    (hro : GrothendieckTopology.RightOreCondition C) {X Y : C} (S : Sieve X) (f : Y ⟶ X) :
    (GrothendieckTopology.atomic hro).Covers S f ↔ ∃ (Z : C) (g : Z ⟶ Y), S (g ≫ f) := by
  rw [GrothendieckTopology.covers_iff, atomic_covering]
  simp

/-!
## Section 2: witness arrows and stability

Two immediate consequences of Section 1: a *witness* arrow belonging to
`S` suffices to cover every arrow towards `X`, and arrow coverage is
stable under precomposition (the `pullback_stable` property of the
topology, rewritten via `Sieve.pullback_comp`).
-/

/-- Any arrow of `S` covers every arrow towards `X` for the atomic
    topology: `S f → (atomic hro).Covers S f`.
    Proof: `S f` forces `S.pullback f = ⊤`
    (`Sieve.pullback_eq_top_of_mem`), and the maximal sieve belongs to
    every topology (`top_mem`). -/
theorem covers_atomic_of_mem {C : Type*} [Category C]
    (hro : GrothendieckTopology.RightOreCondition C) {X Y : C} (S : Sieve X)
    {f : Y ⟶ X} (h : S f) :
    (GrothendieckTopology.atomic hro).Covers S f := by
  rw [GrothendieckTopology.covers_iff, Sieve.pullback_eq_top_of_mem S h]
  exact GrothendieckTopology.top_mem (GrothendieckTopology.atomic hro) Y

/-- The arrow form of `atomic` is stable under precomposition: if `S`
    covers `f : Y ⟶ X`, then `S` also covers `g ≫ f` for every
    `g : Z ⟶ Y`.
    Proof: `covers_iff` on both sides, then `Sieve.pullback_comp`
    identifies `S.pullback (g ≫ f)` with `(S.pullback f).pullback g`,
    and `pullback_stable g h` of the atomic topology concludes. -/
theorem covers_atomic_precomp {C : Type*} [Category C]
    (hro : GrothendieckTopology.RightOreCondition C) {X Y Z : C} (S : Sieve X)
    (f : Y ⟶ X) (g : Z ⟶ Y) :
    (GrothendieckTopology.atomic hro).Covers S f →
      (GrothendieckTopology.atomic hro).Covers S (g ≫ f) := by
  intro h
  rw [GrothendieckTopology.covers_iff] at h ⊢
  rw [Sieve.pullback_comp]
  exact (GrothendieckTopology.atomic hro).pullback_stable g h

/-!
## Section 3: identity and the maximal sieve

`Sieve.pullback_id` makes the pullback along the identity trivial: the
arrow form above `𝟙 X` collapses exactly onto pointwise membership
`S ∈ atomic hro X`. The maximal sieve, for its part, covers every arrow
for every topology — we establish it for `atomic` via
`Sieve.pullback_top`.
-/

/-- The arrow form of `atomic` above the identity coincides with
    pointwise membership:
    `(atomic hro).Covers S (𝟙 X) ↔ S ∈ atomic hro X`.
    Proof: `covers_iff` then `Sieve.pullback_id`. -/
theorem covers_atomic_id {C : Type*} [Category C]
    (hro : GrothendieckTopology.RightOreCondition C) {X : C} (S : Sieve X) :
    (GrothendieckTopology.atomic hro).Covers S (𝟙 X) ↔
      S ∈ GrothendieckTopology.atomic hro X := by
  rw [GrothendieckTopology.covers_iff, Sieve.pullback_id]

/-- The maximal sieve covers every arrow for the atomic topology:
    `(atomic hro).Covers ⊤ f`.
    Proof: `covers_iff` then `Sieve.pullback_top` (`⊤.pullback f = ⊤`),
    and `top_mem` concludes. -/
theorem covers_atomic_top {C : Type*} [Category C]
    (hro : GrothendieckTopology.RightOreCondition C) {X Y : C} (f : Y ⟶ X) :
    (GrothendieckTopology.atomic hro).Covers ⊤ f := by
  rw [GrothendieckTopology.covers_iff, Sieve.pullback_top]
  exact GrothendieckTopology.top_mem (GrothendieckTopology.atomic hro) Y

end Grothendieck.CoversAtomicArrow_en
