/-
Copyright (c) 2026 CoursIA. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Hommage Grothendieck — Part 49 : arrow form of the induced topology

Alexandre Grothendieck (1928-2014).

Extension Phase 5 (#2159, EPIC #1646).

Parts 1-48 established the foundations: categories, sieves, topologies,
lattice laws, pullback identities, sheaf bases, covering closure,
calibration, subcanonicity, dense topologies, sheaves, internal hom,
Čech cohomology, Mayer-Vietoris limit, Kan extensions, adjunctions, monads,
equivalences, monoidal categories, the Grothendieck construction, the
direct/exceptional image, the arrow form of the covering, the coherence
laws of the pullback pseudo-functor, the indexed lattice laws, the arrow
form of the dense and extremal topologies, of the pushforward-pullback
adjunction, of the bind and of the topology generated by a pretopology.

This part applies the guiding thread "arrow form" to the **induced topology**
along a functor. When `G : C ⥤ (D, K)` is locally dense and locally full/
faithful, Mathlib builds a topology `G.inducedTopology K` on `C` (the sieves
whose image under `G` is covering in `D`) and proves
`mem_inducedTopology_sieves_iff` — but **no law connects this topology to the
arrow form `J.Covers`**. We fill the gap: the characteristic arrow form
(`covers_iff`, via `functorPushforward` of the pullback), the bridge to the
coverings of `K` by existence of a pullback (`covers_iff_exists`), and the
consequences (identity, pointwise membership, monotonicity, stability under
precomposition).
-/

import Mathlib.CategoryTheory.Sites.DenseSubsite.InducedTopology

namespace Grothendieck.CoversInducedTopology_en

open CategoryTheory

/-!
## Section 1 : the arrow form of the induced topology

The induced topology declares a sieve `S` covering on `X` as soon as its
image `S.functorPushforward G` is covering in `D`
(`mem_inducedTopology_sieves_iff`). In arrow form, `G.inducedTopology K`
covers `f : Y ⟶ X` by `S` if and only if the image under `G` of the pullback
`S.pullback f` is covering in `K (G.obj Y)`. This is exactly `covers_iff` of
Mathlib, specialized to the induced topology.
-/

/-- Arrow form of `mem_inducedTopology_sieves_iff`: `G.inducedTopology K`
    covers `f : Y ⟶ X` by `S` if and only if the image under `G` of the
    pullback `S.pullback f` is covering in `K (G.obj Y)`.
    Proof: `covers_iff` reduces the left member to
    `S.pullback f ∈ G.inducedTopology K Y`, then
    `mem_inducedTopology_sieves_iff` identifies membership in the induced
    topology with membership of the image under `G`. -/
theorem covers_iff {C : Type*} [Category C] {D : Type*} [Category D] (G : C ⥤ D)
    (K : GrothendieckTopology D) [G.LocallyCoverDense K] [G.IsLocallyFull K]
    [G.IsLocallyFaithful K] {X Y : C} (S : Sieve X) (f : Y ⟶ X) :
    (G.inducedTopology K).Covers S f ↔
      (S.pullback f).functorPushforward G ∈ K (G.obj Y) := by
  rw [GrothendieckTopology.covers_iff, Functor.mem_inducedTopology_sieves_iff]

/-!
## Section 2 : the bridge to the coverings of `K`

Under the assumption that `G` is full and faithful, the theorem of Mathlib
`pushforward_cover_iff_cover_pullback` characterizes the membership of the
image under a pullback: `R.functorPushforward G ∈ K (G.obj Y)` if and only if
there exists a covering `T` of `K (G.obj Y)` whose pullback under `G` is
exactly `R`. Combined with `covers_iff`, this gives the complete arrow form
of the induced topology: `S` covers `f` if and only if `S.pullback f` is the
pullback (under `G`) of a covering of `K` on `G.obj Y`.
-/

/-- The arrow form of the induced topology, via the bridge of
    `pushforward_cover_iff_cover_pullback`: `G.inducedTopology K` covers
    `f : Y ⟶ X` by `S` if and only if there exists a covering
    `T : K (G.obj Y)` whose pullback under `G` is `S.pullback f`.
    Proof: `covers_iff` reduces to the right member; the theorem of Mathlib
    `pushforward_cover_iff_cover_pullback` (full + faithful) converts the
    membership of the image into the existence of such a `T`. -/
theorem covers_iff_exists {C : Type*} [Category C] {D : Type*} [Category D]
    (G : C ⥤ D) (K : GrothendieckTopology D) [G.LocallyCoverDense K]
    [G.IsLocallyFull K] [G.IsLocallyFaithful K] [G.Full] [G.Faithful]
    {X Y : C} (S : Sieve X) (f : Y ⟶ X) :
    (G.inducedTopology K).Covers S f ↔
      ∃ T : K (G.obj Y), T.val.functorPullback G = S.pullback f := by
  rw [covers_iff, Functor.pushforward_cover_iff_cover_pullback]

/-!
## Section 3 : identity and pointwise membership

`Sieve.pullback_id` makes the pullback along the identity trivial:
`S.pullback (𝟙 X) = S`. The arrow form of `G.inducedTopology K` above
`𝟙 X` therefore falls back exactly on the pointwise membership
`S ∈ G.inducedTopology K X`.
-/

/-- The arrow form of `G.inducedTopology K` above the identity coincides
    with the pointwise membership: `S` covers `𝟙 X` if and only if
    `S ∈ G.inducedTopology K X`.
    Proof: `covers_iff` then `Sieve.pullback_id`. -/
theorem covers_id {C : Type*} [Category C] {D : Type*} [Category D] (G : C ⥤ D)
    (K : GrothendieckTopology D) [G.LocallyCoverDense K] [G.IsLocallyFull K]
    [G.IsLocallyFaithful K] {X : C} (S : Sieve X) :
    (G.inducedTopology K).Covers S (𝟙 X) ↔ S ∈ G.inducedTopology K X := by
  rw [GrothendieckTopology.covers_iff, Sieve.pullback_id]

/-- The right member of `covers_iff` above the identity, unfolded:
    `S` covers `𝟙 X` if and only if `S.functorPushforward G ∈ K (G.obj X)`.
    Proof: `covers_id` then `mem_inducedTopology_sieves_iff`. -/
theorem covers_id_iff {C : Type*} [Category C] {D : Type*} [Category D]
    (G : C ⥤ D) (K : GrothendieckTopology D) [G.LocallyCoverDense K]
    [G.IsLocallyFull K] [G.IsLocallyFaithful K] {X : C} (S : Sieve X) :
    (G.inducedTopology K).Covers S (𝟙 X) ↔ S.functorPushforward G ∈ K (G.obj X) := by
  rw [covers_id, Functor.mem_inducedTopology_sieves_iff]

/-!
## Section 4 : monotonicity

`Sieve.functorPushforward` is monotone: if `S ≤ R`, then
`S.functorPushforward G ≤ R.functorPushforward G`. The topology property
`superset_covering` of `K` then transports the membership of the image of `S`
to that of the image of `R`, and `covers_iff` gives the monotonicity of the
arrow form: if `S` covers `f`, any supersieve `R` also covers `f`.
-/

/-- The arrow form of the induced topology is monotone: if `S` covers
    `f : Y ⟶ X`, then any supersieve `R` of `S` also covers `f`.
    Proof: `covers_iff` on both sides, `Sieve.functorPushforward_monotone`
    transports `S ≤ R` to the images, and `superset_covering` of `K`
    concludes. -/
theorem covers_monotone {C : Type*} [Category C] {D : Type*} [Category D]
    (G : C ⥤ D) (K : GrothendieckTopology D) [G.LocallyCoverDense K]
    [G.IsLocallyFull K] [G.IsLocallyFaithful K] {X Y : C} {S R : Sieve X}
    (hSR : S ≤ R) (f : Y ⟶ X) (hS : (G.inducedTopology K).Covers S f) :
    (G.inducedTopology K).Covers R f := by
  rw [covers_iff] at hS ⊢
  exact K.superset_covering
    ((Sieve.functorPushforward_monotone (F := G) (X := Y)) (Sieve.pullback_monotone f hSR)) hS

/-!
## Section 5 : stability under precomposition

The topology property `pullback_stable` of `G.inducedTopology K` says that a
morphism in the induced topology transports along a pullback. By the identity
`S.pullback (g ≫ f) = (S.pullback f).pullback g` (`Sieve.pullback_comp`),
this is exactly the stability of the arrow form: if `S` covers `f`, it also
covers `g ≫ f` for every `g : Z ⟶ Y`.
-/

/-- The arrow form of `G.inducedTopology K` is stable under precomposition:
    if `S` covers `f : Y ⟶ X`, then `S` also covers `g ≫ f` for every
    `g : Z ⟶ Y`.
    Proof: `covers_iff` on both sides, then `Sieve.pullback_comp`
    identifies `S.pullback (g ≫ f)` with `(S.pullback f).pullback g`, and
    `pullback_stable g` of the induced topology concludes. -/
theorem covers_precomp {C : Type*} [Category C] {D : Type*} [Category D]
    (G : C ⥤ D) (K : GrothendieckTopology D) [G.LocallyCoverDense K]
    [G.IsLocallyFull K] [G.IsLocallyFaithful K] {X Y Z : C} (S : Sieve X)
    (f : Y ⟶ X) (g : Z ⟶ Y)
    (h : (G.inducedTopology K).Covers S f) :
    (G.inducedTopology K).Covers S (g ≫ f) := by
  rw [covers_iff] at h ⊢
  rw [Sieve.pullback_comp]
  exact (G.inducedTopology K).pullback_stable g h

end Grothendieck.CoversInducedTopology_en
