/-
Copyright (c) 2026 CoursIA. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

Grothendieck tribute — Part 82 (EN sibling of `Grothendieck/FlasqueExact.lean`):
from the sieve to the epimorphism — extension of sections and the short exact
sequence.

Alexandre Grothendieck (1928-2014).

Phase 2 extension (#2159, Epic #1646).

Part 79 introduced flasqueness by sieves — `IsFlasqueSieves P`: every
compatible family on **any** sieve amalgamates. This part asks what that
reading **implies** and **receives** from Mathlib's topological definition
(`TopCat.Presheaf.IsFlasque`, vendored: restriction maps are epimorphic along
**every** arrow of `(Opens X)ᵒᵖ`), and then carries Godement's theorem across
the site/topology frontier.

Four results:

  - `exists_isAmalgamation_of_sieveTop`: the **maximal** sieve always
    amalgamates, with no hypothesis on `P` — every compatible family there is
    determined by its value at `𝟙`, compatibility with the pair `(g, 𝟙)`
    forcing `x g = P.map g.op (x 𝟙)`. Sieve-flasqueness is thus a condition
    on **proper** sieves only.
  - `exists_lift_of_isFlasqueSieves_of_mono`: sieve-flasque ⇒ every section
    extends along every **mono** `f` (arbitrary site, no topology). The
    singleton family of a section `s` is compatible only if `s` is invariant
    under the pairs `p₁ ≫ f = p₂ ≫ f`; a mono trivializes exactly those pairs
    — this is the "subobject" reading of section extension.
  - `exists_isAmalgamation_of_isFlasque_generate_singleton`: partial converse,
    topological this time — `Presheaf.IsFlasque` (Mathlib, epi on every
    arrow) ⇒ amalgamation on every sieve **generated by a single arrow**.
    The residual gap between `IsFlasque` and `IsFlasqueSieves` is exactly
    amalgamation on multi-generator sieves.
  - `epi_of_shortExact_of_isFlasqueSieves`: **Godement II.3 read on the
    sieve side**. Mathlib's Zorn proof (`epi_of_shortExact`) consumes the
    flasqueness of `X₁` exactly **once**, at the inclusion
    `homOfLE inf_le_right` — the local replay of the argument with the single
    substitution of the mono-extension above shows that the hypothesis
    "epi on every arrow" can there be replaced by "amalgamation on every
    sieve". The short exact sequence theorem already lives in the world of
    sites.

Honest frontier, in line with Parts 80-81: the full converse
(`Presheaf.IsFlasque` ⇒ `IsFlasqueSieves`) would require the Zorn argument on
multi-arrow families — the mono-extension is choice-free, general
amalgamation is not. It remains open and is documented here.

References:
  - R. Godement, *Topologie algébrique et théorie des faisceaux* [God58],
    Chap. II §3 (short exact sequence theorem) and II §5 (Zorn).
  - Mathlib, `Mathlib.Topology.Sheaves.Flasque` (vendored) — the proof
    `epi_of_shortExact` and its single consumption of the hypothesis.
  - SGA 4, Exposé II (sites and sieves).
  - S. Mac Lane, I. Moerdijk, *Sheaves in Geometry and Logic* [MM92],
    Chap. II §3, III.4 (compatible families).
  - Part 79 (`Grothendieck.Flasque`): `IsFlasqueSieves`.
  - Part 80 (`Grothendieck.FlasqueStability`): the "choice-free" line.
  - Part 81 (`Grothendieck.FlasqueRetract`): retracts, same frontier.

i18n convention (EPIC #4980 ratified 2026-07-04): this module is the English
canonical sibling of `Grothendieck/FlasqueExact.lean` — `_en` suffix on the
namespace (`Grothendieck.FlasqueExact_en`), mirror imports, translated
docstrings and comments. Theorem statements, Lean tactics, lemma names and
Mathlib references remain in English (Mathlib 4, standard tactic DSL). Only
the docstrings `/-- ... -/` and comments `-- ...` differ between the two
files. Anti-§D byte-identity guaranteed: the namespace body is preserved bit
for bit (statements and proofs byte-identical between `FlasqueExact.lean`
and `FlasqueExact_en.lean`).

Epic #1646, Phase 2 (#2159). All `sorry`s eliminated at creation.
-/

import Grothendieck.Flasque

namespace Grothendieck.FlasqueExact_en

open CategoryTheory CategoryTheory.Limits Opposite

universe u v

section Site

variable {C : Type u} [Category.{v} C]

/-- The **maximal** sieve always amalgamates: every compatible family on `⊤`
is entirely determined by its value at `𝟙` — compatibility applied to the
pair `(g, 𝟙)` over `(𝟙, g)` forces `x g = P.map g.op (x 𝟙)` for every arrow
`g`. No hypothesis on `P`: sieve-flasqueness (Part 79) is a condition on
**proper** sieves only; the maximal sieve contributes nothing to it. -/
theorem exists_isAmalgamation_of_sieveTop {P : Cᵒᵖ ⥤ Type (max v u)} {A : C}
    (x : (⊤ : Sieve A).arrows.FamilyOfElements P) (hx : x.Compatible) :
    ∃ t, x.IsAmalgamation t := by
  refine ⟨x (𝟙 A) (Sieve.top_apply (𝟙 A)), ?_⟩
  intro Y g _
  have h := hx (Y₁ := A) (Y₂ := Y) (Z := Y) (g₁ := g) (g₂ := 𝟙 Y)
    (f₁ := 𝟙 A) (f₂ := g) (Sieve.top_apply (𝟙 A)) (Sieve.top_apply g) (by simp)
  simpa using h

/-- **Extension along a mono**: a sieve-flasque presheaf extends every
section along every mono arrow `f : B ⟶ A`. The singleton family of a
section `s` of `B` is compatible only if `s` is invariant under the pairs
`p₁ ≫ f = p₂ ≫ f` — a condition a mono makes trivial (`cancel_mono`). This
is the "subobject" reading of section extension: the sieve generated by `f`
is the image of the subobject `B` in `A`, and amalgamation there is exactly
the extension of `s`. -/
theorem exists_lift_of_isFlasqueSieves_of_mono {P : Cᵒᵖ ⥤ Type (max v u)}
    [IsFlasqueSieves P] {A B : C} (f : B ⟶ A) [Mono f] (s : P.obj (op B)) :
    ∃ t : P.obj (op A), P.map f.op t = s := by
  have hx₀ : ((Presieve.FamilyOfElements.singletonEquiv P f).symm s : (Presieve.singleton f).FamilyOfElements P).Compatible := by
    rw [Presieve.FamilyOfElements.compatible_singleton_iff]
    intro Z p₁ p₂ h
    have hp : p₁ = p₂ := (CategoryTheory.cancel_mono f).mp h
    subst hp
    rfl
  obtain ⟨t, ht⟩ := IsFlasqueSieves.amalgamates (Sieve.generate (Presieve.singleton f))
    ((Presieve.FamilyOfElements.singletonEquiv P f).symm s).sieveExtend hx₀.sieveExtend
  have h1 : (((Presieve.FamilyOfElements.singletonEquiv P f).symm s).sieveExtend.restrict
    (Sieve.le_generate (Presieve.singleton f))).IsAmalgamation t :=
    Presieve.isAmalgamation_restrict (Sieve.le_generate (Presieve.singleton f)) _ _ ht
  rw [Presieve.restrict_extend hx₀] at h1
  rw [Presieve.FamilyOfElements.isAmalgamation_singleton_iff] at h1
  exact ⟨t, by simpa [Presieve.FamilyOfElements.singletonEquiv_symm_apply_self] using h1⟩

end Site

section Topologique

open TopCat TopCat.Presheaf TopologicalSpace

open scoped AlgebraicGeometry

variable {X : TopCat.{u}}

/-- **Partial topological converse**: a presheaf flasque in Mathlib's sense
(`Presheaf.IsFlasque` — restriction epimorphic along **every** arrow of
`(Opens X)ᵒᵖ`) amalgamates every compatible family on a sieve **generated
by a single arrow**. Surjectivity along the generator `f` provides the
candidate; compatibility restricted to the singleton is exactly the
amalgamation equation. The residual gap between `Presheaf.IsFlasque` and
`IsFlasqueSieves` (Part 79) lies entirely in **multi-generator** sieves — a
Zorn frontier, documented at the top of the module. -/
theorem exists_isAmalgamation_of_isFlasque_generate_singleton
    {P : TopCat.Presheaf Type X} [P.IsFlasque] {A B : Opens X} (f : B ⟶ A)
    (x : (Sieve.generate (Presieve.singleton f)).arrows.FamilyOfElements P)
    (hx : x.Compatible) : ∃ t, x.IsAmalgamation t := by
  have hf : Epi (P.map f.op) := IsFlasque.epi f.op
  obtain ⟨t, ht⟩ := (CategoryTheory.epi_iff_surjective _).mp hf
    (x f (Sieve.le_generate (Presieve.singleton f) _ _ ⟨⟩))
  have h0 : (x.restrict (Sieve.le_generate (Presieve.singleton f))).IsAmalgamation t :=
    (Presieve.FamilyOfElements.isAmalgamation_singleton_iff f _ _).mpr
      (by simpa [Presieve.FamilyOfElements.restrict] using ht)
  exact ⟨t, by
    rw [← Presieve.extend_restrict hx]
    exact Presieve.isAmalgamation_sieveExtend _ _ h0⟩

open TopCat.Sheaf.IsFlasque in
set_option backward.isDefEq.respectTransparency false in
set_option maxHeartbeats 1000000 in
/-- **Godement II.3 read on the sieve side**: for a short exact sequence of
sheaves of abelian groups, if `X₁` is flasque **in the sieve sense** (Part
79, via the forgetful functor to types), then `S.g` is epimorphic on every
open. Mathlib's Zorn proof (`epi_of_shortExact`) consumes the flasqueness of
`X₁` exactly once, at the inclusion `homOfLE inf_le_right`; the local replay
of the argument — this single link substituted by
`exists_lift_of_isFlasqueSieves_of_mono` — shows that the hypothesis "epi
along every arrow" can be replaced by "amalgamation on every sieve".
[God58] Chap. II §3. -/
theorem epi_of_shortExact_of_isFlasqueSieves {S : ShortComplex (Sheaf AddCommGrpCat X)}
    (hS : S.ShortExact) [IsFlasqueSieves (S.X₁.obj ⋙ CategoryTheory.forget AddCommGrpCat)]
    {U : Opens X} : Epi (S.g.1.app (op U)) := by
  refine (AddCommGrpCat.epi_iff_surjective _).mpr (fun s => ?_)
  obtain ⟨t, ht⟩ := exists_maximal_of_chains_bounded
    (structured_arrows_elements_sheaf_chains_bounded S.g s)
    (fun ⟨f⟩ ⟨g⟩ => ⟨g ≫ f⟩)
  have tle : t.right.1.unop ≤ U := leOfHom t.hom.1.unop
  have tcomp : s |_ t.right.1.unop = S.g.hom.app t.right.1 t.right.2 :=
    CategoryOfElements.map_snd t.hom
  have hU : U ≤ t.right.1.unop := by
    intro x hx
    have hls := (TopCat.Sheaf.isLocallySurjective_iff_epi S.g).mpr hS.epi_g
    obtain ⟨W, Wle, ⟨t₁, ht₁⟩, hW⟩ := (isLocallySurjective_iff S.g.hom).mp hls U s x hx
    let t₂ := t.right.2 |_ (t.right.1.unop ⊓ W) - t₁ |_ (t.right.1.unop ⊓ W)
    have h0 : (S.g.hom.app (op (t.right.1.unop ⊓ W))) t₂ = 0 := by
      simp [map_restrict, ← tcomp, restrict_restrict, ht₁, t₂]
    obtain ⟨t₃, ht₃⟩ := Sheaf.sections_exact_of_left_exact hS.1 hS.2 t₂ h0
    obtain ⟨t₄, (htr : t₄ |_ (t.right.1.unop ⊓ W) = t₃)⟩ :=
      exists_lift_of_isFlasqueSieves_of_mono
        (P := S.X₁.obj ⋙ CategoryTheory.forget AddCommGrpCat)
        (homOfLE inf_le_right) t₃
    let f : Fin 2 → Opens X := ![t.right.1.unop, W]
    let sf : (i : Fin 2) → S.X₂.obj.obj (op (f i))
    | 0 => t.right.2
    | 1 => t₁ + (S.f.hom.app (op W)) t₄
    have hagree : sf 0 |_ (t.right.1.unop ⊓ W) = sf 1 |_ (t.right.1.unop ⊓ W) := by
      dsimp [sf, f]
      simp only [restrict_sum, ← map_restrict, htr, ht₃, t₂, add_sub_cancel]
    obtain ⟨t₅, ht₅, _⟩ : ∃! t₅, IsGluing S.X₂.obj f sf t₅ := by
      apply Sheaf.existsUnique_gluing
      simp only [IsCompatible, Fin.forall_fin_two]
      refine ⟨⟨rfl, hagree⟩, Eq.symm ?_, rfl⟩
      apply_fun (fun s => restrictOpen s (W ⊓ t.right.1.unop)
        (le_of_eq (inf_comm _ _))) at hagree
      rw [restrict_restrict, restrict_restrict] at hagree
      exact hagree
    have le : iSup f ≤ U := iSup_le_iff.mpr (Fin.forall_fin_two.mpr ⟨tle, Wle⟩)
    let t₆ : Under S.g s :=
      StructuredArrow.mk (S := ⟨op U, s⟩)
        (T := (Functor.whiskerRight S.g.hom (CategoryTheory.forget AddCommGrpCat)).mapElements)
        (Y := ⟨op (iSup f), t₅⟩) <| CategoryOfElements.homMk _ _ (homOfLE le).op (by
        refine (TopCat.Sheaf.eq_app_of_locally_eq ht₅ (by rw [Fin.forall_fin_two]; exact ⟨tle, Wle⟩) ?_).symm
        rw [Fin.forall_fin_two]
        refine ⟨tcomp.symm, ?_⟩
        simp only [Fin.isValue, map_add, homOfLE_leOfHom, sf, f]
        have hfg : (S.f.hom.app (op W) ≫ S.g.hom.app (op W)) = 0 := by
          rw [← NatTrans.comp_app, ← ObjectProperty.FullSubcategory.comp_hom, S.zero]
          rfl
        simp [← CategoryTheory.comp_apply, hfg, ht₁]
        rfl)
    have h₆ : Nonempty (t₆ ⟶ t) := Nonempty.intro (StructuredArrow.homMk
      (CategoryOfElements.homMk _ _ (homOfLE (le_iSup f 0)).op (ht₅ 0)) (by cat_disch))
    exact leOfHom ((ht t₆) h₆).some.right.1.unop ((le_iSup f 1) hW)
  exact ⟨t.right.2 |_ U, by simp [map_restrict, ← tcomp, restrict_restrict]⟩

end Topologique

end Grothendieck.FlasqueExact_en
