/-
Grothendieck tribute — Part 67: the local-surjectivity spectrum.

Alexandre Grothendieck (1928-2014).

Extension Phase 2 (#2159, Epic #1646).

Part 66 studied the topologies for which a presheaf is a sheaf. This module
moves from objects to morphisms: for which topologies is a morphism of
presheaves locally surjective?

For `f : F ⟶ G`, Mathlib associates to every section `s` of `G` the sieve
`imageSieve f s` of restrictions admitting a local preimage. The morphism is
locally surjective for `J` when each such sieve is `J`-covering. This
definition exhibits an **upward-closed** spectrum in the lattice of
topologies, dual to Part 66's downward-closed sheaf spectrum:

  - `isLocallySurjective_top`: every morphism is locally surjective for the
    maximal topology, which declares every sieve covering;
  - `isLocallySurjective_sup`: the property for the left operand suffices for
    their supremum;
  - `isLocallySurjective_iSup`: likewise, one witness in a family suffices for
    its supremum;
  - `isLocallySurjective_bot_iff`: at the other endpoint, local surjectivity
    for the minimal topology is equivalent to objectwise surjectivity.

The last result provides the geometric content of the spectrum: under the
minimal topology the only covering sieve is the maximal sieve, so a "local"
preimage over the identity is already a global preimage.

References:
  - Stacks Project, tag 00WL ("Injective and surjective maps of sheaves").
  - S. Mac Lane, I. Moerdijk, *Sheaves in Geometry and Logic* [MM92],
    Ch. III §4.
  - Mathlib, `CategoryTheory.Sites.LocallySurjective`.

i18n convention (EPIC #4980, ratified 2026-07-04): this module is the English
sibling of `LocalSurjectivitySpectrum.lean`. Lean declarations, proofs, and
names remain identical; only docstrings and comments differ.

Epic #1646, Phase 2 (#2159). No `sorry` introduced.
-/

import Grothendieck.TopologyLattice
import Mathlib.CategoryTheory.Sites.LocallySurjective

namespace Grothendieck_en

open CategoryTheory CategoryTheory.GrothendieckTopology Opposite

universe u v w

section Contenu

variable {C : Type u} [Category.{v} C]
variable {F G : Cᵒᵖ ⥤ Type w} (f : F ⟶ G)

/-- Every morphism of presheaves is locally surjective for the maximal
topology: every image sieve is covering there by definition. -/
theorem isLocallySurjective_top :
    Presheaf.IsLocallySurjective (⊤ : GrothendieckTopology C) f := by
  constructor
  intro U s
  exact GrothendieckTopology.top_covering

/-- The local-surjectivity spectrum grows toward every binary supremum.

The image-sieve covering for `J₁` is transported to `J₁ ⊔ J₂` along the
canonical inclusion `J₁ ≤ J₁ ⊔ J₂`. -/
theorem isLocallySurjective_sup {J₁ J₂ : GrothendieckTopology C}
    (h : Presheaf.IsLocallySurjective J₁ f) :
    Presheaf.IsLocallySurjective (J₁ ⊔ J₂) f := by
  exact Presheaf.isLocallySurjective_of_le le_sup_left f h

/-- The local-surjectivity spectrum grows toward an indexed supremum.

One witness in the family supplies the image-sieve covering, then `le_iSup`
transports it to the topology generated by all members. -/
theorem isLocallySurjective_iSup {ι : Type*} {J : ι → GrothendieckTopology C}
    (h : ∃ i, Presheaf.IsLocallySurjective (J i) f) :
    Presheaf.IsLocallySurjective (⨆ i, J i) f := by
  obtain ⟨i, hi⟩ := h
  exact Presheaf.isLocallySurjective_of_le (le_iSup J i) f hi

/-- For the minimal topology, local surjectivity is equivalent to objectwise
surjectivity.

In the forward direction, `bot_covering` forces every image sieve to be
maximal; the identity therefore belongs to it and supplies a global preimage.
The converse is Mathlib's construction from surjective component maps. -/
theorem isLocallySurjective_bot_iff :
    Presheaf.IsLocallySurjective (⊥ : GrothendieckTopology C) f ↔
      ∀ U, Function.Surjective (f.app U) := by
  constructor
  · intro h U s
    have hs : Presheaf.imageSieve f s = ⊤ :=
      GrothendieckTopology.bot_covering.mp (h.imageSieve_mem s)
    have hid : Presheaf.imageSieve f s (𝟙 U.unop) := by
      rw [hs]
      trivial
    obtain ⟨t, ht⟩ := hid
    exact ⟨t, by simpa using ht⟩
  · intro h
    exact Presheaf.isLocallySurjective_of_surjective (⊥ : GrothendieckTopology C) f h

end Contenu

end Grothendieck_en
