/-
Copyright (c) 2026 CoursIA. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Grothendieck Homage — Part 42 : laws of the arrow form under iterated pullback

Alexandre Grothendieck (1928-2014).

Phase 5 extension (#2159, EPIC #1646).

Parts 1-41 established the foundations: categories, sieves, topologies,
lattice laws, pullback identities, sheaf bases, covering closure,
calibration, subcanonicality, dense topologies, sheaves, internal hom,
Cech cohomology, Mayer-Vietoris limit, Kan extensions, adjunctions, monads,
equivalences, monoidal categories, limits and colimits, comma pairs, direct
images, proper theorems on the arrow form (`J.Covers S f`), on the bundled
cover (`J.Cover X`), the coherence laws of the pullback pseudo-functor
(Part 37), the functor laws of pullback (Part 38), the lattice laws of
topologies (Part 39), the laws of the arrow form under pullback (Part 40)
and the order laws of the arrow form (Part 41).

Part 42 establishes the **laws of the arrow form `J.Covers S f` under
iterated pullback of sieves**: Mathlib provides the topology axioms in
arrow form (`arrow_max`, `arrow_stable`, `arrow_trans`, `arrow_intersect`),
the definitional `covers_iff` and the laws of `Sieve.pullback`
(`pullback_id`, `pullback_comp`, `pullback_inter`), but **does not provide**
the reading of these laws in terms of `J.Covers`: the unit of pullback, its
associativity, the distributivity over meet and the commutation with sieve
generation along an arrow (conditioned by the existence of the pullbacks of
the family). This module states and proves them:

  - `covers_pullback_id` : pulling back by the identity is a neutral
    operation in arrow form (unit of the pullback pseudo-functor).
  - `covers_pullback_assoc` : pulling back along `g ≫ f` and then along
    `h` is pulling back along `g` then along `h` (associativity, coherence
    law of the pullback pseudo-functor).
  - `covers_sieve_pullback_inter` : the pullback of a meet sieve is the meet
    of the pullbacks (distributivity of pullback over the sieve lattice, in
    arrow form).
  - `covers_pullback_generate` : covering the sieve generated by
    `R.pullbackArrows f` is covering the sieve generated by `R` along the
    composite (generation / pullback commutation, in arrow form).

Each proof is a **genuine tactic proof** (DEEP vein): it composes the laws of
`Sieve.pullback` (`pullback_id`, `pullback_comp`, `pullback_inter`,
`pullbackArrows_comm`) with the definitional `covers_iff` and the arrow-form
law `covers_comp_iff` (Part 35). No proof is a re-export.

EPIC #1646, Phase 5 (#2159). All `sorry`s eliminated at creation.

### i18n convention (EPIC #4980 ratified by user 2026-07-04)

This module is paired with its French sibling in the sibling file
`PullbackCoversLaws.lean` (sibling pair pattern, see PR #6154 for the pilot
on `Utility.lean`). The `_en` namespace suffix is applied to the EN file
(anti-collision, per code-style.md #4980). Theorem statements, lemma names,
Lean tactics and Mathlib references stay in English; only the docstrings
`/-- ... -/` and comments `-- ...` differ between the two files (byte-identity
preservation).
-/

import Mathlib.CategoryTheory.Sites.Grothendieck
import Grothendieck.CoversArrow

namespace Grothendieck.PullbackCoversLaws_en

open CategoryTheory

/-!
## Section 1 : unit of pullback

`Sieve.pullback_id` identifies the pullback by the identity with the sieve
itself. In arrow form, pulling `S` back by `𝟙 X` therefore changes nothing:
`S.pullback (𝟙 X)` covers `f` exactly when `S` covers `f`. This is the unit
of the pullback pseudo-functor (the arrow-form counterpart of `pullbackId`
of Part 37, which stated it at the level of bundled covers `J.Cover X`).
-/

/-- Pulling the sieve back by the identity is a neutral operation in arrow
    form: `S.pullback (𝟙 X)` covers `f` if and only if `S` covers `f`.
    Proof: the definitional `covers_iff` reduces both sides to
    `S.pullback f ∈ J Y`, then `Sieve.pullback_id` identifies
    `S.pullback (𝟙 X)` with `S`. -/
theorem covers_pullback_id {C : Type*} [Category C] {X Y : C}
    (J : GrothendieckTopology C) (S : Sieve X) (f : Y ⟶ X) :
    J.Covers (S.pullback (𝟙 X)) f ↔ J.Covers S f := by
  rw [GrothendieckTopology.covers_iff, GrothendieckTopology.covers_iff,
    Sieve.pullback_id]

/-!
## Section 2 : associativity of pullback

The law `Sieve.pullback_comp` says that pulling back along a composite
`g ≫ f` is pulling back along `g` of the sieve already pulled back by `f`.
In arrow form, this gives the associativity law of the pullback
pseudo-functor: `(S.pullback f).pullback g` and `S.pullback (g ≫ f)` cover
the same arrows.
-/

/-- The associativity law of pullback in arrow form: `(S.pullback f).pullback g`
    covers `h` if and only if `S.pullback (g ≫ f)` covers `h`. Proof: the
    definitional `covers_iff` reduces to the memberships, then
    `Sieve.pullback_comp` identifies the two pulled-back sieves. -/
theorem covers_pullback_assoc {C : Type*} [Category C] {W X Y Z : C}
    (J : GrothendieckTopology C) (S : Sieve Z) (f : Y ⟶ Z) (g : X ⟶ Y)
    (h : W ⟶ X) :
    J.Covers ((S.pullback f).pullback g) h ↔ J.Covers (S.pullback (g ≫ f)) h := by
  rw [GrothendieckTopology.covers_iff, GrothendieckTopology.covers_iff,
    Sieve.pullback_comp]

/-!
## Section 3 : distributivity of pullback over meet

`Sieve.pullback_inter` pushes pullback into the meet of two sieves. In arrow
form, Part 41 read this law along a composite arrow (`covers_pullback_inter`:
`S ⊓ R` covers `g ≫ f`); here we read it on the pullback of the sieve itself:
`(S ⊓ R).pullback f` covers `g` if and only if `S.pullback f ⊓ R.pullback f`
covers `g`.
-/

/-- The distributivity of sieve pullback over meet, in arrow form:
    `(S ⊓ R).pullback f` covers `g` if and only if
    `S.pullback f ⊓ R.pullback f` covers `g`. Proof: `covers_iff` then
    `Sieve.pullback_inter`. -/
theorem covers_sieve_pullback_inter {C : Type*} [Category C] {X Y Z : C}
    (J : GrothendieckTopology C) (S R : Sieve X) (f : Y ⟶ X) (g : Z ⟶ Y) :
    J.Covers ((S ⊓ R).pullback f) g ↔ J.Covers (S.pullback f ⊓ R.pullback f) g := by
  rw [GrothendieckTopology.covers_iff, GrothendieckTopology.covers_iff,
    Sieve.pullback_inter]

/-!
## Section 4 : generation / pullback commutation

The law `Sieve.pullbackArrows_comm` (Mathlib) relates the sieve generated by
the pullbacks of a family `R` of arrows to `X` with the pullback of the sieve
generated by `R`: `Sieve.generate (R.pullbackArrows f) = (Sieve.generate R).pullback f`,
conditional on the existence of the pullbacks of the arrows of `R` along `f`
(`R.HasPullbacks f`). In arrow form, composed with `covers_comp_iff`
(Part 35), this identity gives the generation / pullback commutation:
covering the sieve generated by the pullbacks of `R` along `f` is covering
the sieve generated by `R` along the composite `g ≫ f`.
-/

/-- The generation / pullback commutation in arrow form: covering the sieve
    generated by `R.pullbackArrows f` is covering the sieve generated by `R`
    along the composite. Proof: `Sieve.pullbackArrows_comm` replaces the
    sieve generated by the pullbacks with the pullback of the generated
    sieve, then `covers_comp_iff` (Part 35) gives its arrow-form reading. -/
theorem covers_pullback_generate {C : Type*} [Category C] {X Y Z : C}
    (J : GrothendieckTopology C) (R : Presieve X) (f : Y ⟶ X) (g : Z ⟶ Y)
    [R.HasPullbacks f] :
    J.Covers (Sieve.generate (R.pullbackArrows f)) g ↔
      J.Covers (Sieve.generate R) (g ≫ f) := by
  rw [Sieve.pullbackArrows_comm]
  exact Grothendieck.CoversArrow.covers_comp_iff J (Sieve.generate R) f g

end Grothendieck.PullbackCoversLaws_en
