/-
Grothendieck tribute — Part 63: the equalizer-product sheaf condition.

Alexandre Grothendieck (1928-2014).

Phase 2 extension (#2159, Epic #1646).

Part 20 (`Sheafification.lean`) established the sheafification adjunction and
Part 62 (`PlusConstruction.lean`) its constructive ingredient. This module
formalises the **conceptual core** of the notion of a sheaf on a site: the
**sheaf condition expressed as an equalizer diagram**.

  A presheaf `P : Cᵒᵖ ⥤ Type*` is a sheaf for a Grothendieck topology `J` if,
  for every covering family `{U_i → X}` (viewed as a sieve `S : Sieve X`
  belonging to `J X`), the restriction diagram

    P(X)  →  ∏ᵢ P(U_i)  ⇉  ∏ᵢⱼ P(U_i ×_X U_j)

  is an **equalizer**. The left arrow is the family of restrictions
  `P(X) → P(U_i)`; the two parallel arrows on the right are induced by the
  two projections of the pullback `U_i ×_X U_j`.

Mathlib exposes this reformulation in
`CategoryTheory.Sites.EqualizerSheafCondition` (namespace
`CategoryTheory.Equalizer`), in two forms:

  - `Equalizer.Sieve.equalizer_sheaf_condition`: `P` is a sheaf for the
    sieve `S` iff the fork `w P S` is an equalizer (sieve form).
  - `Equalizer.Presieve.Arrows.sheaf_condition` (Stacks 00VM): the same
    assertion for the family `ofArrows X π`, with a pairwise pullback
    condition (`HasPairwisePullbacks`).

This module records, in the `Grothendieck_en` namespace, derived bridges
from these two forms to the definition `Presieve.IsSheaf J P` (sheaf for
every covering sieve of the topology) and to the pretopology
characterisation `isSheaf_pretopology`. These are not pure re-exports: each
bridge is a `theorem ... := by` that explicitly chains the vendored lemmas
(`equalizer_sheaf_condition`, `sheaf_condition`, `isSheafFor_iff_generate`,
`isSheaf_pretopology`) to produce the desired equivalence.

References:
  - Stacks Project, tag 00VM ("sheaves on sites via equalizers").
  - Stacks Project, tag 00VL (pretopology form).
  - S. Mac Lane, I. Moerdijk, *Sheaves in Geometry and Logic*
    [MM92], Ch. III §4, equation (3) — the canonical equalizer diagram.
  - M. Kashiwara, P. Schapira, *Categories and Sheaves* [KS06] §17.

All `sorry`s eliminated at creation.
-/

import Mathlib.CategoryTheory.Sites.EqualizerSheafCondition
import Mathlib.CategoryTheory.Sites.SheafOfTypes

namespace Grothendieck_en

open CategoryTheory CategoryTheory.Limits Opposite

universe u v

section Bridges

variable {C : Type u} [Category.{v} C]
  (J : GrothendieckTopology C)
  (P : Cᵒᵖ ⥤ Type (max v u))

/-- **Sheaf condition = equalizer diagram (sieve form).**

A presheaf `P` is a sheaf for the topology `J` if and only if, for every
covering sieve `S ∈ J X`, the restriction fork
`forkMap P S ≫ firstMap = forkMap P S ≫ secondMap` (the compatibility
condition) is an equalizer diagram. This is the "equalizer-product"
reformulation of the sheaf-on-a-site definition: the section `P(X)` is
uniquely reconstructed as the limit of the double arrow of restrictions to
the opens of the sieve. Reference: Stacks 00VM, Mac Lane–Moerdijk [MM92]
Ch. III §4 Eq. (3). -/
theorem sheaf_iff_equalizer_sieve :
    Presieve.IsSheaf J P ↔
      ∀ ⦃X : C⦄ (S : Sieve X), S ∈ J X →
        Nonempty (IsLimit (Fork.ofι _ (Equalizer.Sieve.w P S))) := by
  constructor
  · intro h X S hS
    exact (Equalizer.Sieve.equalizer_sheaf_condition P S).mp (h S hS)
  · intro h X S hS
    exact (Equalizer.Sieve.equalizer_sheaf_condition P S).mpr (h S hS)

/-- **Sheaf condition = equalizer diagram (arrows-family form).**

When the category `C` has pullbacks (`HasPullbacks C`), the sheaf condition
for a covering family `π : (i : I) → X i ⟶ B` (carried by a pretopology
`K`) reads: `P` is a sheaf for the sieve generated by `π` iff the fork
`forkMap P X π ≫ firstMap = forkMap P X π ≫ secondMap` is an equalizer. The
hypothesis `HasPullbacks C` supplies the `HasPairwisePullbacks` instance
required by the arrows form of the vendored lemma. Reference: Stacks 00VM.
-/
theorem sheaf_iff_equalizer_arrows [HasPullbacks C]
    {B : C} {I : Type (max v u)} (X : I → C)
    (π : (i : I) → X i ⟶ B) :
    Presieve.IsSheafFor P (Presieve.ofArrows X π) ↔
      Nonempty (IsLimit (Fork.ofι _ (Equalizer.Presieve.Arrows.w P X π))) := by
  exact Equalizer.Presieve.Arrows.sheaf_condition P X π

/-- **Pretopology characterisation — bridge to `isSheaf_pretopology`.**

Under `HasPullbacks C`, being a sheaf for the topology
`K.toGrothendieck` generated by a pretopology `K` is equivalent to
checking the sheaf condition for each covering family of `K`. This bridge
connects `Presieve.IsSheaf` (sieve form of the topology) to the
pretopological formulation `isSheaf_pretopology`, which is the practical
operational lever: one checks the condition on a basis of covers rather
than on all sieves. Reference: Stacks 00VL, SGA 4 II.1. -/
theorem sheaf_pretopology_iff [HasPullbacks C] (K : Pretopology C) :
    Presieve.IsSheaf K.toGrothendieck P ↔
      ∀ ⦃X : C⦄ (R : Presieve X), R ∈ K X → Presieve.IsSheafFor P R := by
  exact Presieve.isSheaf_pretopology K

end Bridges

end Grothendieck_en
