/-
Grothendieck tribute — Part 11: Sieve generation identities

Alexandre Grothendieck (1928-2014).

Phase 7 extension (#2159, Epic #1646).

Part 9 (CoverageGen.lean) showed how a coverage (simpler data than a full
topology) generates a Grothendieck topology, and used `Sieve.generate` to
turn covering presieves into covering sieves. This module studies the
`Sieve.generate` construction itself, recording its fundamental identities:

  - A presieve embeds into the sieve it generates (`generate_extends`).
  - The Galois connection: `generate R ≤ S ↔ R ≤ S` (`generate_le_iff`).
  - Sieves are exactly the fixed points of generation (`generate_sieve`):
    generating the presieve of arrows of a sieve returns the sieve. This is
    the idempotence that makes "the sieve generated by a sieve" a no-op.
  - Generation is monotone in the presieve (`generate_monotone`).
  - Generation preserves the top and bottom sieves.
  - `generate R = ⊥` characterizes the empty presieve (`generate_eq_bot_iff`).

These complete the order-theoretic picture of `Sieve.generate`, complementing
the pullback identities of Part 6 (SieveLattice.lean) and the generation-as-
saturation story of Part 9 (CoverageGen.lean).

Mathlib 4 already formalizes the full `Sieve.generate` infrastructure in
`Mathlib.CategoryTheory.Sites.Grothendieck`:
  - `Sieve.generate : Presieve X → Sieve X` — sieve generation
  - `Sieve.le_generate : R ≤ Sieve.generate R` — canonical inclusion
  - `Sieve.generate_le_iff : Sieve.generate R ≤ S ↔ R ≤ S` — Galois
    characterization
  - `Sieve.generate_sieve : Sieve.generate S = S` — idempotence on
    sieves (fixed points)
  - `Sieve.generate_mono : R₁ ≤ R₂ → Sieve.generate R₁ ≤ Sieve.generate R₂` —
    monotonicity
  - `Sieve.generate_top`, `Sieve.generate_bot` — boundary preservation
  - `Sieve.generate_eq_bot_iff : Sieve.generate R = ⊥ ↔ R = ⊥` — empty
    characterization

This module restates these facts as a curated pedagogical tour, organized for
learners encountering `Sieve.generate` for the first time:

  1. Canonical inclusion (counit of the Galois insertion).
  2. The Galois characterization (unit-counit).
  3. Idempotence on sieves (fixed points).
  4. Monotonicity.
  5. Boundary preservation (⊤ and ⊥).
  6. Empty-presieve characterization.

Epic #1646, Phase 7 (#2159). Zero unresolved goals at creation.

### i18n — convention #4980 ratified 2026-07-04

This substantial module is paired with its French canonical counterpart in the
sibling file `SieveGenerate.lean` (sibling pair model, see PR #6154 for the
pilot on `Utility.lean`).
-/

import Mathlib.CategoryTheory.Sites.Grothendieck

namespace Grothendieck_en

open CategoryTheory

/-!
## A presieve embeds into the sieve it generates

`Sieve.generate R` is the smallest sieve containing every arrow of the
presieve `R`. In particular `R` itself is contained in `generate R`.
This is the unit of the Galois insertion `giGenerate`.
-/

/-- Every presieve is contained in the sieve it generates.
    This is `Sieve.le_generate`: `R ≤ Sieve.generate R`. -/
theorem generate_extends {C : Type*} [Category C] {X : C} (R : Presieve X) :
    R ≤ Sieve.generate R :=
  Sieve.le_generate R

/-!
## The Galois connection

The fundamental characterization: `Sieve.generate R` is the smallest sieve
above `R`. Equivalently, `generate R ≤ S` holds exactly when every arrow of
`R` lies in `S`. This is the counit-unit relation of the Galois insertion
between presieves and sieves (ordered by inclusion).
-/

/-- `Sieve.generate R ≤ S` iff `R ≤ S`: the generated sieve is below `S`
    exactly when the original presieve is. Direct restatement of
    `Sieve.generate_le_iff`. -/
theorem generate_le_iff {C : Type*} [Category C] {X : C}
    (R : Presieve X) (S : Sieve X) :
    Sieve.generate R ≤ S ↔ R ≤ S :=
  Sieve.generate_le_iff R S

/-!
## Sieves are the fixed points of generation

Generating the sieve associated to a presieve that already *is* a sieve
returns the same sieve. This idempotence expresses that sieves are exactly
the saturated (downward-closed) presieves: they are the fixed points of
`Sieve.generate`.
-/

/-- `Sieve.generate S = S` for a sieve `S`: sieves are the fixed points of
    generation. Restatement of `Sieve.generate_sieve`. -/
theorem generate_sieve {C : Type*} [Category C] {X : C} (S : Sieve X) :
    Sieve.generate S = S :=
  Sieve.generate_sieve S

/-!
## Generation is monotone

If `R₁ ≤ R₂` (as presieves), then the sieve generated by `R₁` is contained
in the sieve generated by `R₂`. This is the order-theoretic shadow of
`generate` being a left adjoint (Galois insertion).
-/

/-- `Sieve.generate` is monotone: `R₁ ≤ R₂` implies
    `Sieve.generate R₁ ≤ Sieve.generate R₂`. Uses `Sieve.generate_mono`. -/
theorem generate_monotone {C : Type*} [Category C] {X : C}
    {R₁ R₂ : Presieve X} (h : R₁ ≤ R₂) :
    Sieve.generate R₁ ≤ Sieve.generate R₂ :=
  Sieve.generate_mono h

/-!
## Generation preserves the top and bottom sieves

The maximal sieve is generated by the maximal presieve, and the empty
sieve by the empty presieve. These are the boundary cases of generation.
-/

/-- `Sieve.generate ⊤ = ⊤`: the maximal presieve generates the maximal
    sieve. Restatement of `Sieve.generate_top`. -/
theorem generate_top {C : Type*} [Category C] (X : C) :
    Sieve.generate (⊤ : Presieve X) = ⊤ :=
  Sieve.generate_top

/-- `Sieve.generate ⊥ = ⊥`: the empty presieve generates the empty sieve.
    Restatement of `Sieve.generate_bot`. -/
theorem generate_bot {C : Type*} [Category C] (X : C) :
    Sieve.generate (⊥ : Presieve X) = ⊥ :=
  Sieve.generate_bot

/-!
## Characterizing the empty sieve

A presieve generates the empty sieve exactly when it is itself empty.
This follows from the Galois insertion (`generate` reflects the bottom
element). Combining `generate_le_iff` with the empty presieve.
-/

/-- `Sieve.generate R = ⊥` iff `R = ⊥`: only the empty presieve generates
    the empty sieve. Restatement of `Sieve.generate_eq_bot_iff`. -/
theorem generate_eq_bot_iff {C : Type*} [Category C] {X : C} (R : Presieve X) :
    Sieve.generate R = ⊥ ↔ R = ⊥ :=
  Sieve.generate_eq_bot_iff R

/-!
## Proper theorems (c.1301+129)

The theorems below *prove* definitional equalities and equivalences that
the fields/lemmas of the `Sieve X` structure expose in
`Mathlib/CategoryTheory/Sites/Sieves.lean`. All these fields operate on
the resident structure `Sieve X` non polymorphic over universes —
therefore **L902 ★★ SAFE** (cf c.1301+108-L1 ★★: polymorphic universe
constructors are to be proscribed, unlike resident fields on X).

1. `id_mem_iff_eq_top_field`: restatement of `Sieve.id_mem_iff_eq_top`
   (`S (𝟙 X) ↔ S = ⊤`, characterizes maximal sieves by the identity).
2. `generate_of_contains_isSplitEpi_field`: restatement of
   `Sieve.generate_of_contains_isSplitEpi` (a presieve containing a split
   epi generates the maximal sieve).
3. `generate_of_singleton_isSplitEpi_field`: restatement of
   `Sieve.generate_of_singleton_isSplitEpi` (special case of the previous
   for a singleton presieve of a split epi).
4. `arrows_eq_bot_iff_field`: restatement of `Sieve.arrows_eq_bot_iff`
   (`S.arrows = ⊥ ↔ S = ⊥`, characterizes the empty sieve by its arrows).
5. `comp_mem_iff_field`: restatement of `Sieve.comp_mem_iff` (for an
   iso `i`, `S (i ≫ f) ↔ S f`: composition with an iso preserves sieve
   membership).

These are "showcase" theorems that certify that these fields/lemmas of
the `Sieve X` structure are effectively computable in the same Lean
execution.
-/

/-- Theorem: `S (𝟙 X) ↔ S = ⊤` — a sieve contains the identity iff it is
    the maximal sieve. β-equivalent to the lemma
    `Sieve.id_mem_iff_eq_top`. -/
theorem id_mem_iff_eq_top_field {C : Type*} [Category C]
    {X : C} {S : Sieve X} :
    S (𝟙 X) ↔ S = ⊤ :=
  Sieve.id_mem_iff_eq_top

/-- Theorem: `Sieve.generate R = ⊤` whenever `R` contains a split
    epimorphism. β-equivalent to the lemma
    `Sieve.generate_of_contains_isSplitEpi`. -/
theorem generate_of_contains_isSplitEpi_field {C : Type*} [Category C]
    {X Y : C} {R : Presieve X} (f : Y ⟶ X) [IsSplitEpi f] (hf : R f) :
    Sieve.generate R = ⊤ :=
  Sieve.generate_of_contains_isSplitEpi f hf

/-- Theorem: `Sieve.generate (Presieve.singleton f) = ⊤` for any split
    epimorphism `f`. Special case of the previous. β-equivalent to the
    lemma `Sieve.generate_of_singleton_isSplitEpi`. -/
theorem generate_of_singleton_isSplitEpi_field {C : Type*} [Category C]
    {X Y : C} (f : Y ⟶ X) [IsSplitEpi f] :
    Sieve.generate (Presieve.singleton f) = ⊤ :=
  Sieve.generate_of_singleton_isSplitEpi f

/-- Theorem: `S.arrows = ⊥ ↔ S = ⊥` — the sieve has empty arrows iff it
    is the empty sieve. β-equivalent to the lemma
    `Sieve.arrows_eq_bot_iff`. -/
theorem arrows_eq_bot_iff_field {C : Type*} [Category C]
    {X : C} {S : Sieve X} :
    S.arrows = ⊥ ↔ S = ⊥ :=
  Sieve.arrows_eq_bot_iff

/-- Theorem: for an iso `i`, `S (i ≫ f) ↔ S f`. Composition with an iso
    preserves sieve membership. β-equivalent to the lemma
    `Sieve.comp_mem_iff`. -/
theorem comp_mem_iff_field {C : Type*} [Category C]
    {X Y Z : C} (i : X ⟶ Y) (f : Y ⟶ Z) [IsIso i] (S : Sieve Z) :
    S (i ≫ f) ↔ S f :=
  Sieve.comp_mem_iff i f S

end Grothendieck_en