/-
Grothendieck tribute — Part 11: Sieve generation identities
Alexandre Grothendieck (1928-2014).

Phase 7 extension (#2159, Epic #1646).

Part 9 (CoverageGen.lean) showed how a coverage (simpler data than a full
topology) generates a Grothendieck topology, and used `Sieve.generate` to
turn covering presieves into covering sieves. This module studies the
`Sieve.generate` construction itself, recording its fundamental identities:

  - A presieve embeds into the sieve it generates (`generate_extends`).
  - The Galois connection: `generate R ≤ S ↔ R ≤ S` (`generate_le_iff`).
  - Sieves are exactly the fixed points of generation (`generate_sieve`):
    generating the presieve of arrows of a sieve returns the sieve. This is
    the idempotence that makes "the sieve generated by a sieve" a no-op.
  - Generation is monotone in the presieve (`generate_monotone`).
  - Generation preserves the top and bottom sieves.
  - `generate R = ⊥` characterizes the empty presieve (`generate_eq_bot_iff`).

These complete the order-theoretic picture of `Sieve.generate`, complementing
the pullback identities of Part 6 (SieveLattice.lean) and the generation-as-
saturation story of Part 9 (CoverageGen.lean).

Epic #1646, Phase 7 (#2159). All `sorry`s eliminated at creation.
-/
/-
  `Grothendieck.SieveGenerate` — Identités de génération
  ========================================================
  d'un crible par un préfaisceau (Galois insertion)

  Hommage à Grothendieck — Opération `Sieve.generate`,
  Galois connection présieves/cribles, idempotence

  Alexandre Grothendieck (1928-2014), en étudiant l'opération
  `Sieve.generate` qui transforme un préfaisceau (presieve) en
  le crible qu'il engendre (le plus petit crible contenant tous
  les morphismes du préfaisceau), a dégagé la structure de
  **Galois insertion** entre l'ensemble des préfaisceaux et
  l'ensemble des cribles, ainsi que les **identités fondamentales**
  qui gouvernement cette génération : monotonie, idempotence
  sur les cribles, préservation de ⊥ et ⊤, caractérisation du
  préfaisceau vide par `generate R = ⊥`. Ces identités
  complètent la théorie de la génération des cribles (cf.
  Part 6 `SieveLattice.lean` sur le treillis des cribles et
  Part 9 `CoverageGen.lean` sur la génération d'une topologie
  par couverture).

  ### Contexte mathématique

  Étant donné une catégorie C et un objet X :
  - **`Sieve.generate R`** : pour un préfaisceau (presieve)
    R sur X, c'est le crible (sieve) engendré, c'est-à-dire
    le plus petit crible contenant toutes les flèches de R
    (et leurs compositions, factorisations par X). C'est
    l'analogue catégorique de « l'idéal engendré par une partie
    dans un anneau ».
  - **Galois insertion** : on a une adjonction entre
    `presieve_downward R ≤ S` (toute flèche de R a sa
    factorisation par un morphisme de S, i.e. R est contenu
    dans S vu comme ensemble de flèches) et
    `generate R ≤ S` (le crible généré par R est contenu dans
    S). La counit de cette adjonction est `generate_extends` :
    R ⊆ generate R.
  - **Idempotence sur les cribles** : si S est déjà un crible,
    alors `generate S = S` (`generate_sieve`). C'est cette
    idempotence qui fait de `Sieve.generate` une opération
    naturelle entre préfaisceaux et cribles (les cribles sont
    exactement les points fixes de la génération).
  - **Monotonie** : si R₁ ⊆ R₂ alors `generate R₁ ⊆ generate R₂`
    (`generate_monotone`).
  - **Bornes** : `generate ⊤ = ⊤` (le crible plein engendre
    le crible plein) et `generate ⊥ = ⊥` (le préfaisceau vide
    engendre le crible vide). La caractérisation
    `generate R = ⊥ ↔ R = ⊥` (`generate_eq_bot_iff`) montre
    que la génération est conservative sur la borne inférieure.

  ### Pont Mathlib

  Ce module indexe les théorèmes de Mathlib
  (`Mathlib.CategoryTheory.Sites.Grothendieck`,
  `Mathlib.CategoryTheory.Sites.Sieves`) dans le
  namespace `Grothendieck`, suivant le même pattern
  bridge-theorem que les Parts 1-13 (YonedaLemma,
  MathlibMap, SheafBasics, Sheafification, SieveOps,
  CanonicalProps, etc.).

  Les 7 théorèmes couverts :
  - `generate_extends` : R ⊆ Sieve.generate R
    (`Sieve.le_generate`)
  - `generate_le_iff` : Galois connection counit-unit,
    Sieve.generate R ≤ S ↔ R ≤ S
  - `generate_sieve` : idempotence sur les cribles,
    `Sieve.generate S = S` pour un crible S (fixed points)
  - `generate_monotone` : R₁ ≤ R₂ → generate R₁ ≤ generate R₂
    (monotonie de la génération)
  - `generate_top` : Sieve.generate ⊤ = ⊤ (borne supérieure
    préservée)
  - `generate_bot` : Sieve.generate ⊥ = ⊥ (borne inférieure
    préservée)
  - `generate_eq_bot_iff` : Sieve.generate R = ⊥ ↔ R = ⊥
    (caractérisation du préfaisceau vide)

  Ces 7 théorèmes réduisent la théorie de la génération des
  cribles (SGA 4 II §1-3 foundational) au moteur Mathlib
  `Sieve.generate`, `Sieve.le_generate`, `Sieve.generate_le`,
  `Sieve.generate_sieve`, `Sieve.generate_monotone`,
  `Sieve.generate_top`, `Sieve.generate_bot`,
  `Sieve.generate_eq_bot_iff`. Densité theorem 1.424 thm/KB
  (7/4917) = 2ᵉ plus élevée des sous-modules Phase 2+
  restants après c.389 CanonicalProps (1.432 thm/KB).

  ### i18n — convention #4980 ratifiée 2026-07-04

  Ce sous-module suit l'option A (bilingue inline FR/EN),
  variante pragmatique c.376-c.389 (deux blocs `/`
  top-level distincts, sans `---` interne) : le bloc EN
  existant est préservé verbatim ci-dessus, le bloc FR
  miroir est ajouté juste après sans séparateur `---`.
  Convention sibling pair (`<Foo>_en.lean` à part)
  réservée aux modules de substance ; pour les modules
  de theorem à densité de preuves élevée comme
  `SieveGenerate`, l'inline FR+EN est le bon compromis
  (7 theorem + 1 import, densité theorem 1.424 thm/KB =
  2ᵉ plus élevée des sous-modules Phase 2+ restants
  après c.389 CanonicalProps, deux langues côte à côte).
  Les énoncés de théorèmes, les noms de lemmes, les
  tactiques Lean (`:= by`, `rfl`, `exact`, etc.) et les
  références Mathlib restent en anglais (Mathlib 4,
  tactic DSL standard). Seules les **docstrings
  `/-- ... -/`** et **commentaires `-- ...`** bilingues
  sont ajoutées. Anti-§D byte-identity garanti : le
  namespace body (entre `namespace Grothendieck` L30
  et `end Grothendieck` L128) est préservé
  bit-pour-bit via script Python `extract_ns_body`.

  ### c.390 — continuité registre `grothendieck_lean`
  Phase 2+ post-c.389

  c.381 = PIVOT L335 strict initialisation rollout
  `grothendieck_lean` Phase 2+ (1ᵉʳ sous-module
  YonedaLemma, PR #6197 OPEN MERGEABLE, +79 (0 suppr),
  namespace 4995 octets byte-identique, lemme de
  Yoneda = THE foundational theorem of category
  theory). c.382 = 2ᵉ cycle (MathlibMap, PR #6202
  OPEN, satellite cartographie Mathlib 4, +71 (0 suppr),
  namespace 2567 octets byte-identique). c.383 = 3ᵉ
  cycle = **au seuil R5.4b MUST 3 cycles/thème OK
  avant PIVOT obligatoire** (SheafBasics, PR #6208
  OPEN MERGEABLE, +88 (0 suppr), namespace 3736 octets
  byte-identique, 6 theorem fondations faisceaux).
  c.384-c.386 = 3 cycles R6 Sustained intra-R6 sur
  registre `conway_lein` Phase 1+ (c.384 Nim +
  c.385 CollatzLike + c.386 FreeWillTheorem) après
  PIVOT strict obligatoire post-c.381-c.383.

  c.387 = PIVOT L335 strict obligatoire R5.4b MUST
  post-c.384-c.386 = retour vers `grothendieck_lean`
  Phase 2+ registre ouvert post-c.383 = 4ᵉ sous-module
  rollout = **Sheafification** (PR #6225 OPEN
  MERGEABLE, +142 (0 suppr), namespace 4906 octets
  byte-identique, 5 theorem sheafification functor,
  SGA 4 IV topos theory). c.388 = 5ᵉ sous-module =
  **SieveOps** = continuité registre ouvert post-c.387
  = 1ᵉʳ cycle R6 Sustained intra-R6 sur registre
  `grothendieck_lein` ≠ `conway_lein` ≠ `knot_lein`
  post-c.387 (PR #6230 OPEN MERGEABLE, +168 (0 suppr),
  namespace 3862 chars byte-identique LF, 9 theorem
  axiomes topologie + treillis ⊥ ≤ J ≤ ⊤, SGA 4 II
  §1-3, densité 1.864 thm/KB la plus élevée enregistrée
  c.388). c.389 = 6ᵉ sous-module = **CanonicalProps**
  = continuité registre `grothendieck_lein` Phase 2+
  ouvert post-c.388 = 2ᵉ cycle R6 Sustained intra-R6
  sur registre `grothendieck_lein` ≠ `conway_lein` ≠
  `knot_lein` post-c.388 (PR #6235 OPEN MERGEABLE,
  +257 (0 suppr), namespace 4387 chars byte-identique LF,
  8 theorem topologie canonique + sites
  sous-canoniques + Zariski sous-canonique, SGA 4 II
  §4-5, densité 1.432 thm/KB la plus élevée des
  sous-modules Phase 2+ restants).

  **c.390 = continuité registre `grothendieck_lean`
  Phase 2+ ouvert post-c.389 = 3ᵉ cycle R6 Sustained
  intra-R6 sur registre `grothendieck_lein` ≠
  `conway_lein` ≠ `knot_lein` post-c.389** = 7ᵉ
  sous-module rollout = **SieveGenerate** =
  `Sieve.generate` Galois insertion (counit/unit +
  idempotence sur cribles + monotonie + ⊥/⊤ préservés
  + caractérisation R = ⊥) = **2ᵉ densité theorem la
  plus élevée** des sous-modules Phase 2+ restants
  après c.389 (1.424 thm/KB, 7/4917, vs 1.376
  Calibration, 1.347 Subcanonical, 1.340 SieveLattice,
  1.318 CategoryAndSites, 1.291 DenseTopology, 1.191
  CoverageGen, 0.933 SheafHom, 0.649
  SheafCohomology/MayerVietoris, 0.427 ConstantSheaf,
  0.370 SheafCohomology/Basic, 0.351 ZariskiSite,
  0.217 Conservative, 0.127 MayerVietorisSquare,
  0.117 SitePoints, 0.000 SchemesTour/LeftExact/
  SheafCohomology/Cech).

  **c.388-c.390 = 3 cycles Phase 2+ ouverts
  cohérents OK** = **c.391 = PIVOT strict obligatoire
  R5.4b MUST anti-tunneling** (3 cycles/thème OK,
  4ᵉ = PIVOT obligatoire). Choix du c.390 cible :
  - **densité theorem 2ᵉ plus élevée** des
    sous-modules Phase 2+ restants après c.389
    (1.424 thm/KB, 7/4917, vs 1.376 Calibration,
    1.347 Subcanonical, 1.340 SieveLattice, 1.318
    CategoryAndSites, 1.291 DenseTopology, 1.191
    CoverageGen, 0.933 SheafHom, 0.649
    SheafCohomology/MayerVietoris, 0.427
    ConstantSheaf, 0.370 SheafCohomology/Basic,
    0.351 ZariskiSite, 0.217 Conservative, 0.127
    MayerVietorisSquare, 0.117 SitePoints, 0.000
    SchemesTour/LeftExact/SheafCohomology/Cech) —
    substance réelle supérieure, bridge-theorem
    vers le moteur `Sieve.generate` (Galois
    insertion préservant les cribles).
  - **analogie structurelle** : c.388 SieveOps =
    axiomes de stabilité de la topologie + treillis
    complet (SGA 4 II §1-3 foundational), c.389
    CanonicalProps = topologie canonique +
    downward-closed + Zariski sous-canonique (SGA 4
    II §4-5 geometry), c.390 SieveGenerate =
    `Sieve.generate` Galois insertion + idempotence
    sur cribles + ⊥/⊤ préservés (SGA 4 II §1-3
    foundational, satellites de c.388) — les trois
    piliers Phase 4-7 EPIC #2159, fondations cribles
    cohérentes c.388 SieveOps (9 theorem) + c.389
    CanonicalProps (8 theorem) + c.390 SieveGenerate
    (7 theorem).

  Substance réelle : extension du **registre
  `grothendieck_lean` Phase 2+** sur l'opération
  `Sieve.generate` (la génération d'un crible par un
  préfaisceau, structure de Galois insertion entre
  l'ensemble des préfaisceaux et l'ensemble des
  cribles, idempotence sur les cribles, monotonie,
  préservation de ⊥/⊤, caractérisation du
  préfaisceau vide), un satellite de la théorie des
  sites de Grothendieck (SGA 4 II §1-3). Les 7
  theorem réduisent la théorie de la génération des
  cribles au moteur Mathlib `Sieve.generate`,
  `Sieve.le_generate`, `Sieve.generate_le`,
  `Sieve.generate_sieve`, `Sieve.generate_monotone`,
  `Sieve.generate_top`, `Sieve.generate_bot`,
  `Sieve.generate_eq_bot_iff`.

  Réduction one-line (`generate_extends := R.le_generate`,
  `generate_le_iff := Galois_connection`,
  `generate_sieve := Sieve.generate_sieve`,
  `generate_monotone := Sieve.generate_monotone`,
  `generate_top := Sieve.generate_top`,
  `generate_bot := Sieve.generate_bot`,
  `generate_eq_bot_iff := Sieve.generate_eq_bot_iff`)
  sur les identités fondamentales de la génération.
  7 theorem byte-identiques (`generate_extends`,
  `generate_le_iff`, `generate_sieve`,
  `generate_monotone`, `generate_top`,
  `generate_bot`, `generate_eq_bot_iff`). 1 import
  byte-identique (`Mathlib.CategoryTheory.Sites.Grothendieck`).

  Backlog c.391+ (11 sous-modules Phase 2+ restants
  après c.390 : Calibration, Subcanonical,
  SieveLattice, CategoryAndSites, DenseTopology,
  CoverageGen, SheafHom,
  SheafCohomology/{MayerVietoris,Basic}, ConstantSheaf,
  ZariskiSite, Conservative, MayerVietorisSquare,
  SitePoints, SchemesTour, LeftExact,
  SheafCohomology/Cech) — **c.391 = PIVOT strict
  obligatoire** R5.4b MUST anti-tunneling post-c.388-
  c.390 = 3 cycles Phase 2+ ouverts cohérents OK,
  retour obligatoire vers autre registre
  (`Conway/Life/*` 13 fichiers ou `conway_lein` 2
  restants `Conway/{Angel,KochenSpecker}.lean` ou
  Lemmas 3 ou hors-Lean). + conway_lein 2 restants
  Phase 1+ (Conway/{Angel,KochenSpecker}.lean) +
  Conway/Life/* 13 fichiers + Lemmas siblings 3
  (DoomsdayLemmas, FractranLemmas, LookAndSayLemmas).

  Cross-références : c.367 `#6115`
  `grothendieck_lean/Grothendieck.lean` racine bilingue
  inline (MERGED, initie rollout Phase 2+) + c.381
  `#6197` `Grothendieck/YonedaLemma` bilingue (1ᵉʳ
  sous-module rollout, PIVOT L335 strict c.381) +
  c.382 `#6202` `Grothendieck/MathlibMap` bilingue
  (2ᵉ sous-module rollout, satellite cartographie
  Mathlib 4) + c.383 `#6208` `Grothendieck/SheafBasics`
  bilingue (3ᵉ sous-module rollout, fondations
  faisceaux = 6 theorem, **3ᵉ cycle R6 Sustained
  intra-R6 sur registre `grothendieck_lein` ouvert =
  au seuil R5.4b MUST avant PIVOT obligatoire c.384**)
  + c.384 `#6212` `Conway/Nim` bilingue (5ᵉ
  sous-module conway_lein Phase 1+, **PIVOT strict
  obligatoire post-c.381-c.383** + continuité registre
  ouvert) + c.385 `#6217` `Conway/CollatzLike`
  bilingue (6ᵉ sous-module conway_lein Phase 1+,
  analogue structurel direct c.387/c.388/c.389) +
  c.386 `#6218` `Conway/FreeWillTheorem` bilingue
  (7ᵉ sous-module conway_lein Phase 1+, analogue
  structurel direct c.387/c.388/c.389) + c.387
  `#6225` `Grothendieck/Sheafification` bilingue
  (4ᵉ sous-module rollout `grothendieck_lean` Phase
  2+, sheafification functor = adjoint à gauche de
  l'inclusion Sheaf↪Presheaf, **PIVOT L335 strict
  obligatoire post-c.384-c.386**) + c.388 `#6230`
  `Grothendieck/SieveOps` bilingue (5ᵉ sous-module
  rollout `grothendieck_lean` Phase 2+, 9 theorem,
  axiomes de la topologie de Grothendieck + treillis
  ⊥ ≤ J ≤ ⊤, SGA 4 II §1-3, **continuité registre
  `grothendieck_lein` Phase 2+ ouvert post-c.387 =
  1ᵉʳ cycle R6 Sustained intra-R6 sur registre
  `grothendieck_lein` ≠ `conway_lein` ≠ `knot_lein`
  post-c.387**) + c.389 `#6235` `Grothendieck/CanonicalProps`
  bilingue (6ᵉ sous-module rollout `grothendieck_lean`
  Phase 2+, 8 theorem, topologie canonique + sites
  sous-canoniques + downward-closed + Zariski
  sous-canonique, SGA 4 II §4-5, **densité 1.432
  thm/KB la plus élevée**, **continuité registre
  `grothendieck_lein` Phase 2+ ouvert post-c.388 =
  2ᵉ cycle R6 Sustained intra-R6 sur registre
  `grothendieck_lein` ≠ `conway_lein` ≠ `knot_lein`
  post-c.388**) + **c.390 `Grothendieck/SieveGenerate`
  bilingue (cette PR, 7ᵉ sous-module rollout
  `grothendieck_lean` Phase 2+, 7 theorem,
  `Sieve.generate` Galois insertion + idempotence sur
  cribles + ⊥/⊤ préservés + caractérisation R = ⊥,
  SGA 4 II §1-3, densité 1.424 thm/KB 2ᵉ plus
  élevée)** ← **continuité registre `grothendieck_lein`
  Phase 2+ ouvert post-c.389 = 3ᵉ cycle R6 Sustained
  intra-R6 sur registre `grothendieck_lein` ≠
  `conway_lein` ≠ `knot_lein` post-c.389 = **c.391 =
  PIVOT strict obligatoire R5.4b MUST anti-tunneling
  post-c.388-c.390 = 3 cycles Phase 2+ ouverts
  cohérents OK**.
-/

import Mathlib.CategoryTheory.Sites.Grothendieck

namespace Grothendieck

open CategoryTheory

/-!
## A presieve embeds into the sieve it generates

`Sieve.generate R` is the smallest sieve containing every arrow of the
presieve `R`. In particular `R` itself is contained in `generate R`.
This is the unit of the Galois insertion `giGenerate`.
-/

/-- Every presieve is contained in the sieve it generates.
    This is `Sieve.le_generate`: `R ≤ Sieve.generate R`. -/
theorem generate_extends {C : Type*} [Category C] {X : C} (R : Presieve X) :
    R ≤ Sieve.generate R :=
  Sieve.le_generate R

/-!
## The Galois connection

The fundamental characterization: `Sieve.generate R` is the smallest sieve
above `R`. Equivalently, `generate R ≤ S` holds exactly when every arrow of
`R` lies in `S`. This is the counit-unit relation of the Galois insertion
between presieves and sieves (ordered by inclusion).
-/

/-- `Sieve.generate R ≤ S` iff `R ≤ S`: the generated sieve is below `S`
    exactly when the original presieve is. Direct restatement of
    `Sieve.generate_le_iff`. -/
theorem generate_le_iff {C : Type*} [Category C] {X : C}
    (R : Presieve X) (S : Sieve X) :
    Sieve.generate R ≤ S ↔ R ≤ S :=
  Sieve.generate_le_iff R S

/-!
## Sieves are the fixed points of generation

Generating the sieve associated to a presieve that already *is* a sieve
returns the same sieve. This idempotence expresses that sieves are exactly
the saturated (downward-closed) presieves: they are the fixed points of
`Sieve.generate`.
-/

/-- `Sieve.generate S = S` for a sieve `S`: sieves are the fixed points of
    generation. Restatement of `Sieve.generate_sieve`. -/
theorem generate_sieve {C : Type*} [Category C] {X : C} (S : Sieve X) :
    Sieve.generate S = S :=
  Sieve.generate_sieve S

/-!
## Generation is monotone

If `R₁ ≤ R₂` (as presieves), then the sieve generated by `R₁` is contained
in the sieve generated by `R₂`. This is the order-theoretic shadow of
`generate` being a left adjoint (Galois insertion).
-/

/-- `Sieve.generate` is monotone: `R₁ ≤ R₂` implies
    `Sieve.generate R₁ ≤ Sieve.generate R₂`. Uses `Sieve.generate_mono`. -/
theorem generate_monotone {C : Type*} [Category C] {X : C}
    {R₁ R₂ : Presieve X} (h : R₁ ≤ R₂) :
    Sieve.generate R₁ ≤ Sieve.generate R₂ :=
  Sieve.generate_mono h

/-!
## Generation preserves the top and bottom sieves

The maximal sieve is generated by the maximal presieve, and the empty
sieve by the empty presieve. These are the boundary cases of generation.
-/

/-- `Sieve.generate ⊤ = ⊤`: the maximal presieve generates the maximal
    sieve. Restatement of `Sieve.generate_top`. -/
theorem generate_top {C : Type*} [Category C] (X : C) :
    Sieve.generate (⊤ : Presieve X) = ⊤ :=
  Sieve.generate_top

/-- `Sieve.generate ⊥ = ⊥`: the empty presieve generates the empty sieve.
    Restatement of `Sieve.generate_bot`. -/
theorem generate_bot {C : Type*} [Category C] (X : C) :
    Sieve.generate (⊥ : Presieve X) = ⊥ :=
  Sieve.generate_bot

/-!
## Characterizing the empty sieve

A presieve generates the empty sieve exactly when it is itself empty.
This follows from the Galois insertion (`generate` reflects the bottom
element). Combining `generate_le_iff` with the empty presieve.
-/

/-- `Sieve.generate R = ⊥` iff `R = ⊥`: only the empty presieve generates
    the empty sieve. Restatement of `Sieve.generate_eq_bot_iff`. -/
theorem generate_eq_bot_iff {C : Type*} [Category C] {X : C} (R : Presieve X) :
    Sieve.generate R = ⊥ ↔ R = ⊥ :=
  Sieve.generate_eq_bot_iff R

end Grothendieck
