/-
Grothendieck tribute — Part 68: the Grothendieck topology of a topological
space.

Alexandre Grothendieck (1928-2014).

Extension Phase 2 (#2159, Epic #1646).

The founding case of the whole theory: sheaves on a topological space `T` are
sheaves on the site `Opens T` — the category of open subsets of `T`, equipped
with the topology of open covers. All previous Parts worked over an arbitrary
category `C` or over schemes; this one reconnects the formalization with the
historical point of entry (Mac Lane – Moerdijk, ch. II).

Over the object `X` (an open subset of `T`), a sieve `S` covers when every
point of `X` belongs to the domain of some arrow of `S` — the exact
transcription of "the family of domains covers `X`". Two constructions are
given, and their coincidence is the central result:

  - `opensTopology`: the topology defined by hand (the three Grothendieck
    topology axioms proved one by one on sieves of opens);
  - `opensPretopology`: the pretopology of open covers (presieves whose
    domains cover), with its three stability axioms;
  - `opensPretopology_toGrothendieck`: the topology generated by the
    pretopology is exactly the hand-defined topology;
  - `toPretopology_opensTopology`: conversely, the pretopology of open covers
    is the largest pretopology generating that topology;
  - `coversTop_isOpenCover_iff`: a family of opens `U : ι → Opens T` is
    covering for the site if and only if it is an `IsOpenCover` in the usual
    topological sense — the bridge between the two worlds.

References:
  - S. Mac Lane, I. Moerdijk, *Sheaves in Geometry and Logic* [MM92],
    Ch. II §1 ("Grothendieck topologies").
  - Mathlib, `CategoryTheory.Sites.Spaces` (starting point of the present
    formalization, of which this module is the own equivalent).

i18n convention (EPIC #4980, ratified 2026-07-04): this module is the English
sibling of `Spaces.lean`. Lean declarations, proofs, and names remain
identical; only docstrings and comments differ.

Epic #1646, Phase 2 (#2159). No `sorry` introduced.
-/

import Mathlib.CategoryTheory.Sites.Pretopology
import Mathlib.CategoryTheory.Sites.CoversTop.Basic
import Mathlib.CategoryTheory.Limits.Lattice
import Mathlib.Topology.Sets.OpenCover

namespace Grothendieck_en

open CategoryTheory TopologicalSpace CategoryTheory.Limits

universe u

section Contenu

variable (T : Type u) [TopologicalSpace T]

/-- The Grothendieck topology of a topological space, defined by hand: a sieve
`S` on the open `X` covers when every point of `X` belongs to the domain of
some arrow of `S`. The three axioms (the maximal sieve covers, pullback
stability, transitivity) are proved directly on this description, without
going through a generating pretopology — this is what gives the membership
predicate its good definitional properties. -/
def opensTopology : GrothendieckTopology (Opens T) where
  sieves X := {S | ∀ x ∈ X, ∃ (U : Opens T) (f : U ⟶ X), S f ∧ x ∈ U}
  top_mem' _ _ hx := ⟨_, 𝟙 _, trivial, hx⟩
  pullback_stable' X Y S f hf y hy := by
    rcases hf y (f.le hy) with ⟨U, g, hg, hU⟩
    refine ⟨U ⊓ Y, homOfLE inf_le_right, ?_, hU, hy⟩
    apply S.downward_closed hg (homOfLE inf_le_left)
  transitive' X S hS R hR x hx := by
    rcases hS x hx with ⟨U, f, hf, hU⟩
    rcases hR hf _ hU with ⟨V, g, hg, hV⟩
    exact ⟨_, g ≫ f, hg, hV⟩

/-- Membership characterization: `S` covers the open `X` for the topology
`opensTopology` if and only if every point of `X` belongs to the domain of
some arrow of `S`. -/
theorem mem_opensTopology_iff {X : Opens T} {S : Sieve X} :
    S ∈ opensTopology T X ↔ ∀ x ∈ X, ∃ (U : Opens T) (f : U ⟶ X), S f ∧ x ∈ U :=
  .rfl

/-- The pretopology of open covers: a presieve `R` on the open `X` covers
when every point of `X` belongs to the domain of some arrow of `R`. The
pretopology axioms (isomorphisms cover, pullback stability, transitivity) are
proved by hand: for pullbacks, the witness domain is the intersection
`U ⊓ Y`, the open pullback of `U` along `f : Y ⟶ X`. -/
def opensPretopology : Pretopology (Opens T) where
  coverings X := {R | ∀ x ∈ X, ∃ (U : Opens T) (f : U ⟶ X), R f ∧ x ∈ U}
  has_isos _ _ f _ _ hx := ⟨_, _, Presieve.singleton_self _, (inv f).le hx⟩
  pullbacks X Y f S hS x hx := by
    rcases hS _ (f.le hx) with ⟨U, g, hg, hU⟩
    refine ⟨_, _, Presieve.pullbackArrows.mk _ _ hg, ?_⟩
    have : U ⊓ Y ≤ pullback g f :=
      leOfHom (pullback.lift (homOfLE inf_le_left) (homOfLE inf_le_right) rfl)
    apply this ⟨hU, hx⟩
  transitive X S Ti hS hTi x hx := by
    rcases hS x hx with ⟨U, f, hf, hU⟩
    rcases hTi f hf x hU with ⟨V, g, hg, hV⟩
    exact ⟨_, _, ⟨_, g, f, hf, hg, rfl⟩, hV⟩

/-- Membership characterization: `R` covers the open `X` for the pretopology
`opensPretopology` if and only if every point of `X` belongs to the domain of
some arrow of `R`. -/
theorem mem_opensPretopology_iff {X : Opens T} {R : Presieve X} :
    R ∈ opensPretopology T X ↔ ∀ x ∈ X, ∃ (U : Opens T) (f : U ⟶ X), R f ∧ x ∈ U :=
  .rfl

/-- The pretopology of open covers is the largest pretopology generating the
topology `opensTopology`. The forward direction unfolds the sieve generated
by a covering presieve; the return direction uses that every presieve is
contained in the sieve it generates. -/
@[simp]
theorem toPretopology_opensTopology :
    (opensTopology T).toPretopology = opensPretopology T := by
  apply le_antisymm
  · intro X R hR x hx
    rcases hR x hx with ⟨U, f, ⟨V, g₁, g₂, hg₂, _⟩, hU⟩
    exact ⟨V, g₂, hg₂, g₁.le hU⟩
  · intro X R hR x hx
    rcases hR x hx with ⟨U, f, hf, hU⟩
    exact ⟨U, f, Sieve.le_generate R U _ hf, hU⟩

/-- **Central result**: the Grothendieck topology generated by the pretopology
of open covers is exactly the hand-defined topology `opensTopology`. The site
`(Opens T, opensTopology T)` can therefore be read equally in terms of sieves
or of open covers. -/
@[simp]
theorem opensPretopology_toGrothendieck :
    (opensPretopology T).toGrothendieck = opensTopology T := by
  rw [← toPretopology_opensTopology]
  exact (Pretopology.gi (Opens T)).l_u_eq _

/-- The bridge to usual topology: a family of opens `U : ι → Opens T` covers
the terminal object of the site if and only if it is an open cover in the
sense of `IsOpenCover`. The categorical notion of cover (the domains cover
`⊤`) coincides with the set-theoretic one (the union of the `U i` equals
`univ`). -/
theorem coversTop_isOpenCover_iff {ι : Type*} (U : ι → Opens T) :
    (opensTopology T).CoversTop U ↔ IsOpenCover U := by
  rw [GrothendieckTopology.coversTop_iff_of_isTerminal _ ⊤ isTerminalTop]
  dsimp only [opensTopology]
  simp only [IsOpenCover, eq_top_iff, SetLike.le_def, exists_and_right, Opens.mem_top,
    Opens.mem_iSup, forall_const]
  refine ⟨fun h x ↦ ?_, fun hU x hx ↦ ?_⟩
  · obtain ⟨V, ⟨u, ⟨i, ⟨hi⟩⟩⟩, hx⟩ := h x trivial
    exact ⟨i, leOfHom hi hx⟩
  · obtain ⟨i, hi⟩ := hU (x := x)
    exact ⟨U i, ⟨homOfLE le_top, ⟨i, ⟨𝟙 _⟩⟩⟩, hi⟩

end Contenu

end Grothendieck_en
