/-
Grothendieck tribute — Part 3: The Zariski site
Alexandre Grothendieck (1928-2014).

English mirror of `ZariskiSite.lean` (FR canonical). Convention EPIC #4980
(decision ratified 2026-07-04, cf `code-style.md` §Lean i18n): distinct FR + EN
sibling files — no inline bilingual block in a single file (Option B rejected).
The module docstring and the public example/theorem docstrings below differ from
the FR version; the body signatures, examples, theorem statement and proofs
remain byte-identical between the two files.

The Zariski topology on the category of schemes is the foundational example
of a Grothendieck topology arising from algebraic geometry. A family of
morphisms {U_i → X} is a Zariski cover iff the U_i are open immersions
that jointly cover X.

Mathlib 4 formalizes this as `Scheme.zariskiTopology`, derived from the
pretopology of open immersions. The key bridge theorem is
`zariskiTopology_eq`: the Grothendieck topology generated by the Zariski
pretopology equals the Zariski topology.

Epic #1646. All `sorry`s eliminated at creation.
-/

import Mathlib.AlgebraicGeometry.Sites.BigZariski

universe v u

namespace Grothendieck_en

open AlgebraicGeometry CategoryTheory

/-!
## The Zariski pretopology

A pretopology specifies covering families (collections of morphisms) directly.
The Zariski pretopology covers X by families of open immersions that are jointly
surjective on the underlying topological space.
-/

/-- The Zariski pretopology on the category of schemes. -/
example : Pretopology Scheme :=
  Scheme.zariskiPretopology

/-!
## From pretopology to Grothendieck topology

Every pretopology generates a Grothendieck topology. The Zariski topology
is precisely the Grothendieck topology generated by the Zariski pretopology.
-/

/-- The Zariski topology as a Grothendieck topology. -/
example : GrothendieckTopology Scheme :=
  Scheme.zariskiTopology

/-- The bridge theorem: the Zariski topology equals the Grothendieck topology
    generated by the Zariski pretopology. This is the key link between the
    concrete (pretopology) and abstract (Grothendieck topology) viewpoints. -/
theorem zariski_topology_eq :
    (Scheme.zariskiTopology : GrothendieckTopology Scheme) =
    Scheme.zariskiPretopology.toGrothendieck :=
  Scheme.zariskiTopology_eq

/-!
## The Zariski topology is subcanonical

A Grothendieck topology is *subcanonical* if every representable presheaf
is already a sheaf. The Zariski topology on schemes is subcanonical.

This means: for every scheme X, the presheaf `Hom(-, X)` satisfies the
sheaf condition with respect to Zariski covers. Intuitively, a morphism
into X is determined by its restrictions to an open cover.
-/

/-- The Zariski topology is subcanonical. -/
example : Scheme.zariskiTopology.Subcanonical :=
  inferInstance

/-!
## Continuity of the forgetful functor

The forgetful functor from schemes to topological spaces is continuous
with respect to the Zariski topology and the usual Grothendieck topology
on TopCat. This means: the preimage of a Zariski covering sieve under
forget is a covering sieve in TopCat.
-/

/-- The forgetful functor is continuous w.r.t. Zariski topology. -/
example : Scheme.forgetToTop.IsContinuous
    Scheme.zariskiTopology TopCat.grothendieckTopology :=
  inferInstance

/-! ## 5. Canonical Mathlib bridges (Grothendieck tribute)

Bridges to the 9 canonical constructors in `Mathlib/AlgebraicGeometry/Sites/BigZariski.lean`
extending the namespace `Grothendieck` with the foundational operators of the Zariski site:
(5.1) the pretopology and topology, (5.2) the Subcanonical instance and continuity of the
forgetful functor, (5.3) the affine hypercover, (5.4) the limits preservation and sieve
inclusion lemmas, (5.5) the sheaf condition for sigma covers. -/

/-! ### 5.1 Bridge-def : the Zariski pretopology and topology

The bridge-lemma exposes `zariskiPretopology` (the underlying pretopology) and
`zariskiTopology` (the derived Grothendieck topology) directly under `Grothendieck.Scheme`. -/

/-- Bridge-def : re-export of the Zariski pretopology on the category of schemes. -/
def zariskiPretopology_field : Pretopology Scheme.{u} :=
  Scheme.zariskiPretopology

/-- Bridge-def : re-export of the Zariski topology (the derived Grothendieck topology). -/
abbrev zariskiTopology_field : GrothendieckTopology Scheme.{u} :=
  Scheme.zariskiTopology

/-! ### 5.2 Bridge-instance : Zariski subcanonical and forgetful functor continuous

The Subcanonical instance on the Zariski topology (cf. Subcanonical.lean Part 16) and
the continuity instance of the forgetful functor to TopCat. -/

/-- Bridge-instance : the Zariski topology is subcanonical. -/
instance subcanonical_zariskiTopology_field : Scheme.zariskiTopology.Subcanonical :=
  Scheme.subcanonical_zariskiTopology

/-- Bridge-instance : the forgetful functor to TopCat is continuous w.r.t. Zariski. -/
instance forgetToTop_continuous_zariskiTopology :
    Scheme.forgetToTop.IsContinuous Scheme.zariskiTopology TopCat.grothendieckTopology :=
  inferInstance

/-! ### 5.3 Bridge-def : affine hypercover (1-hypercover)

For any scheme X, the Zariski 1-hypercover whose all components are affine.
The basic tool for Zariski cohomology. -/

/-- Bridge-def : Zariski 1-hypercover whose all components are affine. -/
noncomputable def affineOneHypercover_field (X : Scheme.{u}) :
    Scheme.zariskiTopology.OneHypercover X :=
  Scheme.affineOneHypercover X

/-! ### 5.4 Bridge-lemma : limits preservation and sieve inclusion

For a Zariski-sheaf presheaf, preservation of discrete-shaped limits; for a
locally directed diagram of open immersions, the colimit inclusions form a
Zariski covering. -/

/-- Bridge-lemma : Zariski-sheaves preserve discrete-shaped limits. -/
lemma preservesLimitsOfShape_discrete_of_isSheaf_zariskiTopology_field
    {F : Scheme.{u}ᵒᵖ ⥤ Type v} {ι : Type*} [Small.{u} ι] [Small.{v} ι]
    (hF : Presieve.IsSheaf Scheme.zariskiTopology F) :
    PreservesLimitsOfShape (Discrete ι) F :=
  Scheme.preservesLimitsOfShape_discrete_of_isSheaf_zariskiTopology hF

/-- Bridge-lemma : for a locally directed diagram of open immersions, the
    colimit inclusions form a Zariski covering. -/
lemma ofArrows_ι_mem_zariskiTopology_of_isColimit_field {J : Type*} [Category J]
    (F : J ⥤ Scheme.{u}) [∀ {i j : J} (f : i ⟶ j), IsOpenImmersion (F.map f)]
    [(F.comp Scheme.forget).IsLocallyDirected] [Quiver.IsThin J] [Small.{u} J]
    (c : Cocone F) (hc : IsColimit c) :
    Sieve.ofArrows _ c.ι.app ∈ Scheme.zariskiTopology c.pt :=
  Scheme.ofArrows_ι_mem_zariskiTopology_of_isColimit F c hc

/-! ### 5.5 Bridge-lemma : sheaf condition for sigma covers

For an `S.Cover (precoverage P)` (where P is Zariski-local-at-source), the
sheaf condition for the sigma cover is equivalent to the sheaf condition for
the initial cover. -/

/-- Bridge-lemma : for an S.Cover, IsSheafFor sigma iff IsSheafFor initial. -/
lemma Cover_isSheafFor_sigma_iff_field {P : MorphismProperty Scheme.{u}}
    {F : Scheme.{u}ᵒᵖ ⥤ Type*} [IsZariskiLocalAtSource P]
    (hF : Presieve.IsSheaf Scheme.zariskiTopology F)
    {S : Scheme.{u}} (𝒰 : S.Cover (precoverage P)) [Finite 𝒰.I₀] :
    Presieve.IsSheafFor F (.ofArrows 𝒰.sigma.X 𝒰.sigma.f) ↔
      Presieve.IsSheafFor F (.ofArrows 𝒰.X 𝒰.f) :=
  Scheme.Cover.isSheafFor_sigma_iff hF 𝒰

end Grothendieck_en
