/-
Grothendieck tribute — Part 3: The Zariski site
Alexandre Grothendieck (1928-2014).

The Zariski topology on the category of schemes is the foundational example
of a Grothendieck topology arising from algebraic geometry. A family of
morphisms {U_i → X} is a Zariski cover iff the U_i are open immersions
that jointly cover X.

Mathlib 4 formalizes this as `Scheme.zariskiTopology`, derived from the
pretopology of open immersions. The key bridge theorem is
`zariskiTopology_eq`: the Grothendieck topology generated by the Zariski
pretopology equals the Zariski topology.

Epic #1646. All `sorry`s eliminated at creation.
-/

import Mathlib.AlgebraicGeometry.Sites.BigZariski

namespace Grothendieck

open AlgebraicGeometry CategoryTheory

/-!
## The Zariski pretopology

A pretopology specifies covering families (collections of morphisms) directly.
The Zariski pretopology covers X by families of open immersions that are jointly
surjective on the underlying topological space.
-/

/-- The Zariski pretopology on the category of schemes. -/
example : Pretopology Scheme :=
  Scheme.zariskiPretopology

/-!
## From pretopology to Grothendieck topology

Every pretopology generates a Grothendieck topology. The Zariski topology
is precisely the Grothendieck topology generated by the Zariski pretopology.
-/

/-- The Zariski topology as a Grothendieck topology. -/
example : GrothendieckTopology Scheme :=
  Scheme.zariskiTopology

/-- The bridge theorem: the Zariski topology equals the Grothendieck topology
    generated by the Zariski pretopology. This is the key link between the
    concrete (pretopology) and abstract (Grothendieck topology) viewpoints. -/
theorem zariski_topology_eq :
    (Scheme.zariskiTopology : GrothendieckTopology Scheme) =
    Scheme.zariskiPretopology.toGrothendieck :=
  Scheme.zariskiTopology_eq

/-!
## The Zariski topology is subcanonical

A Grothendieck topology is *subcanonical* if every representable presheaf
is already a sheaf. The Zariski topology on schemes is subcanonical.

This means: for every scheme X, the presheaf `Hom(-, X)` satisfies the
sheaf condition with respect to Zariski covers. Intuitively, a morphism
into X is determined by its restrictions to an open cover.
-/

/-- The Zariski topology is subcanonical. -/
example : Scheme.zariskiTopology.Subcanonical :=
  inferInstance

/-!
## Continuity of the forgetful functor

The forgetful functor from schemes to topological spaces is continuous
with respect to the Zariski topology and the usual Grothendieck topology
on TopCat. This means: the preimage of a Zariski covering sieve under
forget is a covering sieve in TopCat.
-/

/-- The forgetful functor is continuous w.r.t. Zariski topology. -/
example : Scheme.forgetToTop.IsContinuous
    Scheme.zariskiTopology TopCat.grothendieckTopology :=
  inferInstance

end Grothendieck
