import MathUniverse_en

/-!
# Generators — reifying "generators + composition" (Appendix A, eq. A2)

Direct follow-up to `MathUniverse_en` (issue **#16753**). The previous
module left the criterion "a structure may also be given by its
**generators** and **composition rules**" as a **concrete exhibition**: the
seven `nand_*` lemmas did prove that every relation of (A1) is composed
from NAND, but the composition lived in the *terms of the proof*, not in
the language. This module **reifies** it:

1. **`Term ν`** — the syntax: a variable, or the binary generator applied
   to two subterms. The formulas `R(R(X, Y), R(X, X))` of equation (A2)
   become trees that Lean can inspect, compare and evaluate.
2. **`Term.eval`** — the semantics: a term, a concrete generator
   `g : α → α → α` and an environment `ν → α` determine a value.
3. **`Generates`** — the predicate: `g` generates `f` when some term
   defines `f`. This is the "generated by" of Appendix A, now a statement
   rather than a catalogue.
4. **(A2) as data** (`termA2`): the eight composition terms of the
   paper — `R₈` being the generator itself — and the theorem
   `termA2_generates`: each defines exactly the (A1) operation of the
   same index.
5. **The bridge to the structure**: `relA1_iff_generated` and
   `relA2_iff_generated` relate the tables of `bool8` and `nand8` to the
   graph of the generated operations — hence the corollary
   `relA1_iff_relA2`, the reified, componentwise version of
   `equivStruct_bool8_nand8`.

Source: same Appendix A of R16 (Tegmark, arXiv:0704.0646) as
`MathUniverse_en`. French twin `Generators` (#4980).
-/

namespace MathUniverse.Generators_en

open MathUniverse_en.Examples (nand bool8 nand8 bool8Sig)

/-! ## 1. Term syntax -/

/-- A **term** over a binary generator: either a variable, or the
generator applied to two subterms. This is the composition syntax of
equation (A2) — the smallest one sufficient for the Boolean algebra,
since NAND alone generates the seven other operators. -/
inductive Term (ν : Type) where
  /- a variable of the language -/
  | var : ν → Term ν
  /- the generator applied to two subterms -/
  | gen : Term ν → Term ν → Term ν

/-- **Evaluation**: a term over the variables `ν`, a concrete generator
`g : α → α → α` and an environment `ν → α` determine a value of `α`.
The syntax receives its semantics through this single embedding. The
term is the first explicit argument — dot notation `t.eval g env`
requires it. -/
def Term.eval {α ν : Type} : Term ν → (α → α → α) → (ν → α) → α
  | .var v, _, env => env v
  | .gen s t, g, env => g (s.eval g env) (t.eval g env)

/-- The **function defined by a term**: a term and a generator determine
an operation on environments — each assignment of the variables yields a
value. -/
def Term.funOf {α ν : Type} (t : Term ν) (g : α → α → α) : (ν → α) → α :=
  t.eval g

/-- The generator `g` **generates** the function `f` when some term
defines it: `f` is obtained by finite composition of `g` with the
variables. This is the reification of the "generated by" of Appendix A —
what `MathUniverse_en` proved lemma by lemma becomes a generic
predicate. -/
def Generates {α ν : Type} (g : α → α → α) (f : (ν → α) → α) : Prop :=
  ∃ t : Term ν, t.funOf g = f

/-! ## 2. Equation (A2) as data -/

/-- The two variables of equations (A1)/(A2) of the paper. -/
inductive V where
  | X : V
  | Y : V

/-- The eight **terms of equation (A2)** — each (A1) operation defined by
composition of NAND alone, following the paper's formulas exactly:
R₁ = `R(R(X, R(X,X)), R(X, R(X,X)))`, R₂ = `R(X, R(X,X))`, R₃ = `R(X,X)`,
R₄ = `R(R(X,Y), R(X,Y))`, R₅ = `R(R(X,X), R(Y,Y))`, R₆ = `R(X, R(Y,Y))`,
R₇ = `R(R(X,Y), R(R(X,X), R(Y,Y)))` and R₈ = `R(X,Y)` — the generator
itself. -/
def termA2 : Fin 8 → Term V
  | 0 => .gen (.gen (.var .X) (.gen (.var .X) (.var .X)))
          (.gen (.var .X) (.gen (.var .X) (.var .X)))
  | 1 => .gen (.var .X) (.gen (.var .X) (.var .X))
  | 2 => .gen (.var .X) (.var .X)
  | 3 => .gen (.gen (.var .X) (.var .Y)) (.gen (.var .X) (.var .Y))
  | 4 => .gen (.gen (.var .X) (.var .X)) (.gen (.var .Y) (.var .Y))
  | 5 => .gen (.var .X) (.gen (.var .Y) (.var .Y))
  | 6 => .gen (.gen (.var .X) (.var .Y))
          (.gen (.gen (.var .X) (.var .X)) (.gen (.var .Y) (.var .Y)))
  | 7 => .gen (.var .X) (.var .Y)

/-- The eight **operations of equation (A1)** as functions `V → Bool`:
the constants ignore the environment, negation reads only `X`, the five
binary ones read `X` and `Y`. -/
def opA1 : Fin 8 → (V → Bool) → Bool
  | 0, _ => false
  | 1, _ => true
  | 2, e => !(e V.X)
  | 3, e => e V.X && e V.Y
  | 4, e => e V.X || e V.Y
  | 5, e => !(e V.X) || e V.Y
  | 6, e => (e V.X == e V.Y)
  | 7, e => nand (e V.X) (e V.Y)

/-- **(A2) reified**: the single NAND operator **generates** the eight
operations of (A1) — for each one, the term `termA2 i` defines it exactly.
Where `MathUniverse_en` proved seven pointwise identities, the fact is
now a statement of the language: composition = syntax, generation =
existence of a term. -/
theorem termA2_generates (i : Fin 8) : Generates nand (opA1 i) := by
  refine ⟨termA2 i, ?_⟩
  funext e
  fin_cases i <;> cases hX : e V.X <;> cases hY : e V.Y <;>
    simp [Term.funOf, Term.eval, termA2, opA1, nand, hX, hY]

/-! ## 3. The bridge to the structure -/

/-- The **graph** of an operation `f`, read at index `i` of the
`bool8Sig` signature: the last tuple component carries the result, the
first ones carry the inputs (`X`, then `Y` for the binary ones). The
arity ↔ inputs correspondence follows note 20 of the paper: a function
of arity k becomes a relation of arity k + 1 via its graph. -/
def opGraph : (i : Fin 8) → ((V → Bool) → Bool) → (Fin (bool8Sig i) → Bool) → Prop
  | 0, f, t => t 0 = f (fun _ => false)
  | 1, f, t => t 0 = f (fun _ => false)
  | 2, f, t => t 1 = f (fun v => match v with | .X => t 0 | .Y => false)
  | 3, f, t => t 2 = f (fun v => match v with | .X => t 0 | .Y => t 1)
  | 4, f, t => t 2 = f (fun v => match v with | .X => t 0 | .Y => t 1)
  | 5, f, t => t 2 = f (fun v => match v with | .X => t 0 | .Y => t 1)
  | 6, f, t => t 2 = f (fun v => match v with | .X => t 0 | .Y => t 1)
  | 7, f, t => t 2 = f (fun v => match v with | .X => t 0 | .Y => t 1)

/-- **Every relation of (A1) is the graph of an operation generated by
NAND alone**: the structure `bool8` — given by its eight primitive
tables — is generated by R₈, in the reified sense: an explicit term
(provided by `termA2_generates`) defines the operation whose graph is the
relation. -/
theorem relA1_iff_generated (i : Fin 8) (t : Fin (bool8Sig i) → Bool) :
    bool8.rel i t ↔ opGraph i (opA1 i) t := by
  fin_cases i <;> cases h0 : t 0 <;> cases h1 : t 1 <;> cases h2 : t 2 <;>
    simp [bool8, opGraph, opA1, nand, h0, h1, h2]

/-- Same statement for the structure **(A2)**: the tables of `nand8` —
defined in `MathUniverse_en` by hand-composition of NAND — are also,
component by component, the graphs of the generated operations. The
hand-composition was correct; it is now a piece of syntax. -/
theorem relA2_iff_generated (i : Fin 8) (t : Fin (bool8Sig i) → Bool) :
    nand8.rel i t ↔ opGraph i (opA1 i) t := by
  fin_cases i <;> cases h0 : t 0 <;> cases h1 : t 1 <;> cases h2 : t 2 <;>
    simp [nand8, opGraph, opA1, nand, h0, h1, h2]

/-- **The two definitions generate each other** — the reified,
componentwise version of `equivStruct_bool8_nand8`: since the relations
of (A1) and of (A2) are both the graphs of the same generated operations,
they coincide. The paper: "two structure definitions are equivalent if
they generate each other". -/
theorem relA1_iff_relA2 (i : Fin 8) (t : Fin (bool8Sig i) → Bool) :
    bool8.rel i t ↔ nand8.rel i t :=
  (relA1_iff_generated i t).trans (relA2_iff_generated i t).symm

/-! ## 4. The algorithm confirms, the syntax explains -/

/-- **`decide` recovers the term**: without being given the witness, the
evaluation of `termA2 6` (equivalence, the deepest of the eight
formulas) under NAND returns the table of ⇔ — the syntax of (A2) and the
table of (A1) say the same thing, and the kernel checks it. -/
example : (termA2 6).funOf nand (fun v => match v with | .X => true | .Y => false)
      = (true == false) := by
  decide

end MathUniverse.Generators_en
