import MathUniverse

/-!
# Generators — réifier « générateurs + composition » (Annexe A, éq. A2)

Suite directe de `MathUniverse` (issue **#16753**). Le module précédent
laissait le critère « une structure se donne aussi par ses **générateurs**
et ses **règles de composition** » en **exhibition concrète** : les sept
lemmes `nand_*` prouvaient bien que chaque relation de (A1) est composée de
NAND, mais la composition vivait dans les *termes de la preuve*, pas dans le
langage. Ce module la **réifie** :

1. **`Term ν`** — la syntaxe : une variable, ou le générateur binaire appliqué
   à deux sous-termes. Les formules `R(R(X, Y), R(X, X))` de l'équation (A2)
   deviennent des arbres que Lean peut inspecter, comparer et évaluer.
2. **`Term.eval`** — la sémantique : un terme, un générateur concret
   `g : α → α → α` et un environnement `ν → α` déterminent une valeur.
3. **`Generates`** — le prédicat : `g` génère `f` quand un terme définit `f`.
   C'est le « generated by » de l'Annexe A, désormais un énoncé et non un
   catalogue.
4. **`(A2) comme donnée** (`termA2`) : les huit termes de composition du
   papier — `R₈` étant le générateur lui-même — et le théorème
   `termA2_generates` : chacun définit exactement l'opération de (A1) de
   même indice.
5. **Le pont vers la structure** : `relA1_iff_generated` et
   `relA2_iff_generated` relient les tables de `bool8` et de `nand8` au
   graphe des opérations générées — d'où le corollaire `relA1_iff_relA2`,
   version réifiée, composante par composante, de
   `equivStruct_bool8_nand8`.

Source : même Annexe A de R16 (Tegmark, arXiv:0704.0646) que
`MathUniverse`. Twin anglais `Generators_en` (#4980).
-/

namespace MathUniverse.Generators

open MathUniverse.Examples (nand bool8 nand8 bool8Sig)

/-! ## 1. La syntaxe des termes -/

/-- Un **terme** sur un générateur binaire : soit une variable, soit le
générateur appliqué à deux sous-termes. C'est la syntaxe de composition de
l'équation (A2) — la plus petite qui suffise à l'algèbre de Boole, puisque
NAND seul engendre les sept autres opérateurs. -/
inductive Term (ν : Type) where
  /- une variable du langage -/
  | var : ν → Term ν
  /- le générateur appliqué à deux sous-termes -/
  | gen : Term ν → Term ν → Term ν

/-- **L'évaluation** : un terme sur les variables `ν`, un générateur concret
`g : α → α → α` et un environnement `ν → α` déterminent une valeur de `α`.
La syntaxe reçoit sa sémantique par ce seul plongement. Le terme est en
premier argument explicite — la notation pointée `t.eval g env` l'exige. -/
def Term.eval {α ν : Type} : Term ν → (α → α → α) → (ν → α) → α
  | .var v, _, env => env v
  | .gen s t, g, env => g (s.eval g env) (t.eval g env)

/-- La **fonction définie par un terme** : un terme et un générateur
déterminent une opération sur les environnements — chaque assignation des
variables donne une valeur. -/
def Term.funOf {α ν : Type} (t : Term ν) (g : α → α → α) : (ν → α) → α :=
  t.eval g

/-- Le générateur `g` **génère** la fonction `f` quand un terme la définit :
`f` s'obtient par composition finie de `g` et des variables. C'est la
réification du « generated by » de l'Annexe A — ce que `MathUniverse`
démontrait lemme par lemme devient un prédicat générique. -/
def Generates {α ν : Type} (g : α → α → α) (f : (ν → α) → α) : Prop :=
  ∃ t : Term ν, t.funOf g = f

/-! ## 2. L'équation (A2) comme donnée -/

/-- Les deux variables des équations (A1)/(A2) du papier. -/
inductive V where
  | X : V
  | Y : V

/-- Les huit **termes de l'équation (A2)** — chaque opération de (A1) définie
par composition de NAND seul, en suivant exactement les formules du papier :
R₁ = `R(R(X, R(X,X)), R(X, R(X,X)))`, R₂ = `R(X, R(X,X))`, R₃ = `R(X,X)`,
R₄ = `R(R(X,Y), R(X,Y))`, R₅ = `R(R(X,X), R(Y,Y))`, R₆ = `R(X, R(Y,Y))`,
R₇ = `R(R(X,Y), R(R(X,X), R(Y,Y)))` et R₈ = `R(X,Y)` — le générateur
lui-même. -/
def termA2 : Fin 8 → Term V
  | 0 => .gen (.gen (.var .X) (.gen (.var .X) (.var .X)))
          (.gen (.var .X) (.gen (.var .X) (.var .X)))
  | 1 => .gen (.var .X) (.gen (.var .X) (.var .X))
  | 2 => .gen (.var .X) (.var .X)
  | 3 => .gen (.gen (.var .X) (.var .Y)) (.gen (.var .X) (.var .Y))
  | 4 => .gen (.gen (.var .X) (.var .X)) (.gen (.var .Y) (.var .Y))
  | 5 => .gen (.var .X) (.gen (.var .Y) (.var .Y))
  | 6 => .gen (.gen (.var .X) (.var .Y))
          (.gen (.gen (.var .X) (.var .X)) (.gen (.var .Y) (.var .Y)))
  | 7 => .gen (.var .X) (.var .Y)

/-- Les huit **opérations de l'équation (A1)** comme fonctions `V → Bool` :
les constantes ignorent l'environnement, la négation ne lit que `X`, les
cinq binaires lisent `X` et `Y`. -/
def opA1 : Fin 8 → (V → Bool) → Bool
  | 0, _ => false
  | 1, _ => true
  | 2, e => !(e V.X)
  | 3, e => e V.X && e V.Y
  | 4, e => e V.X || e V.Y
  | 5, e => !(e V.X) || e V.Y
  | 6, e => (e V.X == e V.Y)
  | 7, e => nand (e V.X) (e V.Y)

/-- **(A2) réifiée** : le seul opérateur NAND **génère** les huit opérations
de (A1) — pour chacune, le terme `termA2 i` la définit exactement. Là où
`MathUniverse` prouvait sept identités ponctuelles, le fait est désormais un
énoncé du langage : composition = syntaxe, génération = existence d'un
terme. -/
theorem termA2_generates (i : Fin 8) : Generates nand (opA1 i) := by
  refine ⟨termA2 i, ?_⟩
  funext e
  fin_cases i <;> cases hX : e V.X <;> cases hY : e V.Y <;>
    simp [Term.funOf, Term.eval, termA2, opA1, nand, hX, hY]

/-! ## 3. Le pont vers la structure -/

/-- Le **graphe** d'une opération `f`, lu à l'indice `i` de la signature
`bool8Sig` : la dernière composante du uplet porte le résultat, les
premières portent les entrées (`X`, puis `Y` pour les binaires). La
correspondance arité ↔ entrées suit la note 20 du papier : une fonction
d'arité k devient une relation d'arité k + 1 par son graphe. -/
def opGraph : (i : Fin 8) → ((V → Bool) → Bool) → (Fin (bool8Sig i) → Bool) → Prop
  | 0, f, t => t 0 = f (fun _ => false)
  | 1, f, t => t 0 = f (fun _ => false)
  | 2, f, t => t 1 = f (fun v => match v with | .X => t 0 | .Y => false)
  | 3, f, t => t 2 = f (fun v => match v with | .X => t 0 | .Y => t 1)
  | 4, f, t => t 2 = f (fun v => match v with | .X => t 0 | .Y => t 1)
  | 5, f, t => t 2 = f (fun v => match v with | .X => t 0 | .Y => t 1)
  | 6, f, t => t 2 = f (fun v => match v with | .X => t 0 | .Y => t 1)
  | 7, f, t => t 2 = f (fun v => match v with | .X => t 0 | .Y => t 1)

/-- **Chaque relation de (A1) est le graphe d'une opération générée par NAND
seul** : la structure `bool8` — donnée par ses huit tables primitives — est
engendrée par R₈, au sens réifié : un terme explicite (donné par
`termA2_generates`) définit l'opération dont le graphe est la relation. -/
theorem relA1_iff_generated (i : Fin 8) (t : Fin (bool8Sig i) → Bool) :
    bool8.rel i t ↔ opGraph i (opA1 i) t := by
  fin_cases i <;> cases h0 : t 0 <;> cases h1 : t 1 <;> cases h2 : t 2 <;>
    simp [bool8, opGraph, opA1, nand, h0, h1, h2]

/-- Même énoncé pour la structure **(A2)** : les tables de `nand8` —
définies dans `MathUniverse` par composition manuelle de NAND — sont elles
aussi, composante par composante, les graphes des opérations générées. La
composition manuelle était correcte ; elle est maintenant une donnée
syntaxique. -/
theorem relA2_iff_generated (i : Fin 8) (t : Fin (bool8Sig i) → Bool) :
    nand8.rel i t ↔ opGraph i (opA1 i) t := by
  fin_cases i <;> cases h0 : t 0 <;> cases h1 : t 1 <;> cases h2 : t 2 <;>
    simp [nand8, opGraph, opA1, nand, h0, h1, h2]

/-- **Les deux définitions se génèrent l'une l'autre** — version réifiée,
composante par composante, de `equivStruct_bool8_nand8` : puisque les
relations de (A1) et de (A2) sont toutes deux les graphes des mêmes
opérations générées, elles coïncident. Le papier : « two structure
definitions are equivalent if they generate each other ». -/
theorem relA1_iff_relA2 (i : Fin 8) (t : Fin (bool8Sig i) → Bool) :
    bool8.rel i t ↔ nand8.rel i t :=
  (relA1_iff_generated i t).trans (relA2_iff_generated i t).symm

/-! ## 4. L'algorithme confirme, la syntaxe explique -/

/-- **`decide` retrouve le terme** : sans qu'on lui donne le témoin,
l'évaluation de `termA2 6` (l'équivalence, la plus profonde des huit
formules) sous NAND redonne la table de ⇔ — la syntaxe de (A2) et la table
de (A1) disent la même chose, et le noyau le vérifie. -/
example : (termA2 6).funOf nand (fun v => match v with | .X => true | .Y => false)
      = (true == false) := by
  decide

end MathUniverse.Generators
