import Mathlib

/-!
# MathUniverse — finite mathematical structures (Appendix A, R16 Tegmark)

Lean formalization of **Appendix A** of R16 — *The Mathematical Universe*
(Tegmark, [arXiv:0704.0646](https://arxiv.org/abs/0704.0646), §A.1-A.2) —
the operational definition of a mathematical structure, on which the
Mathematical Universe Hypothesis (MUH) rests: "a mathematical structure is a
set of abstract entities and relations between them".

Formalization slice of the "open, accountable, provable, explainable" arc of
EPIC **#16741** (issue **#16753**). Distilled content:

1. **Definition** (`FinRelStruct`): entities = a finite type `α` (the union
   `S₁ ∪ … ∪ Sₙ` of the paper, single-sorted here), and a **signature**
   `σ : Fin n → ℕ` giving the arity of each of the `n` relations. Every relation
   is a **decidable** predicate on tuples of arity `σ i`. Separating the
   signature from its realization is exactly what model theory does — and it
   is what makes the equivalence of two definitions of the *same* structure
   statable without arity transport. Non-Boolean functions are encoded as
   relations through their graph — "the relation R(a₁,…,aₙ₋₁) = aₙ holds"
   (note 20 of the paper).
2. **Aut(S) is a group** (`aut`): the bijections preserving every relation
   form a subgroup of `Equiv.Perm` — the "easy to see" of Appendix A, an
   ideal exercise according to the paper. Concrete witness: the automorphism
   group of the two-element Boolean algebra is **trivial**
   (`aut_bool8_trivial`), an anchor already used by `EffectiveTheory.InfoBits`
   (`b = log₂(n!/|Aut G|)`: 1 bit for the two-element group).
3. **Decidability of equivalence** (`EquivStruct`, `EquivStruct.decidable`):
   there is "a simple halting algorithm" deciding whether two definitions of
   finite structures are equivalent — rendered here as a `Decidable` instance
   by exhaustive enumeration of the functions between finite types ("the
   enumeration of the tableaus" of the paper). `decide` IS the algorithm.
4. **Examples** (§A.2 of the paper): the cyclic group **C₂** (addition table
   of Z/2), the cyclic group **C₃** (Z/3), and the **two-element Boolean
   algebra** — the eight relations F, T, ¬, ∧, ∨, ⇒, ⇔, | of equation (A1) —
   generated by **NAND alone** (equation A2): the eight composition formulas
   of the paper (`nand_false`, `nand_true`, `nand_not`, `nand_and`, `nand_or`,
   `nand_implies`, `nand_iff`) and the structural confirmation by the decision
   algorithm itself (`decide` on `EquivStruct bool8 nand8`).

Source PDF (GDrive, sha8): R16 `85712871`
(`G:\Mon Drive\MyIA\IA\Bibliographie IA\Consciousness\
2007 - Tegmark - The Mathematical Universe.pdf`).

Sibling of `Perceptron` (Novikoff), `PacLearning` (Valiant), `GradientFlow`
(vanishing/residual survival) and `EffectiveTheory` (arc B, #16752) in the
generalist ML lake. English twin `MathUniverse_en` (#4980).
-/

namespace MathUniverse_en

variable {α : Type*} {β : Type*} [Fintype α] [Fintype β] {n : ℕ} {σ : Fin n → ℕ}

/-! ## 1. The definition (Appendix A.1) -/

/-- A **finite relational structure** of signature `σ`: a finite carrier type
`α` (the entities — the union `S₁ ∪ … ∪ Sₙ` of the paper, single-sorted here),
and for each `i : Fin n` a relation of arity `σ i` — a predicate on tuples of
elements. The decidability required by the `rel_dec` field is the one §A.2 of
the paper calls for: "all these functions must be computable" — a finite
structure is specified by its tableaus, and a finite tableau is walked end to
end. -/
structure FinRelStruct (α : Type*) [Fintype α] {n : ℕ} (σ : Fin n → ℕ) where
  /- each relation: a predicate on tuples of arity `σ i` -/
  rel : (i : Fin n) → ((Fin (σ i) → α) → Prop)
  /- the relation is decidable: the tableau is effectively given -/
  rel_dec : (i : Fin n) → (t : Fin (σ i) → α) → Decidable (rel i t)

/-! ## 2. Aut(S) is a group -/

/-- A map preserves the structure when every relation is invariant under
relabelling of its tuples. For a bijection, preserving "one way" is enough:
the iff is then automatically symmetric. -/
def Preserves (S : FinRelStruct α σ) (f : α → α) : Prop :=
  ∀ i (t : Fin (σ i) → α), S.rel i t ↔ S.rel i (f ∘ t)

/-- **Aut(S)**, the automorphism group of the structure: the bijections
preserving every relation. It is a subgroup of `Equiv.Perm α` — the "easy to
see" of Appendix A: the identity preserves, the composite of two preservations
preserves, and the inverse of a preservation preserves. The group structure is
then the one Mathlib gives to any subgroup. -/
def aut (S : FinRelStruct α σ) : Subgroup (Equiv.Perm α) where
  carrier := {f | Preserves S f}
  one_mem' := by
    intro i t
    simp
  mul_mem' := by
    intro f g hf hg i t
    rw [Equiv.Perm.coe_mul, Function.comp_assoc]
    exact (hg i t).trans (hf i (⇑g ∘ t))
  inv_mem' := by
    intro f hf i t
    have key : S.rel i (⇑f⁻¹ ∘ t) ↔ S.rel i (⇑(f * f⁻¹) ∘ t) := by
      have h := hf i (⇑f⁻¹ ∘ t)
      rwa [show ⇑f ∘ (⇑f⁻¹ ∘ t) = ⇑(f * f⁻¹) ∘ t by
        simp only [Equiv.Perm.coe_mul, Function.comp_assoc]] at h
    rw [mul_inv_cancel, Equiv.Perm.coe_one, Function.id_comp] at key
    exact key.symm

/-- Membership in Aut(S) unfolds to preservation. -/
theorem mem_aut_iff (S : FinRelStruct α σ) (f : Equiv.Perm α) :
    f ∈ aut S ↔ Preserves S f := Iff.rfl

/-! ## 3. Decidability of equivalence (halting enumeration) -/

/-- **Equivalence of structures** (same signature `σ`): there is a bijection
`f` such that every relation of `S` corresponds exactly to the relation of the
same index of `T` through `f`. This is the relational isomorphism — the paper:
"two structure definitions are equivalent if they generate each other"; for
finite structures given by their tableaus, generators included, the equivalence
goes through this correspondence. -/
def EquivStruct (S : FinRelStruct α σ) (T : FinRelStruct β σ) : Prop :=
  ∃ f : α ≃ β, ∀ i (t : Fin (σ i) → α), S.rel i t ↔ T.rel i (f ∘ t)

/-- The version unfolded onto functions: same statement, but quantified over
`α → β` — the enumerable type par excellence (`Fintype.pi`), which carries the
decidability. -/
theorem equivStruct_iff_functions (S : FinRelStruct α σ) (T : FinRelStruct β σ) :
    EquivStruct S T ↔
      ∃ f : α → β, Function.Bijective f ∧
        ∀ i (t : Fin (σ i) → α), S.rel i t ↔ T.rel i (f ∘ t) := by
  constructor
  · rintro ⟨f, hrel⟩
    exact ⟨f, f.bijective, hrel⟩
  · rintro ⟨f, hf, hrel⟩
    exact ⟨Equiv.ofBijective f hf, hrel⟩

/-- **The halting algorithm of Appendix A**: the equivalence of two finite
structures is **decidable** — one enumerates all maps `α → β` (all tableaus),
each tested by decidable predicates, and the enumeration of a finite product of
finite types terminates. Rendered as a `Decidable` instance, `decide` is
literally the tableau enumeration of the paper.

The two local `letI`s expose the `rel_dec` fields as instances: without them,
instance resolution could not climb from `Decidable (S.rel i t)` back to the
field that witnesses it. -/
instance EquivStruct.decidable (S : FinRelStruct α σ) (T : FinRelStruct β σ)
    [DecidableEq α] [DecidableEq β] : Decidable (EquivStruct S T) :=
  letI : ∀ i (t : Fin (σ i) → α), Decidable (S.rel i t) := S.rel_dec
  letI : ∀ i (t : Fin (σ i) → β), Decidable (T.rel i t) := T.rel_dec
  decidable_of_iff (∃ f : α → β, Function.Bijective f ∧
    ∀ i (t : Fin (σ i) → α), S.rel i t ↔ T.rel i (f ∘ t))
    (equivStruct_iff_functions S T).symm

/-! ## 4. Examples (Appendix A.2) -/

namespace Examples

/-! ### The Sheffer operator `|` (nand) -/

/-- NAND on `Bool` (Sheffer symbol `|`) — relation R₈ of equation (A1), and
the single generator of equation (A2). -/
def nand (x y : Bool) : Bool := !(x && y)

/-! ### C₂: the cyclic group Z/2 -/

/-- Signature of `c2`: a single ternary relation. -/
@[reducible]
def c2Sig : Fin 1 → ℕ := fun _ => 3

/-- The cyclic group **C₂** as a relational structure: a single ternary
relation, the addition table of Z/2 ("generalized multiplication table", §A.2
of the paper) — the graph of `(x, y) ↦ x XOR y` on `Bool`, encoded as a
relation by note 20: R(x, y, z) ↔ x + y = z. -/
def c2 : FinRelStruct Bool c2Sig where
  rel := fun _ t => (t 0 ^^ t 1) = t 2
  rel_dec := fun i _ =>
    match i with
    | 0 => inferInstance

/-! ### C₃: the cyclic group Z/3 -/

/-- Signature of `c3`: a single ternary relation. -/
@[reducible]
def c3Sig : Fin 1 → ℕ := fun _ => 3

/-- The cyclic group **C₃**: addition table of Z/3 on `Fin 3` (addition on
`Fin n` is already modular). -/
def c3 : FinRelStruct (Fin 3) c3Sig where
  rel := fun _ t => (t 0 + t 1) = t 2
  rel_dec := fun i _ =>
    match i with
    | 0 => inferInstance

/-! ### The two-element Boolean algebra (equation A1) -/

/-- Signature of `bool8`: the arities of the eight relations of equation
(A1) — two constants (arity 1, encoding "x = F" and "x = T"), one unary
function (¬) and five binary ones (∧, ∨, ⇒, ⇔, |). -/
@[reducible]
def bool8Sig : Fin 8 → ℕ
  | 0 => 1
  | 1 => 1
  | 2 => 2
  | 3 => 3
  | 4 => 3
  | 5 => 3
  | 6 => 3
  | 7 => 3

/-- The eight relations of equation **(A1)**: F, T, ¬, ∧, ∨, ⇒, ⇔, | (nand),
each encoded by its graph (note 20). The constants F and T are zero-arity
functions, hence unary relations "x = F" and "x = T"; the unary and binary
operators become relations of arity 2 and 3. -/
def bool8 : FinRelStruct Bool bool8Sig where
  rel := fun i t =>
    match i with
    | 0 => t 0 = false                    -- R₁ = F  (false constant)
    | 1 => t 0 = true                     -- R₂ = T  (true constant)
    | 2 => (!t 0) = t 1                   -- R₃ = ¬
    | 3 => (t 0 && t 1) = t 2             -- R₄ = ∧
    | 4 => (t 0 || t 1) = t 2             -- R₅ = ∨
    | 5 => (!t 0 || t 1) = t 2            -- R₆ = ⇒
    | 6 => (t 0 == t 1) = t 2             -- R₇ = ⇔
    | 7 => nand (t 0) (t 1) = t 2         -- R₈ = | (nand)
  rel_dec := fun i _ =>
    match i with
    | 0 => inferInstance
    | 1 => inferInstance
    | 2 => inferInstance
    | 3 => inferInstance
    | 4 => inferInstance
    | 5 => inferInstance
    | 6 => inferInstance
    | 7 => inferInstance

/-- **The automorphism group of the Boolean algebra is trivial**: preserving
relation R₁ ("x = F") pins the false constant, and a bijection of `Bool`
fixing `false` fixes `true`. Concrete anchor already used by
`EffectiveTheory.InfoBits` (`b = log₂(n!/|Aut G|)`: 2!/1 = 2, i.e. 1 bit). -/
theorem aut_bool8_trivial (f : Equiv.Perm Bool) (hf : f ∈ aut bool8) :
    f = 1 := by
  have hnot : Preserves bool8 ⇑f := hf
  have h0 : f false = false := by
    simpa [bool8] using (hnot 0 (fun _ => false)).mp rfl
  have h1 : f true = true := by
    obtain ⟨a, ha⟩ := f.surjective true
    cases a with
    | false => exact absurd (h0 ▸ ha) (by simp)
    | true => exact ha
  ext x
  cases x with
  | false => simpa [Equiv.coe_refl] using h0
  | true => simpa [Equiv.coe_refl] using h1

/-! ### Generated by NAND alone (equation A2) -/

/-- **R₁ = F** by NAND composition: the formula
`R(R(X, R(X, X)), R(X, R(X, X)))` of the paper yields the false constant. -/
theorem nand_false (x : Bool) :
    nand (nand x (nand x x)) (nand x (nand x x)) = false := by
  cases x <;> decide

/-- **R₂ = T**: `R(X, R(X, X))` yields the true constant. -/
theorem nand_true (x : Bool) : nand x (nand x x) = true := by
  cases x <;> decide

/-- **R₃ = ¬**: `R(X, X)` yields negation. -/
theorem nand_not (x : Bool) : nand x x = !x := by
  cases x <;> decide

/-- **R₄ = ∧**: `R(R(X, Y), R(X, Y))` yields conjunction. -/
theorem nand_and (x y : Bool) :
    nand (nand x y) (nand x y) = (x && y) := by
  cases x <;> cases y <;> decide

/-- **R₅ = ∨**: `R(R(X, X), R(Y, Y))` yields disjunction. -/
theorem nand_or (x y : Bool) :
    nand (nand x x) (nand y y) = (x || y) := by
  cases x <;> cases y <;> decide

/-- **R₆ = ⇒**: `R(X, R(Y, Y))` yields implication. -/
theorem nand_implies (x y : Bool) :
    nand x (nand y y) = (!x || y) := by
  cases x <;> cases y <;> decide

/-- **R₇ = ⇔**: `R(R(X, Y), R(R(X, X), R(Y, Y)))` yields equivalence (the
table `[[1,0],[0,1]]` of the paper). -/
theorem nand_iff (x y : Bool) :
    nand (nand x y) (nand (nand x x) (nand y y)) = (x == y) := by
  cases x <;> cases y <;> decide

/-- The structure **(A2)**: the same signature as (A1) — eight relations —
but every table is now **defined by NAND composition alone**, following exactly
the formulas of equation (A2) of the paper. The two constants remain unary
relations "x = F" and "x = T" — hence `x = <formula>`, not
`<formula> = false`: the formula yields the constant, it does not assert
it. -/
def nand8 : FinRelStruct Bool bool8Sig where
  rel := fun i t =>
    match i with
    | 0 => t 0 = nand (nand (t 0) (nand (t 0) (t 0))) (nand (t 0) (nand (t 0) (t 0)))
    | 1 => t 0 = nand (t 0) (nand (t 0) (t 0))
    | 2 => nand (t 0) (t 0) = t 1
    | 3 => nand (nand (t 0) (t 1)) (nand (t 0) (t 1)) = t 2
    | 4 => nand (nand (t 0) (t 0)) (nand (t 1) (t 1)) = t 2
    | 5 => nand (t 0) (nand (t 1) (t 1)) = t 2
    | 6 => nand (nand (t 0) (t 1)) (nand (nand (t 0) (t 0)) (nand (t 1) (t 1))) = t 2
    | 7 => nand (t 0) (t 1) = t 2
  rel_dec := fun i _ =>
    match i with
    | 0 => inferInstance
    | 1 => inferInstance
    | 2 => inferInstance
    | 3 => inferInstance
    | 4 => inferInstance
    | 5 => inferInstance
    | 6 => inferInstance
    | 7 => inferInstance

/-- **Equivalence of definitions (A1) and (A2)**: the eight relations
defined by NAND composition coincide exactly with the eight primitive
relations — the identity is the witness. The proof is literally the catalogue
of composition formulas: each `nand_*` lemma above rewrites one line of (A2)
into the corresponding line of (A1). -/
theorem equivStruct_bool8_nand8 : EquivStruct bool8 nand8 := by
  refine ⟨Equiv.refl Bool, ?_⟩
  intro i t
  fin_cases i
  · simp [bool8, nand8, Equiv.coe_refl, nand_false]
  · simp [bool8, nand8, Equiv.coe_refl, nand_true]
  · simp [bool8, nand8, Equiv.coe_refl, nand_not]
  · simp [bool8, nand8, Equiv.coe_refl, nand_and]
  · simp [bool8, nand8, Equiv.coe_refl, nand_or]
  · simp [bool8, nand8, Equiv.coe_refl, nand_implies]
  · simp [bool8, nand8, Equiv.coe_refl, nand_iff]
  · simp [bool8, nand8, Equiv.coe_refl]

/-- **The halting algorithm confirms the paper**: `decide` — the tableau
enumeration of Appendix A — finds that (A1) and (A2) define the same
structure, without being given the witness. -/
example : decide (EquivStruct bool8 nand8) = true := by
  decide +kernel

end Examples

end MathUniverse_en
