"""Generate research.ipynb for Ensemble-DLinear-TFT project.

Weighted ensemble DLinear + TFT with grid search over weights for crypto direction prediction.
Walk-forward 5-fold x 4 seeds. CPU-only.
"""
import json
import uuid


def md(lines):
    return {"cell_type": "markdown", "id": uuid.uuid4().hex[:8], "metadata": {}, "source": lines}


def code(lines):
    return {
        "cell_type": "code",
        "execution_count": None,
        "id": uuid.uuid4().hex[:8],
        "metadata": {},
        "outputs": [],
        "source": lines,
    }


cells = [
    md([
        "# Ensemble DLinear + TFT Crypto Direction Prediction (v2)\n",
        "\n",
        "Ensemble pondere DLinear + TFT avec **grid search des poids** pour la prediction\n",
        "de direction crypto (BTC-USD, ETH-USD).\n",
        "\n",
        "**v2** : les poids ne sont plus hardcodes (0.6/0.4) mais selectionnes par grid search\n",
        "{0.4, 0.5, 0.6, 0.7} sur le fold precedent (walk-forward).\n",
        "\n",
        "**Reference** : #947 a montre Ensemble hardcoded NO BEATS (z=-7.56).\n",
        "\n",
        "**Approche** :\n",
        "- Donnees : BTC-USD + ETH-USD (yfinance, 2018-2024, h=1)\n",
        "- Features : log-returns, RSI(14), MACD signal, Bollinger position, lagged 1-5\n",
        "- Modeles : DLinear, TFT-Lite, Ensemble (grid-search weights)\n",
        "- Validation : Walk-forward 5-fold x 4 seeds (0, 7, 42, 99)\n",
        "- Couts : 10bps par changement de position\n",
        "- CPU-only (po-2025 contrainte thermique)\n",
        "\n",
        "**Verdict honnete** : BEATS / NO BEATS / INCONCLUSIVE (edge >= 2sigma cross-seed)",
    ]),

    code([
        "import numpy as np\n",
        "import pandas as pd\n",
        "import torch\n",
        "import torch.nn as nn\n",
        "import torch.nn.functional as F\n",
        "import matplotlib.pyplot as plt\n",
        "import yfinance as yf\n",
        "from sklearn.preprocessing import StandardScaler\n",
        "import warnings\n",
        "warnings.filterwarnings('ignore')\n",
        "\n",
        "SEEDS = [0, 7, 42, 99]\n",
        "N_FOLDS = 5\n",
        "TCOST_BPS = 10\n",
        "SEQUENCE_LENGTH = 21\n",
        "TICKERS = ['BTC-USD', 'ETH-USD']\n",
        "DEVICE = torch.device('cpu')\n",
        "GRID_WEIGHTS = [0.4, 0.5, 0.6, 0.7]  # v2: grid search instead of hardcoded\n",
        "\n",
        "np.random.seed(42)\n",
        "torch.manual_seed(42)\n",
        "print(f'PyTorch {torch.__version__}, Device: {DEVICE}')\n",
        "print(f'Grid search weights: {GRID_WEIGHTS}')",
    ]),

    md([
        "## 1. Telechargement et Feature Engineering",
    ]),

    code([
        "print('Telechargement des donnees...')\n",
        "raw = yf.download(TICKERS, start='2017-01-01', end='2025-01-01', auto_adjust=True)\n",
        "\n",
        "if isinstance(raw.columns, pd.MultiIndex):\n",
        "    prices = raw['Close'].copy()\n",
        "else:\n",
        "    prices = raw[['Close']].copy()\n",
        "\n",
        "prices = prices.dropna()\n",
        "print(f'Periode: {prices.index[0].date()} a {prices.index[-1].date()}')\n",
        "print(f'Jours: {len(prices)}')\n",
        "\n",
        "raw_returns = {}\n",
        "for t in prices.columns:\n",
        "    c = prices[t].values\n",
        "    raw_returns[t] = np.diff(c) / c[:-1]\n",
        "returns_dates = prices.index[1:]\n",
        "returns_series = {t: pd.Series(raw_returns[t], index=returns_dates) for t in raw_returns}",
    ]),

    code([
        "def compute_features(close_prices):\n",
        "    c = close_prices.values.ravel()\n",
        "    log_ret = np.log(c[1:] / c[:-1])\n",
        "    df = pd.DataFrame({'log_ret': log_ret}, index=close_prices.index[1:])\n",
        "    delta = df['log_ret'].diff()\n",
        "    gain = delta.where(delta > 0, 0).rolling(14).mean()\n",
        "    loss = (-delta.where(delta < 0, 0)).rolling(14).mean()\n",
        "    rs = gain / (loss + 1e-10)\n",
        "    df['rsi14'] = 100 - (100 / (1 + rs))\n",
        "    ema12 = df['log_ret'].ewm(span=12).mean()\n",
        "    ema26 = df['log_ret'].ewm(span=26).mean()\n",
        "    df['macd_signal'] = (ema12 - ema26).ewm(span=9).mean()\n",
        "    sma20 = df['log_ret'].rolling(20).mean()\n",
        "    std20 = df['log_ret'].rolling(20).std()\n",
        "    df['boll_pos'] = (df['log_ret'] - sma20) / (std20 + 1e-10)\n",
        "    for lag in range(1, 6):\n",
        "        df[f'lag_{lag}'] = df['log_ret'].shift(lag)\n",
        "    df['target'] = (df['log_ret'].shift(-1) > 0).astype(int)\n",
        "    df = df.dropna()\n",
        "    return df\n",
        "\n",
        "all_dfs = []\n",
        "for ticker in prices.columns:\n",
        "    feat_df = compute_features(prices[[ticker]])\n",
        "    feat_df['ticker'] = ticker\n",
        "    all_dfs.append(feat_df)\n",
        "\n",
        "data = pd.concat(all_dfs, axis=0).sort_index()\n",
        "feature_cols = ['log_ret', 'rsi14', 'macd_signal', 'boll_pos',\n",
        "                'lag_1', 'lag_2', 'lag_3', 'lag_4', 'lag_5']\n",
        "\n",
        "X_all = data[feature_cols].values.astype(np.float32)\n",
        "y_all = data['target'].values.astype(np.int64)\n",
        "dates_all = data.index\n",
        "tickers_all = data['ticker'].values\n",
        "print(f'Features: {X_all.shape}, Samples: {len(X_all)}')",
    ]),

    md([
        "## 2. Modeles : DLinear, TFT-Lite, Ensemble",
    ]),

    code([
        "class DLinearModel(nn.Module):\n",
        "    def __init__(self, seq_len, input_dim, n_classes=2):\n",
        "        super().__init__()\n",
        "        self.seq_len = seq_len\n",
        "        self.linear = nn.Linear(seq_len * input_dim, n_classes)\n",
        "\n",
        "    def forward(self, x):\n",
        "        B, L, D = x.shape\n",
        "        return self.linear(x.reshape(B, -1))\n",
        "\n",
        "\n",
        "class TFTLiteModel(nn.Module):\n",
        "    def __init__(self, input_dim, d_model=32, n_heads=2, n_classes=2):\n",
        "        super().__init__()\n",
        "        self.input_proj = nn.Linear(input_dim, d_model)\n",
        "        self.lstm = nn.LSTM(d_model, d_model, num_layers=1, batch_first=True)\n",
        "        self.attn = nn.MultiheadAttention(d_model, n_heads, batch_first=True)\n",
        "        self.head = nn.Sequential(\n",
        "            nn.Linear(d_model, d_model // 2),\n",
        "            nn.ReLU(),\n",
        "            nn.Linear(d_model // 2, n_classes)\n",
        "        )\n",
        "\n",
        "    def forward(self, x):\n",
        "        h = self.input_proj(x)\n",
        "        h, _ = self.lstm(h)\n",
        "        h2, _ = self.attn(h, h, h)\n",
        "        h = h + h2\n",
        "        return self.head(h[:, -1, :])\n",
        "\n",
        "print('DLinear + TFT-Lite models defined')",
    ]),

    md([
        "## 3. Walk-Forward Validation Multi-Seed (v2 Grid Search)\n",
        "\n",
        "Pour chaque fold/seed : entraine DLinear et TFT separement,\n",
        "puis selectionne le meilleur poids d'ensemble par grid search\n",
        f"({'{0.4, 0.5, 0.6, 0.7}'}) sur le dernier fold d'entrainement.\n",
        "Compare a chaque modele seul et BH.",
    ]),

    code([
        "def create_sequences(X, y, seq_len):\n",
        "    Xs, ys = [], []\n",
        "    for i in range(seq_len, len(X)):\n",
        "        Xs.append(X[i-seq_len:i])\n",
        "        ys.append(y[i])\n",
        "    return np.array(Xs), np.array(ys)\n",
        "\n",
        "\n",
        "def train_model(model, X_train, y_train, epochs, batch_size, device, lr=1e-3):\n",
        "    model = model.to(device)\n",
        "    optimizer = torch.optim.Adam(model.parameters(), lr=lr)\n",
        "    criterion = nn.CrossEntropyLoss()\n",
        "    X_t = torch.FloatTensor(X_train).to(device)\n",
        "    y_t = torch.LongTensor(y_train).to(device)\n",
        "    best_loss = float('inf')\n",
        "    patience = 5\n",
        "    wait = 0\n",
        "    for epoch in range(epochs):\n",
        "        model.train()\n",
        "        indices = torch.randperm(len(X_t))\n",
        "        total_loss = 0\n",
        "        n_batches = 0\n",
        "        for i in range(0, len(X_t), batch_size):\n",
        "            batch_idx = indices[i:i+batch_size]\n",
        "            batch_X = X_t[batch_idx]\n",
        "            batch_y = y_t[batch_idx]\n",
        "            logits = model(batch_X)\n",
        "            loss = criterion(logits, batch_y)\n",
        "            optimizer.zero_grad()\n",
        "            loss.backward()\n",
        "            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)\n",
        "            optimizer.step()\n",
        "            total_loss += loss.item()\n",
        "            n_batches += 1\n",
        "        avg_loss = total_loss / max(n_batches, 1)\n",
        "        if avg_loss < best_loss - 1e-4:\n",
        "            best_loss = avg_loss\n",
        "            wait = 0\n",
        "        else:\n",
        "            wait += 1\n",
        "            if wait >= patience:\n",
        "                break\n",
        "    return model\n",
        "\n",
        "\n",
        "def predict_probs(model, X_test, device):\n",
        "    model.eval()\n",
        "    with torch.no_grad():\n",
        "        X_t = torch.FloatTensor(X_test).to(device)\n",
        "        logits = model(X_t)\n",
        "        probs = F.softmax(logits, dim=-1)[:, 1].cpu().numpy()\n",
        "    return probs\n",
        "\n",
        "\n",
        "def simulate_strategy(pred_probs, actual_returns, tcost_bps=10):\n",
        "    tcost = tcost_bps / 10000\n",
        "    position = 0\n",
        "    daily_rets = []\n",
        "    for i in range(len(pred_probs)):\n",
        "        new_pos = 1 if pred_probs[i] > 0.5 else 0\n",
        "        cost = abs(new_pos - position) * tcost\n",
        "        ret = new_pos * actual_returns[i] - cost\n",
        "        daily_rets.append(ret)\n",
        "        position = new_pos\n",
        "    daily_rets = np.array(daily_rets)\n",
        "    sharpe = np.mean(daily_rets) / (np.std(daily_rets) + 1e-10) * np.sqrt(252)\n",
        "    cum_ret = np.prod(1 + daily_rets) - 1\n",
        "    return {'sharpe': sharpe, 'cum_return': cum_ret}\n",
        "\n",
        "print('Utilities defined')",
    ]),

    code([
        "X_seq, y_seq = create_sequences(X_all, y_all, SEQUENCE_LENGTH)\n",
        "seq_offset = SEQUENCE_LENGTH\n",
        "dates_seq = dates_all[seq_offset:]\n",
        "tickers_seq = tickers_all[seq_offset:]\n",
        "\n",
        "EPOCHS = 20\n",
        "BATCH_SIZE = 64\n",
        "INPUT_DIM = len(feature_cols)\n",
        "results_all = []\n",
        "weight_log = []  # v2: track selected weights per fold/seed\n",
        "n_total = len(X_seq)\n",
        "fold_size = n_total // (N_FOLDS + 1)\n",
        "val_frac = 0.1  # fraction of training data for weight selection\n",
        "\n",
        "print('='*60)\n",
        "print('ENSEMBLE DLinear+TFT Walk-Forward Validation (v2 Grid)')\n",
        "print('='*60)\n",
        "\n",
        "for SEED in SEEDS:\n",
        "    np.random.seed(SEED)\n",
        "    torch.manual_seed(SEED)\n",
        "\n",
        "    for fold in range(N_FOLDS):\n",
        "        train_end = fold_size * (fold + 1)\n",
        "        test_start = train_end\n",
        "        test_end = min(train_end + fold_size, n_total)\n",
        "        if test_end <= test_start:\n",
        "            continue\n",
        "\n",
        "        X_train_full, X_test = X_seq[:train_end], X_seq[test_start:test_end]\n",
        "        y_train_full, y_test = y_seq[:train_end], y_seq[test_start:test_end]\n",
        "\n",
        "        # v2: split train into train/val for weight selection\n",
        "        n_val = max(int(len(X_train_full) * val_frac), 1)\n",
        "        X_train = X_train_full[:-n_val]\n",
        "        X_val = X_train_full[-n_val:]\n",
        "        y_train = y_train_full[:-n_val]\n",
        "\n",
        "        scaler = StandardScaler()\n",
        "        X_train_s = scaler.fit_transform(\n",
        "            X_train.reshape(-1, INPUT_DIM)).reshape(X_train.shape)\n",
        "        X_val_s = scaler.transform(\n",
        "            X_val.reshape(-1, INPUT_DIM)).reshape(X_val.shape)\n",
        "        X_test_s = scaler.transform(\n",
        "            X_test.reshape(-1, INPUT_DIM)).reshape(X_test.shape)\n",
        "\n",
        "        # Train DLinear\n",
        "        np.random.seed(SEED)\n",
        "        torch.manual_seed(SEED)\n",
        "        dlinear = DLinearModel(SEQUENCE_LENGTH, INPUT_DIM)\n",
        "        dlinear = train_model(dlinear, X_train_s, y_train, EPOCHS, BATCH_SIZE, DEVICE)\n",
        "        probs_dl_val = predict_probs(dlinear, X_val_s, DEVICE)\n",
        "        probs_dl = predict_probs(dlinear, X_test_s, DEVICE)\n",
        "\n",
        "        # Train TFT-Lite\n",
        "        np.random.seed(SEED)\n",
        "        torch.manual_seed(SEED)\n",
        "        tft = TFTLiteModel(INPUT_DIM, d_model=32, n_heads=2)\n",
        "        tft = train_model(tft, X_train_s, y_train, EPOCHS, BATCH_SIZE, DEVICE)\n",
        "        probs_tft_val = predict_probs(tft, X_val_s, DEVICE)\n",
        "        probs_tft = predict_probs(tft, X_test_s, DEVICE)\n",
        "\n",
        "        # v2: Grid search for best weight on validation set\n",
        "        val_dates = dates_seq[train_end - n_val:train_end]\n",
        "        val_tickers = tickers_seq[train_end - n_val:train_end]\n",
        "        val_rets = np.array([\n",
        "            returns_series[t].get(d, 0.0) if t in returns_series else 0.0\n",
        "            for t, d in zip(val_tickers, val_dates)\n",
        "        ])\n",
        "        best_w, best_val_sharpe = 0.5, -999\n",
        "        for w in GRID_WEIGHTS:\n",
        "            ens_val = w * probs_dl_val + (1 - w) * probs_tft_val\n",
        "            res_val = simulate_strategy(ens_val, val_rets, TCOST_BPS)\n",
        "            if res_val['sharpe'] > best_val_sharpe:\n",
        "                best_val_sharpe = res_val['sharpe']\n",
        "                best_w = w\n",
        "\n",
        "        probs_ens = best_w * probs_dl + (1 - best_w) * probs_tft\n",
        "        weight_log.append({'seed': SEED, 'fold': fold, 'w_dlinear': best_w})\n",
        "\n",
        "        # Simulate\n",
        "        test_dates = dates_seq[test_start:test_end]\n",
        "        test_tickers = tickers_seq[test_start:test_end]\n",
        "        actual_rets = np.array([\n",
        "            returns_series[t].get(d, 0.0) if t in returns_series else 0.0\n",
        "            for t, d in zip(test_tickers, test_dates)\n",
        "        ])\n",
        "\n",
        "        for name, probs in [('DLinear', probs_dl), ('TFT-Lite', probs_tft),\n",
        "                             ('Ensemble', probs_ens)]:\n",
        "            res = simulate_strategy(probs, actual_rets, TCOST_BPS)\n",
        "            results_all.append({\n",
        "                'seed': SEED, 'fold': fold, 'model': name,\n",
        "                'sharpe': res['sharpe'], 'cum_return': res['cum_return'],\n",
        "            })\n",
        "\n",
        "        last3 = results_all[-3:]\n",
        "        print(f'Seed={SEED} Fold={fold} w={best_w:.1f}: ' +\n",
        "              ', '.join(f\"{r['model']} S={r['sharpe']:.2f}\" for r in last3))\n",
        "\n",
        "print(f'\\nTotal configs: {len(results_all)}')\n",
        "df_weights = pd.DataFrame(weight_log)\n",
        "print(f'\\nSelected weights (v2 grid search):')\n",
        "print(df_weights.groupby('w_dlinear').size().to_string())",
    ]),

    md([
        "## 4. Resultats et Verdict",
    ]),

    code([
        "df_results = pd.DataFrame(results_all)\n",
        "\n",
        "print('='*60)\n",
        "print('RESULTATS — Ensemble DLinear+TFT')\n",
        "print('='*60)\n",
        "\n",
        "seed_stats = df_results.groupby(['seed', 'model']).agg({\n",
        "    'sharpe': 'mean', 'cum_return': 'mean'\n",
        "}).round(4)\n",
        "print('\\nSharpe par seed et modele:')\n",
        "print(seed_stats['sharpe'].unstack().to_string())\n",
        "\n",
        "# BH benchmark\n",
        "bh_rets = np.mean([raw_returns[t] for t in prices.columns if t in raw_returns], axis=0)\n",
        "bh_sharpe = np.mean(bh_rets) / (np.std(bh_rets) + 1e-10) * np.sqrt(252)\n",
        "print(f'\\nBH Sharpe: {bh_sharpe:.2f}')\n",
        "\n",
        "model_sharpes = {}\n",
        "for model_name in df_results['model'].unique():\n",
        "    model_data = df_results[df_results['model'] == model_name]\n",
        "    seed_means = model_data.groupby('seed')['sharpe'].mean().values\n",
        "    model_sharpes[model_name] = seed_means\n",
        "\n",
        "print('\\n--- Verdicts ---')\n",
        "for model_name, sharpes in model_sharpes.items():\n",
        "    edges = sharpes - bh_sharpe\n",
        "    mean_edge = np.mean(edges)\n",
        "    std_edge = np.std(edges, ddof=1) if len(edges) > 1 else 1.0\n",
        "    z = mean_edge / std_edge if std_edge > 1e-10 else 0\n",
        "    verdict = 'BEATS' if z > 2 else ('NO BEATS' if z < -2 else 'INCONCLUSIVE')\n",
        "    print(f'{model_name}: Sharpe={np.mean(sharpes):.3f}, '\n",
        "          f'Edge={mean_edge:.3f} (std={std_edge:.3f}), z={z:.2f} -> {verdict}')\n",
        "\n",
        "# Ensemble vs best individual\n",
        "ens_sharpes = model_sharpes.get('Ensemble', np.array([0]))\n",
        "dl_sharpes = model_sharpes.get('DLinear', np.array([0]))\n",
        "ensemble_vs_dlinear = ens_sharpes - dl_sharpes\n",
        "mean_diff = np.mean(ensemble_vs_dlinear)\n",
        "std_diff = np.std(ensemble_vs_dlinear, ddof=1) if len(ensemble_vs_dlinear) > 1 else 1.0\n",
        "z_diff = mean_diff / std_diff if std_diff > 1e-10 else 0\n",
        "print(f'\\nEnsemble vs DLinear: diff={mean_diff:.3f}, z={z_diff:.2f}')\n",
        "print(f'  Ensemble BEATS DLinear: {\"YES\" if z_diff > 2 else \"NO\"}')",
    ]),

    md([
        "## 5. Visualisation",
    ]),

    code([
        "fig, axes = plt.subplots(1, 3, figsize=(18, 5))\n",
        "colors_map = {'DLinear': '#4CAF50', 'TFT-Lite': '#FF9800', 'Ensemble': '#9C27B0'}\n",
        "\n",
        "for model_name in df_results['model'].unique():\n",
        "    model_data = df_results[df_results['model'] == model_name]\n",
        "    seed_means = model_data.groupby('seed')['sharpe'].mean()\n",
        "    axes[0].plot(seed_means.index, seed_means.values, 'o-',\n",
        "                 label=model_name, color=colors_map.get(model_name, 'gray'))\n",
        "axes[0].axhline(y=bh_sharpe, color='navy', linestyle='--', label=f'BH={bh_sharpe:.2f}')\n",
        "axes[0].set_title('Sharpe par Seed')\n",
        "axes[0].set_ylabel('Sharpe')\n",
        "axes[0].legend()\n",
        "axes[0].grid(True, alpha=0.3)\n",
        "\n",
        "model_names = list(df_results['model'].unique())\n",
        "sharpes_by_model = [df_results[df_results['model'] == m]['sharpe'].values for m in model_names]\n",
        "bp = axes[1].boxplot(sharpes_by_model, labels=model_names, patch_artist=True)\n",
        "for patch, name in zip(bp['boxes'], model_names):\n",
        "    patch.set_facecolor(colors_map.get(name, 'lightgray'))\n",
        "axes[1].axhline(y=bh_sharpe, color='navy', linestyle='--', label=f'BH={bh_sharpe:.2f}')\n",
        "axes[1].set_title('Sharpe Distribution')\n",
        "axes[1].legend()\n",
        "axes[1].grid(True, alpha=0.3)\n",
        "\n",
        "for model_name in df_results['model'].unique():\n",
        "    model_data = df_results[df_results['model'] == model_name]\n",
        "    seed_cumrets = model_data.groupby('seed')['cum_return'].mean()\n",
        "    axes[2].bar([f'{model_name}\\nS{s}' for s in seed_cumrets.index],\n",
        "                seed_cumrets.values, alpha=0.7,\n",
        "                color=colors_map.get(model_name, 'gray'))\n",
        "axes[2].set_title('Cum Return par Seed')\n",
        "axes[2].grid(True, alpha=0.3)\n",
        "\n",
        "ens_mean = np.mean(model_sharpes.get('Ensemble', [0]))\n",
        "dl_mean = np.mean(model_sharpes.get('DLinear', [0]))\n",
        "best_label = 'Ensemble' if ens_mean > dl_mean else 'DLinear'\n",
        "plt.suptitle(f'Ensemble DLinear+TFT — Best: {best_label}', fontsize=14, fontweight='bold')\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print(f'\\nResume (v2 grid search):')\n",
        "print(f'  Ensemble weights selected by grid search per fold/seed')\n",
        "print(f'  DLinear Sharpe: {np.mean(model_sharpes.get(\"DLinear\", [0])):.3f}')\n",
        "print(f'  TFT-Lite Sharpe: {np.mean(model_sharpes.get(\"TFT-Lite\", [0])):.3f}')\n",
        "print(f'  Ensemble Sharpe: {ens_mean:.3f}')\n",
        "print(f'  BH Sharpe: {bh_sharpe:.3f}')",
    ]),
]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.10.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

output_path = "research.ipynb"
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f"Notebook generated: {output_path}")
print(f"Cells: {len(cells)} ({sum(1 for c in cells if c['cell_type']=='code')} code, {sum(1 for c in cells if c['cell_type']=='markdown')} markdown)")
