<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <NoWarn>IKVM0101</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="IKVM" Version="8.14.0" />
    <PackageReference Include="IKVM.MSBuild" Version="8.14.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Placeholder.cs" />
  </ItemGroup>
  <ItemGroup>
    <IkvmReference Include="..\libs\org.tweetyproject.tweety-bipolar-java8-shade.jar">
      <AssemblyName>org.tweetyproject.tweety-bipolar</AssemblyName>
      <AssemblyVersion>1.21.0.0</AssemblyVersion>
      <AssemblyFileVersion>1.21.0.0</AssemblyFileVersion>
    </IkvmReference>
  </ItemGroup>
</Project>
