"""Generate TFT-Crypto-Ranking research notebook.

Temporal Fusion Transformer (Lim et al., 2021) for cross-sectional crypto ranking.
Same data/features as Crypto-LSTM (#937), with TFT architecture added.
Walk-forward 5-fold x 4 seeds, 10bps transaction costs.
"""
import json
import uuid


def md(lines):
    return {"cell_type": "markdown", "id": uuid.uuid4().hex[:8], "metadata": {}, "source": lines}


def code(lines):
    return {
        "cell_type": "code",
        "execution_count": None,
        "id": uuid.uuid4().hex[:8],
        "metadata": {},
        "outputs": [],
        "source": lines,
    }


cells = [
    md([
        "# TFT Crypto Cross-Sectional Ranking - Research Notebook\n",
        "\n",
        "**Objectif** : Evaluer le Temporal Fusion Transformer (TFT, Lim et al., 2021) pour le\n",
        "ranking cross-sectionnel crypto (BTC vs ETH), en complement des modeles DLinear et LSTM\n",
        "deja evalues dans Crypto-LSTM-Prediction (#937).\n",
        "\n",
        "## Pourquoi TFT ?\n",
        "\n",
        "Le TFT combine :\n",
        "- **Variable Selection Networks (VSN)** : apprend quelles features importent\n",
        "- **Gated Residual Networks (GRN)** : skip connections non-lineaires avec gating\n",
        "- **LSTM encoder** : traitement sequentiel de l'historique\n",
        "- **Multi-head temporal attention** : dependances longues distance\n",
        "\n",
        "## Architectures comparees\n",
        "\n",
        "| Modele | Origine | Parametres | Approche |\n",
        "|--------|---------|------------|----------|\n",
        "| **DLinear** | AAAI 2023 | ~300 | Decomposition + lineaire |\n",
        "| **LSTM** | 2015 | ~77K | Recurrent |\n",
        "| **TFT** | Lim et al., 2021 | ~25K | VSN + GRN + LSTM + attention |\n",
        "\n",
        "## Validation\n",
        "\n",
        "- Walk-forward 5-fold (fenetre expandante)\n",
        "- 4 seeds (0, 7, 42, 99) pour robustesse statistique\n",
        "- Cout de transaction 10 bps (crypto)\n",
        "- Benchmarks : DLinear, LSTM, Buy-and-Hold BTC\n",
        "- Verdict honnete multi-seed : BEATS / NO BEATS / INCONCLUSIVE",
    ]),

    code([
        "!pip install yfinance matplotlib scikit-learn -q",
    ]),

    md(["## 1. Imports et Configuration"]),

    code([
        "import numpy as np\n",
        "import pandas as pd\n",
        "import matplotlib.pyplot as plt\n",
        "import warnings\n",
        "warnings.filterwarnings('ignore')\n",
        "\n",
        "import torch\n",
        "import torch.nn as nn\n",
        "import torch.nn.functional as F\n",
        "from torch.utils.data import DataLoader, TensorDataset\n",
        "from sklearn.preprocessing import StandardScaler\n",
        "\n",
        "import yfinance as yf\n",
        "\n",
        "SEEDS = [0, 7, 42, 99]\n",
        "SEQ_LEN = 60\n",
        "EPOCHS = 20\n",
        "BATCH_SIZE = 128\n",
        "N_FOLDS = 5\n",
        "TCOST_BPS = 10\n",
        "DEVICE = torch.device('cpu')\n",
        "\n",
        "print(f'PyTorch {torch.__version__} on {DEVICE}')\n",
        "print(f'Seeds: {SEEDS}, Folds: {N_FOLDS}, TCOST: {TCOST_BPS}bps')\n",
        "print(f'Seq length: {SEQ_LEN}, Epochs: {EPOCHS}')",
    ]),

    md([
        "## 2. Donnees Reelles Crypto (yfinance)\n",
        "\n",
        "Meme source que Crypto-LSTM (#937) : BTC-USD et ETH-USD quotidiennes.",
    ]),

    code([
        "print('Telechargement BTC-USD...')\n",
        "btc_raw = yf.download('BTC-USD', start='2015-01-01', end='2025-01-01', auto_adjust=True)\n",
        "print('Telechargement ETH-USD...')\n",
        "eth_raw = yf.download('ETH-USD', start='2015-01-01', end='2025-01-01', auto_adjust=True)\n",
        "\n",
        "if isinstance(btc_raw.columns, pd.MultiIndex):\n",
        "    btc_raw.columns = btc_raw.columns.get_level_values(0)\n",
        "if isinstance(eth_raw.columns, pd.MultiIndex):\n",
        "    eth_raw.columns = eth_raw.columns.get_level_values(0)\n",
        "\n",
        "common_idx = btc_raw.index.intersection(eth_raw.index)\n",
        "btc = btc_raw.loc[common_idx].copy()\n",
        "eth = eth_raw.loc[common_idx].copy()\n",
        "\n",
        "print(f'Periode commune: {common_idx[0].date()} a {common_idx[-1].date()}')\n",
        "print(f'BTC: {len(btc)} jours, ETH: {len(eth)} jours')\n",
        "print(f'BTC Close: ${float(btc[\"Close\"].iloc[-1]):,.0f}')\n",
        "print(f'ETH Close: ${float(eth[\"Close\"].iloc[-1]):,.0f}')",
    ]),

    md([
        "## 3. Feature Engineering Multi-Actifs\n",
        "\n",
        "26 features : 11 BTC + 11 ETH + 4 cross-asset (meme que #937).",
    ]),

    code([
        "def compute_asset_features(df):\n",
        "    close = df['Close'].values\n",
        "    high = df['High'].values\n",
        "    low = df['Low'].values\n",
        "    n = len(close)\n",
        "    features = np.full((n, 11), np.nan)\n",
        "    for i in range(50, n):\n",
        "        c = close[:i+1]\n",
        "        h = high[:i+1]\n",
        "        l = low[:i+1]\n",
        "        ret_5d = (c[-1] / c[-6] - 1) if i >= 5 else 0\n",
        "        ret_10d = (c[-1] / c[-11] - 1) if i >= 10 else 0\n",
        "        ret_20d = (c[-1] / c[-21] - 1) if i >= 20 else 0\n",
        "        rets = np.diff(c[-21:]) / c[-21:-1]\n",
        "        vol20 = np.std(rets) if len(rets) > 1 else 0\n",
        "        delta = np.diff(c[-15:])\n",
        "        gain = np.where(delta > 0, delta, 0)\n",
        "        loss = np.where(delta < 0, -delta, 0)\n",
        "        avg_gain = np.mean(gain[-14:])\n",
        "        avg_loss = np.mean(loss[-14:]) + 1e-10\n",
        "        rsi = 100 - 100 / (1 + avg_gain / avg_loss)\n",
        "        rsi_norm = (rsi - 50) / 50\n",
        "        sma20 = np.mean(c[-20:])\n",
        "        sma50 = np.mean(c[-50:])\n",
        "        ma_ratio = sma20 / sma50 if sma50 > 0 else 1\n",
        "        h20 = np.max(h[-20:])\n",
        "        l20 = np.min(l[-20:])\n",
        "        pos_range = (c[-1] - l20) / (h20 - l20 + 1e-10)\n",
        "        dist_high = (h20 - c[-1]) / (c[-1] + 1e-10)\n",
        "        dist_low = (c[-1] - l20) / (c[-1] + 1e-10)\n",
        "        tr = np.maximum(h[-14:] - l[-14:],\n",
        "                np.maximum(np.abs(h[-14:] - c[-15:-1]),\n",
        "                           np.abs(l[-14:] - c[-15:-1])))\n",
        "        atr = np.mean(tr) / (c[-1] + 1e-10)\n",
        "        bb_mean = np.mean(c[-20:])\n",
        "        bb_std = np.std(c[-20:]) + 1e-10\n",
        "        bb_pos = (c[-1] - bb_mean + 2*bb_std) / (4*bb_std)\n",
        "        features[i] = [ret_5d, ret_10d, ret_20d, vol20, rsi_norm, ma_ratio,\n",
        "                       pos_range, dist_high, dist_low, atr, bb_pos]\n",
        "    return features\n",
        "\n",
        "\n",
        "def compute_cross_features(btc_close, eth_close):\n",
        "    n = len(btc_close)\n",
        "    cross = np.full((n, 4), np.nan)\n",
        "    for i in range(50, n):\n",
        "        bc = btc_close[:i+1]\n",
        "        ec = eth_close[:i+1]\n",
        "        ratio = bc[-1] / (ec[-1] + 1e-10)\n",
        "        rel_mom5 = (bc[-1]/bc[-6] - 1) - (ec[-1]/ec[-6] - 1) if i >= 5 else 0\n",
        "        rel_mom20 = (bc[-1]/bc[-21] - 1) - (ec[-1]/ec[-21] - 1) if i >= 20 else 0\n",
        "        ret_b = np.diff(bc[-21:]) / bc[-21:-1]\n",
        "        ret_e = np.diff(ec[-21:]) / ec[-21:-1]\n",
        "        corr = np.corrcoef(ret_b, ret_e)[0, 1] if len(ret_b) > 2 else 0\n",
        "        cross[i] = [np.log(ratio + 1e-10), rel_mom5, rel_mom20, corr]\n",
        "    return cross\n",
        "\n",
        "\n",
        "btc_feat = compute_asset_features(btc)\n",
        "eth_feat = compute_asset_features(eth)\n",
        "cross_feat = compute_cross_features(btc['Close'].values, eth['Close'].values)\n",
        "\n",
        "all_features = np.concatenate([btc_feat, eth_feat, cross_feat], axis=1)\n",
        "valid_mask = ~np.any(np.isnan(all_features), axis=1)\n",
        "all_features = all_features[valid_mask]\n",
        "btc_close_clean = btc['Close'].values[valid_mask]\n",
        "eth_close_clean = eth['Close'].values[valid_mask]\n",
        "dates_clean = btc.index[valid_mask]\n",
        "\n",
        "print(f'Features: {all_features.shape[1]} (26 attendus)')\n",
        "print(f'Echantillons valides: {all_features.shape[0]}')\n",
        "print(f'NaN residuels: {np.isnan(all_features).sum()}')",
    ]),

    md([
        "## 4. Cible Ranking Cross-Sectionnel\n",
        "\n",
        "Predict si BTC surperforme ETH le jour suivant (classification binaire).",
    ]),

    code([
        "btc_returns = np.diff(btc_close_clean) / btc_close_clean[:-1]\n",
        "eth_returns = np.diff(eth_close_clean) / eth_close_clean[:-1]\n",
        "ranking_target = (btc_returns[1:] > eth_returns[1:]).astype(int)\n",
        "X_all = all_features[:-2]\n",
        "y_all = ranking_target\n",
        "dates_aligned = dates_clean[:-2]\n",
        "\n",
        "print(f'X: {X_all.shape}, y: {y_all.shape}')\n",
        "print(f'BTC > ETH: {y_all.sum()} ({y_all.mean()*100:.1f}%)')\n",
        "print(f'ETH > BTC: {(1-y_all).sum()} ({(1-y_all).mean()*100:.1f}%)')",
    ]),

    md([
        "## 5. Modeles : DLinear, LSTM, TFT\n",
        "\n",
        "TFT (Temporal Fusion Transformer) : VSN + GRN + LSTM encoder + temporal attention.",
    ]),

    code([
        "class SeriesDecomposition(nn.Module):\n",
        "    def __init__(self, kernel_size=25):\n",
        "        super().__init__()\n",
        "        self.moving_avg = nn.AvgPool1d(kernel_size=kernel_size, stride=1,\n",
        "                                        padding=kernel_size // 2)\n",
        "    def forward(self, x):\n",
        "        trend = self.moving_avg(x.transpose(1, 2)).transpose(1, 2)\n",
        "        trend = trend[:, :x.shape[1], :]\n",
        "        seasonal = x - trend\n",
        "        return seasonal, trend\n",
        "\n",
        "\n",
        "class DLinear(nn.Module):\n",
        "    def __init__(self, seq_len=60, enc_in=26):\n",
        "        super().__init__()\n",
        "        self.decomposition = SeriesDecomposition(kernel_size=25)\n",
        "        self.linear_seasonal = nn.Linear(seq_len, 1)\n",
        "        self.linear_trend = nn.Linear(seq_len, 1)\n",
        "    def forward(self, x):\n",
        "        seasonal, trend = self.decomposition(x)\n",
        "        seasonal_agg = seasonal.mean(dim=2)\n",
        "        trend_agg = trend.mean(dim=2)\n",
        "        return self.linear_seasonal(seasonal_agg) + self.linear_trend(trend_agg)\n",
        "\n",
        "\n",
        "class SimpleLSTM(nn.Module):\n",
        "    def __init__(self, input_size=26, hidden_size=64, num_layers=2):\n",
        "        super().__init__()\n",
        "        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True)\n",
        "        self.fc = nn.Linear(hidden_size, 1)\n",
        "    def forward(self, x):\n",
        "        out, _ = self.lstm(x)\n",
        "        return self.fc(out[:, -1, :])\n",
        "\n",
        "\n",
        "# --- TFT Components ---\n",
        "\n",
        "class GatedResidualNetwork(nn.Module):\n",
        "    \"\"\"GRN with skip connection (Lim et al., 2021).\"\"\"\n",
        "    def __init__(self, input_dim, hidden_dim, output_dim=None, dropout=0.1):\n",
        "        super().__init__()\n",
        "        output_dim = output_dim or input_dim\n",
        "        self.fc1 = nn.Linear(input_dim, hidden_dim)\n",
        "        self.fc2 = nn.Linear(hidden_dim, output_dim)\n",
        "        self.gate_fc = nn.Linear(hidden_dim, output_dim)\n",
        "        self.layer_norm = nn.LayerNorm(output_dim)\n",
        "        self.dropout = nn.Dropout(dropout)\n",
        "        self.skip = nn.Linear(input_dim, output_dim) if input_dim != output_dim else nn.Identity()\n",
        "\n",
        "    def forward(self, x):\n",
        "        residual = self.skip(x)\n",
        "        hidden = F.elu(self.fc1(x))\n",
        "        hidden = self.dropout(hidden)\n",
        "        gate = torch.sigmoid(self.gate_fc(hidden))\n",
        "        gated = gate * self.fc2(hidden)\n",
        "        return self.layer_norm(residual + gated)\n",
        "\n",
        "\n",
        "class VariableSelectionNetwork(nn.Module):\n",
        "    \"\"\"VSN: learns feature importance (Lim et al., 2021).\"\"\"\n",
        "    def __init__(self, n_vars, hidden_dim, dropout=0.1):\n",
        "        super().__init__()\n",
        "        self.grn = GatedResidualNetwork(n_vars, hidden_dim, n_vars, dropout)\n",
        "\n",
        "    def forward(self, x):\n",
        "        weights = F.softmax(self.grn(x), dim=-1)\n",
        "        return x * weights, weights\n",
        "\n",
        "\n",
        "class TFTClassifier(nn.Module):\n",
        "    \"\"\"TFT adapted for binary ranking classification.\"\"\"\n",
        "    def __init__(self, n_vars, seq_len, d_model=32, n_heads=2,\n",
        "                 lstm_layers=1, dropout=0.1):\n",
        "        super().__init__()\n",
        "        self.input_proj = nn.Linear(n_vars, d_model)\n",
        "        self.vsn = VariableSelectionNetwork(n_vars, d_model, dropout)\n",
        "        self.lstm = nn.LSTM(d_model, d_model, lstm_layers, batch_first=True,\n",
        "                           dropout=dropout if lstm_layers > 1 else 0.0)\n",
        "        self.attention = nn.MultiheadAttention(d_model, n_heads, dropout=dropout,\n",
        "                                              batch_first=True)\n",
        "        self.pos_encoding = nn.Parameter(torch.randn(1, seq_len, d_model) * 0.02)\n",
        "        self.post_attn_grn = GatedResidualNetwork(d_model, d_model * 2, d_model, dropout)\n",
        "        self.decoder_grn = GatedResidualNetwork(d_model, d_model * 2, d_model, dropout)\n",
        "        self.output_proj = nn.Linear(d_model, 1)\n",
        "        self.final_norm = nn.LayerNorm(d_model)\n",
        "\n",
        "    def forward(self, x):\n",
        "        B, T, N = x.shape\n",
        "        selected, attn_weights = self.vsn(x)\n",
        "        encoded = self.input_proj(selected)\n",
        "        lstm_out, _ = self.lstm(encoded)\n",
        "        lstm_out = lstm_out + self.pos_encoding[:, :T, :]\n",
        "        attn_out, _ = self.attention(lstm_out, lstm_out, lstm_out)\n",
        "        attn_out = self.post_attn_grn(attn_out + lstm_out)\n",
        "        last_hidden = attn_out[:, -1, :]\n",
        "        decoded = self.decoder_grn(last_hidden)\n",
        "        decoded = self.final_norm(decoded)\n",
        "        return self.output_proj(decoded)\n",
        "\n",
        "\n",
        "N_FEATURES = X_all.shape[1]\n",
        "dlinear = DLinear(seq_len=SEQ_LEN, enc_in=N_FEATURES)\n",
        "lstm = SimpleLSTM(input_size=N_FEATURES)\n",
        "tft = TFTClassifier(n_vars=N_FEATURES, seq_len=SEQ_LEN, d_model=32, n_heads=2)\n",
        "\n",
        "def count_params(m):\n",
        "    return sum(p.numel() for p in m.parameters() if p.requires_grad)\n",
        "\n",
        "print('=== Modeles ===')\n",
        "print(f'DLinear: {count_params(dlinear):,} params')\n",
        "print(f'LSTM:    {count_params(lstm):,} params')\n",
        "print(f'TFT:     {count_params(tft):,} params')",
    ]),

    md([
        "## 6. Walk-Forward Validation Multi-Seed\n",
        "\n",
        "Walk-forward 5-fold x 4 seeds x 3 modeles avec couts de transaction 10 bps.",
    ]),

    code([
        "def prepare_sequences(X, y, seq_len):\n",
        "    X_seq, y_seq = [], []\n",
        "    for i in range(seq_len, len(X)):\n",
        "        X_seq.append(X[i-seq_len:i])\n",
        "        y_seq.append(y[i])\n",
        "    return np.array(X_seq), np.array(y_seq)\n",
        "\n",
        "\n",
        "def train_model(model, X_train, y_train, epochs, batch_size, device, lr=0.001):\n",
        "    criterion = nn.BCEWithLogitsLoss()\n",
        "    optimizer = torch.optim.Adam(model.parameters(), lr=lr)\n",
        "    X_t = torch.FloatTensor(X_train).to(device)\n",
        "    y_t = torch.FloatTensor(y_train).unsqueeze(1).to(device)\n",
        "    dataset = TensorDataset(X_t, y_t)\n",
        "    loader = DataLoader(dataset, batch_size=batch_size, shuffle=True)\n",
        "    model.train()\n",
        "    for epoch in range(epochs):\n",
        "        for bx, by in loader:\n",
        "            optimizer.zero_grad()\n",
        "            pred = model(bx)\n",
        "            if pred.shape != by.shape:\n",
        "                by = by.view_as(pred)\n",
        "            loss = criterion(pred, by)\n",
        "            loss.backward()\n",
        "            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)\n",
        "            optimizer.step()\n",
        "    return model\n",
        "\n",
        "\n",
        "def predict_proba(model, X, device):\n",
        "    model.eval()\n",
        "    with torch.no_grad():\n",
        "        X_t = torch.FloatTensor(X).to(device)\n",
        "        logits = model(X_t).cpu().numpy().flatten()\n",
        "    return 1 / (1 + np.exp(-logits))\n",
        "\n",
        "\n",
        "def simulate_trading(prob_btc, btc_rets, eth_rets, tcost_bps=10):\n",
        "    tcost = tcost_bps / 10000\n",
        "    position = None\n",
        "    returns = []\n",
        "    for i in range(len(prob_btc)):\n",
        "        target = 'btc' if prob_btc[i] > 0.5 else 'eth'\n",
        "        cost = tcost if position is not None and position != target else 0\n",
        "        position = target\n",
        "        daily_ret = btc_rets[i] if target == 'btc' else eth_rets[i]\n",
        "        returns.append(daily_ret - cost)\n",
        "    returns = np.array(returns)\n",
        "    sharpe = np.mean(returns) / (np.std(returns) + 1e-10) * np.sqrt(252) if len(returns) > 1 else 0\n",
        "    return {'cum_return': float(np.sum(returns)), 'sharpe': sharpe, 'returns': returns}\n",
        "\n",
        "\n",
        "print('Fonctions de walk-forward definies.')",
    ]),

    code([
        "# Walk-Forward Validation Multi-Seed\n",
        "print('='*60)\n",
        "print('WALK-FORWARD: 5 folds x 4 seeds x 3 modeles (DLinear, LSTM, TFT)')\n",
        "print('='*60)\n",
        "\n",
        "n_total = len(X_all)\n",
        "fold_size = n_total // (N_FOLDS + 2)\n",
        "results_all = []\n",
        "\n",
        "for SEED in SEEDS:\n",
        "    np.random.seed(SEED)\n",
        "    torch.manual_seed(SEED)\n",
        "\n",
        "    for fold in range(N_FOLDS):\n",
        "        test_start = n_total - (N_FOLDS - fold) * fold_size\n",
        "        test_end = test_start + fold_size\n",
        "        if fold == N_FOLDS - 1:\n",
        "            test_end = n_total\n",
        "\n",
        "        train_X_raw = X_all[:test_start]\n",
        "        train_y_raw = y_all[:test_start]\n",
        "        test_X_raw = X_all[test_start:test_end]\n",
        "        test_y_raw = y_all[test_start:test_end]\n",
        "\n",
        "        scaler = StandardScaler()\n",
        "        train_X_flat = scaler.fit_transform(train_X_raw)\n",
        "        test_X_flat = scaler.transform(test_X_raw)\n",
        "\n",
        "        train_X, train_y = prepare_sequences(train_X_flat, train_y_raw, SEQ_LEN)\n",
        "        test_X, test_y = prepare_sequences(test_X_flat, test_y_raw, SEQ_LEN)\n",
        "\n",
        "        if len(train_X) < SEQ_LEN or len(test_X) < 10:\n",
        "            continue\n",
        "\n",
        "        ret_start = test_start + SEQ_LEN\n",
        "        ret_end = test_end\n",
        "        test_btc_rets = btc_returns[ret_start:ret_end]\n",
        "        test_eth_rets = eth_returns[ret_start:ret_end]\n",
        "\n",
        "        for model_name in ['DLinear', 'LSTM', 'TFT']:\n",
        "            torch.manual_seed(SEED)\n",
        "            np.random.seed(SEED)\n",
        "\n",
        "            if model_name == 'DLinear':\n",
        "                model = DLinear(seq_len=SEQ_LEN, enc_in=N_FEATURES).to(DEVICE)\n",
        "            elif model_name == 'LSTM':\n",
        "                model = SimpleLSTM(input_size=N_FEATURES).to(DEVICE)\n",
        "            else:\n",
        "                model = TFTClassifier(n_vars=N_FEATURES, seq_len=SEQ_LEN,\n",
        "                                      d_model=32, n_heads=2).to(DEVICE)\n",
        "\n",
        "            model = train_model(model, train_X, train_y, EPOCHS, BATCH_SIZE, DEVICE)\n",
        "            prob = predict_proba(model, test_X, DEVICE)\n",
        "\n",
        "            pred_binary = (prob > 0.5).astype(int)\n",
        "            accuracy = np.mean(pred_binary == test_y[:len(prob)])\n",
        "\n",
        "            min_len = min(len(prob), len(test_btc_rets), len(test_eth_rets))\n",
        "            trade_result = simulate_trading(\n",
        "                prob[:min_len], test_btc_rets[:min_len], test_eth_rets[:min_len], TCOST_BPS)\n",
        "\n",
        "            results_all.append({\n",
        "                'seed': SEED, 'fold': fold, 'model': model_name,\n",
        "                'accuracy': accuracy, **trade_result\n",
        "            })\n",
        "\n",
        "        if fold == 0:\n",
        "            print(f'Seed {SEED}: train {len(train_X)}, test {len(test_X)}')\n",
        "\n",
        "print(f'\\nResultats: {len(results_all)} configurations testees')",
    ]),

    md([
        "## 7. Resultats et Verdict Multi-Seed\n",
        "\n",
        "Edge = Sharpe modele - Sharpe BTC B&H. z-score = edge / std(edge) cross-seed.",
    ]),

    code([
        "df_results = pd.DataFrame(results_all)\n",
        "\n",
        "print('='*60)\n",
        "print('RESULTATS MULTI-SEED (5 folds x 4 seeds x 3 modeles)')\n",
        "print('='*60)\n",
        "\n",
        "bh_sharpe_all = np.mean(btc_returns) / (np.std(btc_returns) + 1e-10) * np.sqrt(252)\n",
        "print(f'BTC Buy-and-Hold Sharpe: {bh_sharpe_all:.3f}\\n')\n",
        "\n",
        "for model_name in ['DLinear', 'LSTM', 'TFT']:\n",
        "    sub = df_results[df_results['model'] == model_name]\n",
        "    sharpe_mean = sub['sharpe'].mean()\n",
        "    sharpe_std = sub['sharpe'].std()\n",
        "    acc_mean = sub['accuracy'].mean()\n",
        "    cum_mean = sub['cum_return'].mean()\n",
        "    edge = sharpe_mean - bh_sharpe_all\n",
        "\n",
        "    # z-score par seed (mean fold sharpe par seed)\n",
        "    seed_sharpes = sub.groupby('seed')['sharpe'].mean().values\n",
        "    edges = seed_sharpes - bh_sharpe_all\n",
        "    mean_edge = np.mean(edges)\n",
        "    std_edge = np.std(edges, ddof=1) if len(edges) > 1 else 1.0\n",
        "    z_score = mean_edge / std_edge if std_edge > 1e-10 else 0\n",
        "\n",
        "    print(f'--- {model_name} ({len(sub)} configs) ---')\n",
        "    print(f'  Sharpe: {sharpe_mean:.3f} +/- {sharpe_std:.3f}')\n",
        "    print(f'  Accuracy: {acc_mean:.3f}')\n",
        "    print(f'  Edge vs B&H: {edge:.3f} (z={z_score:.2f})')\n",
        "    print(f'  Seed range: [{seed_sharpes.min():.3f}, {seed_sharpes.max():.3f}]')\n",
        "\n",
        "# Verdict sur meilleur modele\n",
        "best_model = None\n",
        "best_sharpe = -999\n",
        "for mn in ['DLinear', 'LSTM', 'TFT']:\n",
        "    s = df_results[df_results['model'] == mn]['sharpe'].mean()\n",
        "    if s > best_sharpe:\n",
        "        best_sharpe = s\n",
        "        best_model = mn\n",
        "\n",
        "best_sub = df_results[df_results['model'] == best_model]\n",
        "best_seed_sharpes = best_sub.groupby('seed')['sharpe'].mean().values\n",
        "best_edges = best_seed_sharpes - bh_sharpe_all\n",
        "best_mean_edge = np.mean(best_edges)\n",
        "best_std_edge = np.std(best_edges, ddof=1)\n",
        "best_z = best_mean_edge / best_std_edge if best_std_edge > 1e-10 else 0\n",
        "\n",
        "if best_z > 2:\n",
        "    verdict = 'BEATS'\n",
        "elif best_z < -2:\n",
        "    verdict = 'NO BEATS'\n",
        "else:\n",
        "    verdict = 'INCONCLUSIVE'\n",
        "\n",
        "print(f'\\n=== VERDICT ===')\n",
        "print(f'Meilleur modele: {best_model} (Sharpe {best_sharpe:.3f})')\n",
        "print(f'BTC B&H Sharpe: {bh_sharpe_all:.3f}')\n",
        "print(f'Edge: {best_mean_edge:.3f}, z: {best_z:.2f}')\n",
        "print(f'Verdict: {verdict}')",
    ]),

    md(["## 8. Visualisation"]),

    code([
        "fig, axes = plt.subplots(1, 3, figsize=(18, 5))\n",
        "\n",
        "colors_map = {'DLinear': '#3498db', 'LSTM': '#e74c3c', 'TFT': '#2ecc71'}\n",
        "\n",
        "# 1. Sharpe par modele/seed\n",
        "for model_name in ['DLinear', 'LSTM', 'TFT']:\n",
        "    sub = df_results[df_results['model'] == model_name]\n",
        "    seed_stats = sub.groupby('seed')['sharpe'].mean()\n",
        "    axes[0].bar([f'{model_name[:3]}-S{s}' for s in seed_stats.index],\n",
        "                seed_stats.values, color=colors_map[model_name], alpha=0.7, label=model_name)\n",
        "axes[0].axhline(y=bh_sharpe_all, color='navy', linestyle='--', label=f'BTC B&H={bh_sharpe_all:.2f}')\n",
        "axes[0].set_title('Sharpe par Modele et Seed')\n",
        "axes[0].tick_params(axis='x', rotation=45, labelsize=7)\n",
        "axes[0].legend(fontsize=7)\n",
        "axes[0].grid(True, alpha=0.3)\n",
        "\n",
        "# 2. Accuracy par modele\n",
        "for model_name in ['DLinear', 'LSTM', 'TFT']:\n",
        "    sub = df_results[df_results['model'] == model_name]\n",
        "    seed_acc = sub.groupby('seed')['accuracy'].mean()\n",
        "    axes[1].plot(seed_acc.index.astype(str), seed_acc.values, 'o-',\n",
        "                 color=colors_map[model_name], label=model_name)\n",
        "axes[1].axhline(y=0.5, color='gray', linestyle='--', label='Random 50%')\n",
        "axes[1].set_title('Accuracy Ranking par Seed')\n",
        "axes[1].legend(fontsize=8)\n",
        "axes[1].grid(True, alpha=0.3)\n",
        "\n",
        "# 3. Equity curves\n",
        "for model_name in ['DLinear', 'LSTM', 'TFT']:\n",
        "    sub = df_results[df_results['model'] == model_name]\n",
        "    all_rets = np.concatenate(sub['returns'].values)\n",
        "    equity = np.cumprod(1 + all_rets)\n",
        "    axes[2].plot(equity, color=colors_map[model_name], label=model_name, linewidth=2)\n",
        "bh_equity = np.cumprod(1 + btc_returns)\n",
        "axes[2].plot(bh_equity[:len(equity)], 'k--', label='B&H BTC', alpha=0.5)\n",
        "axes[2].set_title('Equity Curves')\n",
        "axes[2].legend(fontsize=8)\n",
        "axes[2].grid(True, alpha=0.3)\n",
        "\n",
        "plt.suptitle(f'TFT Crypto Ranking - Verdict: {verdict}', fontweight='bold')\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print(f'\\nResume:')\n",
        "print(f'  Modeles: DLinear + LSTM + TFT')\n",
        "print(f'  Data: BTC-USD + ETH-USD (yfinance)')\n",
        "print(f'  Features: {X_all.shape[1]} (multi-asset)')\n",
        "print(f'  Validation: {N_FOLDS}-fold WF x {len(SEEDS)} seeds')\n",
        "print(f'  Transaction costs: {TCOST_BPS} bps')\n",
        "print(f'  VERDICT: {verdict} (z={best_z:.2f})')",
    ]),

    md([
        "## 9. Conclusion\n",
        "\n",
        "### Comparaison avec Crypto-LSTM (#937)\n",
        "\n",
        "Ce notebook etend l'evaluation de #937 en ajoutant le TFT (Temporal Fusion Transformer)\n",
        "aux modeles DLinear et LSTM. Le TFT apporte :\n",
        "- Variable Selection Networks pour l'interpretation des features\n",
        "- Temporal attention pour les dependances longues distance\n",
        "- Gated Residual Networks pour des skip connections adaptees\n",
        "\n",
        "### Recommandation\n",
        "\n",
        "Le TFT etant plus complexe que DLinear, il doit demontrer un edge significatif\n",
        "(z > 2 cross-seed) pour justifier son utilisation en production.",
    ]),
]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {
            "codemirror_mode": {"name": "ipython", "version": 3},
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbformat_minor": 2,
            "pygments_lexer": "ipython3",
            "version": "3.13.0",
        },
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

output_path = "research.ipynb"
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f"Notebook generated: {output_path}")
print(f"Cells: {len(cells)} ({sum(1 for c in cells if c['cell_type']=='code')} code, {sum(1 for c in cells if c['cell_type']=='markdown')} markdown)")
