"""Generate GraphSAGE-MultiAsset-Ranking research notebook.

GraphSAGE (Hamilton et al., 2017) for cross-asset direction prediction.
Builds correlation graph across 8 diverse-sector stocks, applies 2-layer
GraphSAGE with mean aggregation. Walk-forward 5-fold x 4 seeds, 10bps tcosts.

No FAANG/Mag7 in training set (per PR review discipline).
"""
import json
import uuid


def md(lines):
    return {"cell_type": "markdown", "id": uuid.uuid4().hex[:8], "metadata": {}, "source": lines}


def code(lines):
    return {
        "cell_type": "code",
        "execution_count": None,
        "id": uuid.uuid4().hex[:8],
        "metadata": {},
        "outputs": [],
        "source": lines,
    }


cells = [
    md([
        "# GraphSAGE Multi-Asset Direction Prediction - Research Notebook\n",
        "\n",
        "**Objectif** : Evaluer GraphSAGE (Hamilton et al., 2017) pour la prediction de\n",
        "direction cross-asset sur 8 actions de secteurs diversifies.\n",
        "\n",
        "## Pourquoi GraphSAGE ?\n",
        "\n",
        "GraphSAGE apprend des representations de noeuds en agregeant les features\n",
        "des voisins dans un graphe. Pour le cross-asset :\n",
        "- **Graphe de correlation** : aretes entre actions correlees (|corr| > seuil)\n",
        "- **Message passing** : chaque action informe ses voisins de son etat\n",
        "- **Representation contextuelle** : capture les dependances inter-secteurs\n",
        "\n",
        "## Modeles compares\n",
        "\n",
        "| Modele | Approche |\n",
        "|--------|----------|\n",
        "| **MLP baseline** | Prediction isolee par action, pas de graphe |\n",
        "| **GraphSAGE-Mean** | Aggregation moyenne des voisins, 2 couches |\n",
        "\n",
        "## Validation\n",
        "\n",
        "- Walk-forward 5-fold x 4 seeds (0, 7, 42, 99)\n",
        "- Couts de transaction : 10bps par changement de position\n",
        "- Benchmark : Buy-and-Hold equity-weighted\n",
        "- **Verdict honnete** : BEATS / NO BEATS / INCONCLUSIVE (edge >= 2sigma)\n",
    ]),

    code([
        "import numpy as np\n",
        "import pandas as pd\n",
        "import matplotlib.pyplot as plt\n",
        "import torch\n",
        "import torch.nn as nn\n",
        "import torch.nn.functional as F\n",
        "import yfinance as yf\n",
        "import warnings\n",
        "warnings.filterwarnings('ignore')\n",
        "\n",
        "SEEDS = [0, 7, 42, 99]\n",
        "N_FOLDS = 5\n",
        "TCOST_BPS = 10\n",
        "SEQ_LEN = 21\n",
        "EPOCHS = 20\n",
        "BATCH_SIZE = 32\n",
        "HIDDEN_DIM = 32\n",
        "CORR_THRESHOLD = 0.5\n",
        "FEATURE_WINDOWS = [2, 5, 10, 21]\n",
        "\n",
        "# Diverse sectors - NO FAANG/Mag7 per PR review discipline\n",
        "TICKERS = ['JPM', 'JNJ', 'XOM', 'PG', 'UNP', 'V', 'HD', 'BA']\n",
        "SECTOR_MAP = {\n",
        "    'JPM': 'Financials', 'JNJ': 'Healthcare', 'XOM': 'Energy',\n",
        "    'PG': 'Staples', 'UNP': 'Industrials', 'V': 'Fintech',\n",
        "    'HD': 'Discretionary', 'BA': 'Aerospace'\n",
        "}\n",
        "\n",
        "DEVICE = torch.device('cpu')\n",
        "np.random.seed(42)\n",
        "torch.manual_seed(42)\n",
        "print(f'Setup OK - {len(TICKERS)} stocks, {len(SEEDS)} seeds, {N_FOLDS} folds')\n",
        "print(f'GraphSAGE hidden={HIDDEN_DIM}, corr_threshold={CORR_THRESHOLD}')",
    ]),

    md([
        "## 1. Telechargement des Donnees\n",
        "\n",
        "8 actions de secteurs diversifies (2015-2025).",
    ]),

    code([
        "print('Telechargement des donnees...')\n",
        "raw = yf.download(TICKERS, start='2014-01-01', end='2025-01-01', auto_adjust=True)\n",
        "\n",
        "if isinstance(raw.columns, pd.MultiIndex):\n",
        "    prices = raw['Close'].copy()\n",
        "else:\n",
        "    prices = raw[['Close']].copy() if 'Close' in raw.columns else raw.copy()\n",
        "\n",
        "prices = prices.dropna(axis=1, thresh=len(prices) * 0.9)\n",
        "prices = prices.dropna()\n",
        "\n",
        "valid_tickers = [t for t in TICKERS if t in prices.columns]\n",
        "prices = prices[valid_tickers]\n",
        "\n",
        "print(f'Periode: {prices.index[0].date()} a {prices.index[-1].date()}')\n",
        "print(f'Actions: {list(prices.columns)}')\n",
        "print(f'Jours: {len(prices)}')\n",
        "for t in prices.columns:\n",
        "    print(f'  {t} ({SECTOR_MAP.get(t, \"?\")}): ${float(prices[t].iloc[-1]):,.2f}')",
    ]),

    md([
        "## 2. Construction du Graphe de Correlation\n",
        "\n",
        "Matrice d'adjacence basee sur la correlation des rendements.\n",
        "Arete entre deux actions si |corr(returns_i, returns_j)| > seuil.",
    ]),

    code([
        "# Rendements quotidiens\n",
        "returns = prices.pct_change().dropna()\n",
        "\n",
        "# Matrice de correlation\n",
        "corr_matrix = returns.corr()\n",
        "\n",
        "# Matrice d'adjacence (seuil sur |correlation|)\n",
        "n_assets = len(prices.columns)\n",
        "adj_matrix = (corr_matrix.abs() > CORR_THRESHOLD).astype(float).values.copy()\n",
        "np.fill_diagonal(adj_matrix, 0)  # pas d'auto-boucle dans le seuil\n",
        "\n",
        "# Ajouter auto-boucles pour GraphSAGE\n",
        "adj_with_self = adj_matrix + np.eye(n_assets)\n",
        "\n",
        "# Degré normalise pour mean aggregation\n",
        "degree = adj_with_self.sum(axis=1, keepdims=True)\n",
        "degree_inv = np.where(degree > 0, 1.0 / degree, 0)\n",
        "norm_adj = adj_with_self * degree_inv\n",
        "\n",
        "print(f'Matrice de correlation:')\n",
        "print(corr_matrix.round(3).to_string())\n",
        "print(f'\\nAretes (|corr| > {CORR_THRESHOLD}):')\n",
        "for i in range(n_assets):\n",
        "    for j in range(i + 1, n_assets):\n",
        "        if adj_matrix[i, j] > 0:\n",
        "            print(f'  {prices.columns[i]} -- {prices.columns[j]} (corr={corr_matrix.iloc[i,j]:.3f})')\n",
        "print(f'\\nDensite du graphe: {adj_matrix.sum() / (n_assets * (n_assets - 1)):.2%}')",
    ]),

    md([
        "## 3. Feature Engineering\n",
        "\n",
        "Features temporelles par action : rendements 2j, 5j, 10j, 21j.\n",
        "Cible : direction du rendement suivant.\n",
        "Les features sont construites par date, toutes actions confondues.",
    ]),

    code([
        "# Construction des features par (date, action)\n",
        "all_data = []\n",
        "\n",
        "for ticker in prices.columns:\n",
        "    close = prices[ticker].values\n",
        "    dates = prices.index\n",
        "    n = len(close)\n",
        "    \n",
        "    feats = np.full((n, len(FEATURE_WINDOWS)), np.nan)\n",
        "    for j, w in enumerate(FEATURE_WINDOWS):\n",
        "        feats[w:, j] = close[w:] / close[:-w] - 1\n",
        "    \n",
        "    target = np.full(n, np.nan)\n",
        "    target[:-1] = (close[1:] > close[:-1]).astype(int)\n",
        "    \n",
        "    ret = np.full(n, np.nan)\n",
        "    ret[1:] = close[1:] / close[:-1] - 1\n",
        "    \n",
        "    valid = ~np.any(np.isnan(feats), axis=1) & ~np.isnan(target) & ~np.isnan(ret)\n",
        "    \n",
        "    for idx in np.where(valid)[0]:\n",
        "        all_data.append({\n",
        "            'date': dates[idx],\n",
        "            'ticker': ticker,\n",
        "            'ticker_idx': prices.columns.get_loc(ticker),\n",
        "            'features': feats[idx],\n",
        "            'target': int(target[idx]),\n",
        "            'return': ret[idx]\n",
        "        })\n",
        "\n",
        "print(f'Echantillons totaux: {len(all_data)}')\n",
        "print(f'Features par echantillon: {len(FEATURE_WINDOWS)}')\n",
        "print(f'Taux de hausse: {np.mean([d[\"target\"] for d in all_data]):.3f}')",
    ]),

    md([
        "## 4. Modeles : MLP Baseline et GraphSAGE\n",
        "\n",
        "Deux architectures comparees :\n",
        "- **MLP** : prediction isolee par action (pas de graphe)\n",
        "- **GraphSAGE-Mean** : agregation moyenne des voisins dans le graphe de correlation",
    ]),

    code([
        "class MLPBaseline(nn.Module):\n",
        "    def __init__(self, input_dim, hidden_dim):\n",
        "        super().__init__()\n",
        "        self.net = nn.Sequential(\n",
        "            nn.Linear(input_dim, hidden_dim),\n",
        "            nn.ReLU(),\n",
        "            nn.Dropout(0.1),\n",
        "            nn.Linear(hidden_dim, hidden_dim // 2),\n",
        "            nn.ReLU(),\n",
        "            nn.Linear(hidden_dim // 2, 1)\n",
        "        )\n",
        "    \n",
        "    def forward(self, x, ticker_idx=None):\n",
        "        return self.net(x).squeeze(-1)\n",
        "\n",
        "\n",
        "class GraphSAGEModel(nn.Module):\n",
        "    \"\"\"GraphSAGE avec agregation au niveau des actifs.\n",
        "    \n",
        "    Pour chaque batch :\n",
        "    1. Project features -> hidden dim\n",
        "    2. Aggregate hidden states per asset -> [n_assets, hidden]\n",
        "    3. Graph convolution: h' = W_self @ h + W_neigh @ (A_norm @ h)\n",
        "    4. Map contextualized asset reps back to samples\n",
        "    5. Classify\n",
        "    \"\"\"\n",
        "    def __init__(self, input_dim, hidden_dim, n_assets, norm_adj):\n",
        "        super().__init__()\n",
        "        self.n_assets = n_assets\n",
        "        self.hidden_dim = hidden_dim\n",
        "        self.input_proj = nn.Linear(input_dim, hidden_dim)\n",
        "        self.W_self = nn.Linear(hidden_dim, hidden_dim, bias=True)\n",
        "        self.W_neigh = nn.Linear(hidden_dim, hidden_dim, bias=False)\n",
        "        self.classifier = nn.Sequential(\n",
        "            nn.ReLU(),\n",
        "            nn.Linear(hidden_dim * 2, hidden_dim // 2),\n",
        "            nn.ReLU(),\n",
        "            nn.Linear(hidden_dim // 2, 1)\n",
        "        )\n",
        "        self.register_buffer('norm_adj', torch.FloatTensor(norm_adj))\n",
        "    \n",
        "    def forward(self, x, ticker_idx):\n",
        "        h = F.relu(self.input_proj(x))  # [batch, hidden]\n",
        "        \n",
        "        # Aggregate per asset: [n_assets, hidden]\n",
        "        asset_h = torch.zeros(self.n_assets, self.hidden_dim).to(x.device)\n",
        "        asset_count = torch.zeros(self.n_assets, 1).to(x.device)\n",
        "        idx_exp = ticker_idx.unsqueeze(1).expand_as(h)\n",
        "        asset_h.scatter_add_(0, idx_exp, h)\n",
        "        asset_count.scatter_add_(0, ticker_idx.unsqueeze(1),\n",
        "                                  torch.ones(h.size(0), 1).to(x.device))\n",
        "        asset_h = asset_h / (asset_count + 1e-8)  # mean per asset\n",
        "        \n",
        "        # Graph convolution: aggregate neighbor features\n",
        "        neigh_agg = torch.matmul(self.norm_adj, asset_h)  # [n_assets, hidden]\n",
        "        contextualized = self.W_self(asset_h) + self.W_neigh(neigh_agg)\n",
        "        \n",
        "        # Map back to samples: concat [local_h, context_h]\n",
        "        sample_context = contextualized[ticker_idx]  # [batch, hidden]\n",
        "        combined = torch.cat([h, sample_context], dim=1)  # [batch, 2*hidden]\n",
        "        return self.classifier(combined).squeeze(-1)\n",
        "\n",
        "\n",
        "def train_model(model, X, y, ticker_idx, epochs, batch_size, device, lr=0.001):\n",
        "    model.train()\n",
        "    optimizer = torch.optim.Adam(model.parameters(), lr=lr)\n",
        "    criterion = nn.BCEWithLogitsLoss()\n",
        "    X_t = torch.FloatTensor(X).to(device)\n",
        "    y_t = torch.FloatTensor(y).to(device)\n",
        "    idx_t = torch.LongTensor(ticker_idx).to(device)\n",
        "    \n",
        "    for epoch in range(epochs):\n",
        "        indices = torch.randperm(len(X_t))\n",
        "        for start in range(0, len(X_t), batch_size):\n",
        "            batch_idx = indices[start:start + batch_size]\n",
        "            batch_X = X_t[batch_idx]\n",
        "            batch_y = y_t[batch_idx]\n",
        "            batch_tidx = idx_t[batch_idx]\n",
        "            optimizer.zero_grad()\n",
        "            pred = model(batch_X, batch_tidx)\n",
        "            loss = criterion(pred, batch_y)\n",
        "            loss.backward()\n",
        "            optimizer.step()\n",
        "    return model\n",
        "\n",
        "\n",
        "# Test dimensions\n",
        "n_features = len(FEATURE_WINDOWS)\n",
        "mlp_test = MLPBaseline(n_features, HIDDEN_DIM)\n",
        "gs_test = GraphSAGEModel(n_features, HIDDEN_DIM, n_assets, norm_adj)\n",
        "print(f'MLP params: {sum(p.numel() for p in mlp_test.parameters()):,}')\n",
        "print(f'GraphSAGE params: {sum(p.numel() for p in gs_test.parameters()):,}')\n",
        "print(f'Input features: {n_features}')\n",
        "print(f'Assets in graph: {n_assets}')",
    ]),

    md([
        "## 5. Walk-Forward Validation Multi-Seed\n",
        "\n",
        "Walk-forward 5-fold avec fenetre expansive.\n",
        "Strategie : investir dans les 3 actions avec la plus forte probabilite de hausse.\n",
        "Couts de transaction : 10bps par changement de position.",
    ]),

    code([
        "def simulate_portfolio(preds, returns, tickers, dates, n_top=3, tcost_bps=10):\n",
        "    tcost = tcost_bps / 10000\n",
        "    df = pd.DataFrame({\n",
        "        'prob': preds, 'ret': returns, 'ticker': tickers, 'date': dates\n",
        "    })\n",
        "    unique_dates = sorted(df['date'].unique())\n",
        "    position = set()\n",
        "    daily_returns = []\n",
        "    \n",
        "    for d in unique_dates:\n",
        "        day_data = df[df['date'] == d]\n",
        "        top_n = day_data.nlargest(n_top, 'prob')['ticker'].tolist()\n",
        "        new_pos = set(top_n)\n",
        "        n_changes = len(position.symmetric_difference(new_pos))\n",
        "        cost = n_changes * tcost / 2\n",
        "        day_rets = day_data[day_data['ticker'].isin(top_n)]['ret'].values\n",
        "        port_ret = np.mean(day_rets) - cost if len(day_rets) > 0 else 0\n",
        "        daily_returns.append(port_ret)\n",
        "        position = new_pos\n",
        "    \n",
        "    daily_returns = np.array(daily_returns)\n",
        "    sharpe = np.mean(daily_returns) / (np.std(daily_returns) + 1e-10) * np.sqrt(252)\n",
        "    return {'sharpe': sharpe, 'cum_return': np.sum(daily_returns), 'n_days': len(daily_returns)}",
    ]),

    code([
        "print('=' * 60)\n",
        "print('WALK-FORWARD VALIDATION - GraphSAGE Multi-Asset')\n",
        "print('=' * 60)\n",
        "\n",
        "# Preparer les donnees en arrays\n",
        "all_features = np.array([d['features'] for d in all_data])\n",
        "all_targets = np.array([d['target'] for d in all_data])\n",
        "all_returns = np.array([d['return'] for d in all_data])\n",
        "all_ticker_idx = np.array([d['ticker_idx'] for d in all_data])\n",
        "all_dates_arr = np.array([d['date'] for d in all_data])\n",
        "all_tickers_arr = np.array([d['ticker'] for d in all_data])\n",
        "\n",
        "n_total = len(all_features)\n",
        "fold_size = n_total // (N_FOLDS + 1)\n",
        "\n",
        "results_all = []\n",
        "\n",
        "for SEED in SEEDS:\n",
        "    np.random.seed(SEED)\n",
        "    torch.manual_seed(SEED)\n",
        "    \n",
        "    for fold in range(N_FOLDS):\n",
        "        train_end = fold_size * (fold + 1)\n",
        "        test_start = train_end\n",
        "        test_end = min(train_end + fold_size, n_total)\n",
        "        if test_end <= test_start:\n",
        "            continue\n",
        "        \n",
        "        X_train = all_features[:train_end]\n",
        "        y_train = all_targets[:train_end]\n",
        "        X_test = all_features[test_start:test_end]\n",
        "        y_test = all_targets[test_start:test_end]\n",
        "        \n",
        "        # Standardisation\n",
        "        mean = X_train.mean(axis=0)\n",
        "        std = X_train.std(axis=0) + 1e-8\n",
        "        X_train_s = (X_train - mean) / std\n",
        "        X_test_s = (X_test - mean) / std\n",
        "        \n",
        "        for model_name in ['MLP', 'GraphSAGE']:\n",
        "            if model_name == 'MLP':\n",
        "                model = MLPBaseline(n_features, HIDDEN_DIM).to(DEVICE)\n",
        "            else:\n",
        "                model = GraphSAGEModel(n_features, HIDDEN_DIM, n_assets, norm_adj).to(DEVICE)\n",
        "            \n",
        "            model = train_model(model, X_train_s, y_train, all_ticker_idx[:train_end],\n",
        "                                EPOCHS, BATCH_SIZE, DEVICE)\n",
        "            model.eval()\n",
        "            with torch.no_grad():\n",
        "                X_test_t = torch.FloatTensor(X_test_s).to(DEVICE)\n",
        "                tidx_test = torch.LongTensor(all_ticker_idx[test_start:test_end]).to(DEVICE)\n",
        "                logits = model(X_test_t, tidx_test).cpu().numpy()\n",
        "            prob_up = 1.0 / (1.0 + np.exp(-logits))\n",
        "            pred_binary = (prob_up > 0.5).astype(int)\n",
        "            accuracy = (pred_binary == y_test).mean()\n",
        "            \n",
        "            test_dates = all_dates_arr[test_start:test_end]\n",
        "            test_tickers = all_tickers_arr[test_start:test_end]\n",
        "            test_rets = all_returns[test_start:test_end]\n",
        "            \n",
        "            trade_result = simulate_portfolio(prob_up, test_rets, test_tickers, test_dates,\n",
        "                                              n_top=3, tcost_bps=TCOST_BPS)\n",
        "            \n",
        "            results_all.append({\n",
        "                'seed': SEED, 'fold': fold, 'model': model_name,\n",
        "                'accuracy': accuracy,\n",
        "                'sharpe': trade_result['sharpe'],\n",
        "                'cum_return': trade_result['cum_return']\n",
        "            })\n",
        "            \n",
        "            print(f'Seed={SEED}, Fold={fold}, {model_name}: '\n",
        "                  f'Acc={accuracy:.3f}, Sharpe={trade_result[\"sharpe\"]:.2f}')\n",
        "\n",
        "print(f'\\nTotal configs: {len(results_all)}')",
    ]),

    md([
        "## 6. Resultats et Verdict Multi-Seed\n",
        "\n",
        "Agreger les resultats walk-forward et calculer le verdict honnete.\n",
        "- Edge = Sharpe modele - Sharpe benchmark\n",
        "- z-score = edge / std(edge) cross-seed\n",
        "- Verdict : BEATS si z > 2, NO BEATS si z < -2, INCONCLUSIVE sinon",
    ]),

    code([
        "df_results = pd.DataFrame(results_all)\n",
        "\n",
        "print('=' * 60)\n",
        "print('RESULTATS MULTI-SEED - GraphSAGE Multi-Asset')\n",
        "print('=' * 60)\n",
        "\n",
        "# Benchmark: Buy-and-Hold equity-weighted\n",
        "bh_rets = returns.mean(axis=1).values\n",
        "bh_sharpe = np.mean(bh_rets) / (np.std(bh_rets) + 1e-10) * np.sqrt(252)\n",
        "print(f'Benchmark BH Sharpe: {bh_sharpe:.2f}')\n",
        "\n",
        "best_z = -999\n",
        "best_model = ''\n",
        "best_sharpe = -999\n",
        "\n",
        "for model_name in ['MLP', 'GraphSAGE']:\n",
        "    model_data = df_results[df_results['model'] == model_name]\n",
        "    seed_stats = model_data.groupby('seed').agg({'sharpe': 'mean'}).reset_index()\n",
        "    \n",
        "    print(f'\\n--- {model_name} ({len(model_data)} configs) ---')\n",
        "    print(f'Sharpe: {seed_stats[\"sharpe\"].mean():.3f} +/- {seed_stats[\"sharpe\"].std():.3f}')\n",
        "    print(f'Accuracy: {model_data[\"accuracy\"].mean():.3f}')\n",
        "    \n",
        "    edges = seed_stats['sharpe'].values - bh_sharpe\n",
        "    mean_edge = np.mean(edges)\n",
        "    std_edge = np.std(edges, ddof=1) if len(edges) > 1 else 1.0\n",
        "    z = mean_edge / std_edge if std_edge > 1e-10 else 0\n",
        "    print(f'Edge moyen vs BH: {mean_edge:.3f} (z={z:.2f})')\n",
        "    \n",
        "    if z > best_z:\n",
        "        best_z = z\n",
        "        best_model = model_name\n",
        "        best_sharpe = seed_stats['sharpe'].mean()\n",
        "\n",
        "# Verdict\n",
        "if best_z > 2:\n",
        "    verdict = 'BEATS'\n",
        "elif best_z < -2:\n",
        "    verdict = 'NO BEATS'\n",
        "else:\n",
        "    verdict = 'INCONCLUSIVE'\n",
        "\n",
        "print(f'\\n=== VERDICT ===')\n",
        "print(f'Meilleur modele: {best_model} (Sharpe {best_sharpe:.3f})')\n",
        "print(f'BH Sharpe: {bh_sharpe:.2f}')\n",
        "print(f'z-score: {best_z:.2f}')\n",
        "print(f'VERDICT: {verdict}')",
    ]),

    md([
        "## 7. Visualisation",
    ]),

    code([
        "fig, axes = plt.subplots(1, 3, figsize=(18, 5))\n",
        "\n",
        "model_colors = {'MLP': '#3498db', 'GraphSAGE': '#2ecc71'}\n",
        "\n",
        "# 1. Sharpe par modele et seed\n",
        "for i, model_name in enumerate(['MLP', 'GraphSAGE']):\n",
        "    model_data = df_results[df_results['model'] == model_name]\n",
        "    seed_sharpes = model_data.groupby('seed')['sharpe'].mean()\n",
        "    axes[0].bar([f'{model_name}\\nSeed {s}' for s in seed_sharpes.index],\n",
        "                seed_sharpes.values, color=model_colors[model_name], alpha=0.7)\n",
        "\n",
        "axes[0].axhline(y=bh_sharpe, color='navy', linestyle='--', label=f'BH={bh_sharpe:.2f}')\n",
        "axes[0].set_title('Sharpe Ratio par Modele et Seed')\n",
        "axes[0].set_ylabel('Sharpe')\n",
        "axes[0].legend()\n",
        "axes[0].grid(True, alpha=0.3)\n",
        "\n",
        "# 2. Accuracy par fold\n",
        "for model_name in ['MLP', 'GraphSAGE']:\n",
        "    model_data = df_results[df_results['model'] == model_name]\n",
        "    fold_acc = model_data.groupby('fold')['accuracy'].mean()\n",
        "    axes[1].plot(fold_acc.index, fold_acc.values, 'o-',\n",
        "                 color=model_colors[model_name], label=model_name)\n",
        "axes[1].axhline(y=0.5, color='gray', linestyle='--', label='Random')\n",
        "axes[1].set_title('Accuracy par Fold')\n",
        "axes[1].set_xlabel('Fold')\n",
        "axes[1].set_ylabel('Accuracy')\n",
        "axes[1].legend()\n",
        "axes[1].grid(True, alpha=0.3)\n",
        "\n",
        "# 3. Distribution des rendements cumules\n",
        "for model_name in ['MLP', 'GraphSAGE']:\n",
        "    model_data = df_results[df_results['model'] == model_name]\n",
        "    axes[2].hist(model_data['cum_return'], bins=8, alpha=0.5,\n",
        "                 color=model_colors[model_name], label=model_name)\n",
        "axes[2].set_title('Distribution Rendements Cumules')\n",
        "axes[2].set_xlabel('Rendement Cumule')\n",
        "axes[2].legend()\n",
        "axes[2].grid(True, alpha=0.3)\n",
        "\n",
        "plt.suptitle(f'GraphSAGE Multi-Asset - Verdict: {verdict}', fontweight='bold')\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print(f'\\nResume final:')\n",
        "print(f'  Modeles: MLP + GraphSAGE (2-layer)')\n",
        "print(f'  Actions: {n_assets} ({list(prices.columns)})')\n",
        "print(f'  Graphe: correlation > {CORR_THRESHOLD}')\n",
        "print(f'  Validation: {N_FOLDS}-fold WF x {len(SEEDS)} seeds')\n",
        "print(f'  Transaction costs: {TCOST_BPS} bps')\n",
        "print(f'  VERDICT: {verdict} (z={best_z:.2f})')",
    ]),

    md([
        "## 8. Conclusion\n",
        "\n",
        "### Ce que ce notebook evalue\n",
        "\n",
        "Le GraphSAGE utilise un graphe de correlation statique entre actions pour\n",
        "propager l'information entre actifs correles. L'hypothese est que les\n",
        "dependances inter-secteurs ameliorent la prediction de direction.\n",
        "\n",
        "### Limites identifiees\n",
        "\n",
        "1. **Graphe statique** : la correlation est calculee sur toute la periode,\n",
        "   pas de mise a jour dynamique par fold\n",
        "2. **Seuil arbitraire** : le seuil de correlation a 0.5 est un hyperparametre\n",
        "3. **8 actions seulement** : le graphe est petit (8 noeuds), GraphSAGE\n",
        "   est concu pour des graphes beaucoup plus grands\n",
        "4. **Features simples** : seulement 4 features de momentum par action\n",
        "\n",
        "### Verdict honnete\n",
        "\n",
        "Le verdict (BEATS / NO BEATS / INCONCLUSIVE) est calcule sur la base\n",
        "du z-score de l'edge cross-seed. Un verdict INCONCLUSIVE signifie que\n",
        "les resultats ne sont pas statistiquement significatifs avec cette\n",
        "methodologie.",
    ]),
]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.10.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

output_path = "research.ipynb"
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f"Notebook generated: {output_path}")
print(f"Cells: {len(cells)} ({sum(1 for c in cells if c['cell_type']=='code')} code, {sum(1 for c in cells if c['cell_type']=='markdown')} markdown)")
